version: "3.3"
services:
  webmaildemo:
    build: .
    volumes:
      - ".:/webmail"
      - "/webmail/node_modules"
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    command: npx nodemon -w src app.js
