/*********************************************************************************************************
 * English Copyright (C) 2017-2019 by Qboxmail Srl
 *
 * All rights reserved. No part of this publication may be reproduced, distributed, or transmitted in any
 * form or by any means, including photocopying, recording, or other electronic or mechanical
 * methods, without the prior written permission of the publisher, except in the case of brief quotations
 * embodied in critical reviews and certain other noncommercial uses permitted by copyright law. For
 * permission requests, write to the publisher at the address below.
 *
 * Qboxmail Srl - IT02338120971
 * https://www.qboxmail.it - info@qboxmail.it
 *
 * Italiano Copyright (C) 2017-2019 by Qboxmail Srl
 *
 * Tutti i diritti riservati. Nessuna parte di questa pubblicazione può essere riprodotta, memorizzata in
 * sistemi di recupero o trasmessa in qualsiasi forma o attraverso qualsiasi mezzo elettronico, meccanico,
 * mediante fotocopiatura, registrazione o altro, senza l'autorizzazione del possessore del copyright salvo
 * nel caso di brevi citazioni a scopo critico o altri usi non commerciali consentiti dal copyright. Per le
 * richieste di autorizzazione, scrivere all'editore al seguente indirizzo.
 *
 * Qboxmail Srl - IT02338120971
 * https://www.qboxmail.it - info@qboxmail.it
 *********************************************************************************************************/

export default {
  addressbook: {
    contact: {
      oneSelectContacts: "Selected contact",
      oneSelectLists: "Selected list",
      notSelected: "Select a contact",
      sectionLabels: {
        address: "Address",
        company: "Organization",
        email: "Email",
        info: "Info",
        telephone: "Telephone",
        homeUrl: "Personal web site",
        workUrl: "Company web site",
      },
      sections: {
        cell: "Mobile",
        home: "Home",
        homeFax: "Fax home",
        work: "Work",
        workFax: "Fax work",
        title: "Role",
        company: "Organization",
        note: "Notes",
        bday: "Birthday",
      },
      selectContacts: "Selected contacts",
      selectLists: "Selected lists",
      selectedInfo: "Select a contact from the list to view the details.",
    },
    contactsList: {
      emptyContacts: "This address book is empty",
      emptyContactsInfo: "Add a contact to the address book",
      emptyLists: "There are no lists",
      emptyListsInfo: "Add a new list",
      foundContacts: "Found",
      notFound: "No contacts found",
      notFoundInfo: "The search did not produce any result, try again using different criteria.",
      totalContacts: "Contacts",
    },
    tabs: {
      contacts: "Contacts",
      lists: "Lists",
    },
    contextualMenuLabels: {
      address: "Address",
      birthday: "Birthday",
      cancel: "Cancel",
      cell: "Mobile",
      delete: "Delete",
      downloadVCard: "Download VCard",
      email: "Email",
      newContact: "New contact",
      createList: "Create list",
      newList: "New list",
      note: "Note",
      phone: "Phone",
      shareVCard: "Share",
      showVCard: "Show VCard",
      sendAsAttachment: "Send by email",
      sendMail: "Send email",
      url: "URL",
      info: "Info",
      title: "Role",
      company: "Organization",
      home: "Home",
      homeFax: "Fax home",
      work: "Work",
      workFax: "Fax work",
      nickname: "Nickname",
      displayName: "Display name",
      companyName: "Name",
      homeUrl: "Personal web site",
      workUrl: "Company web site",
      team: "Team",
      merge: "Merge",
    },
    deleteContactDsc:
      "By deleting the contact <code>{{contact}}</code> all related information will be deleted.<br/><b>The operation is not reversible</b>.",
    deleteContactDscList:
      "Deleting selected contact will also delete all related information.<br/><b>The operation is not reversible</b>.",
    deleteContactTitle: "Delete contact",

    deleteContactsDsc:
      "Deleting selected contacts will also delete all their information.<br/><b>The operation is not reversible</b>.",
    deleteContactsTitle: "Delete contacts",

    deleteListDsc:
      "By deleting the list <code>{{contact}}</code>, all related information will be deleted.<br/><b>The operation is not reversible</b>.",
    deleteListTitle: "Delete list",

    editContactModal: {
      title: "Edit contact",
    },
    editListModal: {
      title: "Edit list",
    },
    exportAddressBookModal: {
      desc: "You are exporting the address book: <code>{{addressbookExport}}</code><br/>Please choose the format for exporting all the contacts present",
      title: "Export address book",
    },
    import: {
      contactsInvalid: "Not valid:",
      contactsNr: "Total contacts to be imported:",
      contactsValid: "Valid:",
      desc: "You are importing contacts in the address book: <code>{{addressbookImport}}</code><br/>You can import contacts from other email apps using a vCard (<strong>.vcf</strong>) or <strong>.ldif</strong> file format.\u000AFor example, you can export contacts from Gmail or from Outlook and import them here.\u000AThe import will not replace any of the existing contacts.",
      dropFiles: "Upload or drop here the file to be imported",
      error: "Contacts could not be imported",
      importing:
        "We are importing <b>{{contactsNumber}}</b> contact in the address book: <code>{{addressbookImport}}</code>",
      loading: "Loading...",
      success: "Import successfull!",
      title: "Import contacts",
      uploadedFile: "Uploaded",
      uploadingFile: "Uploading",
    },
    list: {
      desc: "By creating a contact list, it is possible to send emails to many people at once. Up to 150 members can be added by choosing them from the contacts in the selected address book.</br></br><b>Note</b>: It is not possible to add email addresses that are not in the selected address book. First add the contacts to the address book and then add them to the list.",
      members: "List members",
    },
    messages: {
      newContactAddressBookBody:
        "You can not add a contact in <b>Organization contacts</b>.<br/>Select a personal or shared address book.",
      newContactAddressBookTitle: "Select address book",
      resetListBody:
        "List's members are related to the address book selected. This change will reset the members list. Continue ?",
      resetListTitle: "Members deletion",
    },
    modifyAddressBookModal: {
      desc: "",
      title: "Edit address book",
    },
    newAddressBookModal: {
      desc: "",
      title: "Add address book",
    },
    newContactModal: {
      title: "Add contact",
    },
    newListModal: {
      title: "Add list",
    },
    shareModal: {
      desc: "You are sharing the address book: <code>{{addressbookShare}}</code><br/>Select the contacts you want to share the address book with and allow them to manage.",
      title: "Share address book",
    },
    sidebar: {
      allContacts: "All contacts",
      deleteAddressbookDsc:
        "Deleting the address book <code>{{addressbook}}</code> will delete all included contacts.<br/><b>The operation is not reversible</b>.",
      deleteAddressbookTitle: "Delete address book",
      globalAddressbook: "Organization contacts",
      personalAddressbook: "Personal contacts",
      sharedAddressbooks: "Shared address books",
      userAddressbooks: "User address book",
    },
    subscribeModal: {
      desc: "",
      noAddressbook: "There are no address books to be subscribed to",
      title: "Subscribe to a shared Address Book",
    },
  },

  app: {
    addressbook: "Address book",
    calendar: "Calendar",
    chat: "Chat",
    meeting: "Meeting",
    mtm: "Mail Time Machine",
    of: "of",
    webmail: "Webmail",
    modal: {
      updateAvailable: {
        title: "Update available",
        description:
          "A <b>new version of Webmail</b> is available.<br/>Click to reload and update, your settings will remain unchanged.<br/><br/>The application will automatically update between:",
      },
    },
  },

  avatarEditorModal: {
    photoTitle: "Take a picture",
    title: "Edit avatar",
    zoom: "Zoom -/+",
  },

  banner: {
    info: {
      mailRetention: "Messages in this folder are deleted automatically after 30 days.",
    },
    warning: {
      labelCalendarUpdate:
        "Please note that if a label is renamed, it will no longer be visible in the events where it is used.",
      labelMailUpdate:
        "Please note that if a label is renamed, it will no longer be visible in the emails where it is used.",
      labelTaskUpdate:
        "Please note that if a label is renamed, it will no longer be visible in the activities where it is used.",
      mailRetention:
        "Attention, messages will be automatically deleted definitively without possibility of recovery.<br><b>The cancellation will be operative within 24 hours.</b>",
    },
  },

  buttons: {
    accept: "Accept",
    add: "Add",
    addAction: "Add action",
    addAddressbook: "Address book",
    addAsAttachment: "Attach",
    addAttachments: "Add attachments",
    addCalendar: "Calendar",
    addField: "Add field",
    addHolidayCalendar: "Holiday calendar",
    addInline: "Add in line",
    addLabel: "Add label",
    addParameter: "Add parameter",
    addSignature: "Add signature",
    addToList: "Add to list",
    allow: "Allow",
    apply: "Apply",
    assign: "Assign",
    backAddressbook: "Close",
    backTo: "Back",
    cancel: "Cancel",
    changeImage: "Change image",
    changePassword: "Change password",
    checkFreeBusy: "Check availability",
    close: "Close",
    comeBackLater: "Come back later",
    configure: "Configure",
    confirm: "Confirm",
    copied: "Copied",
    copy: "Copy",
    copyLink: "Copy link",
    createFolder: "New folder",
    decline: "Declines",
    delete: "Delete",
    deleteDraft: "Delete draft",
    details: "Details",
    disable: "Disable",
    disabled: "Disabled",
    disableOTP: "Disable OTP",
    download: "Download",
    edit: "Edit",
    editLabel: "Edit label",
    editSignature: "Edit signature",
    empty: "Empty",
    enable: "Enable",
    event: "Event",
    export: "Export",
    generateNewPassword: "Generate new password",
    generateRandomPassword: "Generate random password",
    goToCalendar: "Go to calendar",
    goToEventDay: "Go to event day",
    goToMail: "Return to mail",
    goToOldWebmail: "Go to old webmail",
    goToSettings: "Go to Settings page",
    hide: "Hide",
    ignore: "Ignore",
    import: "Import",
    insertHTML: "Insert HTML",
    keep: "Keep",
    label: "Label",
    later: "Later",
    learnMore: "Learn more",
    leftRotate: "Left rotate 90 degrees",
    loadImage: "Upload image",
    loading: "Loading",
    logout: "Logout",
    makePhoto: "Take a picture",
    markRead: "Read",
    markSeen: "Mark",
    markUnread: "Unread",
    message: "Message",
    modify: "Edit",
    new: "New",
    newContact: "New contact",
    newEvent: "New event",
    newMessage: "New message",
    newSignature: "New signature",
    newTask: "New task",
    newWebmail: "New Webmail",
    next: "Next",
    noThanks: "No, thanks",
    occurrence: "Occurrence",
    ok: "Ok",
    oldWebmail: "Old Webmail",
    openMap: "Open in map",
    otherOptions: "Other options",
    override: "Override",
    participate: "Join",
    postpone: "Postpone",
    reloadPage: "Reload page",
    removeImage: "Remove image",
    rename: "Rename",
    reorder: "Reorder",
    reorderEnd: "End reorder",
    report: "Report",
    restore: "Ask for restore",
    retryImport: "Retry",
    save: "Save",
    saveDraft: "Save draft and close",
    saveNextAvailability: "Save suggested availability",
    search: "Search",
    send: "Send",
    series: "Series",
    setOtp: "Set OTP",
    share: "Share",
    show: "Show",
    showAll: "Show all",
    showMore: "Show more",
    showToDo: "Show to do",
    showUrlsAddressbook: "Show address book URLS",
    showUrlsCalendar: "Show calendar URLS",
    snooze: "Snooze",
    starred: "Star",
    subscribe: "Subscribe",
    subscribeAddressbook: "Subscribe to an Address Book",
    subscribeCalendar: "Subscribe to a Calendar",
    tentative: "Maybe",
    understand: "I got it",
    unlink: "Remove link",
    unsetOtp: "Disable OTP",
    unsubscribe: "Unsubscribe",
    unsubscribeList: "Cancel subscription",
    update: "Update",
    updateFilter: "Update filter",
    defaultImg: "Use default image",
    viewMap: "View map",
  },

  buttonIcons: {
    activeSync: "Synchronize using Microsoft® Exchange ActiveSync",
    activeSyncNot: "DisableMicrosoft® Exchange ActiveSync",
    alignCenter: "Align center",
    alignLeft: "Align left",
    alignRight: "Align right",
    backgroundColor: "Background color",
    backTo: "Back",
    bold: "Bold",
    cannedMsg: "Email templates",
    close: "Close",
    confirm: "Confirm",
    createTask: "Create Task",
    delete: "Delete",
    download: "Download",
    downloadVCard: "Download VCard",
    edit: "Edit",
    emoji: "Emoji",
    forward: "Forward",
    fullscreen: "Fullscreen",
    fullscreenNot: "Windowed mode",
    imageAdd: "Add image",
    indent: "Increase indent",
    insertHTML: "Insert HTML",
    italic: "Italic",
    link: "Insert link",
    maintenance: "Compact",
    maxmized: "Enlarge",
    minimized: "Reduce",
    more: "More",
    moveDown: "Move down",
    moveUp: "Move up",
    next: "Next",
    orderList: "Ordered list",
    outdent: "Decrease indent",
    pin: "Pin",
    previous: "Previous",
    print: "Print",
    quote: "Quote",
    removeFormatting: "Remove formatting",
    removeQuote: "Remove quote",
    reply: "Reply",
    replyAll: "Reply to all",
    saveDraft: "Save draft",
    sendDebug: "Send message that can not be viewed",
    sendMail: "Send email",
    sendByEmail: "Send by email",
    share: "Share",
    showSidebar: "Show / hide sidebar",
    showSourceCode: "Show source code",
    showVCard: "Show VCard",
    spam: "Mark as Spam",
    spamNot: "Mark as Not Spam",
    startChat: "Start chat",
    startMeeting: "Start meeting",
    strike: "Strike",
    subscribe: "Subscribe",
    textColor: "Text color",
    thanks: "Thanks",
    underline: "Underline",
    understand: "I got it",
    undo: "Undo",
    unlink: "Remove link",
    unorderList: "Unordered list",
    unSubscribe: "Unsubscribe",
  },

  calendar: {
    alarmDurations: {
      after: "after",
      before: "before",
      day: "days",
      hour: "hours",
      minute: "minutes",
      second: "seconds",
      week: "weeks",
    },
    deleteEvent: "Delete event",
    deleteEventDsc: "Proceed with the deletion of the selected event?",
    deleteSeries: "Delete series",
    deleteSeriesDsc: "Proceed with the deletion of the selected series?",
    event: {
      alarmsNotPresent: "No alerts",
      deleteEventOccurrenceTitle: "Delete event or series?",
      deleteEventOccurrenceDesc:
        "The event you want to delete has several occurrencies. Deleting the single occurrence will leave others unaltered.",
      eventNotes: "Event notes",
      eventAttendees: "Event attendees",
      fromDay: "from",
      labelsNotPresent: "No labels",
      locationContextualMenuLabels: {
        zoomLabel: "Zoom",
        zoomHint: "Web meeting",
        personalMeetingLabel: "Personal meeting room",
        personalMeetingHint: "Web Meeting",
        locationLabel: "In-person Meeting",
        locationHint: "Set an address or place",
        textLabel: "Custom",
        textHint: "Insert a custom text",
      },
      locationSelector: "Select event location",
      locationZoomNoMeeting: "Once the event is saved, the Zoom meeting link will be present here",
      maxAttachmentsNumberTitle: "Too many attachments!",
      maxAttachmentsNumberDsc:
        "You can enter up to 4 attachments. If you need to attach more than 4 files, we suggest you create a zipped folder.",
      maxLabelsNumberTitle: "Too many labels!",
      maxLabelsNumberDsc:
        "You have reached the maximum number of labels that can be associated with an event. To add a new label you must first remove one of those already present.",
      noTitle: "Untitled",
      notIncludedInFreeBusy:
        "This calendar is not included in Free/Busy. This implies that you and the people you invite will be shown as <b>free</b> during the events created in this calendar.",
      organizerTitle: "Created by",
      pendingMsg: "Event awaiting confirmation",
      permissionDenied:
        "Unable to view the details of the selected event, you may not have the necessary permissions.",
      repeatEvent: "This event is part of recurring events",
      saveEventOccurrenceTitle: "Show event or recurring events?",
      saveEventOccurrenceDesc:
        "The event you want to view or edit has several occurrences. Editing the single occurrence will leave others unaltered.",
      setAlert: "Set alert",
      toDay: "to",
    },
    eventRepetition: {
      WeekDayNumberInMonth_1: "First",
      WeekDayNumberInMonth_2: "Second",
      WeekDayNumberInMonth_3: "Third",
      WeekDayNumberInMonth_4: "Fourth",
      WeekDayNumberInMonth_5: "Fifth",
      never: "Never",
      after: "After;recurrencies",
      inDate: "On date",
      end: "End repetition",
    },
    filterView: {
      listmonth: "Agenda",
      day: "Day",
      month: "Month",
      week: "Week",
      workWeek: "Work week",
      year: "Year",
    },
    import: {
      contactsInvalid: "Not valid:",
      contactsNr: "Total events to be imported:",
      contactsValid: "Valid:",
      dropFiles: "Upload or drop here the file to be imported",
      error: "Events could not be imported",
      importing:
        "We are importing <b>{{eventsNumber}}</b> event in the calendar: <code>{{calendarImport}}</code>",
      info: "You are importing events in the calendar: <code>{{calendarImport}}</code><br/>You can import events from other email apps using a ICS file format. For example, you can export events from Gmail or from Outlook in ICS format and import them into Qboxmail.<br/><b>The import will not replace any of the existing events</b>.",
      loading: "Loading...",
      success: "All your events have been successfully imported!",
      title: "Import events",
      uploadedFile: "Uploaded",
      uploadingFile: "Uploading",
    },
    modifyCalendarModal: {
      desc: "",
      title: "Edit calendar",
    },
    newCalendarModal: {
      desc: "",
      title: "Add calendar",
      freeBusyInfo:
        "If the calendar is not included in <b>Free/Busy</b>, you and the people you invite will be shown as <b>free</b> during the events created in this calendar.",
    },
    newEvent: {
      attachmentsList: {
        headerItem: "Attachments",
        placeholderList: " ",
      },
      desc: "",
      dropFiles: "Upload or drop here the file to attach<br>(maximum 4 attachments, 3 MB each)",
      freeBusy: {
        legend: {
          event: "Event",
          busy: "Busy",
          waiting: "Waiting",
          availability: "Next availability",
        },
      },
      hideDetails: "Hide details",
      participantsList: {
        headerItem: "Participants",
        answeredHeaderItem: "Answered",
        notAnsweredHeaderItem: "Waiting for an answer",
        placeholderList: " ",
      },
      showDetails: "Show details",
      tabAttachments: "Attachments",
      tabDetails: "Details",
      tabParticipants: "Participants",
      tabSeries: "Repetitions",
      tabSettings: "Settings",
      title: "Create event",
      titleEdit: {
        event: "Event",
        series: "Series",
      },
      titleFreebusy: "Participant availability",
    },
    nextAvailability: "Next availability",
    searchEvents: {
      notFound: "No events found",
      notFoundInfo: "The search did not produce results, try again using different criteria.",
    },
    shareModal: {
      desc: "You are sharing the calendar: <code>{{calendarShare}}</code><br/>Select the contacts you want to share the calendar with and allow them to manage.",
      title: "Share calendar",
    },
    sidebar: {
      labels: "Labels",
      personalCalendar: "Personal calendar",
      sharedCalendars: "Shared calendars",
      userCalendars: "User calendars",
      deleteCalendarDsc:
        "By deleting the calendar <code>{{calendar}}</code> all included events will be deleted.<br/><b>The operation is not reversible</b>.",
      deleteCalendarTitle: "Delete calendar",
    },
    subscribeModal: {
      desc: "",
      noCalendar: "There are no calendars to be subscribed to",
      title: "Subscribe to a shared Calendar",
    },
    today: "Today",
  },

  circularLoopBar: {
    uploading: "Uploading",
  },

  comingSoon: "Development in progress...",

  contactImport: {
    title: "Searching contacts",
    desc: "We are importing your old contacts. The operation may take some time, please wait.",
  },

  datasets: {
    actionsFlags: {
      "\\\\Answered": "Answered",
      "\\\\Deleted": "Deleted",
      "\\\\Draft": "Draft",
      "\\\\Flagged": "Marked",
      "\\\\Seen": "Read",
    },
    antispamFilterTypes: {
      whitelist_from: "Allow from",
      whitelist_to: "Allow to",
    },
    calendarMinutesInterval: {
      15: "15 minutes",
      30: "30 minutes",
      60: "60 minutes",
    },
    calendarNewEventFreeBusy: {
      busy: "Busy",
      free: "Free",
      outofoffice: "Out of office",
      temporary: "Temporary",
    },
    calendarNewEventPartecipation: {
      ACCEPTED: "Accept",
      DECLINED: "Decline",
      TENTATIVE: "Maybe",
    },
    calendarNewEventParticipationRoles: {
      CHAIR: "Chairman",
      "REQ-PARTICIPANT": "Requested",
      "OPT-PARTICIPANT": "Not requested",
      "NON-PARTICIPANT": "For information purpose",
    },
    calendarNewEventPriority: {
      0: "None",
      1: "High",
      5: "Medium",
      9: "Low",
    },
    calendarNewEventTypes: {
      public: "Public",
      confidential: "Confidential",
      private: "Private",
    },
    calendarStartWeekDay: {
      saturday: "Saturday",
      sunday: "Sunday",
      monday: "Monday",
    },
    calendarView: {
      year: "Year",
      month: "Month",
      week: "Week",
      workWeek: "Work week",
      day: "Day",
      listmonth: "List",
    },
    calendarEventFilterBy: {allEvents: "All", nextEvents: "All next events"},
    calendarEventSearchIn: {title: "Title/label/place", all: "Full content"},
    cancelSendTimer: {
      0: "Disabled",
      5000: "5 seconds",
      10000: "10 seconds",
      20000: "20 seconds",
      30000: "30 seconds",
    },
    contactNameFormat: {
      firstName: "First name, Last name",
      lastName: "Last name, First name",
    },
    contactsOrder: {
      firstName: "First name",
      lastName: "Last name",
    },
    countries: {
      AD: "Andorra",
      AE: "United Arab Emirates",
      AG: "Antigua & Barbuda",
      AI: "Anguilla",
      AL: "Albania",
      AM: "Armenia",
      AO: "Angola",
      AR: "Argentina",
      AS: "American Samoa",
      AT: "Austria",
      AU: "Australia",
      AW: "Aruba",
      AX: "Åland Islands",
      AZ: "Azerbaijan",
      BA: "Bosnia and Herzegovina",
      BB: "Barbados",
      BD: "Bangladesh",
      BE: "Belgium",
      BF: "Burkina Faso",
      BG: "Bulgaria",
      BH: "Bahrain",
      BI: "Burundi",
      BJ: "Bénin",
      BL: "Saint Barthélemy",
      BM: "Bermuda",
      BN: "Brunei",
      BO: "Bolivia",
      BQ: "Bonaire, Sint Eustatius and Saba",
      BR: "Brasil",
      BS: "Bahamas",
      BW: "Botswana",
      BY: "Belarus",
      BZ: "Belize",
      CA: "Canada",
      CC: "Cocos (Keeling) Islands",
      CD: "Democratic Republic of the Congo",
      CF: "Central African Republic",
      CG: "Republic of the Congo",
      CH: "Switzerland",
      CL: "Chile",
      CM: "Cameroun",
      CN: "China",
      CO: "Colombia",
      CR: "Costa Rica",
      CU: "Cuba",
      CV: "Cabo Verde",
      CW: "Curaçao",
      CX: "Christmas Island",
      CY: "Cyprus",
      CZ: "Czech Republic",
      DE: "Germany",
      DK: "Denmark",
      DM: "Dominica",
      DO: "Dominican Republic",
      EC: "Ecuador",
      EE: "Estonia",
      ES: "Spain",
      ET: "Ethiopia",
      FI: "Finland",
      FO: "Faroe Islands",
      FR: "France",
      GA: "Gabon",
      GB: "United Kingdom",
      GD: "Grenada",
      GF: "French Guiana",
      GG: "Guernsey",
      GI: "Gibraltar",
      GL: "Greenland",
      GP: "Guadeloupe",
      GQ: "Equatorial Guinea",
      GR: "Greece",
      GT: "Guatemala",
      GU: "Guam",
      GY: "Guyana",
      HN: "Honduras",
      HR: "Croatia",
      HT: "Haiti",
      HU: "Hungary",
      IE: "Ireland",
      IM: "Isle of Man",
      IS: "Island",
      IT: "Italy",
      JE: "Jersey",
      JM: "Jamaica",
      JP: "Japan",
      KE: "Kenya",
      KR: "South Korea",
      LI: "Lichtenstein",
      LS: "Lesotho",
      LT: "Lithuania",
      LU: "Luxembourg",
      LV: "Latvia",
      MC: "Monaco",
      MD: "Moldova",
      ME: "Montenegro",
      MG: "Madagascar",
      MK: "North Macedonia",
      MQ: "Martinique",
      MT: "Malta",
      MW: "Malawi",
      MX: "Mexico",
      MZ: "Mozambique",
      NA: "Namibia",
      NI: "Nicaragua",
      NL: "Netherlands",
      NO: "Norway",
      NZ: "New Zealand",
      PA: "Panama",
      PE: "Perú",
      PH: "Philippines",
      PL: "Poland",
      PT: "Portugal",
      PY: "Paraguay",
      RE: "Réunion",
      RO: "Romania",
      RS: "Serbia",
      RU: "Russia",
      RW: "Rwanda",
      SE: "Sweden",
      SG: "Singapore",
      SH: "Saint Helena",
      SI: "Slovenia",
      SJ: "Svalbard & Jan Mayen",
      SK: "Slovakia",
      SM: "San Marino",
      SO: "Somalia",
      SS: "South Sudan",
      SV: "El Salvador",
      TG: "Togo",
      TO: "Tonga",
      TR: "Turkey",
      TZ: "Tanzania",
      UA: "Ukraine",
      UG: "Uganda",
      US: "United States of America",
      UY: "Uruguay",
      VA: "Città del Vaticano",
      VE: "Venezuela",
      VN: "Vietnam",
      XK: "Kosovo",
      YT: "Mayotte",
      ZA: "South Africa",
      ZM: "Zambia",
      ZW: "Zimbabwe",
    },
    deliveryNotifications: {
      always: "Always ask for delivery confirmation",
      never: "Never ask for delivery confirmation",
    },
    markReadAfter: {
      manually: "Manually",
      onOpen: "When message is open",
      5000: "After 5 seconds",
      10000: "After 10 seconds",
      30000: "After 30 seconds",
    },
    eventAlarmPostponeTime: {
      60: "for 1 minute",
      300: "for 5 minutes",
      900: "for 15 minutes",
      1800: "for 30 minutes",
      3600: "for 1 hour",
      7200: "for 2 hours",
      86400: "for 1 day",
      604800: "for 1 week",
    },

    eventTimeIntervals: {
      5: "5 minutes",
      10: "10 minutes",
      15: "15 minutes",
      20: "20 minutes",
      30: "30 minutes",
    },

    calendarTaskStatus: {
      "NEEDS-ACTION": "Needs action",
      COMPLETED: "Completed",
      PROCESS: "In progress",
      CANCELLED: "Cancelled",
    },

    feedbackAreas: {
      addressbookSidebar: "Address book list",
      contactList: "Contacts list",
      contactView: "Contact display",
      mailSearch: "Search messages",
      mailSidebar: "Folders list",
      messageList: "Messages list",
      messageView: "Message display",
      newMessage: "New message composition",
      other: "More",
      settings: "Settings",
    },
    filterMail: {
      all: "All",
      byDate: "Date",
      byFrom: "From",
      bySize: "Size",
      bySubject: "Subject",
      flagged: "Marked",
      filter: "Filters",
      orderBy: "Order by",
      seen: "Read",
      unseen: "Unread",
    },
    filtersActions: {
      discard: "Remove",
      addflag: "Mark message as",
      setkeyword: "Add label",
      fileinto: "Move message in",
      fileinto_copy: "Copy message in",
      keep: "Keep message",
      redirect: "Redirect message to",
      redirect_copy: "Send copy to",
      reject: "Reject with following message",
      stop: "Stop processing filters",
    },
    filtersDateOperators: {
      gt: "After",
      is: "is equal to",
      lt: "Before",
      notis: "is not equal to",
    },
    filtersEnvelopeSubtypes: {From: "From", To: "To"},
    filtersDateSubTypes: {date: "Date", time: "Time", weekday: "Week day"},
    filtersDateWeekdays: {
      monday: "Monday",
      tuesday: "Tuesday",
      wednesday: "Wednesday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",
      sunday: "Sunday",
    },
    filtersRules: {
      Bcc: "Bcc",
      body: "Body",
      Cc: "Cc",
      currentdate: "Check-in date",
      envelope: "Message",
      From: "Sender",
      other: "Other header",
      size: "Size",
      Subject: "Subject",
      To: "Recipient",
    },
    filtersSizeMUnits: {B: "Bytes", K: "Kilobytes", M: "Megabytes"},
    filtersSizeOperators: {over: "is bigger than", under: "is less than"},
    filtersStringOperators: {
      contains: "contains",
      exists: "exists",
      is: "is equal to",
      notcontains: "not contain",
      notexists: "not exists",
      notis: "is not equal to",
    },
    fontSize: {
      extraSmall: "Extra small",
      huge: "Huge",
      large: "Large",
      medium: "Medium",
      normal: "Normal",
      small: "Small",
    },
    languages: {
      de: "German",
      en: "English",
      fr: "French",
      gr: "Greek",
      it: "Italian",
      nl: "Dutch",
      sv: "Swedish",
      es: "Spanish",
      pt: "Portuguese",
    },
    mailRetention: {
      0: "Never",
      30: "older than 1 month",
      90: "older than 3 months",
      180: "older than 6 months",
      365: "older than 1 year",
      730: "older than 2 years",
      1095: "older than 3 years",
      1460: "older than 4 years",
      1825: "older than 5 years",
    },
    matchTypes: {
      allof: "Satisfy all parameters",
      anyof: "Satisfy at least one parameter",
    },
    newAllDayEventAlert: {
      never: "Never",
      eventDate: "Event date",
      "-PT17H": "One day before, at 9am",
      "-P6DT17H": "One week before, at 9am",
    },
    newEventAlert: {
      never: "Never",
      eventHour: "Event start time",
      //P[n]Y[n]M[n]DT[n]H[n]M[n]S
      "-PT5M": "5 minutes before",
      "-PT10M": "10 minutes before",
      "-PT15M": "15 minutes before",
      "-PT30M": "30 minutes before",
      "-PT1H": "1 hour before",
      "-PT2H": "2 hours before",
      "-PT12H": "12 hours before",
      "-P1D": "1 day before",
      "-P7D": "1 week before",
    },
    newEventRepeatDayWeek: {
      MO: "Monday",
      TU: "Tuesday",
      WE: "Wednesday",
      TH: "Thursday",
      FR: "Friday",
      SA: "Saturday",
      SU: "Sunday",
    },
    newEventRepeatFrequency: {
      NEVER: "Never",
      DAILY: "Daily",
      WEEKLY: "Weekly",
      MONTHLY: "Monthly",
      YEARLY: "Yearly",
    },
    newEventRepeatMonths: {
      1: "January",
      2: "February",
      3: "March",
      4: "April",
      5: "May",
      6: "June",
      7: "July",
      8: "August",
      9: "Settembre",
      10: "October",
      11: "November",
      12: "December",
    },
    orderSelector: {
      byLastname: "Last name",
      byMail: "Email",
      byName: "First name",
      byOrg: "Organization",
      orderBy: "Order by",
      showOnlyLists: "Show only lists",
    },
    readConfirmations: {
      always: "Always ask for reading confirmation",
      never: "Never ask for reading confirmation",
    },
    readingConfirmation: {
      always: "Always",
      ask: "Always ask",
      never: "Never",
    },
    selectMail: {
      all: "All",
      cancel: "Cancel",
      modify: "Edit",
      none: "Deselect",
      select: "Select",
    },
    shareOptionsCalendar: {
      None: "None",
      DAndTViewer: "View date and time",
      Viewer: "View all",
      Responder: "Respond to",
      Modifier: "Modify",
    },
    showImages: {
      always: "Always",
      contacts: "Contacts and trusted",
      never: "Never",
    },
    themes: {
      dark: "Dark",
      light: "Light",
    },
    timeFormats: {
      "12h": "12h",
      "24h": "24h",
    },
    viewMode: {
      label: {
        viewColumns: "Columns",
        viewHalf: "Preview",
        viewFull: "List",
      },
      desc: {
        viewColumns: "Show three columns layout with reading pane on the right of the screen.",
        viewHalf: "Show two columns layout with reading pane on the bottom of the screen.",
        viewFull:
          "Show two columns layout with only message list. Reading pane will be show full page on click.",
      },
    },
  },

  dropdownMenu: {
    activesync: "Microsoft® ActiveSync",
    delete: "Delete",
    download: "Download",
    edit: "Edit",
    exportContacts: "Export contacts",
    feedback: "Feedback",
    importContacts: "Import contacts",
    importEvents: "Import events",
    news: "News & Updates",
    remove: "Remove",
    rename: "Rename",
    share: "Share",
    shortcuts: "Keyboard shortcuts",
    syncNo: "Not synchronize",
    syncYes: "Synchronize",
    unsubscribe: "Unsubscribe",
  },

  dropdownUser: {
    feedback: "Feedback",
    logout: "Log out",
    settings: "Settings",
  },

  errors: {
    emailDomainAlreadyPresent: "Email address or domain already present",
    emptyField: "Empty field",
    invalidEmail: "Email not valid",
    invalidEmailDomain: "Email address or domain not valid",
    invalidPassword: "Not valid password",
    invalidPasswordFormat: "Invalid format, enter at least 8 alphanumeric characters",
    invalidValue: "Not valid value",
    mandatory: "Required field",
    notAllowedCharacter: "Not allowed character",
    notChanged: "Not modified field",
    permissionDenied: "Permission denied",
    tooLong: "Too long field",
  },

  feedback: {
    disclaimer:
      "Send a feedback and help us improve the service.<br/>For any questions or problems, related to the use of webmail, contact support.",
    labels: {
      feedbackAreas: "On which area you want to leave feedback?",
      note: "Leave a message (optional)",
    },
    msgError: {
      title: "Your feedback could not be sent",
      desc: "Please try again later, it is important for us to know what you think of our webmail. Your feedback will help us create a better experience for you and all our users.",
    },
    msgSuccess: {
      title: "Thanks for your feedback!",
      desc: "We really appreciate the time you took to help us improve our webmail. Your feedback will help us create a better experience for you and for all our users.",
    },
    privacy:
      "The collected data will be processed in compliance with the current legislation on Privacy.",
    title: "Feedback",
  },

  inputs: {
    labels: {
      addAddress: "Add address",
      addContactToAddressbook: "Add contact to address book",
      addDomain: "Add address or domain",
      addLabel: "Label name",
      addMembers: "Add members",
      addParticipant: "Add participant",
      addressbookName: "Address book",
      addUser: "Add user",
      alert2: "Second alert",
      alert: "Alert",
      assignTask: "Assign task to",
      at: "at",
      calendar: "Calendar",
      calendarBusinessDayEndHour: "Working day end",
      calendarBusinessDayStartHour: "Working day start",
      calendarColor: "Calendar color",
      calendarMinutesInterval: "Calendar time interval",
      calendarName: "Calendar name",
      calendarView: "Default view",
      company: "Organization",
      companyName: "Name",
      confidentialEvents: "Confidential events",
      confirmNewPassword: "Confirm password",
      contactNameFormat: "Display order",
      contactsOrder: "Contacts sort order",
      contains: "Contains",
      country: "Country",
      dateFormat: "Date format",
      dateInterval: "Date interval",
      defaultAddressbook: "Default address book",
      defaultCalendar: "Default calendar",
      displayName: "Disp. name",
      email: "Email",
      encryptionMethod: "Encryption method",
      endDate: "End date",
      event: "Event",
      eventDailyRepetition: "Every;day/s",
      eventDailyWorkdayRepetition: "Every week day",
      eventMonthlyLastDayRepetition: "Last day of month, every;month/s",
      eventMonthlyLastWeekDayRepetition: "Last {{WeekDay}}, every;month/s",
      eventMonthlyRepetition: "On {{DayNumber}}, every;month/s",
      eventMonthlyWeekDayRepetition: "On {{WeekDayNumber}}, every;month/s",
      eventPartecipation: "Partecipation status",
      eventPriority: "Event priority",
      eventType: "Event type",
      eventWeeklyRepetition: "Every;week/s, on:",
      eventYearlyLastDayRepetition: "Last day of {{Month}}, every;year/s",
      eventYearlyLastWeekDayRepetition: "Last {{WeekDay}} of {{Month}}, every;year/s",
      eventYearlyRepetition: "On {{DayNumber}} of {{Month}}, every;year/s",
      eventYearlyWeekDayRepetition: "On {{WeekDayNumber}} of {{Month}}, every;year/s",
      exportAsLdiff: "Export in LDIF format",
      exportAsVcard: "Export in VCard format",
      faxHome: "Fax home",
      faxWork: "Fax work",
      filter: "Filter by",
      filterName: "Rule name",
      firstName: "First name",
      folderName: "Folder name",
      freeBusy: "Show as",
      from: "From",
      fromDate: "From date",
      home: "Home",
      hour: "Time",
      includeFreeBusy: "Include in Free/Busy",
      label: "Label",
      labelColor: "Label color",
      language: "Language",
      lastName: "Last name",
      linkText: "Displayed text",
      linkURL: "Web address (URL)",
      listName: "List name",
      location: "Location",
      loginAddressbook: "Initial address book",
      mailAccount: "Account",
      mailRetention: "Delete folder's messages",
      mailRetentionDefault: "Message deletion is automatically set to 30 days",
      mailRetentionDiscalimer:
        "Attention, messages will be automatically deleted definitively without possibility of recovery. The cancellation will be operative within 24 hours.",
      mailRetentionHint:
        "Specify the time interval, after receiving the message, to proceed with automatic deletion.",
      markReadAfter: "Mark message as read",
      mobile: "Mobile",
      newAddressBook: "New address book",
      newAddressBookMobile: "New address book",
      newAllDayEventAlert: "New all day events alert",
      newBcc: "Add Bcc recipients",
      newCalendar: "New calendar",
      newEventAlert: "New events alert",
      newForward: "Add recipient to list",
      newPassword: "New password",
      nickname: "Nickname",
      object: "Subject",
      oldPassword: "Current password",
      parentFolder: "Path",
      password: "Password",
      personalMeetingRoom: "Link to personal meeting room",
      phone: "Phone",
      port: "Port",
      portFor: "Port for",
      priority: "Priority",
      privateEvents: "Private events",
      publicEvents: "Public events",
      readingConfirmation: "Send reading confirmation",
      recoveryEmail: "Recovery email",
      renameAddressbook: "Rename address book",
      repeatEvery: "Repeat",
      reportBugNote: "Problem description",
      reportBugPhoneNumber: "Phone number",
      searchAddressbookToSubscribe: "Search for a user to see their shared address books",
      searchCalendarToSubscribe: "Search for a user to see their shared calendars",
      searchIn: "Search in",
      selectCalendar: "Select calendar",
      selectIdentity: "Select identity",
      selectList: "Select list",
      selectSnapshotDate: "Choose date",
      serverName: "Server name",
      shareCalendarCalDAVURL: "CalDAV URL",
      shareCalendarWebDavICSURL: "WebDAV ICS URL",
      shareCalendarWebDavXMLURL: "WebDAV XML URL",
      shareToAddressbook: "Who do you want to share the address book with?",
      shareToCalendar: "Who do you want to share the calendar with?",
      shareToFolder: "Who do you want to share the folder with?",
      showImages: "Show images",
      signatureName: "Display name",
      signatureText: "Signature text",
      startDate: "Start date",
      team: "Team",
      templateName: "Name",
      templateSubject: "Subject",
      templateText: "Message body",
      theme: "Theme",
      timeFormat: "Time format",
      timezone: "Time zone",
      title: "Title",
      to: "To",
      untilDate: "Until day",
      username: "Username",
      weekStart: "First day of the week",
      work: "Work",
    },
    placeholder: {
      addressbookName: "Address book name",
      birthday: "Birthday",
      city: "City",
      company: "Organization",
      country: "Country",
      customText: "Enter a custom text",
      email: "Email",
      endDate: "End date",
      firstName: "First name",
      lastName: "Last name",
      members: "Members",
      newFolderName: "New folder name",
      newNameAddressbook: "New address book name",
      newPassword: "At least 8 alphanumeric characters",
      note: "Note",
      password: "Your password",
      phone: "Phone",
      place: "Enter a street or place",
      postCode: "Postcode",
      region: "Region",
      role: "Role",
      search: "Search",
      searchActivity: "Search activity",
      searchEvent: "Search event",
      searchUser: "Search for user in your domain",
      select: "Select",
      snooze: "Snooze alert",
      startDate: "Start date",
      street: "Street",
    },
    hint: {
      cancelSendMessage:
        "Select the time available to retract a message during sending, if you decide you don't want to send the email.",
      newForward: "You can add until max {{max}} forward address.",
      newBcc: "You can add up to {{max}} Bcc recipients.",
      mailRetention:
        "Specify the time interval, after receiving the message, to proceed with automatic deletion.",
      passwordScore: {
        check: "Password strength",
        poor: "Very poor password",
        easy: "Password too easy",
        weak: "Password too weak",
        strong: "Strong password",
        great: "Great password!",
      },
    },
  },

  labels: {
    attendees: "Attendees",
    calendarAdvancedSearch: "Where do you want to search?",
    clearAdvancedFilters: "Clear filters",
    clearFields: "Clear fields",
    default: "Default",
    forDomain: "On domain",
    forward: "Fwd",
    holidayCalendar: "Holiday",
    organizer: "Organizer",
    otherFilters: "Other filters",
    searchResults: "Search results",
    withAllUsers: "With all users",
  },

  loaderFullscreen: {
    description: "The contents are coming, please wait.",
    descriptionEvents: "Your events are coming, please wait.",
    descriptionFolder: "Your folders are coming, please wait.",
    title: "Loading",
    titleEvent: "Loading event",
  },

  mail: {
    confirmMailLabel: "OK, I confirm!",
    contextualMenuLabels: {
      addAddressBook: "Add to address book",
      addEvent: "Add event",
      alarm: "Alarm",
      archive: "Archive",
      archiveThread: "Archive thread",
      backTo: "Back",
      cancel: "Cancel",
      close: "Close",
      confirm: "Confirm",
      copyIn: "Copy in",
      copyThreadIn: "Copy thread",
      delete: "Delete",
      deletePerm: "Permanently delete",
      deleteThread: "Delete thread",
      deleteXMessages: "Delete {{MessagesNumber}} messages",
      deliveryNotification: "Delivery confirmation",
      download: "Download",
      editAsNew: "Edit as new",
      emptySpam: "Mark Spam read",
      emptyTrash: "Empty trash",
      forward: "Forward",
      import: "Import mail",
      label: "Label",
      labelsManagement: "Manage labels",
      labelThread: "Label thread",
      markAllAsRead: "Mark all as read",
      markAs: "Mark as",
      markThreadAs: "Mark thread",
      manageFolders: "Manage folders",
      modify: "Edit",
      more: "More",
      moveThreadTo: "Move thread",
      moveTo: "Move to",
      newSubFolder: "Add subfolder",
      plainText: "Plain text mode",
      print: "Print",
      priorityHigh: "High priority",
      readed: "Read",
      readedNot: "Unread",
      readingNotification: "Reading confirmation",
      rename: "Rename",
      reply: "Reply",
      replyToAll: "Reply to all",
      restore: "Restore",
      restoreThreadIn: "Restore thread",
      restoreIn: "Restore in",
      sendAsAttachment: "Forward as attachment",
      showSourceCode: "Show source code",
      spam: "Spam",
      spamNot: "Not Spam",
      starred: "Starred",
      starredNot: "Unstarred",
      thanks: "Thanks",
      thread: "Thread actions",
    },
    deleteMailDsc:
      "If a storage system is not active, the message will be permanently deleted.<br/><b>The operation is not reversible</b>.",
    deleteMailTitle: "Delete message",
    deleteMailsDsc:
      "If a storage system is not active, the messages will be permanently deleted.<br/><b>The operation is not reversible<b>.",
    deleteMailsTitle: "Delet selected messages",
    dropFiles: "Release here the files to attach",
    emptyTrashDsc:
      "If a storage system is not active, emptying the trash, all messages will be eliminated <b>irreversibly</b>.<br/>After <b>30 days</b> the messages are deleted automatically.",
    emptyTrashTitle: "Empty trash",
    goToOldWebmailModal: {
      description:
        "<br/>We invite you to immediately use the new Webmail, which offers additional features such as: <br/> <ul> <li> Automatic identity management </li> <li> Shared address book and calendar </ li > <li> Zoom integration for video meetings </li> <li> Predefined messages </li> <li> Search all folders </li> <li> and more features </li> </ul> ",
      title: "The old Webmail will no longer be accessible from October 31st",
    },
    import: {
      messagesInvalid: "Not valid:",
      messagesNr: "Total messages to be imported:",
      messagesValid: "Valid:",
      desc: "You are importing messages in folder: <code>{{folderImport}}</code><br/>You can import messages from other email apps using a eml file (<strong>.eml</strong>).",
      dropFiles: "Upload or drop here the file to be imported",
      error: "Messages could not be imported",
      importing:
        "We are importing <b>{{messagesNumber}}</b> messages in folder: <code>{{folderImport}}</code>",
      loading: "Loading...",
      success: "Import successfull!",
      title: "Import messages",
      uploadedFile: "Uploaded",
      uploadingFile: "Uploading",
    },
    loading: {
      desc: "Your messages are coming, please wait.",
      title: "Loading",
    },
    markSpamReadDsc:
      "Mark all the messages in the folder as read.<br/>After <b>30 days</b> the messages are deleted automatically.",
    markSpamReadTitle: "Mark messages as read",
    maxLabelsNumberTitle: "Too many labels!",
    maxLabelsNumberDsc:
      "You have reached the maximum number of labels that can be associated with an message. To add a new label you must first remove one of those already present.",
    message: {
      add: "Add",
      addToAddressBook: "Add contact to address book",
      attachedMessage: "Attached message",
      attachments: "attachments",
      bugMsg: "Don't see the message?",
      cc: "Cc:",
      date: "Date:",
      draftsSelectedInfo: "Select a message from the list and continue to write.",
      downloadAll: "Download all",
      downloadAttachments: "Download attachments",
      editPartecipationStatusDecription: "",
      editPartecipationStatusTitle: "Edit partecipation status",
      eventActionAccept: "Accept",
      eventActionDecline: "Decline",
      eventActionTentative: "Maybe",
      eventAddToCalendar: "This event is not present in your calendar",
      eventAttendees: "Attendees",
      eventAttendeeStatusAccepted: "Event accepted",
      eventAttendeeStatusDeclined: "Event declined",
      eventAttendeeStatusTentative: "Tentative of partecipation",
      eventCounterProposal: "This message contains a counter proposal for the event",
      eventDeleted: "Event deleted",
      eventInvitation: "Event invitation:",
      eventLocationEmpty: "Not specified",
      eventModify: "Edit",
      eventNeedAction: "Confirm event partecipation",
      eventNotNeedAction: "Event already processed",
      eventOutDated: "The event has been modified",
      eventStatusAccepted: "Accepted",
      eventStatusDeclined: "Declined",
      eventStatusTentative: "Tentative",
      eventUpdate: "Update event",
      external: "External",
      externalLabel: "This email address is from outside your organization.",
      folderSelectedInfo: "Select a message from the list and discover its contents.",
      from: "From:",
      hideAllAttachments: "Hide",
      hugeMessage:
        "Content too big to display entirely, click the link below to view the message source code.",
      hugeMessageNotice: "Message truncated",
      inboxSelectedInfo: "Select a message from the list and find out who wrote you.",
      isMailingList: "This message is from a mailing list.",
      localAttachments: "There are additional attachments inside the event",
      message: "message",
      messageForwarded: "Forwarded message",
      messages: "messages",
      messagesQuota: "Used messages quota:",
      newMessageinThread: "There is a new message",
      noContent: "This message has no content.",
      notSelected: "Select a message",
      oneSelectMessages: "Selected message",
      oneSelectThreads: "Seleted thread",
      readNotificationLabel: "{{Sender}} asked reading confirmation for the message.",
      readNotificationLabelSimple: "Asked reading confirmation for message.",
      readNotificationResponse:
        "<P>Message<BR><BR>&nbsp;&nbsp;&nbsp; A:&nbsp; %TO%<BR>&nbsp;&nbsp;&nbsp; Subject:&nbsp; %SUBJECT%<BR>&nbsp;&nbsp;&nbsp; Sent:&nbsp; %SENDDATE%<BR><BR>it was read the day %READDATE%.</P>",
      readNotificationSubjectPrefix: "Read:",
      replyTo: "Reply to:",
      sender: "Sender:",
      sentSelectedInfo: "Select a message from the list and see who you wrote.",
      showAllAttachments: "Show other",
      showMoreThread: "Show more",
      selectMessages: "Selected messages",
      selectThreads: "Selected thread",
      spamNotSelected: "Keep the folder in order",
      spamSelectedInfo: "Check messages and mark spam as read.",
      subject: "Subject:",
      to: "To:",
      trashNotSelected: "Check the trash",
      trashSelectedInfo: "You can recover messages from the trash within 30 days.",
      updating: "Edit in progress",
      unsubscribedMailingList: "You removed yourself from this mailing list.",
      yesterday: "Yesterday",
      wrote: "wrote:",
    },
    messagesList: {
      allMessagesLoaded: "All messages have been uploaded",
      ctaDeletedMessages: "Compact folder",
      ctaSpamInfo: "Mark all as read",
      ctaTrashInfo: "Empty trash",
      deletedMessages:
        "There are messages awaiting deletion, compact the folder to complete the operation.",
      folderEmpty: "This folder is empty",
      folderInfo: "Start a conversation or move a message.",
      foundMessages: "Found",
      foundMessagesNum: "Found: <b>{{found}}</b> of <b>{{total}}</b>",
      moveMessage: "Move message",
      moveMessages: "Move {{NumMessages}} messages",
      notFound: "No messages found",
      notFoundInfo: "The search did not produce results, try again using different criteria.",
      pullDownToRefresh: "Drag to update",
      releaseToRefresh: "Release to update",
      searchInfo: "messages found",
      searchLimited:
        "Indexing in progress. The search is limited to the <b>single folders</b> and the <b>from</b>, <b>to</b> and <b>subject</b> fields of the message.",
      searchNotAvailable: "Search not available",
      searchNotAvailableInfo: "The search is currently unavailable, please try again later",
      selectMessages: "Selected",
      showMoreThread: "Show more",
      spamEmpty: "All spam has run away!",
      spamInfo: "Messages in spam are automatically deleted after 30 days.",
      trashEmpty: "The trash is empty",
      trashInfo: "Messages in trash are deleted automatically after 30 days.",
      totalMessages: "Messages",
      totalMessagesNum: "Messages: <b>{{total}}</b> ",
    },
    mtm: {
      archivePromo:
        "<b> But that's not all ... </b> <br/> <br/> The email archive service provides you a twin, read-only mailbox, where all sent and received messages are stored by users, for 10 years without space limits.",
      backupSelector: "Select a backup to continue",
      description:
        "Using this service you can access the backups of your mailbox made in the last 15 days, check the status of your backups or restore messages.",
      title: "Welcome in Mail Time Machine",
    },
    newMessage: {
      addAttach: "Add attachment",
      addHTMLTitle: "Insert HTML",
      addImgeDsc:
        "You can insert images directly inline, in the body of the message or attach them to the message.",
      addImgeTitle: "Insert images",
      addLinkTitle: "Insert link",
      advanced: "Advanced",
      attachInfo: {
        noAttach: "There are no attachments",
        attachNumber: "Attachments:",
      },
      editLinkTitle: "Edit link",
      bcc: "Bcc",
      cc: "Cc",
      cancelSend: "Sending mail successfully canceled",
      delete: "Delete",
      deleted: "Message deleted successfully",
      deleteInProgress: "Message deletion in progress",
      discardChanges: "Discard changes",
      fontSize: {
        smaller: "Smaller",
        small: "Small",
        normal: "Normal",
        medium: "Medium",
        big: "Big",
        bigger: "Bigger",
      },
      from: "From",
      hide: "Hide",
      invalidMails: "Invalid mail address is present, check addresses and try again",
      moreAttachments: "Others",
      noDraftChanged: "No change to save",
      object: "Subject",
      saveDraftDsc:
        "The message has not been sent and contains unsaved changes. You can save it as a draft and resume writing later.",
      saveDraftTitle: "Save message as draft?",
      savedDraft: "Draft saved!",
      savingDraft: "Save in progress",
      sendInProgress: "Send message in progress",
      sent: "Message sent successfully",
      sizeExceeded: "Attachments too large. The maximum sending size is of {{messageMaxSize}} MB.",
      templateCreateModal: {
        description:
          "<br/>Create your first canned message to make composing recurring emails easier. You can choose a custom subject and add attachments to be sent automatically in the email message.",
        title: "You don't have canned messages yet",
      },
      templateSubjectModal: {
        description:
          "A custom object is defined in the selected canned message. Do you want to replace the one in the compose window or do you want to keep it?",
        title: "Subject already present",
      },
      to: "To",
      toMore: "Others",
      useTemplate: "Canned message",
      windowSubject: "New message",
    },
    reportBug: {
      title: "Report message",
      message: {
        issue:
          "If you don't see the message correctly, you can help us solve the problem and improve the service.<br/>If you have any questions or problems regarding the use of webmail, please contact your technical referent for assistance.",
        issueFormatting:
          "Is the message content not show correctly? You describe the problem, we will do everything possible to fix it in the next updates.",
        issueBlank:
          "When the messages are devoid of any content, these are indicated in the Webmail interface with a special banner.<br/><br/>If this banner is not present, it could be a formatting problem, so <b>check for the presence of the banner</b> and maybe report the message as <code>not correctly formatted</code>.",
        issueAttach:
          "Does the message appear to be free of attachments? Probably the sender sent the message forgetting to insert the attachments.<br/><br/><b>Ask the sender to verify and resend the attachments to youu</b>.",
        issueOther:
          "You describe the problem, we will do everything possible to fix it in the next updates.<br/>If you have any questions or problems regarding the use of webmail, please contact your technical referent for assistance.",
        disclaimer:
          "Sending this feedback, your message can will be analysed by our development team to improve the service.<br/><br/><b>The information will NOT be shared with third parties and the data will be processed in compliance with current legislation on Privacy</b>.",
      },
    },
    restoreRequest: {
      desc: "You have requested the restore of the <b>{{username}}</b> mailbox with the backup dated <b>{{restore_date}}</b>.<br/>With this operation we will restore all the messages present in the backup indicated, without deleting any message that in the meantime has been received or sent from the mailbox.<br/><br/><b>The restore operation is subject to a cost.</b><br/><br/>Do you want to proceed with the request?",
      restoreRequested:
        "We received your restore request. You will be contacted as soon as the procedure will be completed.",
      title: "Request a restore",
      titleRestoreRequested: "Request sent",
      deniedTitle: "Request denied",
      restoreRequestDenied:
        "There is a pending restore request for this account. It is not possible to request more than one restore each time.",
    },
    searchMail: {
      attachments: "Attachments",
      cleanFilters: "Clean filters",
      marked: "Starred",
      results: "Search results",
      searchIn: "Search in",
      allFolders: "All folders",
      currentFolder: "Current folder",
    },
    sidebar: {
      createLabel: {
        desc: "",
        title: "Create label",
      },
      createFolder: {
        desc: "",
        title: "Create folder",
      },
      modifyFolder: {
        desc: "",
        title: "Edit folder",
      },
      restoreFolder: {
        desc: "",
        title: "Restore folder",
      },
      folder: "Folders",
      folders: "Personal folders",
      labels: "Labels",
      newFoderName: "New folder name",
      occupiedSpace: "Used space",
      sharedFolders: "Shared folders",
      unlimitedSpace: "Unlimited space",
    },
    thanksMailLabel: "OK, thanks!",
    tooManyCompositionsDsc:
      "You have reached the maximum number of new messages that you can write at the same time. Complete at least one message from the ones you are writing to start a new composition.",
    tooManyCompositionsTitle: "Finish writing!",
    unsubscribeListDsc: "Stop receiving messages for this mailing list?",
    unsubscribeListTitle: "Cancel subscription",
  },

  mailboxes: {
    archive: "Archive",
    drafts: "Drafts",
    inbox: "Inbox",
    more: "More",
    sent: "Sent",
    shared: "Shared folders",
    spam: "Spam",
    trash: "Trash",
  },

  navbar: {
    addressbook: "Contacts",
    calendar: "Calendar",
    chat: "Chat",
    mail: "Mail",
    meeting: "Meeting",
    news: "News",
  },

  news: {
    notFound: "News not found",
    notFoundInfo: "The search did not produce results, try again using different criteria.",
  },

  newsTags: {
    news: "News",
    suggestions: "Tips",
    fix: "Fix",
    comingSoon: "Coming soon",
    beta: "Beta",
  },

  pageLogout: {
    title: "Logout in progress",
    desc: "",
  },

  pageIndexing: {
    title: "Your account is indexing",
    desc: "The operation may take some time, please wait.",
  },

  pageNotFound: {
    pageNotFound: "Something went wrong",
    pageNotFoundInfo: "The page you are looking for is not available, do not lose hope!",
  },

  powered: "powered by Qboxmail",
  poweredCollaborationWith: "in collaboration with ",

  radioButtons: {
    labels: {
      askDeliveryConfirmation: "Delivery message confirmation",
      askReadConfirmation: "Reading message confirmation",
      defaultView: "Default layout",
      newEventFreeBusy: "Show new events availability",
      newEventTimeInterval: "New event default time interval",
      newEventType: "New events type",
      other: "Other",
      reportBugBlank: "The message appears blank",
      reportBugNoAttachments: "The message has no attachments",
      reportBugNoFormatted: "The content is not properly formatted",
      selectIssue: "What is your issue?",
    },
  },

  shareOptions: {
    delete: "Deletion",
    read: "Reading",
    update: "Editing",
    write: "Writing",
  },

  shareOptionsCalendar: {
    canCreateObjects: "Allow to insert events in this calendar",
    canEraseObjects: "Allow to delete events in this calendar",
  },

  shortcuts: {
    addressbook: {
      newContact: "New contact",
      editContact: "Edit contact",
      deleteContact: "Delete contact",
    },
    calendar: {
      newEvent: "New event",
      editEvent: "Edit event",
      deleteEvent: "Delete event",
      moveRangeNext: "View next interval",
      moveRangePrevious: "View previous interval",
    },
    general: {
      switchModuls: "Switch modules",
      refresh: "Refresh page",
      tabForward: "Move forward among the clickable elements",
      tabBack: "Move back among the clickable elements",
      closeModal: "Close modal",
      openSettings: "Open settings",
      copy: "Copy selected item",
      past: "Paste selected item",
      cut: "Cut selected item",
    },
    mail: {
      confirm: "Confirm",
      deleteMessage: "Delete message",
      deleteSelectMessage: "Delete selected messages",
      editAsNew: "Edit as new",
      empityTrash: "Empty trash",
      expandThread: "Expand thread",
      extendSelectDown: "Extend selection down on messages list",
      extendSelectUp: "Extend selection up on messages list",
      forward: "Forward",
      markRead: "Mark as read/unread",
      moveDown: "Move down on messages list",
      moveUp: "Move up on messages list",
      newMessage: "New message",
      openSelectMessage: "Open selected message",
      printMessage: "Print message",
      reduceThread: "Reduce thread",
      reply: "Reply",
      replyAll: "Reply all",
      thanks: "Thanks",
    },
  },

  settings: {
    addressbook: {
      management: {
        automaticSave: {
          desc: "Choose if collect all contacts not present in your address books in automatic way.",
          title: "Automatic save",
        },
        personalAddressbooks: {
          desc: "Manage your personal address books and decide if you want share them with other user.",
          headerActiveSync: "Sync",
          headerItem: "Address book",
          placeholderList: " ",
          title: "Personal address book",
        },
        sharedAddressbooks: {
          desc: "Manage address books shared with you by other users.",
          headerItem: "Subscribed address book",
          placeholderList: " ",
          title: "Shared address book",
        },
        title: "Address books",
      },
      title: "Contacts",
      view: {
        desc: "Manage your preferences for contacts and address books visualization.",
        title: "View contacts",
      },
    },
    calendar: {
      events: {
        title: "Events",
        desc: "Manage your preferences for new events for all calendars, if it isn't set a specific default.",
        alertTitle: "Alerts",
        alertDesc:
          "Manage your preferences for event alerts for all calendars, if it isn't set a specific default.",
        personalMeetingRoomTitle: "Personal meeting room",
        personalMeetingRoomDesc:
          "Generate a room in your online meeting application and enter the link here. It can then be selected as 'Location' when creating an event.",
      },
      invitations: {
        desc: "Choose if to enable events invitations only for users you want.",
        title: "Events invitations",
        msgFromHeader: "Allow invitations only from",
        placeholderList: " ",
      },
      labels: {
        title: "Calendar labels",
        titleSettingsPage: "Calendar labels",
        desc: "Create custom colored labels to keep your events in order.",
        deleteLabelDsc: "Deleting the label will remove it from all the calendar events.",
      },
      management: {
        title: "Calendars",
        holidayCalendars: {
          title: "Holiday calendars",
          desc: "Choose holidays calendars that you prefer.",
          headerItem: "Calendars",
          placeholderList: " ",
        },
        personalCalendars: {
          title: "Personal calendars",
          desc: "Manage your personal calendars and decide if you want share them with other user.",
          headerActiveSync: "Sync",
          headerItem: "Calendars",
          placeholderList: " ",
        },
        sharedCalendars: {
          desc: "Manage calendars shared with you by other users.",
          headerActiveSync: "Sync",
          headerItem: "Subscribed calendars",
          placeholderList: " ",
          title: "Shared calendars",
        },
        includeInFreeBusy: "Include in Free/Busy",
        showActivities: "Show activities",
        showAlarms: "Show alarms",
        syncWithActivesync: "Synchronize using Microsoft® Exchange ActiveSync",
        sendMeMailOnMyEdit: "Send me an email when I modify the calendar",
        sendMeMailOnOtherEdit: "Send me an email when someone modifies the calendar",
        sendMailOnEditTo: "When I modify send an email to",
      },
      view: {
        desc: "Manage your preferences for calendars visualization.",
        showBusyOutsideWorkingHours: "Show as busy outside working hours",
        showWeekNumbers: "Show week number",
        title: "View calendars",
      },
      title: "Calendar",
    },
    chat: {
      title: "Chat",
      view: {
        title: "View",
      },
    },
    general: {
      integrations: {
        desc: "Manage integrations with service providers outside the webmail.",
        title: "Integrations",
        card: {
          zoom: {
            askSeller: "Ask your reseller for more information",
            title: "Zoom",
            text: "Save time when scheduling meetings adding an unique Zoom conference details to an event.",
          },
        },
      },
      notifications: {
        title: "Push notifications",
        generalNotification: {
          desc: "Enables notifications indicating the receipt of a new message.",
          longDesc:
            "Allow Webmail to send notifications via your browser when you receive a new message. This setting is not sufficient to receive notifications, you must also enable notifications for each browser you intend to use.",
          title: "General setting of notifications",
        },
        allowedPush: {
          allowed:
            "Notifications enabled on the browser in use. To receive them, they must also be enabled in the section above.",
          default:
            "If you would like your current browser to notify you with a notification when you receive a new message, you must enable notifications (in the section above) and then enable push notifications in your browser. Click on the button and allow notifications, or click on the lock icon and allow notifications by pressing the Allow button.",
          isIos:
            "If you wish to receive notifications on your iOS device (version 16.4 and higher), you need to add Webmail to your device's home screen.",
        },
        browserNotification: {
          desc: "Check the status and manage notifications for the browser currently in use.",
          title: "Status of notifications of the browser in use",
        },
        granted: "Your browser notifications are correctly configured!",
        noPush: {
          title: "Unfortunately, the Safari browser does not support the notification system.",
          titleios:
            "Unfortunately, the iOS operating system does not support browser notifications.",
          desc: "To enable notifications use the most updated version of one of the following browsers",
        },
        deniedPush: {
          title: "Your browser is blocking push notifications.",
          desc: "Remove the block to activate push notifications when a new message arrives.",
        },
        modal: {
          title: "Would you like to allow push notifications?",
          text: "You can always allow or block them at any time from webmail settings.",
        },
      },
      parameters: {
        title: "Parameters",
        host: {
          title: "Device configuration",
          desc: "Connect your device to receive and send email with your account.",
        },
        imap: {
          title: "IMAP",
        },
        smtp: {
          title: "SMTP",
        },
      },
      profile: {
        email: "User email",
        generalSettings: {
          desc: "Manage preferences about language and time.",
          title: "General settings",
        },
        personalInfo: {
          desc: "Manage your profile informations.",
          title: "Personal information",
        },
        title: "Profile",
      },
      security: {
        changepassword: {
          info: "Password of at least 8 alphanumeric characters",
          desc: "Manage password to access your webmail.",
          resetpassword: "Set new password",
          resetpassworddisabled: "Password change is disabled on this account",
          resetpasswordexpired: "Your password is expired, set a new one",
          title: "Change password",
        },
        days: "day/s",
        passwordexpiration: {
          activeExpiration: "Automatic password expiration is enabled for your email account.",
          desc: "Check the status of your account password.",
          expirationDate: "The password expires on",
          expirationCountdown: "The password expires in",
          modalTitle: "Your password is about to expire",
          modalDesc:
            "There is/are {{password_expiration_relative_days}} day/s left until your account password expires. We recommend that you change it right away.",
          title: "Password expiration",
        },
        otp: {
          cantDisableOtp: "Two-factor authentication can't be disabled on this account",
          desc: "Manage two factor authentication to access your webmail.",
          disableOtp: "Disable two-factor authentication",
          downloadParams: "Download activation data",
          hideParams: "Hide parameters",
          instructionDisableOtp:
            "Enter the code generated by the application in the form below to disable two-factor authentication for this account.",
          instructionsSetOtp:
            "Scan the QRCode with the application and enter the code generated in the form below. Or enter the parameters for manually activation.",
          labelEnterCode: "Enter code generated by the application",
          paramAccount: "Account",
          paramCode: "Code",
          paramType: "Time based",
          paramTypeVal: "Active",
          params: "Enter code manually",
          paramsInstruction: "Enter the following parameters in the application",
          setOtp: "Enable two-factor authentication",
          title: "Set OTP",
          titleDisableOtp: "Disable OTP",
          titleSetOtp: "Enable OTP",
        },
        sessions: {
          browser: "Browser:",
          currentSession: "Current",
          device: "Device:",
          desc: "Manage access sessions to your webmail.",
          ip: "IP:",
          os: "OS:",
          platform: "Platform:",
          removeAll: "Remove all",
          removeSession: "Remove",
          startdate: "Start:",
          title: "Open sessions",
        },
        title: "Security",
      },
      title: "General",
    },
    mail: {
      accounts: {desc: "", title: "Accounts"},
      antispam: {
        blacklist: {
          desc: "Add address or domain to list (es. 'name@domain' or '*@domain')",
          msgNoHeader: "Not allow messages from",
          title: "Black list",
        },
        deleteRuleDsc: "Delete rule set to <code>{{ruleEmail}}</code>.",
        deleteRuleTitle: "Delete antispam rule",
        placeholderList: " ",
        title: "Antispam",
        whitelist: {
          desc: "Add address or domain to list (es. 'name@domain' or '*@domain')",
          msgFromHeader: "Allow messages from",
          msgToHeader: "Allow messages to",
          title: "White list",
        },
      },
      autoresponder: {
        desc: "Set an automatic reply message for when you are out of office or you can't reply to received messages.<br/>If a contact has sent you several messages, the automatic reply will be sent only once every 24 hours.",
        msg: "Message",
        placholdeSubject: "Subject",
        placholderTextarea: "Message text",
        title: "Autoresponder",
      },
      compose: {
        cancelSend: {
          desc: "Choose the timeout to cancel the sending of a message in progress, if you decide you don't want to send the message anymore.",
          title: "Cancel send email",
        },
        confirmations: {
          desc: "Manage reading and delivery notification for yours received and sent messages.",
          title: "Reading / delivery confirmation",
        },
        title: "Composition",
      },
      delegations: {desc: "", title: "Delegation"},
      filters: {
        actionsTitle: "Actions",
        activeFiltersTitle: "Active rules",
        desc: "Create specific rules to sort incoming messages and organize them as you want in your mailbox.",
        headerItem: "Rule",
        headerStatus: "Active",
        hintEqualOperator:
          "Attention: the use of the <em><b>is equal to</b></em> / <em><b>is not equal to</b></em> operator is recommended only to expert users. Alternatively, it is recommended to use the operator <em><b>contains</b></em> / <em><b>not contains</b></em>. <br>To use the <em><b>is equal to</b></em> / <em><b>is not equal to</b></em> operator, you must match all the elements that make up the field. For example, to indicate the <em>Sender</em> you must indicate all the following elements: <b>description &lt;email address&gt;<b>.",
        parametersTitle: "Parameters",
        placeholderList: {
          parameter: "Add parameter to the rule",
          action: "Add action to the rule",
        },

        title: "Rules",
      },
      folders: {
        compactFolder: "Remove all messages marked as deleted from the folder",
        deleteFolderDsc:
          "Deleting the <code>{{folderName}}</code> folder will delete all messages in it.<br/><b>The operation is not reversible</b>.",
        deleteFoldersTitle: "Delete folders",
        desc: "Manage and share your personal folders",
        descShared: "Manage your shared folders",
        headerItem: "Folders",
        headerMsg: "Messages",
        headerPermissions: "Permissions",
        headerSelectedUsers: "Selected users",
        headerUnread: "Unread",
        modifyFolder: "Edit folder",
        newFolder: "Add new folder",
        retention: "Automatic deletion rules set",
        rootFolder: "-- Root --",
        shared: "Shared with other users",
        subscribe: "Subscribe",
        tabInfo: "Folder info",
        tabShare: "Share folder",
        title: "Folders",
        titleShared: "Shared folders",
      },
      forward: {
        description: "Choose the email addresses to forward the messages you receive to.",
        headerItem: "Recipients",
        placeholderList: " ",
        title: "Forward messages",
        titleSection: "Forward messages",
      },
      labels: {
        desc: "Create custom colored labels to keep your email messages in order.",
        headerItem: "Labels",
        deleteLabelTitle: "Delete label",
        deleteLabelTitleDsc: "Deleting the label will remove it from all messages.",
        placeholderList: " ",
        title: "Mail labels",
      },
      reading: {
        layout: {
          desc: "Choose how you want the reading pane to appear.",
          title: "Layout",
        },
        markReadSettings: {
          desc: "Set when a message should be marked as read.",
          title: "Mark message as read",
        },
        readingSettings: {
          desc: "Set your reading preference for messages.",
          title: "Reading settings",
        },
        title: "View",
      },
      signature: {
        title: "Signature",
        bcc: {
          headerItem: "Bcc recipients",
          placeholderList: "",
        },
        default: "Default",
        deleteNewSignatureModal: {
          description:
            "The content of the new signature has not been saved, it will be lost if you open another one.<br/>Do you want to continue ?",
          title: "Delete new signature",
        },
        dropFiles: "Drop here the image to add",
        management: {
          title: "Signature management",
        },
        onlyNewMessages: "Don't add signature on replies",
        placeholderList: "Add your first identity",
        senderBcc: "Add sender in Bcc",
        setAsDefault: "Set as default sender",
        signatures: {
          desc: "For each identity (group of aliases) associated with your account you can customise the signature at the bottom of the emails you send and the name displayed by those who receive your messages. Choose the default sender and add email address lists in Bcc.",
          headerItemSignature: "Display name",
          headerItemIdentity: "Identity",
          title: "Signatures and identities",
        },
      },
      template: {
        addAttachment: "Select a file to add it as an attachment to the message",
        deleteTemplateModal: {
          description:
            "Confirm to delete the selected message? The files attached to the message will also be deleted from our systems.",
          title: "Delete canned message",
        },
        title: "Canned messages",
        description:
          "Select a canned message from the list to automatically fill in the new composing message",
        placeholderList: "Add your first canned message",
        placeholderSearch: "Filter messages",
        searchHint:
          "Use this field to filter the canned message list below. The filter works on the name, subject and content of the message.",
        templates: {
          desc: "Simplify composing recurring emails by saving canned messages to choose from when composing the email.",
          headerItemPreview: "Preview",
          headerItemSubject: "Subject",
          headerItemTemplate: "Name",
          maxAttachmentsNrBasic:
            "Maximum {{attachmentNr}} attachments. Maximum {{templateSize}} MB in total. Contact your email service provider to increase these limits.",
          maxAttachmentsNr:
            "Maximum {{attachmentNr}} attachments. Maximum {{templateSize}} MB in total.",
          maxTemplateNrReached:
            "The maximum number of configurable canned messages has been reached.",
          maxTemplateNrReachedContactReseller:
            "The maximum number of configurable canned messages has been reached. If you need to add more email templates, please contact your email service provider for more information.",
          newTemplate: "New canned message",
          title: "Canned messages",
        },
      },
      title: "Mail",
    },
    meeting: {
      title: "Meeting",
      view: {
        desc: "",
        title: "View",
      },
    },
    news: {
      readMore: "Read more",
      title: "News & Updates",
    },
    privacy: {
      title: "Privacy",
      cookie: {
        title: "Cookie Policy",
      },
      privacy: {
        title: "Privacy Policy",
      },
    },
    shortcuts: {
      title: "Keyboard shortcuts",
    },
    tasks: {
      notifications: {
        desc: "Receive an email when a task is assigned to you or when a task you have assigned is closed",
        title: "Email notifications",
      },
      labels: {
        title: "Tasks labels",
        desc: "Create custom colored labels to catalog your tasks.",
      },
      title: "Tasks",
    },
    title: "Settings",
    unsaved: "There are unsaved changes",
  },

  tasks: {
    add: "Create task for my list",
    assignedBy: "Assigned by",
    assignedTaskLabel: "<b>{{user}}</b> assigned to you a new task:",
    assignedTaskTitle: "New task assigned",
    assignedTo: "Assigned to",
    assignTask: "Create task to assign",
    basic: {
      label:
        "Tasks management is a service available<br />when you update your profile.<br /><br />The update also includes shared calendar<br />and built-in video meeting.",
      modalTitle: "Tools to optimize your work",
      modalSubTitle: "available with profile update",
      modalFooter:
        "Your technical agent can present you in detail the additional features, without obligation",

      calendarLabel: "Shared <b>Calendar</b>.",
      tasksLabel: "<b>Tasks</b> and reminders.",
      signatureLabel: "Centralized email <b>Signature</b>.",
      zoomLabel: "Built-in <b>Zoom</b> for video meeting.",
      requestInfo: "I'm interested",
      requestInfoConfirmation: {
        text: "You will be contacted by your technical agent.",
        title: "The request for information has been sent.",
      },
      requestLater: "Maybe later",
    },
    closedTaskLabel: "<b>{{user}}</b> completed a task:",
    closedTaskTitle: "Assigned task completed",
    completionDate: "Completed",
    deleteTaskModal: {
      desc: "Are you sure you want to delete the selected task? If the task has been assigned to other users, it will be deleted for them as well.",
      title: "Delete task",
    },
    dueTime: {
      today: "Today",
      tomorrow: "Tomorrow",
      nextWeekend: "Next weekend",
      thisWeekend: "This weekend",
      custom: "Date and Time",
    },
    labels: "Labels",
    deleteLabelTitle: "Delete label",
    deleteLabelDsc:
      "This label has been assigned to one or more activities. Proceed with its elimination?",
    linkedMail: "Linked email",
    listImagesLabels: {
      completed: {
        text: "The list of completed tasks is empty",
        title: "No tasks completed",
      },
      overdue: {
        text: "You have no overdue tasks yet to do",
        title: "Good job",
      },
      notCompleted: {
        text: "You have not planned any tasks to do",
        title: "Nothing to do here",
      },
      search: {
        text: "Write something to run a search",
        title: "Search...",
      },
      assignedToDo: {
        text: "The list of assigned tasks is empty",
        title: "You have not assigned any activities",
      },
      assignedCompleted: {
        text: "The list of completed assigned tasks is empty",
        title: "No assigned tasks completed",
      },
      noResult: {
        title: "No results found",
      },
    },
    lists: "Lists",
    modalTitle: "Task details",
    note: "Notes (1000 characters maximum)",
    occurrences: {
      all: "All occurrences",
      occurrence: "Only this occurrence",
    },
    openedTaskLabel: "<b>{{user}}</b> has reopened a completed task:",
    openedTaskTitle: "Assigned task re-opened",
    openMessageModal: {
      desc: "If you open the message linked to the task, the task list will be closed.",
      title: "Do you want to open the message?",
    },
    overdueTasksPresent: "Overdue tasks: {{overdueTasksPresentCount}}",
    planned: "When",
    repeat: "Repeat",
    repetitions: {
      NEVER: "Never",
      DAILY: "Daily",
      WEEKLY: "Weekly",
      MONTHLY: "Monthly",
      YEARLY: "Yearly",
    },
    showMyTasks: "My tasks",
    showAssignedTasks: "Assigned to others",
    task: "Task",
    taskFromNotification:
      "Do you want to view the details of the notified task and lose the data of the new task being composed?",
    title: "Tasks",
    types: {
      view_todo: "To do",
      view_all: "All",
      view_today: "Today",
      view_next7: "Next 7 days",
      view_overdue: "Overdue",
      view_completed: "Completed",
    },
  },

  toast: {
    error: {
      alreadyPresent: "Warning, the resource already exists",
      avatarTooBig: "Warning, avatar size too big",
      compact: "Error compacting folder",
      connectionUnavailable: "No connection available",
      delete: "Error on deletion",
      deleteDraft: "Error on draft deletion",
      emailAddressNotValid: "Email address is not valid",
      enqueued: "Updating settings, try again",
      fetchingAttachments: "Error fetching attachments",
      filterActionsMissing: "Actions not present",
      filterConditionsMissing: "Parameters not present",
      filterNameMissing: "Rule name missing",
      folderCreation: "Error creating new folder",
      folderCreationCharNotValid: "Error creating/renaming folder, character not valid ({{char}})",
      folderCreationNoName: "Error creating folder, you need to specify a valid name",
      folderDelete: "Error deleting folder",
      folderNotPresent: "Folder not present",
      folderRename: "Error renaming folder, already present",
      folderSubscribe: "Error subscribing folder",
      generic: "Something went wrong",
      invalidDateRange: "Date range not valid",
      maxMembers: "Warning, maximum number of members achieved",
      maxSignatureSize: "Maximum signature size exceeded. Max {{maxSize}}",
      maxTemplateAttachmentsNumberReached:
        "The limit of attachments for this canned message has been reached",
      maxTemplateSize: "Warning, canned message size too large",
      maxTemplatesNumberReached:
        "The limit of canned messages that can be configured for this account has been reached",
      messageCopy: "Error copying messages",
      messageMove: "Error moving messages",
      messageNotFound: "Message not found",
      messageRemove: "Error removing messages",
      missingParameters: "Missing parameters",
      missingSettings: "Missing user settings",
      notifications: "Error getting notifications",
      notPermitted: "Operation not permitted",
      notValid: "Warning, invalid value",
      onlyOneHomeAddress: "You can insert only one home address",
      onlyOneWorkAddress: "You can insert only one work address",
      save: "Error saving",
      saveAcl: "Errore saving folder permissions",
      saveEvent: "An error occurred, you may not have sufficient permissions on this calendar",
      saveZoomMeeting: "Unable to create the meeting on the Zoom platform",
      savingDraft: "Draft save in progress, please try again at the end",
      searchNotAvailable: "Search not available at the moment",
      sendingMessage: "Error on message delivery",
      serverDisconnection: "Server being updated, please try again later!",
      sessionExpired: "Session expired",
      smtpBlockedByAntispam: "Message not sent: blocked by antispam",
      smtpBlockedByAntivirus: "Message not sent: blocked by antivirus",
      smtpDisabled: "Message not sent: SMTP disabled on this account",
      smtpQuotaExceeded: "Message not sent: sent message quota exceeded",
      requestLimit: "Request number limit exceeded, try again later",
      requestError: "Request error has occurred, try again later",
      updateFolders: "An error occurred on folders update",
      updateMessageEvent: "Error getting event status update",
      updatingParentFlags: "Error updating message flags",
    },
    info: {
      newVersionAvailable: {
        desc: "This operation is safe, your settings will not be modified.",
        title:
          "New features are available, reload the page to update the webmail to the lastest version.",
      },
      serverReconnected: "Webmail back online",
      sourceMail: "Email source copied to clipboard",
    },
    progress: {
      newFolder: "New folder creating in progress...",
      operationInProgress: "Operation in progress...",
    },
    success: {
      compact: "Folder compacted successfully",
      copiedLink: "Link copied to clipboard",
      copiedMail: "Message successfully copied",
      copiedMailAddress: "Email address copied to clipboard",
      copiedText: "Text copied to the clipboard",
      createFolder: "Folder created successfully",
      delete: "Deleted successful",
      disabledOtp: "OTP disabled successfully",
      enabledOtp: "OTP enabled successfully",
      movedMail: "Message moved successfully",
      notificationEnabled: "Browser notifications successfully enabled",
      otpDisabled: "OTP successfully disabled",
      otpEnable: "OTP successfully enabled",
      save: "Saved successfully",
      saveAcl: "Permissions saved successfully",
      saveDraft: "Draft saved successfully",
      saveFolder: "Folder updated successfully",
      sentMail: "Message sent successfully",
      subscribeFolder: "Subscription updated successfully",
      updateMessageEvent: "Event status updated",
    },
    warning: {
      forwardSet: "At least one forwarding has been configured on this account",
      notificationNotSupported: "Warning, your browser does not support notifications",
    },
  },

  toggles: {
    labels: {
      allDayEvent: "All day",
      autoSaveContact: "Save automatically all recipients not present in your address books",
      denyInvites: "Prevent invitations to appointments",
      enableAutorespopnd: "Enable autoresponder",
      enableAutorespopndInterval: "Enable date range",
      enableBrowserNotification: "Enable browser notifications",
      enableDateSearch: "Enable date search",
      enableFullBody: "Enable full body search",
      enableNotification: "Enable browser notifications",
      keepCopy: "Keep copy of the message locally",
      showPriority: "Show received message priority",
      showThreads: "Show messages as thread",
      subscribeFolder: "Subscribe to a Folder",
      tasksEmailNotifications: "Enable email notifications",
    },
    hint: {
      enableFullBody:
        "The full body search is available only for a single folder. Select a folder to enable it.",
    },
  },

  wizard: {
    layout: {
      desc: "Customize your Webmail by choosing view settings that you prefer.",
      title: "View options",
    },
    wizardData: {
      desc: "Customize your profile by adding an image and completing the missing data",
      title: "Complete profile",
    },
  },
};
