/*********************************************************************************************************
 * English Copyright (C) 2017-2019 by Qboxmail Srl
 *
 * All rights reserved. No part of this publication may be reproduced, distributed, or transmitted in any
 * form or by any means, including photocopying, recording, or other electronic or mechanical
 * methods, without the prior written permission of the publisher, except in the case of brief quotations
 * embodied in critical reviews and certain other noncommercial uses permitted by copyright law. For
 * permission requests, write to the publisher at the address below.
 *
 * Qboxmail Srl - IT02338120971
 * https://www.qboxmail.it - info@qboxmail.it
 *
 * Italiano Copyright (C) 2017-2019 by Qboxmail Srl
 *
 * Tutti i diritti riservati. Nessuna parte di questa pubblicazione può essere riprodotta, memorizzata in
 * sistemi di recupero o trasmessa in qualsiasi forma o attraverso qualsiasi mezzo elettronico, meccanico,
 * mediante fotocopiatura, registrazione o altro, senza l'autorizzazione del possessore del copyright salvo
 * nel caso di brevi citazioni a scopo critico o altri usi non commerciali consentiti dal copyright. Per le
 * richieste di autorizzazione, scrivere all'editore al seguente indirizzo.
 *
 * Qboxmail Srl - IT02338120971
 * https://www.qboxmail.it - info@qboxmail.it
 *********************************************************************************************************/

export default {
  addressbook: {
    contact: {
      oneSelectContacts: "Contacto seleccionado",
      oneSelectLists: "Lista seleccionada",
      notSelected: "Seleccione un contacto",
      sectionLabels: {
        address: "Address",
        company: "Empresa",
        email: "Correo electrónico",
        info: "Info",
        telephone: "Teléfono",
        homeUrl: "Sitio web personal",
        workUrl: "Sitio web de la empresa",
      },
      sections: {
        cell: "Móvil",
        home: "Hogar",
        homeFax: "Enviar fax a casa",
        work: "Trabajo",
        workFax: "Enviar fax al trabajo",
        title: "Rol",
        company: "Empresa",
        note: "Notas",
        bday: "Cumpleaños",
      },
      selectContacts: "Contactos seleccionados",
      selectLists: "Listas seleccionadas",
      selectedInfo: "Seleccione un contacto de la lista para ver los detalles.",
    },
    contactsList: {
      emptyContacts: "Esta agenda está vacía",
      emptyContactsInfo: "Agregar un contacto a la agenda",
      emptyLists: "No hay listas",
      emptyListsInfo: "Añadir una nueva lista",
      foundContacts: "Encontrado",
      notFound: "No hay contactos",
      notFoundInfo:
        "La búsqueda no produjo ningún resultado, inténtalo de nuevo utilizando criterios distintos",
      totalContacts: "Contactos",
    },
    tabs: {
      contacts: "Contactos",
      lists: "Listas",
    },
    contextualMenuLabels: {
      address: "Dirección de correo",
      birthday: "Fecha de nacimiento",
      cancel: "Cancelar",
      cell: "Móvil",
      delete: "Borrar",
      downloadVCard: "Descargar vCard",
      email: "Email",
      newContact: "Nuevo contacto",
      createList: "Crear lista",
      newList: "Nueva lista",
      note: "Nota",
      phone: "Teléfono",
      shareVCard: "Compartir",
      showVCard: "Mostrar VCard",
      sendAsAttachment: "Enviar por correo electrónico",
      sendMail: "Enviar correo electrónico",
      url: "URL",
      info: "Info",
      title: "Rol",
      company: "Empresa",
      home: "Casa",
      homeFax: "Enviar fax a casa",
      work: "Trabajo",
      workFax: "Enviar fax al trabajo",
      nickname: "Apodo",
      displayName: "Nombre mostrado",
      companyName: "Nombre",
      homeUrl: "Sitio web personal",
      workUrl: "Sitio web de la empresa",
      team: "Equipo",
      merge: "Fusionar",
    },
    deleteContactDsc:
      "Al eliminar el contacto <code>{{contact}}</code> toda la información relacionada con este contacto se eliminará también.<br/><b>La operación no es reversible.</b>.",
    deleteContactDscList:
      "Al eliminar el contacto seleccionado también se eliminará toda la información relacionada.<br/><b>La operación no es reversible.</b>.",
    deleteContactTitle: "Eliminar contacto",

    deleteContactsDsc:
      "Al eliminar estos contactos, toda la información relacionada con estos contactos se eliminarán también.<br/><b>La operación no es reversible.</b>.",
    deleteContactsTitle: "Eliminar contactos",

    deleteListDsc:
      "Al eliminar la lista <code>{{contact}}</code> toda la información relacionada con esta lista se eliminará también.<br/><b>La operación no es reversible.</b>.",
    deleteListTitle: "Eliminar lista",

    editContactModal: {
      title: "Editar contacto",
    },
    editListModal: {
      title: "Editar lista",
    },
    exportAddressBookModal: {
      desc: "Está exportando la agenda: <code>{{addressbookExport}}</code><br/>Por favor, seleccione el formato para exportar todos los contactos presentes",
      title: "Exportar agenda",
    },
    import: {
      contactsInvalid: "No es válido:",
      contactsNr: "Contactos totales a importar:",
      contactsValid: "Válido:",
      desc: "Vas a importar contactos a la agenda: <code>{{addressbookImport}}</code><br/>Vas a importar contactos a la agenda. Puedes importar contactos de otras aplicaciones de correo electrónico utilizando un formato vCard (<strong>.vcf</strong>) o <strong>.ldif</strong> archivo.\u000APor ejemplo, puedes exportar contactos desde Gmail o desde Outlook e importarlos aquí.\u000ALos contactos importados no van a sobreescribir a ninguno de los contactos existentes.",
      dropFiles: "Subir o soltar aquí el archivo que desea importar",
      error: "No pudieron importarse los contactos",
      importing:
        "Estamos importando <b>{{contactsNumber}}</b> evento en el calendario: <code>{{addressbookImport}}</code>",
      loading: "Cargando...",
      success: "Importación exitosa!",
      title: "Importar contactos",
      uploadedFile: "Subido",
      uploadingFile: "Subiendo",
    },
    list: {
      desc: "Al crear una lista de contactos, es posible enviar correos electrónicos a muchas personas a la vez. Se pueden añadir hasta 150 miembros eligiéndolos entre los contactos de la libreta de direcciones seleccionada.</br></br><b>Nota</b>: No es posible añadir direcciones de correo electrónico que no estén en la libreta de direcciones seleccionada. Añada primero los contactos a la libreta de direcciones y, a continuación, añádalos a la lista.",
      members: "Lista de miembros",
    },
    messages: {
      newContactAddressBookBody:
        "No se puede agregar contacto <b>Contactos corporativos</b>.<br/>Seleccione una agenda personal o compartida.",
      newContactAddressBookTitle: "Seleccionar agenda",
      resetListBody:
        "Miembros de listas estan relacionados con la agenda seleccionada. Este cambio va a reiniciar la lista de miembros. ¿Continuar?",
      resetListTitle: "Eliminación de miembros",
    },
    modifyAddressBookModal: {
      desc: "",
      title: "Editar agenda",
    },
    newAddressBookModal: {
      desc: "",
      title: "Añadir agenda",
    },
    newContactModal: {
      title: "Añadir contacto",
    },
    newListModal: {
      title: "Añadir lista",
    },
    shareModal: {
      desc: "Estás compartiendo la agenda: <code>{{addressbookShare}}</code><br/>Selecciona los contactos con los que deseas compartir la agenda y permiteles editarla.",
      title: "Compartir agenda",
    },
    sidebar: {
      allContacts: "Todos los contactos",
      deleteAddressbookDsc:
        "Al eliminar la libreta de direcciones <code>{{addressbook}}</code> se borrarán todos los contactos incluidos.<br/><b>La operación no es reversible.</b>.",
      deleteAddressbookTitle: "Eliminar agenda",
      globalAddressbook: "Contactos corporativos",
      personalAddressbook: "Contactos personales",
      sharedAddressbooks: "Agendas compartidas",
      userAddressbooks: "Agenda del usuario",
    },
    subscribeModal: {
      desc: "",
      noAddressbook: "No hay agendas a las que subscribirse",
      title: "Suscribirse a una Agenda compartida",
    },
  },

  app: {
    addressbook: "Agenda",
    calendar: "Calendario",
    chat: "Chat",
    meeting: "Reunión",
    mtm: "Mail Time Machine",
    of: "de",
    webmail: "Webmail",
    modal: {
      updateAvailable: {
        title: "Actualización disponible",
        description:
          "Hay una <b>nueva versión de Webmail</b> disponible.<br/>Haga clic para volver a cargar y actualizar, su configuración permanecerá sin cambios.<br/><br/>La aplicación se actualizará automáticamente entre:",
      },
    },
  },

  avatarEditorModal: {
    photoTitle: "Tomar una foto",
    title: "Editar avatar",
    zoom: "Zoom -/+",
  },

  banner: {
    info: {
      mailRetention: "Los mensajes en esta carpeta se eliminan automáticamente después de 30 días.",
    },
    warning: {
      labelCalendarUpdate:
        "Tenga en cuenta que si se cambia el nombre de una etiqueta, ya no será visible en los eventos en los que se utilice.",
      labelMailUpdate:
        "Tenga en cuenta que si se cambia el nombre de una etiqueta, ya no será visible en los correos electrónicos en los que se utilice.",
      labelTaskUpdate:
        "Tenga en cuenta que si se cambia el nombre de una etiqueta, ya no será visible en las actividades en las que se utilice.",
      mailRetention:
        "Atención, los mensajes se borrarán automáticamente de forma definitiva sin posibilidad de recuperación.<br><b>La cancelación será operativa en 24 horas.</b>",
    },
  },

  buttons: {
    accept: "Aceptar",
    add: "Añadir",
    addAction: "Agregar acción",
    addAddressbook: "Agenda",
    addAsAttachment: "Adjuntar",
    addAttachments: "Agregar adjuntos",
    addCalendar: "Calendario",
    addField: "Añadir campo",
    addHolidayCalendar: "Calendario de vacaciones",
    addLabel: "Agregar etiqueta",
    addInline: "Añadir en línea",
    addParameter: "Añadir parámetro",
    addSignature: "Añadir firma",
    addToList: "Añadir a la lista",
    allow: "Permitir",
    apply: "Aplicar",
    assign: "Asignar",
    backTo: "Atrás",
    backAddressbook: "Cerrar",
    cancel: "Cancelar",
    changeImage: "Cambiar imagen",
    changePassword: "Cambiar la contraseña",
    checkFreeBusy: "Ver disponibilidad",
    close: "Cerrar",
    createFolder: "Nueva carpeta",
    comeBackLater: "Vuelve mas tarde",
    configure: "Configurar",
    confirm: "Confirmar",
    copied: "Copiado",
    copy: "Copiar",
    copyLink: "Copiar link",
    decline: "Declinar",
    delete: "Eliminar",
    deleteDraft: "Eliminar borrador",
    details: "Detalles",
    disable: "Desactivar",
    disabled: "Desactivado",
    disableOTP: "Desactivar OTP",
    download: "Descargar",
    edit: "Editar",
    editLabel: "Editar etiqueta",
    editSignature: "Editar firma",
    empty: "Vacío",
    enable: "Habilitar",
    event: "Evento",
    export: "Exportar",
    generateNewPassword: "Generar nueva contraseña",
    generateRandomPassword: "Generar contraseña aleatoria",
    goToCalendar: "Ir al calendario",
    goToEventDay: "Ir al día del evento",
    goToMail: "Volver al correo",
    goToOldWebmail: "Ir al antiguo correo web",
    goToSettings: "Ir a la página de configuración",
    hide: "Esconder",
    ignore: "Ignorar",
    import: "Importar",
    insertHTML: "Insertar HTML",
    keep: "Mantener",
    label: "Etiqueta",
    later: "Después",
    learnMore: "Aprende más",
    leftRotate: "Girar 90 grados a la izquierda",
    loadImage: "Subir imagen",
    loading: "Cargando",
    logout: "Cerrar sesión",
    makePhoto: "Tomar una foto",
    markRead: "Leer",
    markSeen: "Marcar",
    markUnread: "No leído",
    message: "Mensaje",
    modify: "Editar",
    new: "Nuevo",
    newContact: "Nuevo contacto",
    newEvent: "Nuevo evento",
    newMessage: "Nuevo mensaje",
    newSignature: "Nueva firma",
    newTask: "Nueva tarea",
    newWebmail: "Nueva Webmail",
    next: "Siguiente",
    noThanks: "No, gracias",
    occurrence: "Ocurrencia",
    ok: "Ok",
    oldWebmail: "Vieja Webmail",
    openMap: "Abrir en mapa",
    otherOptions: "Otras opciones",
    override: "Anular",
    participate: "Unirse",
    postpone: "Posponer",
    reloadPage: "Recargar página",
    removeImage: "Quita la imagen",
    rename: "Renombrar agenda",
    reorder: "Reordenar",
    reorderEnd: "Finalizar reorden",
    report: "Reportar",
    restore: "Solicitar restauración",
    retryImport: "Reintentar",
    save: "Guardar",
    saveDraft: "Guardar borrador y cerrar",
    saveNextAvailability: "Guardar disponibilidad sugerida",
    search: "Buscar",
    send: "Enviar",
    series: "Serie",
    setOtp: "Establecer OTP",
    share: "Compartir",
    show: "Mostrar",
    showAll: "Mostrar todo",
    showMore: "Mostrar más",
    showToDo: "Mostrar para hacer",
    showUrlsAddressbook: "Mostrar URLS de la agenda",
    showUrlsCalendar: "Mostrar URLS del calendario",
    snooze: "Posponer",
    starred: "Estrella",
    subscribe: "Suscribir",
    subscribeAddressbook: "Subscribir agenda",
    subscribeCalendar: "Suscribir calendario",
    tentative: "Tal vez",
    understand: "Entendido",
    unlink: "Remover link",
    unsetOtp: "Desactivar OTP",
    unsubscribe: "Darse de baja",
    unsubscribeList: "Cancel subscription",
    update: "Actualizar",
    updateFilter: "Actualizar filtro",
    defaultImg: "Usar imagen predeterminada",
    viewMap: "Ver el mapa",
  },

  buttonIcons: {
    activeSync: "Sincronizar con Microsoft® Exchange ActiveSync",
    activeSyncNot: "Desactivar Microsoft® Exchange ActiveSync",
    alignCenter: "Alinear al centro",
    alignLeft: "Alinear a la izquierda",
    alignRight: "Alinear a la derecha",
    backgroundColor: "Color de fondo",
    backTo: "Atrás",
    bold: "Negrita",
    cannedMsg: "Canned messages",
    close: "Cerrar",
    confirm: "Confirmar",
    createTask: "Create Task",
    delete: "Eliminar",
    download: "Descargar",
    downloadVCard: "Descargar vCard",
    edit: "Editar",
    emoji: "Emoji",
    forward: "Reenviar",
    fullscreen: "Pantalla completa",
    fullscreenNot: "Modo ventana",
    imageAdd: "Añadir imagen",
    indent: "Aumentar sangría",
    insertHTML: "Insertar HTML",
    italic: "Cursiva",
    link: "Insertar link",
    maintenance: "Compacta",
    maxmized: "Agrandar",
    minimized: "Reducir",
    more: "Más",
    moveDown: "Descender",
    moveUp: "Ascender",
    next: "Siguiente",
    orderList: "Lista de pedidos",
    outdent: "Disminuir sangría",
    pin: "Marcar",
    previous: "Anterior",
    print: "Imprimir",
    quote: "Cita",
    removeFormatting: "Eliminar formato",
    removeQuote: "Eliminar cita",
    reply: "Contestar",
    replyAll: "Contestar a todos",
    saveDraft: "Guardar borrador",
    sendDebug: "Enviar mensaje que no se puede visualizar",
    sendMail: "Enviar correo electrónico",
    sendByEmail: "Enviar por correo electrónico",
    share: "Compartir",
    showSidebar: "Mostrar / ocultar la barra lateral",
    showSourceCode: "Mostrar código fuente",
    showVCard: "Mostrar VCard",
    spam: "Marcar como spam",
    spamNot: "Marcar como no spam",
    startChat: "Comenzar chat",
    startMeeting: "Comenzar reunión",
    strike: "Tachar",
    subscribe: "Suscribir",
    textColor: "Color del texto",
    thanks: "Gracias",
    underline: "Subrayar",
    understand: "Entendido",
    undo: "Deshacer",
    unlink: "Remover link",
    unorderList: "Desordenar lista",
    unSubscribe: "Darse de baja",
  },

  calendar: {
    alarmDurations: {
      after: "después",
      before: "antes",
      day: "días",
      hour: "horas",
      minute: "minutos",
      second: "segundos",
      week: "semanas",
    },
    deleteEvent: "Borrar evento",
    deleteEventDsc: "¿Proceder a la eliminación del evento seleccionado?",
    deleteSeries: "Borrar serie",
    deleteSeriesDsc: "¿Proceder a la eliminación de la serie seleccionada?",
    event: {
      alarmsNotPresent: "Sin alertas",
      deleteEventOccurrenceTitle: "¿Eliminar evento o serie?",
      deleteEventOccurrenceDesc:
        "El evento que desea borrar tiene varios incidentes. Eliminar un incidente dejará inalterados los demás",
      eventNotes: "Notas del evento",
      eventAttendees: "Asistentes a eventos",
      fromDay: "de",
      labelsNotPresent: "Sin etiqueta",
      locationContextualMenuLabels: {
        zoomLabel: "Zoom",
        zoomHint: "Reunión web",
        personalMeetingLabel: "Sala de reuniones personal",
        personalMeetingHint: "Reunión web",
        locationLabel: "Reunión en persona",
        locationHint: "Establecer una dirección o lugar",
        textLabel: "Personalizado",
        textHint: "Insertar un texto personalizado",
      },
      locationSelector: "Seleccione la ubicación del evento",
      locationZoomNoMeeting:
        "Una vez que se guarde el evento, el enlace de la reunión de Zoom estará presente aquí",
      maxAttachmentsNumberTitle: "¡Demasiados archivos adjuntos!",
      maxAttachmentsNumberDsc:
        "Puede ingresar hasta 4 archivos adjuntos. Si necesita adjuntar más de 4 archivos, le sugerimos que cree una carpeta comprimida.",
      maxLabelsNumberTitle: "¡Demasiadas etiquetas!",
      maxLabelsNumberDsc:
        "Has alcanzado el máximo número de etiquetas. Para añadir una nueva etiqueta debes eliminar primero una de las ya presentes.",
      noTitle: "Intitulado",
      notIncludedInFreeBusy:
        "Este calendario no está incluido en Free/Busy. Esto implica que usted y las personas que invite aparecerán como <b>disponibles</b> durante los eventos creados en este calendario.",
      organizerTitle: "Creado por",
      pendingMsg: "Evento pendiente de confirmación",
      permissionDenied:
        "No puede ver los detalles del evento seleccionado, es posible que no tenga los permisos necesarios.",
      repeatEvent: "Este evento es parte de eventos recurrentes",
      saveEventOccurrenceTitle: "¿Mostrar evento o eventos recurrentes?",
      saveEventOccurrenceDesc:
        "El evento que deseas ver o editar esta repetido varias veces. Editar este evento dejará inalterado el resto",
      setAlert: "Configurar alerta",
      toDay: "para",
    },
    eventRepetition: {
      WeekDayNumberInMonth_1: "Primero",
      WeekDayNumberInMonth_2: "Segundo",
      WeekDayNumberInMonth_3: "Tercero",
      WeekDayNumberInMonth_4: "Cuarto",
      WeekDayNumberInMonth_5: "Quinto",
      never: "Nunca",
      after: "Después;repeticiones",
      inDate: "A fecha",
      end: "Fin de la repetición",
    },
    filterView: {
      listmonth: "Agenda",
      day: "Día",
      month: "Mes",
      week: "Semana",
      workWeek: "Semana de trabajo",
      year: "Año",
    },
    import: {
      contactsInvalid: "No es válido:",
      contactsNr: "Eventos totales a importar:",
      contactsValid: "Válido:",
      dropFiles: "Subir o soltar aquí el archivo que desea importar",
      error: "Los eventos no pudieron ser importados",
      importing:
        "Estamos importando <b>{{eventsNumber}}</b> evento en el calendario: <code>{{calendarImport}}</code>",
      info: "Estas importando eventos en el calendário: <code>{{calendarImport}}</code><br/>Puedes importar eventos de otras aplicaciones de correo electrónico usando un formato de archivo ICS. Por ejemplo, puedes importar eventos desde Gmail o desde Outlook en formato ICS e importarlos a Qboxmail.<br/><b>La importación no reemplazará ninguno de los ecentos existentes</b>.",
      loading: "Cargando...",
      success: "¡Todos tus eventos han sido importados con éxito!",
      title: "Importar eventos",
      uploadedFile: "Subido",
      uploadingFile: "Subiendo",
    },
    modifyCalendarModal: {
      desc: "",
      title: "Editar calendario",
    },
    newCalendarModal: {
      desc: "",
      title: "Agregar calendario",
      freeBusyInfo:
        "Si el calendario no está incluido en <b>Free/Busy</b>, usted y las personas que invite aparecerán como <b>disponibles</b> durante los eventos creados en este calendario.",
    },
    newEvent: {
      attachmentsList: {
        headerItem: "Archivos adjuntos",
        placeholderList: " ",
      },
      desc: "",
      dropFiles:
        "Subir o soltar aquí el archivo que deseas adjuntar<br>(máximo 4 archivos adjuntos, 3 MB cada uno)",
      freeBusy: {
        legend: {
          event: "Evento",
          busy: "Ocupado",
          waiting: "Esperando",
          availability: "Siguiente disponibilidad",
        },
      },
      hideDetails: "Ocultar detalles",
      participantsList: {
        headerItem: "Participantes",
        answeredHeaderItem: "Respondido",
        notAnsweredHeaderItem: "Esperando una respuesta",
        placeholderList: " ",
      },
      showDetails: "Mostrar detalles",
      tabAttachments: "Archivos adjuntos",
      tabDetails: "Detalles",
      tabParticipants: "Participantes",
      tabSeries: "Repeticiones",
      tabSettings: "Ajustes",
      title: "Crear evento",
      titleEdit: {
        event: "Evento",
        series: "Serie",
      },
      titleFreebusy: "Disponibilidad de los participantes",
    },
    nextAvailability: "Siguiente disponibilidad",
    searchEvents: {
      notFound: "No se han encontrado eventos",
      notFoundInfo:
        "La búsqueda no ha dado ningún resultado, inténtalo de nuevo utilizando diferentes criterios",
    },
    shareModal: {
      desc: "Estás compartiendo el calendario: <code>{{calendarShare}}</code><br/>Selecciona los contactos con los que quieres compartir el calendario y dejarles editar.",
      title: "Compartir calendario",
    },
    sidebar: {
      labels: "Etiquetas",
      personalCalendar: "Calendario personal",
      sharedCalendars: "Calendarios compartidos",
      userCalendars: "Calendarios de usuarios",
      deleteCalendarDsc:
        "Al borrar el calendario <code>{{calendar}}</code> se borrarán todos los eventos incluidos.<br/><b>Esta operación no es reversible</b>.",
      deleteCalendarTitle: "Eliminar calendario",
    },
    subscribeModal: {
      desc: "",
      noCalendar: "No hay calendarios a los que suscribirse",
      title: "Suscribirse a un calendario compartido",
    },
    today: "Hoy",
  },

  circularLoopBar: {
    uploading: "Subiendo",
  },

  comingSoon: "Desarrollo en progreso...",

  contactImport: {
    title: "Buscando contactos",
    desc: "Estamos importando tus antiguos contactos. La operación puede tardar algo de tiempo, espera, por favor",
  },

  datasets: {
    actionsFlags: {
      "\\\\Answered": "Respondido",
      "\\\\Deleted": "Supreso",
      "\\\\Draft": "Sequía",
      "\\\\Flagged": "Marcado",
      "\\\\Seen": "Leer",
    },
    antispamFilterTypes: {
      whitelist_from: "Permitir a partir del",
      whitelist_to: "Permitir",
    },
    calendarMinutesInterval: {
      15: "15 minutos",
      30: "30 minutos",
      60: "60 minutos",
    },
    calendarNewEventFreeBusy: {
      busy: "Ocupado",
      free: "Disponible",
      outofoffice: "Fuera de la oficina",
      temporary: "Temporal",
    },
    calendarNewEventPartecipation: {
      ACCEPTED: "Aceptar",
      DECLINED: "Rechazar",
      TENTATIVE: "Quizás",
    },
    calendarNewEventParticipationRoles: {
      CHAIR: "Presidente",
      "REQ-PARTICIPANT": "Solicitado",
      "OPT-PARTICIPANT": "No solicitado",
      "NON-PARTICIPANT": "Con fines de información",
    },
    calendarNewEventPriority: {
      0: "Ninguna",
      1: "Alta",
      5: "Media",
      9: "Baja",
    },
    calendarNewEventTypes: {
      public: "Público",
      confidential: "Confidencial",
      private: "Privado",
    },
    calendarStartWeekDay: {
      saturday: "Sábado",
      sunday: "Domingo",
      monday: "Lunes",
    },
    calendarView: {
      year: "Año",
      month: "Mes",
      week: "Semana",
      workWeek: "Semana de trabajo",
      day: "Día",
      listmonth: "Lista",
    },
    calendarEventFilterBy: {
      allEvents: "Todos",
      nextEvents: "Todos los próximos eventos",
    },
    calendarEventSearchIn: {
      title: "Título/etiqueta/lugar",
      all: "Contenido completo",
    },
    cancelSendTimer: {
      0: "Deshabilitado",
      5000: "5 segundos",
      10000: "10 segundos",
      20000: "20 segundos",
      30000: "30 segundos",
    },
    contactNameFormat: {
      firstName: "Nombre, Apellido",
      lastName: "Apellido, nombre",
    },
    contactsOrder: {
      firstName: "Nombre",
      lastName: "Apellido",
    },
    countries: {
      AD: "Andorra",
      AE: "United Arab Emirates",
      AG: "Antigua & Barbuda",
      AI: "Anguilla",
      AL: "Albania",
      AM: "Armenia",
      AO: "Angola",
      AR: "Argentina",
      AS: "American Samoa",
      AT: "Austria",
      AU: "Australia",
      AW: "Aruba",
      AX: "Åland Islands",
      AZ: "Azerbaijan",
      BA: "Bosnia and Herzegovina",
      BB: "Barbados",
      BD: "Bangladesh",
      BE: "Belgium",
      BF: "Burkina Faso",
      BG: "Bulgaria",
      BH: "Bahrain",
      BI: "Burundi",
      BJ: "Bénin",
      BL: "Saint Barthélemy",
      BM: "Bermuda",
      BN: "Brunei",
      BO: "Bolivia",
      BQ: "Bonaire, Sint Eustatius and Saba",
      BR: "Brasil",
      BS: "Bahamas",
      BW: "Botswana",
      BY: "Belarus",
      BZ: "Belize",
      CA: "Canada",
      CC: "Cocos (Keeling) Islands",
      CD: "Democratic Republic of the Congo",
      CF: "Central African Republic",
      CG: "Republic of the Congo",
      CH: "Switzerland",
      CL: "Chile",
      CM: "Cameroun",
      CN: "China",
      CO: "Colombia",
      CR: "Costa Rica",
      CU: "Cuba",
      CV: "Cabo Verde",
      CW: "Curaçao",
      CX: "Christmas Island",
      CY: "Cyprus",
      CZ: "Czech Republic",
      DE: "Germany",
      DK: "Denmark",
      DM: "Dominica",
      DO: "Dominican Republic",
      EC: "Ecuador",
      EE: "Estonia",
      ES: "Spain",
      ET: "Ethiopia",
      FI: "Finland",
      FO: "Faroe Islands",
      FR: "France",
      GA: "Gabon",
      GB: "United Kingdom",
      GD: "Grenada",
      GF: "French Guiana",
      GG: "Guernsey",
      GI: "Gibraltar",
      GL: "Greenland",
      GP: "Guadeloupe",
      GQ: "Equatorial Guinea",
      GR: "Greece",
      GT: "Guatemala",
      GU: "Guam",
      GY: "Guyana",
      HN: "Honduras",
      HR: "Croatia",
      HT: "Haiti",
      HU: "Hungary",
      IE: "Ireland",
      IM: "Isle of Man",
      IS: "Island",
      IT: "Italy",
      JE: "Jersey",
      JM: "Jamaica",
      JP: "Japan",
      KE: "Kenya",
      KR: "South Korea",
      LI: "Lichtenstein",
      LS: "Lesotho",
      LT: "Lithuania",
      LU: "Luxembourg",
      LV: "Latvia",
      MC: "Monaco",
      MD: "Moldova",
      ME: "Montenegro",
      MG: "Madagascar",
      MK: "North Macedonia",
      MQ: "Martinique",
      MT: "Malta",
      MW: "Malawi",
      MX: "Mexico",
      MZ: "Mozambique",
      NA: "Namibia",
      NI: "Nicaragua",
      NL: "Netherlands",
      NO: "Norway",
      NZ: "New Zealand",
      PA: "Panama",
      PE: "Perú",
      PH: "Philippines",
      PL: "Poland",
      PT: "Portugal",
      PY: "Paraguay",
      RE: "Réunion",
      RO: "Romania",
      RS: "Serbia",
      RU: "Russia",
      RW: "Rwanda",
      SE: "Sweden",
      SG: "Singapore",
      SH: "Saint Helena",
      SI: "Slovenia",
      SJ: "Svalbard & Jan Mayen",
      SK: "Slovakia",
      SM: "San Marino",
      SO: "Somalia",
      SS: "South Sudan",
      SV: "El Salvador",
      TG: "Togo",
      TO: "Tonga",
      TR: "Turkey",
      TZ: "Tanzania",
      UA: "Ukraine",
      UG: "Uganda",
      US: "United States of America",
      UY: "Uruguay",
      VA: "Città del Vaticano",
      VE: "Venezuela",
      VN: "Vietnam",
      XK: "Kosovo",
      YT: "Mayotte",
      ZA: "South Africa",
      ZM: "Zambia",
      ZW: "Zimbabwe",
    },
    deliveryNotifications: {
      always: "Pedir siempre confirmación de entrega",
      never: "Nunca pedir confirmación de entrega",
    },
    markReadAfter: {
      manually: "Manualmente",
      onOpen: "Cuando el mensaje está abierto",
      5000: "Después de 5 segundos",
      10000: "Después de 10 segundos",
      30000: "Después de 30 segundos",
    },
    eventAlarmPostponeTime: {
      60: "Durante 1 minuto",
      300: "Durante 5 minutos",
      900: "Durante 15 minutos",
      1800: "Durante 30 minutos",
      3600: "Durante 1 hora",
      7200: "Durante 2 horas",
      86400: "Durante 1 días",
      604800: "Durante 1 semana",
    },

    eventTimeIntervals: {
      5: "5 minutos",
      10: "10 minutos",
      15: "15 minutos",
      20: "20 minutos",
      30: "30 minutos",
    },

    calendarTaskStatus: {
      "NEEDS-ACTION": "Necesita una accion",
      COMPLETED: "Terminado",
      PROCESS: "En progreso",
      CANCELLED: "Cancelado",
    },

    feedbackAreas: {
      addressbookSidebar: "Lista de la agenda",
      contactList: "Lista de contactos",
      contactView: "Mostrar contactos",
      mailSearch: "Buscar mensajes",
      mailSidebar: "Lista de carpetas",
      messageList: "Lista de mensajes",
      messageView: "Mostrar mensajes",
      newMessage: "Componer un nuevo mensaje",
      other: "Más",
      settings: "Ajustes",
    },
    filterMail: {
      all: "Todos",
      byDate: "Fecha",
      byFrom: "De",
      bySize: "Tamaño",
      bySubject: "Asunto",
      flagged: "Marcado",
      filter: "Filtros",
      orderBy: "Ordenar por",
      seen: "Leer",
      unseen: "No leído",
    },
    filtersActions: {
      discard: "Eliminar",
      addflag: "Marcar el mensaje como",
      setkeyword: "Agregar etiqueta",
      fileinto: "Mover el mensaje",
      fileinto_copy: "Copiar mensaje",
      keep: "Mantener mensaje",
      redirect: "Redirigir mensaje a",
      redirect_copy: "Enviar copia a",
      reject: "Rechazar con mensaje",
      stop: "Dejar de procesar filtros",
    },
    filtersDateOperators: {
      gt: "Después",
      is: "Es igual a",
      lt: "Antes de",
      notis: "No es igual a",
    },
    filtersEnvelopeSubtypes: {From: "De", To: "Para"},
    filtersDateSubTypes: {
      date: "Fecha",
      time: "Hora",
      weekday: "Día laborable",
    },
    filtersDateWeekdays: {
      monday: "Lunes",
      tuesday: "Martes",
      wednesday: "Miércoles",
      thursday: "Jueves",
      friday: "Viernes",
      saturday: "Sábado",
      sunday: "Domingo",
    },
    filtersRules: {
      Bcc: "CCO",
      body: "Cuerpo",
      Cc: "Cc",
      currentdate: "Fecha de llegada",
      envelope: "Mensaje",
      From: "Remitente",
      other: "Otra cabecera",
      size: "Tamaño",
      Subject: "Asunto",
      To: "Destinatario",
    },
    filtersSizeMUnits: {B: "Bytes", K: "Kilobytes", M: "Megabytes"},
    filtersSizeOperators: {over: "es mayor que", under: "es menor que"},
    filtersStringOperators: {
      contains: "contiene",
      exists: "existe",
      is: "es igual a",
      notcontains: "no contiene",
      notexists: "no existe",
      notis: "no es igual a",
    },
    fontSize: {
      extraSmall: "Extra Pequeño",
      huge: "Enorme",
      large: "Grande",
      medium: "Medio",
      normal: "Normal",
      small: "Pequeño",
    },
    languages: {
      de: "Alemán",
      en: "Inglés",
      fr: "Francés",
      gr: "Griego",
      it: "Italiano",
      nl: "Holandés",
      sv: "Sueco",
      es: "Español",
      pt: "Portugués",
    },
    mailRetention: {
      0: "Nunca",
      30: "más de 1 mes",
      90: "mayores de 3 meses",
      180: "mayores de 6 meses",
      365: "más de 1 año",
      730: "mayores de 2 años",
      1095: "mayores de 3 años",
      1460: "mayores de 4 años",
      1825: "mayores de 5 años",
    },
    matchTypes: {
      allof: "Satisface todos los parámetros",
      anyof: "Satisface al menos un parámetro",
    },
    newAllDayEventAlert: {
      never: "Nunca",
      eventDate: "Fecha del evento",
      "-PT17H": "Un día antes, a las 9 am",
      "-P6DT17H": "Una semana antes, a las 9 am",
    },
    newEventAlert: {
      never: "Nunca",
      eventHour: "El tiempo de inicio del evento",
      //P[n]Y[n]M[n]DT[n]H[n]M[n]S
      "-PT5M": "5 minutos antes ",
      "-PT10M": "10 minutos antes",
      "-PT15M": "15 minutos antes",
      "-PT30M": "30 minutos antes",
      "-PT1H": "1 hora antes ",
      "-PT2H": "2 horas antes",
      "-PT12H": "12 horas antes",
      "-P1D": "1 día antes",
      "-P7D": "1 semana antes",
    },
    newEventRepeatDayWeek: {
      MO: "Lunes",
      TU: "Martes",
      WE: "Miércoles",
      TH: "Jueves",
      FR: "Viernes",
      SA: "Sábado",
      SU: "Domingo",
    },
    newEventRepeatFrequency: {
      NEVER: "Nunca",
      DAILY: "Diariamente",
      WEEKLY: "Semanalmente",
      MONTHLY: "Mensualmente",
      YEARLY: "Anualmente",
    },
    newEventRepeatMonths: {
      1: "Enero",
      2: "Febrero",
      3: "Marzo",
      4: "Abril",
      5: "Mayo",
      6: "Junio",
      7: "Julio",
      8: "Agosto",
      9: "Setiembre",
      10: "Octubre",
      11: "Noviembre",
      12: "Diciembre",
    },
    orderSelector: {
      byLastname: "Apellido",
      byMail: "Email",
      byName: "Nombre",
      byOrg: "Empresa",
      orderBy: "Ordenar por",
      showOnlyLists: "Mostrar solamente las listas",
    },
    readConfirmations: {
      always: "Pedir siempre confirmación de lectura",
      never: "Nunca pedir la confirmación de lectura",
    },
    readingConfirmation: {
      always: "Siempre",
      ask: "Preguntar siempre",
      never: "Nunca",
    },
    selectMail: {
      all: "Todo",
      cancel: "Cancelar",
      modify: "Editar",
      none: "Deseleccionar",
      select: "Seleccionar",
    },
    shareOptionsCalendar: {
      None: "Ninguno",
      DAndTViewer: "Ver fecha y hora",
      Viewer: "Ver todo",
      Responder: "Responder a",
      Modifier: "Modificar",
    },
    showImages: {
      always: "Siempre",
      contacts: "Contactos y de confianza",
      never: "Nunca",
    },
    themes: {
      dark: "Oscuro",
      light: "Claro",
    },
    timeFormats: {
      "12h": "12h",
      "24h": "24h",
    },
    viewMode: {
      label: {
        viewColumns: "Columnas",
        viewHalf: "Vista previa",
        viewFull: "Lista",
      },
      desc: {
        viewColumns:
          "Mostrar diseño de tres columnas con panel de lectura a la derecha de la pantalla.",
        viewHalf:
          "Mostrar diseño de dos columnas con panel de lectura en la parte inferior de la pantalla.",
        viewFull:
          "Mostrar el diseño de dos columnas con solo la lista de mensajes. El panel de lectura mostrará la página completa al hacer clic",
      },
    },
  },

  dropdownMenu: {
    activesync: "Microsoft® ActiveSync",
    delete: "Eliminar",
    download: "Descargar",
    edit: "Editar",
    exportContacts: "Exportar contactos",
    feedback: "Feedback",
    importContacts: "Importar contactos",
    importEvents: "Importar eventos",
    news: "News & Updates",
    remove: "Eliminar",
    rename: "Renombrar agenda",
    share: "Compartir",
    shortcuts: "Atajos de teclado",
    syncNo: "No sincronizar",
    syncYes: "Sincronizar",
    unsubscribe: "Darse de baja",
  },

  dropdownUser: {
    feedback: "Feedback",
    logout: "Cerrar sesión",
    settings: "Ajustes",
  },

  errors: {
    emailDomainAlreadyPresent: "Dirección de correo electrónico o dominio ya presente",
    emptyField: "Campo vacío",
    invalidEmail: "Correo electrónico no válido",
    invalidEmailDomain: "Dirección de correo electrónico o dominio no válido",
    invalidPassword: "Contraseña no válida",
    invalidPasswordFormat: "Formato no válido, introduzca al menos 8 caracteres alfanuméricos",
    invalidValue: "No es un valor válido",
    mandatory: "Campo requerido",
    notAllowedCharacter: "Caracter no permitido",
    notChanged: "Campo no modificado",
    permissionDenied: "Permiso denegado",
    tooLong: "Campo demasiado largo",
  },

  feedback: {
    disclaimer:
      "Envíe sus comentarios y ayúdenos a mejorar el servicio.<br/>Si tiene alguna pregunta o problema relacionado con el uso del correo web, comuníquese con soporte",
    labels: {
      feedbackAreas: "¿Sobre que área quieres dejar un comentario?",
      note: "Deja un mensaje (opcional)",
    },
    msgError: {
      title: "Sus comentarios no pudieron ser enviados",
      desc: "Por favor, inténtalo de nuevo más adelante, es importante para nosotros saber lo que piensas de nuestro webmail. Tus comentarios nos ayudarán a crear una mejor experiencia para ti y todos nuestros usuarios",
    },
    msgSuccess: {
      title: "¡Gracias por su respuesta!",
      desc: "Apreciamos de forma sincera el tiempo que has usado para ayudar a mejorar nuestro correo web. Tus comentarios nos ayudarán a crear una mejor experiencia para ti y para todos nuestros usuarios",
    },
    privacy:
      "Los datos recogidos serán tratados de conformidad con la legislación vigente en materia de privacidad",
    title: "Comentarios",
  },

  inputs: {
    labels: {
      addAddress: "Añadir dirección",
      addContactToAddressbook: "Añadir contacto a la libreta de direcciones",
      addDomain: "Agregar dirección o dominio",
      addLabel: "Nombre de etiqueta",
      addMembers: "Añadir miembros",
      addParticipant: "Añada participante",
      addressbookName: "Agenda",
      addUser: "Agregar usuario",
      alert2: "Segunda alerta",
      alert: "Alerta",
      assignTask: "Asignar la tarea a",
      at: "A",
      calendar: "Calendario",
      calendarBusinessDayEndHour: "Final del día de trabajo",
      calendarBusinessDayStartHour: "Al comienzo del día de trabajo",
      calendarColor: "Color del calendario",
      calendarMinutesInterval: "Intervalo de tiempo del calendario",
      calendarName: "Nombre del calendario",
      calendarView: "Vista predeterminada",
      company: "Empresa",
      companyName: "Nombre",
      confidentialEvents: "Eventos confidenciales",
      confirmNewPassword: "Confirmar contraseña",
      contactNameFormat: "Mostrar como",
      contactsOrder: "Ordenar contactos por",
      contains: "Contiene",
      country: "País",
      dateFormat: "Formato de fecha",
      dateInterval: "Date interval",
      defaultAddressbook: "Agenda predeterminada",
      defaultCalendar: "Calendario predeterminado",
      displayName: "Disp. Nombre",
      email: "Email",
      encryptionMethod: "método de cifrado",
      endDate: "Fecha final",
      event: "Evento",
      eventDailyRepetition: "Todos;los dias",
      eventDailyWorkdayRepetition: "Cada día de la semana",
      eventMonthlyLastDayRepetition: "El último día del mes, cada;mes",
      eventMonthlyLastWeekDayRepetition: "Último {{WeekDay}}, cada;mes",
      eventMonthlyRepetition: "En {{DayNumber}}, cada;mes",
      eventMonthlyWeekDayRepetition: "En {{WeekDayNumber}}, cada;mes",
      eventPartecipation: "Estado de partecipacion",
      eventPriority: "Prioridad del evento",
      eventType: "Tipo de evento",
      eventWeeklyRepetition: "Cada;semana, en:",
      eventYearlyLastDayRepetition: "Último día de {{Month}}, cada;año",
      eventYearlyLastWeekDayRepetition: "Último {{WeekDay}} de {{Month}}, cada;año",
      eventYearlyRepetition: "El {{DayNumber}} de {{Month}}, cada;año ",
      eventYearlyWeekDayRepetition: "En {{WeekDayNumber}} de {{Month}}, cada;año",
      exportAsLdiff: "Exportar en formato LDIF",
      exportAsVcard: "Exportar en formato vCard",
      faxHome: "Enviar fax a casa",
      faxWork: "Enviar fax al trabajo",
      filter: "Filtrar por",
      filterName: "Nombre de la regla",
      firstName: "Nombre",
      folderName: "Nombre de la carpeta",
      freeBusy: "Mostrar como",
      from: "De",
      fromDate: "Desde la fecha",
      home: "Casa",
      hour: "Hora",
      includeFreeBusy: "Incluir en el Free/Busy",
      label: "Etiqueta",
      labelColor: "Color de la etiqueta",
      language: "Idioma",
      lastName: "Apellido",
      linkText: "Texto visualizado",
      linkURL: "Dirección web (URL)",
      listName: "Nombre de la lista",
      location: "Ubicación",
      loginAddressbook: "Agenda inicial",
      mailAccount: "Cuenta",
      mailRetention: "Eliminar los mensajes de la carpeta",
      mailRetentionDefault: "La eliminación de mensajes se establece automáticamente en 30 días",
      mailRetentionDiscalimer:
        "Atención, los mensajes se borrarán automáticamente de forma definitiva sin posibilidad de recuperación. La cancelación será operativa en 24 horas.",
      mailRetentionHint:
        "Especifique el intervalo de tiempo, después de recibir el mensaje, para proceder con la eliminación automática.",
      markReadAfter: "Marcar mensaje como leído",
      mobile: "Móvil",
      newAddressBook: "Nueva agenda",
      newAddressBookMobile: "Nueva agenda",
      newAllDayEventAlert: "Nueva alerta a todos los eventos del día",
      newBcc: "Añadir destinatarios en CCO",
      newCalendar: "Nuevo calendario",
      newEventAlert: "Nueva alerta de eventos",
      newForward: "Añadir destinatario a la lista",
      newPassword: "Nueva contraseña",
      nickname: "Apodo",
      object: "Asunto",
      oldPassword: "Contraseña actual",
      parentFolder: "Camino",
      password: "Password",
      personalMeetingRoom: "Enlace a la sala de reuniones personal",
      phone: "Teléfono",
      port: "Port",
      priority: "Prioridad",
      portFor: "Port for",
      privateEvents: "Eventos privados",
      publicEvents: "Eventos públicos",
      readingConfirmation: "Enviar confirmación de lectura",
      recoveryEmail: "Recuperación de correo",
      renameAddressbook: "Renombrar agenda",
      repeatEvery: "Repetir",
      reportBugNote: "Descripción del problema",
      reportBugPhoneNumber: "Número de teléfono",
      searchAddressbookToSubscribe: "Busque un usuario para ver sus agendas compartidas",
      searchCalendarToSubscribe: "Busque un usuario para ver sus calendarios compartidas",
      searchIn: "Buscar en",
      selectCalendar: "Seleccionar el calendario",
      selectIdentity: "Seleccionar la identidad",
      selectList: "Seleccionar la lista",
      selectSnapshotDate: "Elegir fecha",
      serverName: "Nombre del servidor",
      shareCalendarCalDAVURL: "CalDAV URL",
      shareCalendarWebDavICSURL: "WebDAV ICS URL",
      shareCalendarWebDavXMLURL: "WebDAV XML URL",
      shareToAddressbook: "¿Con quien deseas compartir la agenda?",
      shareToCalendar: "¿Con quien deseas compartir el calendario?",
      shareToFolder: "¿Con quien deseas compartir la carpeta?",
      showImages: "Mostrar imagenes",
      signatureName: "Nombre a mostrar",
      signatureText: "Texto de la firma",
      startDate: "Fecha de inicio",
      team: "Equipo",
      templateName: "Nombre",
      templateSubject: "Sujeto",
      templateText: "Cuerpo del mensaje",
      theme: "Tema",
      timeFormat: "Formato de tiempo",
      timezone: "Zona horaria",
      title: "Título",
      to: "Para",
      untilDate: "Hasta el día",
      username: "Nombre de usuario",
      weekStart: "Primer día de la semana",
      work: "Trabajo",
    },
    placeholder: {
      addressbookName: "Nombre de la agenda",
      birthday: "Fecha de nacimiento",
      city: "Ciudad",
      company: "Empresa",
      country: "País",
      customText: "Introduce un texto personalizado",
      email: "Email",
      endDate: "End date",
      firstName: "Nombre",
      lastName: "Apellido",
      members: "Miembros",
      newFolderName: "Nuevo nombre de carpeta",
      newNameAddressbook: "Nuevo nombre de la agenda",
      newPassword: "Al menos 8 caracteres alfanuméricos",
      note: "Nota",
      password: "Tu contraseña",
      phone: "Teléfono",
      place: "Enter a street or place",
      postCode: "Código postal",
      region: "Región",
      role: "Papel",
      search: "Buscar",
      searchActivity: "Buscar actividad",
      searchEvent: "Buscar eventos",
      searchUser: "Buscar usuario en su dominio",
      select: "Seleccionar",
      snooze: "Posponer alerta",
      startDate: "Fecha de inicio",
      street: "Calle",
    },
    hint: {
      cancelSendMessage:
        "Seleccione el tiempo disponible para retractarse de un mensaje durante el envío, si decide que no desea enviar el correo electrónico.",
      newForward: "Puede agregar hasta un máximo de {{max}} dirección de reenvío.",
      newBcc: "Puede añadir hasta {{max}} destinatarios en CCO.",
      mailRetention:
        "Especifique el intervalo de tiempo, después de recibir el mensaje, para proceder con la eliminación automática",
      passwordScore: {
        check: "Fuerza de la contraseña",
        poor: "Contraseña muy pobre",
        easy: "Contraseña demasiado fácil",
        weak: "Contraseña demasiado débil",
        strong: "Contraseña fuerte",
        great: "¡Contraseña genial!",
      },
    },
  },

  labels: {
    attendees: "Asistentes",
    calendarAdvancedSearch: "¿Dónde quieres buscar?",
    clearAdvancedFilters: "Eliminar filtros",
    clearFields: "Borrar campos",
    default: "Defecto",
    forDomain: "En el dominio",
    forward: "Fwd",
    holidayCalendar: "Fiesta",
    organizer: "Organizador",
    otherFilters: "Otros filtros",
    searchResults: "Resultados de la búsqueda",
    withAllUsers: "Con todos los usuarios",
  },

  loaderFullscreen: {
    descriptionEvents: "Tus eventos están llegando, por favor espere",
    description: "Los contenidos están llegando, por favor espere",
    descriptionFolder: "Las carpetas están llegando, por favor espere",
    title: "Cargando",
    titleEvent: "Cargando evento",
  },

  mail: {
    confirmMailLabel: "OK, confirmo!",
    contextualMenuLabels: {
      addAddressBook: "Agregar a la agenda",
      addEvent: "Añadir evento",
      alarm: "Alarma",
      archive: "Archive",
      archiveThread: "Archive thread",
      backTo: "Atrás",
      cancel: "Cancelar",
      close: "Cerrar",
      confirm: "Confirmar",
      copyIn: "Copiar en",
      copyThreadIn: "Copiar conversación",
      delete: "Eliminar",
      deletePerm: "Borrar permanentemente",
      deleteThread: "Eliminar conversación",
      deleteXMessages: "Borrar {{MessagesNumber}} mensajes",
      deliveryNotification: "Confirmacion de envio",
      download: "Descargar",
      editAsNew: "Editar como nuevo",
      emptySpam: "Marcar como spam",
      emptyTrash: "Papelera vacía",
      forward: "Reenviar",
      import: "Importar correo",
      label: "Etiqueta",
      labelsManagement: "Administrar etiquetas",
      labelThread: "Hilo de etiquetas",
      markAllAsRead: "Marcar todo como leido",
      markAs: "Marcar como",
      markThreadAs: "Marcar conversación",
      manageFolders: "Administrar carpetas",
      modify: "Editar",
      more: "Más",
      moveThreadTo: "Mover conversación",
      moveTo: "Mover a",
      newSubFolder: "Agregar subcarpeta",
      plainText: "El modo de texto sin formato",
      print: "Impresión",
      priorityHigh: "Alta prioridad",
      readed: "Leer",
      readedNot: "No leído",
      readingNotification: "Confirmación de lectura",
      rename: "Renombrar agenda",
      reply: "Responder",
      replyToAll: "Responder a todos",
      restore: "Restaurar",
      restoreThreadIn: "Restaurar hilo",
      restoreIn: "Restaurar en",
      sendAsAttachment: "Reenviar como adjunto",
      showSourceCode: "Mostrar código fuente",
      spam: "Spam",
      spamNot: "No spam",
      starred: "Destacado",
      starredNot: "No destacado",
      thanks: "Gracias",
      thread: "Acciones en hilo",
    },
    deleteMailDsc:
      "Si no hay ningún sistema de almacenamiento activo, se eliminará permanentemente el mensaje.<br/><b>La operación no es reversible</b>.",
    deleteMailTitle: "Borrar mensaje",
    deleteMailsDsc:
      "Si no hay ningún sistema de almacenamiento activo, se eliminarán permanentemente los mensajes.<br/><b>La operación no es reversible<b>.",
    deleteMailsTitle: "Borrar mensajes seleccionados",
    dropFiles: "Soltar aquí los archivos a adjuntar",
    emptyTrashDsc:
      "Si no existe ningún sistema de almacenamiento activo al vaciar la papelera, todos los mensajes serán eliminados <b>de forma irreversible</b>.<br/>Después de <b>30 dìas</b> en la papelera, los mensajes se eliminan automáticamente.",
    emptyTrashTitle: "Papelera vacía",
    goToOldWebmailModal: {
      description:
        "<br/>Lo invitamos a usar de inmediato el nuevo Webmail, que ofrece funciones adicionales como:<br/><ul><li>Administración automática de identidades</li><li>Libreta de direcciones y calendario compartidos</li><li>Integración de Zoom para videoconferencias</li><li>Mensajes predefinidos</li><li>Buscar en todas las carpetas</li><li>y más funciones</li></ul>",
      title: "El antiguo Webmail ya no estará disponible a partir del 31 de octubre",
    },
    import: {
      messagesInvalid: "No es válido:",
      messagesNr: "Total de mensajes a importar:",
      messagesValid: "Válido:",
      desc: "Esta importando mensajes en la carpeta: <code>{{folderImport}}</code><br/>Puedes importar mensajes de otras aplicaciones de correo electrónico usando un formato de archivo eml (<strong>.eml</strong>).",
      dropFiles: "Subir o soltar aquí el archivo que desea importar",
      error: "Los mensajes no pudieron importarse",
      importing:
        "Estamos importando <b>{{messagesNumber}}</b> mensajes en la carpeta: <code>{{folderImport}}</code>",
      loading: "Cargando...",
      success: "Importación realizada con éxito!",
      title: "Importar mensajes",
      uploadedFile: "Subido",
      uploadingFile: "Subiendo",
    },
    loading: {
      desc: "Tus mensajes están llegando, por favor espera.",
      title: "Cargando",
    },
    markSpamReadDsc:
      "Marcar todos los mensajes en la carpeta como leídos.<br/>Despudés de <b>30 dìas</b>, los mensajes se eliminan automáticamente.",
    markSpamReadTitle: "Marcar mensajes como leídos",
    maxLabelsNumberTitle: "¡Demasiadas etiquetas!",
    maxLabelsNumberDsc:
      "Has alcanzado el máximo de etiquetas que pueden asociarse a un mensaje. Para añadir una etiqueta nueva, debes quitar primero una de las ya presentes.",
    message: {
      add: "Añadir",
      addToAddressBook: "Añadir contacto a la agenda",
      attachedMessage: "Mensaje adjunto",
      attachments: "Archivos adjuntos",
      bugMsg: "¿No ve el mensaje?",
      cc: "Cc:",
      date: "Fecha:",
      draftsSelectedInfo: "Seleccionar un mensaje de la lista y continuar escribiendo",
      downloadAll: "Descargar todo",
      downloadAttachments: "Descargar archivos",
      editPartecipationStatusDecription: "",
      editPartecipationStatusTitle: "Editar estado de participación",
      eventActionAccept: "Aceptar",
      eventActionDecline: "Rechazar",
      eventActionTentative: "Quizás",
      eventAddToCalendar: "Este evento no está presente en su calendario",
      eventAttendees: "Los asistentes",
      eventAttendeeStatusAccepted: "Evento aceptado",
      eventAttendeeStatusDeclined: "Evento rechazado",
      eventAttendeeStatusTentative: "Tentativa de participación",
      eventCounterProposal: "Este mensaje contiene una contrapropuesta al evento",
      eventDeleted: "Evento eliminado",
      eventInvitation: "Event invitation:",
      eventLocationEmpty: "No especificado",
      eventModify: "Editar",
      eventNeedAction: "Confirmar participación",
      eventNotNeedAction: "Evento ya procesado",
      eventOutDated: "El evento se ha modificado",
      eventStatusAccepted: "Aceptado",
      eventStatusDeclined: "Rechazado",
      eventStatusTentative: "Tentativa",
      eventUpdate: "Actualizar evento",
      external: "Externo",
      externalLabel: "Esta dirección de correo electrónico es externa a su organización.",
      folderSelectedInfo: "Seleccione un mensaje de la lista y descubrir su contenido.",
      from: "De:",
      hideAllAttachments: "Esconder",
      hugeMessage:
        "Contenido demasiado grande para mostrar completamente, haga clic en el enlace a continuación para ver el código fuente del mensaje.",
      hugeMessageNotice: "Mensaje truncado",
      inboxSelectedInfo: "Seleccione un mensaje de la lista y averiguar quién lo escribió.",
      isMailingList: "Este mensaje es de una lista de correo.",
      localAttachments: "Hay archivos adjuntos adicionales dentro del evento.",
      message: "Mensaje",
      messageForwarded: "Mensaje reenviado",
      messages: "Mensajes",
      messagesQuota: "Cuota de mensajes usados:",
      newMessageinThread: "Hay un mesaje nuevo",
      noContent: "Este mensaje no tiene contenido.",
      notSelected: "Seleccione un mensaje",
      oneSelectMessages: "Mensaje seleccionado",
      oneSelectThreads: "Seleccionar conversación",
      readNotificationLabel: "{{Sender}} ha solicitado confirmación de lectura para el mesaje.",
      readNotificationLabelSimple: "Confirmación de lectura del mensaje solicitada.",
      readNotificationResponse:
        "<P>Mensaje<BR><BR>&nbsp;&nbsp;&nbsp; R:&nbsp; %TO%<BR>&nbsp;&nbsp;&nbsp; Asunto:&nbsp; %ASUNTO%<BR>&nbsp;&nbsp;&nbsp; Enviado:&nbsp; %SENDDATE%<BR><BR>se leyó el día %READDATE%.</P>",
      readNotificationSubjectPrefix: "Leer:",
      replyTo: "Responder a:",
      sender: "Remitente:",
      sentSelectedInfo: "Seleccionar un mensaje de la lista y ver a quien le escribiste.",
      showAllAttachments: "Mostrar otros",
      showMoreThread: "Mostrar más",
      selectMessages: "Los mensajes seleccionados",
      selectThreads: "Conversación seleccionada",
      spamNotSelected: "Mantener la carpeta en orden",
      spamSelectedInfo: "Comprobar mensajes y marcar spam como leído.",
      subject: "Asunto:",
      to: "Para:",
      trashNotSelected: "Compruebar la papelera",
      trashSelectedInfo: "Puede recuperar los mensajes de la papelera durante 30 días.",
      updating: "Edición en curso",
      unsubscribedMailingList: "Usted se eliminó de esta lista de correo.",
      yesterday: "Ayer",
      wrote: "escribió:",
    },
    messagesList: {
      allMessagesLoaded: "Todos los mensajes se han subido",
      ctaDeletedMessages: "Compacto carpeta",
      ctaSpamInfo: "Marcar todo como leido",
      ctaTrashInfo: "Papelera vacía",
      deletedMessages:
        "Hay mensajes en espera de eliminación, compacte la carpeta para completar la operación.",
      folderEmpty: "Esta carpeta está vacía",
      folderInfo: "Iniciar una conversación o mover un mensaje.",
      foundMessages: "Encontrado",
      foundMessagesNum: "Encontrado: <b>{{found}}</b> de <b>{{total}}</b>",
      moveMessage: "Mover el mensaje",
      moveMessages: "Mover {{NumMessages}} mensajes",
      notFound: "No se han encontrado mensajes",
      notFoundInfo:
        "La búsqueda no ha dado ningún resultado, inténtalo de nuevo utilizando diferentes criterios",
      pullDownToRefresh: "Arrastra para actualizar",
      releaseToRefresh: "Suelta para actualizar",
      searchInfo: "Mensajes encontrados",
      searchLimited:
        "Indexación en curso. La búsqueda se limita a las <b>carpetas individuales</b> y los campos <b>de</b>, <b>a</b> y <b>asunto</b> del mensaje.",
      searchNotAvailable: "Búsqueda no disponible",
      searchNotAvailableInfo:
        "La búsqueda no está disponible actualmente, inténtelo de nuevo más tarde",
      selectMessages: "Seleccionados",
      showMoreThread: "Mostrar más",
      spamEmpty: "¡Todo el spam se ha escapado!",
      spamInfo: "Los mensajes de spam se eliminan automáticamente después de 30 días",
      trashEmpty: "La papelera está vacía",
      trashInfo: "Los mensajes de la papelera se eliminan automáticamente después de 30 días",
      totalMessages: "Mensajes",
      totalMessagesNum: "Mensajes: <b>{{total}}</b>",
    },
    mtm: {
      archivePromo:
        "<b> Pero eso no es todo... </b> <br/> <br/> El servicio de archivo de correo electrónico le proporciona un buzón gemelo de solo lectura, donde todos los mensajes enviados y recibidos son almacenados por los usuarios durante 10 años. sin límites de espacio.",
      backupSelector: "Seleccione una copia de seguridad para continuar",
      description:
        "Mediante este servicio puedes acceder a las copias de seguridad de tu buzón realizadas en los últimos 15 días, consultar el estado de tus copias de seguridad o restaurar mensajes.",
      title: "Bienvenido en Mail Time Machine",
    },
    newMessage: {
      addAttach: "Añadir un adjunto",
      addHTMLTitle: "Insertar HTML",
      addImgeDsc:
        "Puede insertar imágenes directamente en línea, en el cuerpo del mensaje o adjuntarlas al mensaje.",
      addImgeTitle: "Insertar imágenes",
      addLinkTitle: "Insertar link",
      editLinkTitle: "Editar link",
      advanced: "Avanzado",
      attachInfo: {
        noAttach: "No hay archivos adjuntos",
        attachNumber: "Archivos adjuntos:",
      },
      bcc: "CCO",
      cc: "Cc",
      cancelSend: "Envío de correo cancelado con éxito",
      delete: "Eliminar",
      deleted: "Mensaje eliminado correctamente",
      deleteInProgress: "Eliminación de mensaje en curso",
      discardChanges: "Descartar los cambios",
      fontSize: {
        smaller: "Más pequeño",
        small: "Pequeño",
        normal: "Normales",
        medium: "Medio",
        big: "Grande",
        bigger: "Más grande",
      },
      from: "De",
      hide: "Esconder",
      invalidMails:
        "Dirección de correo electrónico no válida, comprueba las direcciones y vuelve a intentarlo",
      moreAttachments: "Otros",
      noDraftChanged: "No hay cambios para guardar",
      object: "Asunto",
      saveDraftDsc:
        "El mensaje no se ha enviado y contiene cambios no guardados. Puedes guardarlo como borrador y reanudar la escritura posteriormente",
      saveDraftTitle: "¿Guardar el mensaje como borrador?",
      savedDraft: "¡Borrador guardado!",
      savingDraft: "Guardar en curso",
      sendInProgress: "Enviar mensaje en curso",
      sent: "Mensaje enviado con éxito",
      sizeExceeded:
        "Adjuntos demasiado grandes. El tamaño máximo de envío es de {{messageMaxSize}} MB.",
      templateCreateModal: {
        description:
          "<br/>Cree su primer mensaje enlatado para facilitar la redacción de correos electrónicos recurrentes. Puede elegir un asunto personalizado y agregar archivos adjuntos para que se envíen automáticamente en el mensaje de correo electrónico.",
        title: "Todavía no tienes mensajes enlatados",
      },
      templateSubjectModal: {
        description:
          "Se define un objeto personalizado en el mensaje enlatado seleccionado. ¿Desea reemplazar el que está en la ventana de redacción o desea conservarlo?",
        title: "Sujeto ya presente",
      },
      to: "Para",
      toMore: "Otros",
      useTemplate: "Mensaje enlatado",
      windowSubject: "Nuevo mensaje",
    },
    reportBug: {
      title: "Denunciar mensaje",
      message: {
        issue:
          "Si no ve el mensaje correctamente, puede ayudarnos a resolver el problema y mejorar el servicio.<br/>Si tiene alguna pregunta o problema con respecto al uso del correo web, comuníquese con su referente técnico para obtener ayuda",
        issueFormatting:
          "¿El contenido del mensaje no se muestra correctamente? Describe el problema, haremos todo lo posible para solucionarlo en las próximas actualizaciones",
        issueBlank:
          "Cuando los mensajes carecen de contenido, estos se indican en la interfaz de Webmail con un banner especial.<br/><br/>Si este banner no está presente, podría tratarse de un problema de formato, así que <b>verifique el presencia del banner</b> y tal vez reportar el mensaje como <code>no formateado correctamente</code>.",
        issueAttach:
          "¿El mensaje parece estar libre de archivos adjuntos? Probablemente el remitente envió el mensaje olvidándose de insertar los archivos adjuntos.<br/><br/><b>Pídale al remitente que verifique y le reenvíe los archivos adjuntos</b>.",
        issueOther:
          "Usted describe el problema, haremos todo lo posible para solucionarlo en las próximas actualizaciones.<br/>Si tiene alguna pregunta o problema con respecto al uso del correo web, comuníquese con su referente técnico para obtener ayuda.",
        disclaimer:
          "Al enviar este comentario, su mensaje puede ser analizado por nuestro equipo de desarrollo para mejorar el servicio.<br/><br/><b>La información NO se compartirá con terceros y los datos se procesarán de conformidad con la legislación vigente en Privacidad</b>.",
      },
    },
    restoreRequest: {
      desc: "Ha solicitado la restauración del buzón <b>{{username}}</b> con la copia de seguridad fechada <b>{{restore_date}}</b>.<br/>Con esta operación restauraremos todos los mensajes presentes en la copia de seguridad indicada, sin borrar ningún mensaje que entretanto se haya recibido o enviado desde el buzón.<br/><br/><b>La operación de restauración tiene un coste.</b><br/ ><br/>¿Desea continuar con la solicitud?",
      restoreRequested:
        "Recibimos su solicitud de restauración. Se le contactará tan pronto como se complete el procedimiento.",
      title: "Solicitar una restauración",
      titleRestoreRequested: "Request sent",
      deniedTitle: "Solicitud rechazada",
      restoreRequestDenied:
        "Esta cuenta tiene otra solicitud de restauración en curso. No es posible solicitar más de una solicitud de restauración a la vez.",
    },
    searchMail: {
      attachments: "Archivos adjuntos",
      cleanFilters: "Borrar los filtros",
      marked: "Destacado",
      results: "Resultados de la búsqueda",
      searchIn: "Busca en",
      allFolders: "Todas las carpetas",
      currentFolder: "Carpeta actual",
    },
    sidebar: {
      createLabel: {
        desc: "",
        title: "Crear etiqueta",
      },
      createFolder: {
        desc: "",
        title: "Crear carpeta",
      },
      modifyFolder: {
        desc: "",
        title: "Editar carpeta",
      },
      restoreFolder: {
        desc: "",
        title: "Restaurar carpeta",
      },
      folder: "Carpetas",
      folders: "Carpetas personales",
      labels: "Etiquetas",
      newFoderName: "Nuevo nombre de carpeta",
      occupiedSpace: "Espacio usado",
      sharedFolders: "Carpetas compartidas",
      unlimitedSpace: "Espacio ilimitado",
    },
    thanksMailLabel: "¡OK, gracias!",
    tooManyCompositionsDsc:
      "Has alcanzado el máximo numero de mensajes nuevos que puedes redactar al mismo tiempo. Completa al menos uno de los mensajes que estás escribiendo para empezar a componer uno nuevo.",
    tooManyCompositionsTitle: "¡Termina el escrito!",
    unsubscribeListDsc: "¿Dejar de recibir mensajes para esta lista de distribución?",
    unsubscribeListTitle: "Cancelar suscripción",
  },

  mailboxes: {
    archive: "Archive",
    drafts: "Borradores",
    inbox: "Bandeja de entrada",
    more: "Más",
    sent: "Enviado el",
    shared: "Carpetas compartidas",
    spam: "Spam",
    trash: "Papelera",
  },

  navbar: {
    addressbook: "Contactos",
    calendar: "Calendario",
    chat: "Chat",
    mail: "Correo",
    meeting: "Reunión",
    news: "Noticias",
  },

  news: {
    notFound: "Noticias no encontradas",
    notFoundInfo: "La búsqueda no arrojó resultados, inténtalo de nuevo usando otros criterios.",
  },

  newsTags: {
    news: "Noticias",
    suggestions: "Consejos",
    fix: "Reparar",
    comingSoon: "Próximamente",
    beta: "Beta",
  },

  pageLogout: {
    title: "Salida en curso",
    desc: "",
  },

  pageIndexing: {
    title: "Tu cuenta está siendo indexada",
    desc: "La operación puede tardar algún tiempo, por favor, espera.",
  },

  pageNotFound: {
    pageNotFound: "Algo salió mal",
    pageNotFoundInfo: "La página que estás buscando no está disponible. ¡No pierdas la esperanza!",
  },

  powered: "Impulsado por Qboxmail",
  poweredCollaborationWith: "en colaboración con ",

  radioButtons: {
    labels: {
      askDeliveryConfirmation: "Confirmación de la entrega de mensajes",
      askReadConfirmation: "Confirmación de lectura del mensaje",
      defaultView: "Diseño predeterminado",
      newEventType: "Tipo del nuevo evento",
      newEventFreeBusy: "Mostrar la disponibilidad de nuevos eventos",
      newEventTimeInterval: "Nuevo intervalo de tiempo predeterminado del evento",
      other: "Otro",
      reportBugBlank: "El mensaje aparece en blanco",
      reportBugNoAttachments: "El mensaje no tiene archivos adjuntos",
      reportBugNoFormatted: "El contenido no tiene el formato correcto",
      selectIssue: "¿Cuál es su problema?",
    },
  },

  shareOptions: {
    delete: "Eliminación",
    read: "Leyendo",
    update: "Editando",
    write: "Escribiendo",
  },

  shareOptionsCalendar: {
    canCreateObjects: "Permitir insertar eventos en este calendario",
    canEraseObjects: "Permitir eliminar eventos en este calendario",
  },

  shortcuts: {
    addressbook: {
      newContact: "Nuevo contacto",
      editContact: "Editar contacto",
      deleteContact: "Borrar contacto",
    },
    calendar: {
      newEvent: "Nuevo evento",
      editEvent: "Editar evento",
      deleteEvent: "Borrar evento",
      moveRangeNext: "Ver siguiente intervalo",
      moveRangePrevious: "Ver intervalo previo",
    },
    general: {
      switchModuls: "Cambiar módulos",
      refresh: "Actualizar página",
      tabForward: "Avanzar entre los elementos en los que se puede hacer clic",
      tabBack: "Retroceder entre los elementos en los que se puede hacer clic",
      closeModal: "Cerrar módulo",
      openSettings: "Configuración abierta",
      copy: "Copiar elemento seleccionado",
      past: "Pegar elemento seleccionado",
      cut: "Cortar el elemento seleccionado",
    },
    mail: {
      confirm: "Confirmar",
      deleteMessage: "Borrar mensaje",
      deleteSelectMessage: "Eliminar mensajes seleccionados",
      editAsNew: "Editar como nuevo",
      empityTrash: "Papelera vacía",
      expandThread: "Expandir conversación",
      extendSelectDown: "Extender selección hacia abajo en la lista de mensajes",
      extendSelectUp: "Extender selección hacia arriba en la lista de mensajes",
      forward: "Reenviar",
      markRead: "Marcar como leído / no leído",
      moveDown: "Mover hacia abajo en la lista de mensajes",
      moveUp: "Mover hacia arriba en la lista de mensajes",
      newMessage: "Nuevo mensaje",
      openSelectMessage: "Abrir mensaje seleccionado",
      printMessage: "Imprimir mensaje",
      reduceThread: "Reducir el hilo",
      reply: "Responder",
      replyAll: "Responder a todos",
      thanks: "Gracias",
    },
  },

  settings: {
    addressbook: {
      management: {
        automaticSave: {
          desc: "Elija si recopilar todos los contactos que no están presentes en sus libretas de direcciones de forma automática.",
          title: "Guardado automático",
        },
        personalAddressbooks: {
          desc: "Administre sus libretas de direcciones personales y decida si desea compartirlas con otros usuarios.",
          headerActiveSync: "Sync",
          headerItem: "Agenda",
          placeholderList: " ",
          title: "Agenda personal",
        },
        sharedAddressbooks: {
          desc: "Administre las libretas de direcciones compartidas con usted por otros usuarios.",
          headerItem: "Agenda subscrita",
          placeholderList: " ",
          title: "Agenda compartida",
        },
        title: "Agendas",
      },
      title: "Contactos",
      view: {
        desc: "Administre sus preferencias para la visualización de contactos y libretas de direcciones.",
        title: "Ver contactos",
      },
    },
    calendar: {
      events: {
        title: "Eventos",
        desc: "Administre sus preferencias para nuevos eventos para todos los calendarios, si no se establece un valor predeterminado específico.",
        alertTitle: "Alertas",
        alertDesc:
          "Administre sus preferencias para las alertas de eventos para todos los calendarios, si no se establece un valor predeterminado específico.",
        personalMeetingRoomTitle: "Sala de reuniones personal",
        personalMeetingRoomDesc:
          "Genere una sala en su aplicación de reuniones en línea e introduzca el enlace aquí. A continuación, podrá seleccionarla como 'Ubicación' al crear un evento.",
      },
      invitations: {
        desc: "Elija si habilitar las invitaciones a eventos solo para los usuarios que desee.",
        title: "Invitaciones eventos",
        msgFromHeader: "Permitir invitaciones unicamente provenientes de",
        placeholderList: " ",
      },
      labels: {
        title: "Etiquetas Calendario",
        titleSettingsPage: "Etiquetas Calendario",
        desc: "Crea etiquetas de colores personalizadas para mantener tus eventos en orden.",
        deleteLabelDsc: "Eliminar la etiqueta la eliminará de todos los eventos del calendario.",
      },
      management: {
        title: "Calendarios",
        holidayCalendars: {
          title: "Calendarios vacaciones",
          desc: "Elige los calendarios de festivos que prefieras.",
          headerItem: "Calendarios",
          placeholderList: " ",
        },
        personalCalendars: {
          title: "Calendarios personales",
          desc: "Gestiona tus calendarios personales y decide si quieres compartirlos con otros usuarios.",
          headerActiveSync: "Sync",
          headerItem: "Calendarios",
          placeholderList: " ",
        },
        sharedCalendars: {
          desc: "Administre calendarios compartidos con usted por otros usuarios.",
          headerActiveSync: "Sync",
          headerItem: "Calendarios suscritos",
          placeholderList: " ",
          title: "Calendarios compartidos",
        },
        includeInFreeBusy: "Incluir en Free/Busy",
        showActivities: "Mostrar actividades",
        showAlarms: "Mostrar alarmas",
        syncWithActivesync: "Sincronizar con Microsoft® Exchange ActiveSync",
        sendMeMailOnMyEdit: "Envíame un correo electrónico cuando modifique el calendario",
        sendMeMailOnOtherEdit:
          "Envíame un correo electrónico cuando alguien modifique el calendario",
        sendMailOnEditTo: "Cuando modifique envía un correo electrónico a",
      },
      view: {
        desc: "Administra tus preferencias para la visualización de calendarios.",
        showBusyOutsideWorkingHours: "Mostrar como ocupado fuera de horário laboral",
        showWeekNumbers: "Mostrar número de la semana",
        title: "Ver calendarios",
      },
      title: "Calendario",
    },
    chat: {
      title: "Chat",
      view: {
        title: "Ver",
      },
    },
    general: {
      integrations: {
        desc: "Gestionar integraciones con proveedores de servicios fuera del webmail.",
        title: "Integraciones",
        card: {
          zoom: {
            askSeller: "Solicite más información a su distribuidor",
            title: "Zoom",
            text: "Ahorre tiempo al programar reuniones agregando detalles únicos de la conferencia Zoom a un evento.",
          },
        },
      },
      notifications: {
        title: "Notificaciones push",
        generalNotification: {
          desc: "Activa las notificaciones que indican la recepción de un nuevo mensaje.",
          longDesc:
            "Permitir que Webmail envíe notificaciones a través de su navegador cuando reciba un nuevo mensaje. Esta configuración no es suficiente para recibir notificaciones, también debe habilitar las notificaciones para cada navegador que pretenda utilizar.",
          title: "Configuración general de las notificaciones",
        },
        allowedPush: {
          allowed:
            "Notificaciones habilitadas en el navegador utilizado. Para recibirlas, también deben estar habilitadas en la sección anterior.",
          default:
            "Si quieres que tu navegador actual te avise con una notificación cuando recibas un nuevo mensaje, debes permitir las notificaciones (en la sección anterior) y después permitir las notificaciones push en tu navegador. Haz clic en el botón y permite las notificaciones, o haz clic en el icono del candado y permite las notificaciones pulsando el botón Permitir.",
          isIos:
            "Si deseas recibir notificaciones en tu dispositivo iOS (a partir de la versión 16.4), debes añadir Webmail a la pantalla de inicio de tu dispositivo.",
        },
        browserNotification: {
          desc: "Comprueba el estado y gestiona las notificaciones del navegador actualmente en uso.",
          title: "Estado de las notificaciones del navegador en uso",
        },
        granted: "¡Las notificaciones de su navegador están configuradas correctamente!",
        noPush: {
          title:
            "Desafortunadamente, el navegador Safari no es compatible con el sistema de notificación.",
          titleios:
            "Desafortunadamente, el sistema operativo iOS no admite notificaciones del navegador.",
          desc: "Para habilitar las notificaciones, use la versión más actualizada de uno de los siguientes navegadores",
        },
        deniedPush: {
          title: "Su navegador está bloqueando las notificaciones automáticas.",
          desc: "Elimina este bloque para activar las notificaciones automáticas cuando llegue un nuevo mensaje.",
        },
        modal: {
          title: "¿Le gustaría permitir las notificaciones automáticas?",
          text: "Siempre puede permitirlos o bloquearlos en cualquier momento desde la configuración del correo web",
        },
      },
      parameters: {
        title: "Parámetros",
        host: {
          title: "Configuración de dispositivos",
          desc: "Conecte sus dispositivos para recibir y enviar correo electrónico con su cuenta.",
        },
        imap: {
          title: "IMAP",
        },
        smtp: {
          title: "SMTP",
        },
      },
      profile: {
        email: "Correo electrónico del usuario",
        generalSettings: {
          desc: "Gestionar preferencias de idioma y tiempo.",
          title: "Configuración general",
        },
        personalInfo: {
          desc: "Administre la información de su perfil.",
          title: "Informacion personal",
        },
        title: "Perfil",
      },
      security: {
        changepassword: {
          info: "Contraseña de al menos 8 caracteres alfanuméricos",
          desc: "Administrar contraseña para acceder a su webmail.",
          resetpassword: "Crear una contraseña nueva",
          resetpassworddisabled: "Cambio de contraseña desactivado en esta cuenta",
          resetpasswordexpired: "Su contraseña ha caducado, establecer una nueva",
          title: "Cambiar la contraseña",
        },
        days: "día/s",
        passwordexpiration: {
          activeExpiration:
            "La caducidad automática de la contraseña está habilitada para su cuenta de correo electrónico.",
          desc: "Verifique el estado de la contraseña de su cuenta.",
          expirationDate: "La contraseña caduca el",
          expirationCountdown: "La contraseña caduca en",
          modalTitle: "Su contraseña está a punto de caducar",
          modalDesc:
            "Quedan {{password_expiration_relative_days}} día/s hasta que caduque la contraseña de su cuenta. Le recomendamos que lo cambie de inmediato.",
          title: "Caducidad de la contraseña",
        },
        otp: {
          cantDisableOtp: "Autenticación de dos factores no se puede desactivar en esta cuenta",
          desc: "Administre la autenticación de dos factores para acceder a su correo web",
          disableOtp: "Desactivar autentificación en dos factores",
          downloadParams: "Download activation data",
          hideParams: "Ocultar parámetros",
          instructionDisableOtp:
            "Ingrese el código generado por la aplicación en el siguiente formulario para deshabilitar la autenticación de dos factores para esta cuenta.",
          instructionsSetOtp:
            "Escanea el Código QR con la aplicación e introduzca el código generado en el formulario. Alternativamente, introduzca manualmente los parámetros para la activación.",
          labelEnterCode: "Introducir código generado por la aplicación",
          paramAccount: "Cuenta",
          paramCode: "Código",
          paramType: "Basada en el tiempo",
          paramTypeVal: "Activa",
          params: "Introduce el código manualmente",
          paramsInstruction: "Introduzca los siguientes parámetros en la aplicación",
          setOtp: "Habilitar la autenticación de dos factores",
          title: "Establecer OTP",
          titleDisableOtp: "Desactivar OTP",
          titleSetOtp: "Habilitar OTP",
        },
        sessions: {
          browser: "Navegador:",
          currentSession: "Actual",
          device: "Dispositivo:",
          desc: "Gestiona las sesiones de acceso a tu webmail",
          ip: "IP:",
          os: "OS:",
          platform: "Plataforma:",
          removeAll: "Eliminar todo",
          removeSession: "Eliminar",
          startdate: "Comenzar:",
          title: "Sesiones abiertas",
        },
        title: "Seguridad",
      },
      title: "General",
    },
    mail: {
      accounts: {desc: "", title: "Cuentas"},
      antispam: {
        blacklist: {
          desc: "Agregar dirección o dominio a la lista (es. 'nombre@dominio' o '*@dominio')",
          msgNoHeader: "No permitir que los mensajes de",
          title: "Lista negra",
        },
        deleteRuleDsc: "Eliminar conjunto de normas para <code>{{ruleEmail}}</code>.",
        deleteRuleTitle: "Eliminar la norma antispam",
        placeholderList: " ",
        title: "Antispam",
        whitelist: {
          desc: "Agregar dirección o dominio a la lista (es. 'Nombre @ dominio' o '* @ dominio')",
          msgFromHeader: "Permitir mensajes de",
          msgToHeader: "Permitir que los mensajes",
          title: "Lista blanca",
        },
      },
      autoresponder: {
        desc: "Configure un mensaje de respuesta automática para cuando esté fuera de la oficina o no pueda responder a los mensajes recibidos.<br/>Si un contacto le ha enviado varios mensajes, la respuesta automática se enviará solo una vez cada 24 horas.",
        msg: "Mensaje",
        placholdeSubject: "Asunto",
        placholderTextarea: "Mensaje de texto",
        title: "Respuesta automática",
      },
      compose: {
        cancelSend: {
          desc: "Elija el tiempo de espera para cancelar el envío de un mensaje en curso, si decide que no desea enviar más el mensaje.",
          title: "Cancelar enviar correo electrónico",
        },
        confirmations: {
          desc: "Gestiona la lectura y notificación de envío de tus mensajes recibidos y enviados.",
          title: "Lectura / confirmación de entrega",
        },
        title: "Composición",
      },
      delegations: {desc: "", title: "Delegación"},
      filters: {
        actionsTitle: "Acciones",
        activeFiltersTitle: "Reglas activas",
        desc: "Crea reglas específicas para ordenar los mensajes entrantes y organízalos como quieras en tu buzón",
        headerItem: "Regla",
        headerStatus: "Activo",
        hintEqualOperator:
          "Atención: el uso del operador <em><b>es igual a</b></em> / <em><b>no es igual a</b></em> se recomienda solo a usuarios expertos. Alternativamente, se recomienda utilizar el operador <em><b>contiene</b></em> / <em><b>no contiene</b></em>. <br>Para usar el operador <em><b>es igual a</b></em> / <em><b>no es igual a</b></em>, debe hacer coincidir todos los elementos que componen el campo. Por ejemplo, para indicar el <em>Remitente</em> debe indicar todos los siguientes elementos: <b>descripción &lt;dirección de correo electrónico&gt;<b>.",
        parametersTitle: "Parámetros",
        placeholderList: {
          parameter: "Añadir parámetro a la regla",
          action: "Añadir acción a la regla",
        },

        title: "Reglas",
      },
      folders: {
        compactFolder: "Eliminar todos los mensajes marcados como eliminados de la carpeta",
        deleteFolderDsc:
          "Al eliminar la carpeta <code>{{folderName}}</code> se eliminarán todos los mensajes que contenga.<br/><b>La operación no es reversible.</b>.",
        deleteFoldersTitle: "Eliminar carpetas",
        desc: "Gestionar y compartir sus carpetas personales",
        descShared: "Administrar las carpetas compartidas",
        headerItem: "Carpetas",
        headerMsg: "Mensajes",
        headerPermissions: "Permisos",
        headerSelectedUsers: "Usuarios seleccionados",
        headerUnread: "No leído",
        modifyFolder: "Editar carpeta",
        newFolder: "Añadir nueva carpeta",
        retention: "Conjunto de reglas de eliminación automática",
        rootFolder: "- Raíz -",
        shared: "Compartido con otros usuarios",
        subscribe: "Suscribir",
        tabInfo: "Información de la carpeta",
        tabShare: "Compartir carpeta",
        title: "Carpetas",
        titleShared: "Carpetas compartidas",
      },
      forward: {
        description:
          "Elija las direcciones de correo electrónico para reenviar los mensajes que recibe.",
        headerItem: "Destinatarios",
        placeholderList: " ",
        title: "Reenviar mensajes",
        titleSection: "Reenviar mensajes",
      },
      labels: {
        desc: "Cree etiquetas de colores personalizadas para mantener sus mensajes de correo electrónico en orden.",
        headerItem: "Etiquetas",
        deleteLabelTitle: "Eliminar etiqueta",
        deleteLabelTitleDsc: "Al borrar la etiqueta, ésta desaparecerá de todos los mensajes.",
        placeholderList: " ",
        title: "Etiquetas correo",
      },
      reading: {
        layout: {
          desc: "Elija cómo desea que aparezca el panel de lectura.",
          title: "Diseño",
        },
        markReadSettings: {
          desc: "Establezca cuándo un mensaje debe marcarse como leído.",
          title: "Marcar mensaje como leído",
        },
        readingSettings: {
          desc: "Establezca su preferencia de lectura para los mensajes.",
          title: "Ajustes de lectura",
        },
        title: "Ver",
      },
      signature: {
        title: "Firma",
        bcc: {
          headerItem: "Destinatarios en CCO",
          placeholderList: "",
        },
        default: "Default",
        deleteNewSignatureModal: {
          description:
            "El contenido de la nueva firma no se ha guardado, se perderá si abre otra.<br/>¿Desea continuar?",
          title: "Eliminar nueva firma",
        },
        dropFiles: "Colocar aquí la imagen a añadir",
        management: {
          title: "Gestión de firmas",
        },
        onlyNewMessages: "No agregue firma en las respuestas",
        placeholderList: "Agrega tu primera identidad",
        senderBcc: "Añadir remitente en CCO",
        setAsDefault: "Establecer como remitente predeterminado",
        signatures: {
          desc: "Para cada identidad (grupo de alias) asociada a su cuenta, puede personalizar la firma que aparece al final de los correos electrónicos que envía y el nombre que muestran quienes reciben sus mensajes. Elija el remitente predeterminado y añada listas de direcciones de correo electrónico en CCO.",
          headerItemSignature: "Nombre a mostrar",
          headerItemIdentity: "Identidad",
          title: "Firmas e identidades",
        },
      },
      template: {
        addAttachment: "Seleccione un archivo para agregarlo como archivo adjunto al mensaje",
        deleteTemplateModal: {
          description:
            "¿Confirmar para eliminar el mensaje seleccionado? Los archivos adjuntos al mensaje también se eliminarán de nuestros sistemas.",
          title: "Eliminar mensaje enlatado",
        },
        title: "Mensajes enlatados",
        description:
          "Seleccione un mensaje enlatado de la lista para completar automáticamente el nuevo mensaje de redacción",
        placeholderList: "Agrega tu primer mensaje enlatado",
        placeholderSearch: "Filtrar mensajes",
        searchHint:
          "Utilice este campo para filtrar la lista de mensajes enlatados a continuación. El filtro funciona sobre el nombre, asunto y contenido del mensaje.",
        templates: {
          desc: "Simplifique la redacción de correos electrónicos recurrentes guardando mensajes enlatados para elegir al redactar el correo electrónico.",
          headerItemPreview: "Vista previa",
          headerItemSubject: "Asunto",
          headerItemTemplate: "Nombre",
          maxAttachmentsNrBasic:
            "Máximo {{attachmentNr}} archivos adjuntos. Máximo {{templateSize}} MB en total. Póngase en contacto con su proveedor de servicios de correo electrónico para aumentar estos límites.",
          maxAttachmentsNr:
            "Máximo {{attachmentNr}} archivos adjuntos. Máximo {{templateSize}} MB en total.",
          maxTemplateNrReached:
            "Se ha alcanzado el número máximo de mensajes enlatados configurables.",
          maxTemplateNrReachedContactReseller:
            "Se ha alcanzado el número máximo de mensajes enlatados configurables. Si necesita agregar más plantillas de correo electrónico, comuníquese con su proveedor de servicios de correo electrónico para obtener más información.",
          newTemplate: "Nuevo mensaje",
          title: "Mensajes enlatados",
        },
      },
      title: "Correo",
    },
    meeting: {
      title: "Reunión",
      view: {
        desc: "",
        title: "Ver",
      },
    },
    news: {
      readMore: "Leer mas",
      title: "News & Updates",
    },
    privacy: {
      title: "Privacy",
      cookie: {
        title: "Cookie Policy",
      },
      privacy: {
        title: "Privacy Policy",
      },
    },
    shortcuts: {
      title: "Atajos de teclado",
    },

    tasks: {
      notifications: {
        desc: "Reciba un correo electrónico cuando se le asigne una tarea o cuando se cierre una tarea que haya asignado",
        title: "Notificaciónes por Correo Electrónico",
      },
      labels: {
        title: "Etiquetas de tareas",
        desc: "Crea etiquetas de colores personalizadas para catalogar tus tareas.",
      },
      title: "Tareas",
    },

    title: "Ajustes",
    unsaved: "Hay cambios sin guardar",
  },

  tasks: {
    add: "Crear tarea para mi lista",
    assignedBy: "Asignado por",
    assignedTaskLabel: "<b>{{user}}</b> te asignó una nueva tarea:",
    assignedTaskTitle: "Nueva tarea asignada",
    assignedTo: "Asignado a",
    assignTask: "Crear tarea para asignar",
    basic: {
      label:
        "La gestión de tareas es un servicio disponible<br />cuando actualizas tu perfil.<br /><br />La actualización también incluye un calendario<br />compartido y una videoconferencia integrada.",
      modalTitle: "Herramientas para optimizar tu trabajo",
      modalSubTitle: "disponible con actualización de perfil",
      modalFooter:
        "Su referente puede presentarle en detalle las características adicionales, sin compromiso",
      calendarLabel: "<b>Calendario</b> compartido.",
      tasksLabel: "<b>Tareas</b> y recordatorios.",
      signatureLabel: "<b>Firma</b> de correo electrónico centralizada.",
      zoomLabel: "<b>Zoom</b> integrado para videollamadas.",
      requestInfo: "Estoy interesado",
      requestInfoConfirmation: {
        text: "Será contactado por su referente..",
        title: "La solicitud de información ha sido enviada.",
      },
      requestLater: "Quizas mas tarde",
    },
    closedTaskLabel: "<b>{{user}}</b> completó una tarea:",
    closedTaskTitle: "Tarea asignada completada",
    completionDate: "Terminada",
    deleteTaskModal: {
      desc: "¿Está seguro de que desea eliminar la tarea seleccionada? Si la tarea se ha asignado a otros usuarios, también se eliminará para ellos.",
      title: "Eliminar tarea",
    },
    dueTime: {
      today: "Hoy dia",
      tomorrow: "Mañana",
      nextWeekend: "Próximo fin de semana",
      thisWeekend: "Este fin de semana",
      custom: "Fecha y hora",
    },
    labels: "Etiquetas",
    deleteLabelTitle: "Elimina la etiqueta",
    deleteLabelDsc:
      "Esta etiqueta ha sido asignada a una o más actividades. ¿Proceder a su eliminación?",
    linkedMail: "Correo electrónico vinculado",
    listImagesLabels: {
      completed: {
        text: "La lista de tareas completadas está vacía.",
        title: "Sin tareas completadas",
      },
      overdue: {
        text: "No tienes tareas atrasadas por hacer",
        title: "Buen trabajo",
      },
      notCompleted: {
        text: "No has planeado ninguna tarea para hacer",
        title: "Nada que hacer aquí",
      },
      search: {
        text: "Escribe algo para realizar una búsqueda.",
        title: "Busca...",
      },
      assignedToDo: {
        text: "La lista de tareas asignadas está vacía",
        title: "No has asignado ninguna actividad",
      },
      assignedCompleted: {
        text: "La lista de tareas asignadas completadas está vacía",
        title: "No se completaron las tareas asignadas",
      },
      noResult: {
        title: "No se han encontrado resultados",
      },
    },
    lists: "Listas",
    modalTitle: "Detalles de la tarea",
    note: "Notas (1000 caracteres máximo)",
    occurrences: {
      all: "Todas las ocurrencias",
      occurrence: "Solo esta ocurrencia",
    },
    openedTaskLabel: "<b>{{user}}</b> ha vuelto a abrir una tarea completada:",
    openedTaskTitle: "Tarea asignada reabierta",
    openMessageModal: {
      desc: "Si abre el mensaje vinculado a la tarea, se cerrará la lista de tareas.",
      title: "¿Quieres abrir el mensaje?",
    },
    overdueTasksPresent: "Tareas atrasadas: {{overdueTasksPresentCount}}",
    planned: "Cuándo",
    repeat: "Repetir",
    repetitions: {
      NEVER: "Nunca",
      DAILY: "A diario",
      WEEKLY: "Semanalmente",
      MONTHLY: "Mensualmente",
      YEARLY: "Anualmente",
    },
    showMyTasks: "Mis tareas",
    showAssignedTasks: "Asignado a otros",
    task: "Tarea",
    taskFromNotification:
      "¿Quieres ver los detalles de la tarea notificada y perder los datos de la nueva tarea que se está elaborando?",
    title: "Tareas",
    types: {
      view_todo: "Que hacer",
      view_all: "Todas",
      view_today: "Hoy dia",
      view_next7: "próximos 7 días",
      view_overdue: "Atrasadas",
      view_completed: "Terminadas",
    },
  },

  toast: {
    error: {
      alreadyPresent: "Advertencia, el recurso ya existe",
      avatarTooBig: "Advertencia, el tamaño del avatar es demasiado grande",
      compact: "Error al compactar carpeta",
      connectionUnavailable: "No hay conexión disponible",
      delete: "Error en la supresión",
      deleteDraft: "Error eliminando el borrador",
      emailAddressNotValid: "El correo electrónico no es válido",
      enqueued: "Actualizando los ajustes, vuelva a intentarlo",
      fetchingAttachments: "Error al buscar archivo adjunto",
      filterActionsMissing: "Acciones que no están presentes",
      filterConditionsMissing: "Los parámetros no presentes",
      filterNameMissing: "Falta el nombre de la regla",
      folderCreation: "Error al crear nueva carpeta",
      folderCreationCharNotValid:
        "Error al crear / cambiar el nombre de la carpeta, caracter no válido ({{char}})",
      folderCreationNoName: "Error al crear la carpeta, necesita especificar un nombre válido",
      folderDelete: "Error al eliminar la carpeta",
      folderNotPresent: "Carpeta no presente",
      folderRename: "Error al cambiar el nombre de la carpeta, ya se encuentra presente",
      folderSubscribe: "Error al suscribirse a la carpeta",
      generic: "Algo salió mal",
      invalidDateRange: "Date range not valid",
      maxMembers: "Alerta, número máximo de miembros alcanzado",
      maxSignatureSize: "Se ha superado el tamaño máximo de firma. Max {{maxSize}}",
      maxTemplateAttachmentsNumberReached:
        "Se ha alcanzado el límite de archivos adjuntos para este mensaje enlatado",
      maxTemplateSize: "Advertencia, el tamaño del mensaje enlatado es demasiado grande",
      maxTemplatesNumberReached:
        "Se ha alcanzado el límite de mensajes enlatados que se pueden configurar para esta cuenta",
      messageCopy: "Error copiando mensajes",
      messageMove: "Error al mover mensajes",
      messageNotFound: "Mensaje no encontrado",
      messageRemove: "Error al borrar mensajes",
      missingParameters: "Faltan parámetros",
      missingSettings: "Falta la configuración del usuario",
      notifications: "Error al obtener notificaciones",
      notPermitted: "Operación no permitida",
      notValid: "Advertencia, valor no válido",
      onlyOneHomeAddress: "Sólo se puede insertar una dirección de casa",
      onlyOneWorkAddress: "Sólo se puede insertar una dirección de trabajo",
      save: "Error al guardar",
      saveAcl: "Error al guardar los permisos de la carpeta",
      saveEvent:
        "Ocurrió un error, es posible que no tenga suficientes permisos en este calendario",
      saveZoomMeeting: "No se ha podido crear la reunión en la plataforma Zoom",
      savingDraft: "Guardado de borrador en progreso, por favor, inténtalo de nuevo al acabar",
      searchNotAvailable: "Búsqueda no disponible en este momento",
      sendingMessage: "Error en la entrega de mensajes",
      serverDisconnection:
        "El servidor se está actualizando, por favor, inténtalo de nuevo más tarde",
      sessionExpired: "Ha expirado la sesión",
      smtpBlockedByAntispam: "Mensaje no enviado: bloqueado por antispam",
      smtpBlockedByAntivirus: "Mensaje no enviado: bloqueado por antivirus",
      smtpDisabled: "Mensaje no enviado: SMTP deshabilitado en esta cuenta",
      smtpQuotaExceeded: "Mensaje no enviado: se ha sobrepasados la cuota de mensajes enviados ",
      requestLimit:
        "Se ha excedido el límite de solicitud de números, inténtalo de nuevo más tarde",
      requestError: "Error durante la solicitud, inténtalo de nuevo más tarde",
      updateFolders: "Se ha producido un error en la actualización de carpetas",
      updateMessageEvent: "Error al obtener la actualización del estado del evento",
      updatingParentFlags: "Error al actualizar las alertas de mesaje",
    },
    info: {
      newVersionAvailable: {
        desc: "Esta operación es segura, no se modificarán los ajustes",
        title:
          "Las nuevas características están disponibles, vuelve a cargar la página para actualizar el correo web a la última versión",
      },
      serverReconnected: "Webmail está en línea de nuevo",
      sourceMail: "Fuente del correo copiada al portapapeles",
    },
    progress: {
      newFolder: "Creacion de nueva carpeta en curso",
      operationInProgress: "Operación en curso",
    },
    success: {
      compact: "Carpeta compactada con éxito",
      copiedLink: "Link copiado al portapapeles",
      copiedMail: "Mensaje copiado con éxito",
      copiedMailAddress: "Dirección de correo electrónico copiado al portapapeles",
      copiedText: "Text copied to the clipboard",
      createFolder: "Carpeta creada correctamente",
      delete: "Eliminado con éxito",
      disabledOtp: "OTP desactivado con éxito",
      enabledOtp: "OTP activado con éxito",
      movedMail: "Mensaje trasladado con éxito",
      notificationEnabled: "Notificaciones del navegador activadas correctamente",
      otpDisabled: "OTP deshabilitado con éxito",
      otpEnable: "OTP activado con éxito",
      save: "Guardado con éxito",
      saveAcl: "Permisos guardados correctamente",
      saveDraft: "Borrador guardado correctamente",
      saveFolder: "Carpeta actualizada correctamente",
      sentMail: "Mensaje enviado con éxito",
      subscribeFolder: "Suscripción actualizada correctamente",
      updateMessageEvent: "Estado del evento actualizado",
    },
    warning: {
      forwardSet: "Se ha configurado al menos un reenvío en esta cuenta",
      notificationNotSupported: "Atención, su navegador no admite notificaciones",
    },
  },

  toggles: {
    labels: {
      allDayEvent: "Todo el dia",
      autoSaveContact:
        "Guardar automáticamente todos los destinatarios que no están presentes en sus agendas",
      denyInvites: "Evitar invitaciones a citas",
      enableAutorespopnd: "Habilitar respuesta automática",
      enableAutorespopndInterval: "Habilitar el rango de fechas",
      enableBrowserNotification: "Enable browser notifications",
      enableDateSearch: "Habilitar búsqueda de fecha",
      enableFullBody: "Habilitar la búsqueda en el cuerpo de texto",
      enableNotification: "Enable browser notifications",
      keepCopy: "Mantener copia del mensaje a nivel local",
      showPriority: "Mostrar prioridad del mensaje recibido",
      showThreads: "Mostrar mensajes como hilo",
      subscribeFolder: "Subscribirse a carpeta",
      tasksEmailNotifications: "Habilitar notificaciones por correo electrónico",
    },
    hint: {
      enableFullBody:
        "La búsqueda de cuerpo completo está disponible solo para una sola carpeta. Seleccione una carpeta para habilitarla.",
    },
  },

  wizard: {
    layout: {
      desc: "Personalizar el Webmail eligiendo los parámetros de vista que prefieras",
      title: "Ver opciones",
    },
    wizardData: {
      desc: "Personalizar su perfil añadiendo una imagen y completando los datos que faltan",
      title: "Perfil completo",
    },
  },
};
