/*********************************************************************************************************
 * English Copyright (C) 2017-2019 by Qboxmail Srl
 *
 * All rights reserved. No part of this publication may be reproduced, distributed, or transmitted in any
 * form or by any means, including photocopying, recording, or other electronic or mechanical
 * methods, without the prior written permission of the publisher, except in the case of brief quotations
 * embodied in critical reviews and certain other noncommercial uses permitted by copyright law. For
 * permission requests, write to the publisher at the address below.
 *
 * Qboxmail Srl - IT02338120971
 * https://www.qboxmail.it - info@qboxmail.it
 *
 * Italiano Copyright (C) 2017-2019 by Qboxmail Srl
 *
 * Tutti i diritti riservati. Nessuna parte di questa pubblicazione può essere riprodotta, memorizzata in
 * sistemi di recupero o trasmessa in qualsiasi forma o attraverso qualsiasi mezzo elettronico, meccanico,
 * mediante fotocopiatura, registrazione o altro, senza l'autorizzazione del possessore del copyright salvo
 * nel caso di brevi citazioni a scopo critico o altri usi non commerciali consentiti dal copyright. Per le
 * richieste di autorizzazione, scrivere all'editore al seguente indirizzo.
 *
 * Qboxmail Srl - IT02338120971
 * https://www.qboxmail.it - info@qboxmail.it
 *********************************************************************************************************/

export default {
  addressbook: {
    contact: {
      oneSelectContacts: "Contatto selezionato",
      oneSelectLists: "Lista selezionata",
      notSelected: "Seleziona un contatto",
      sectionLabels: {
        address: "Indirizzo",
        company: "Azienda",
        email: "Email",
        info: "Info",
        telephone: "Telefono",
        homeUrl: "Sito web personale",
        workUrl: "Sito web lavoro",
      },
      sections: {
        cell: "Cellulare",
        home: "Casa",
        homeFax: "Fax casa",
        work: "Lavoro",
        workFax: "Fax lavoro",
        title: "Ruolo",
        company: "Azienda",
        note: "Note",
        bday: "Data di nascita",
      },
      selectContacts: "Contatti selezionati",
      selectLists: "Liste selezionate",
      selectedInfo: "Scegli un contatto dalla lista per visualizzare le informazioni.",
    },
    contactsList: {
      emptyContacts: "Questa rubrica è vuota",
      emptyContactsInfo: "Aggiungi un contatto alla rubrica",
      emptyLists: "Non ci sono liste",
      emptyListsInfo: "Aggiungi una nuova lista",
      foundContacts: "Trovati",
      notFound: "Nessun contatto trovato",
      notFoundInfo: "La ricerca non ha prodotto risultati, riprova utilizzando criteri diversi.",
      totalContacts: "Contatti",
    },
    tabs: {
      contacts: "Contatti",
      lists: "Liste",
    },
    contextualMenuLabels: {
      address: "Indirizzo",
      birthday: "Compleanno",
      cancel: "Annulla",
      cell: "Cellulare",
      delete: "Elimina",
      downloadVCard: "Download VCard",
      email: "Email",
      newContact: "Nuovo contatto",
      createList: "Crea lista",
      newList: "Nuova lista",
      note: "Note",
      phone: "Telefono",
      shareVCard: "Condividi",
      showVCard: "Visualizza VCard",
      sendAsAttachment: "Invia per email",
      sendMail: "Invia email",
      url: "Sito",
      info: "Info",
      title: "Ruolo",
      company: "Azienda",
      home: "Casa",
      homeFax: "Fax casa",
      work: "Lavoro",
      workFax: "Fax lavoro",
      nickname: "Nickname",
      displayName: "Nome visualizzato",
      companyName: "Nome",
      homeUrl: "Sito web personale",
      workUrl: "Sito web lavoro",
      team: "Team",
      merge: "Unisci",
    },
    deleteContactDsc:
      "Eliminando il contatto <code>{{contact}}</code> tutte le informazioni relative saranno cancellate.<br/><b>L'operazione non è reversibile</b>.",
    deleteContactDscList:
      "Eliminando il contatto selezionato tutte le informazioni relative saranno cancellate.<br/><b>L'operazione non è reversibile</b>.",
    deleteContactTitle: "Elimina contatto",

    deleteContactsDsc:
      "Eliminando i contatti selezionati tutte le informazioni relative saranno cancellate.<br/><b>L'operazione non è reversibile</b>.",
    deleteContactsTitle: "Elimina contatti",

    deleteListDsc:
      "Eliminando la lista <code>{{contact}}</code> tutte le informazioni relative saranno cancellate.<br/><b>L'operazione non è reversibile</b>.",
    deleteListTitle: "Elimina lista",

    editContactModal: {
      title: "Modifica contatto",
    },
    editListModal: {
      title: "Modifica lista",
    },
    exportAddressBookModal: {
      desc: "Stai esportando la rubrica: <code>{{addressbookExport}}</code><br/>Scegli il formato con cui esportare tutti i contatti presenti",
      title: "Esporta rubrica",
    },
    import: {
      contactsInvalid: "Non validi:",
      contactsNr: "Totale contatti da importare:",
      contactsValid: "Validi:",
      desc: "Stai importando dei contatti nella rubrica: <code>{{addressbookImport}}</code><br/>È possibile importare contatti da altre app di posta utilizzando un file in formato vCard (<strong>.vcf</strong>) o <strong>.ldif</strong>.\u000AAd esempio, puoi esportare i contatti da Gmail o da Outlook e importarli qui.\u000AL'importazione non sostituirà nessuno dei contatti già esistenti.",
      dropFiles: "Carica o rilascia qui il file da importare",
      error: "Non è stato possibile importare i contatti",
      importing:
        "Stiamo importando <b>{{contactsNumber}}</b> contatti nella rubrica: <code>{{addressbookImport}}</code>",
      loading: "Caricamento...",
      success: "Importazione avvenuta con successo!",
      title: "Importa contatti",
      uploadedFile: "Caricato",
      uploadingFile: "Caricamento",
    },
    list: {
      desc: "Creando una lista contatti, è possibile mandare email a più persone contemporaneamente. Possono essere aggiunti fino a 150 membri scegliendoli dalla lista dei contatti nella rubrica selezionata.</br></br><b>Nota</b>: Non è possibile aggiungere indirizzi email che non si trovano nella rubrica selezionata. Aggiungi i contatti alla rubrica prima di aggiungerli alla lista.",
      members: "Membri lista",
    },
    messages: {
      newContactAddressBookBody:
        "Non è possibile inserire un contatto su <b>Rubrica aziendale</b>.<br/>Seleziona una rubrica personale o condivisa.",
      newContactAddressBookTitle: "Seleziona rubrica",
      resetListBody:
        "I membri della lista sono collegati alla rubrica selezionata. La modifica porterà alla cancellazione dei contatti inseriti. Proseguire ?",
      resetListTitle: "Cancellazione membri",
    },
    modifyAddressBookModal: {
      desc: "",
      title: "Modifica rubrica",
    },
    newAddressBookModal: {
      desc: "",
      title: "Crea rubrica",
    },
    newContactModal: {
      title: "Crea contatto",
    },
    newListModal: {
      title: "Crea lista",
    },
    shareModal: {
      desc: "Stai condividendo la rubrica: <code>{{addressbookShare}}</code><br/>Seleziona i contatti con cui vuoi condividere la rubrica e assegna loro dei permessi di gestione.",
      title: "Condividi rubrica",
    },
    sidebar: {
      allContacts: "Tutti i contatti",
      deleteAddressbookDsc:
        "Eliminando la rubrica <code>{{addressbook}}</code> verranno eliminati tutti i contatti inclusi.<br/><b>L'operazione non è reversibile</b>.",
      deleteAddressbookTitle: "Eliminare rubrica",
      globalAddressbook: "Rubrica aziendale",
      personalAddressbook: "Rubrica personale",
      sharedAddressbooks: "Rubriche condivise",
      userAddressbooks: "Rubriche utente",
    },
    subscribeModal: {
      desc: "",
      noAddressbook: "Non ci sono rubriche da sottoscrivere",
      title: "Sottoscrivi una rubrica condivisa",
    },
  },

  app: {
    addressbook: "Rubrica",
    calendar: "Calendario",
    chat: "Chat",
    meeting: "Meeting",
    mtm: "Mail Time Machine",
    of: "di",
    webmail: "Webmail",
    modal: {
      updateAvailable: {
        title: "Aggiornamento disponibile",
        description:
          "È disponibile una <b>nuova versione della Webmail</b>.<br/>Clicca per ricaricare e aggiornare, le tue impostazioni rimarranno invariate.<br/><br/>L'applicazione si aggiornerà automaticamente tra:",
      },
    },
  },

  avatarEditorModal: {
    photoTitle: "Scatta foto",
    title: "Modifica avatar",
    zoom: "Zoom -/+",
  },

  banner: {
    info: {
      mailRetention:
        "I messaggi in questa cartella verranno automaticamente eliminati dopo 30 giorni.",
    },
    warning: {
      labelCalendarUpdate:
        "Si prega di notare che se un'etichetta viene rinominata, non sarà più visibile negli eventi in cui viene utilizzata.",
      labelMailUpdate:
        "Si prega di notare che se un'etichetta viene rinominata, non sarà più visibile nei messaggi email in cui viene utilizzata.",
      labelTaskUpdate:
        "Si prega di notare che se un'etichetta viene rinominata, non sarà più visibile nelle attività in cui viene utilizzata.",
      mailRetention:
        "Attenzione, i messaggi verranno cancellati automaticamente in modo definitivo senza possibilità di recupero.<br><b>La cancellazione sarà operativa entro 24 ore.</b>",
    },
  },

  buttons: {
    accept: "Accetta",
    add: "Aggiungi",
    addAction: "Aggiungi azione",
    addAddressbook: "Rubrica",
    addAsAttachment: "Allega",
    addAttachments: "Aggiungi allegati",
    addCalendar: "Calendario",
    addField: "Aggiungi campo",
    addHolidayCalendar: "Calendario festività",
    addInline: "Inserisci in linea",
    addLabel: "Aggiungi etichetta",
    addParameter: "Aggiungi parametro",
    addSignature: "Aggiungi firma",
    addToList: "Aggiungi alla lista",
    allow: "Consenti",
    apply: "Applica",
    assign: "Assegna",
    backAddressbook: "Chiudi",
    backTo: "Indietro",
    cancel: "Annulla",
    changeImage: "Cambia immagine",
    changePassword: "Cambia password",
    checkFreeBusy: "Verifica disponibilità",
    close: "Chiudi",
    comeBackLater: "Torna più tardi",
    configure: "Configura",
    confirm: "Conferma",
    copied: "Copiato",
    copy: "Copia",
    copyLink: "Copia link",
    createFolder: "Nuova cartella",
    decline: "Rifiuta",
    delete: "Elimina",
    deleteDraft: "Elimina bozza",
    details: "Dettagli",
    disable: "Disabilita",
    disabled: "Disabilitata",
    disableOTP: "Disattiva OTP",
    download: "Scarica",
    edit: "Modifica",
    editLabel: "Modifica etichetta",
    editSignature: "Modifica firma",
    empty: "Svuota",
    enable: "Abilita",
    event: "Evento",
    export: "Esporta",
    generateNewPassword: "Genera nuova password",
    generateRandomPassword: "Genera password casuale",
    goToCalendar: "Vai al calendario",
    goToEventDay: "Vai al giorno dell'evento",
    goToMail: "Torna alla mail",
    goToOldWebmail: "Vai alla vecchia webmail",
    goToSettings: "Vai alla gestione",
    hide: "Nascondi",
    ignore: "Ignora",
    import: "Importa",
    insertHTML: "Inserisci HTML",
    keep: "Mantieni",
    label: "Etichetta",
    later: "Più tardi",
    learnMore: "Scopri di più",
    leftRotate: "Ruota a sinistra di 90 gradi",
    loadImage: "Carica immagine",
    loading: "Caricamento",
    logout: "Logout",
    makePhoto: "Scatta foto",
    markRead: "Letto",
    markSeen: "Marca",
    markUnread: "Non letto",
    message: "Messaggio",
    modify: "Modifica",
    new: "Nuovo",
    newContact: "Nuovo contatto",
    newEvent: "Nuovo evento",
    newMessage: "Nuovo messaggio",
    newSignature: "Nuova firma",
    newTask: "Nuova attività",
    newWebmail: "Nuova Webmail",
    next: "Successivo",
    noThanks: "No, grazie",
    occurrence: "Ricorrenza",
    ok: "Ok",
    oldWebmail: "Vecchia Webmail",
    openMap: "Apri in mappa",
    otherOptions: "Altre opzioni",
    override: "Sovrascrivi",
    participate: "Partecipa",
    postpone: "Posticipa",
    reloadPage: "Ricarica pagina",
    removeImage: "Rimuovi immagine",
    rename: "Rinomina",
    reorder: "Riordina",
    reorderEnd: "Fine riordina",
    report: "Segnala",
    restore: "Richiedi ripristino",
    retryImport: "Ritenta",
    save: "Salva",
    saveDraft: "Salva bozza e chiudi",
    saveNextAvailability: "Salva disponibilità proposta",
    search: "Cerca",
    send: "Invia",
    series: "Serie",
    setOtp: "Attiva OTP",
    share: "Condividi",
    show: "Mostra",
    showAll: "Mostra tutte",
    showMore: "Mostra altro",
    showToDo: "Mostra da fare",
    showUrlsAddressbook: "Mostra URL rubrica",
    showUrlsCalendar: "Mostra URL calendario",
    snooze: "Posponi",
    starred: "Segna",
    subscribe: "Sottoscrivi",
    subscribeAddressbook: "Sottoscrivi rubrica",
    subscribeCalendar: "Sottoscrivi calendario",
    tentative: "Forse",
    understand: "Ho capito",
    unlink: "Rimuovi link",
    unsetOtp: "Disattiva OTP",
    unsubscribe: "Desottoscrivi",
    unsubscribeList: "Annulla iscrizione",
    update: "Aggiorna",
    updateFilter: "Aggiorna filtro",
    defaultImg: "Usa immagine predefinita",
    viewMap: "Visualizza mappa",
  },

  buttonIcons: {
    activeSync: "Sincronizza con Microsoft® Exchange ActiveSync",
    activeSyncNot: "Rimuovi Microsoft® Exchange ActiveSync",
    alignCenter: "Centra",
    alignLeft: "Allinea a sinistra",
    alignRight: "Allinea a destra",
    backgroundColor: "Colore sfondo",
    backTo: "Indietro",
    bold: "Grassetto",
    cannedMsg: "Modelli email",
    close: "Chiudi",
    confirm: "Conferma",
    createTask: "Crea attività",
    delete: "Elimina",
    download: "Download",
    downloadVCard: "Download VCard",
    edit: "Modifica",
    emoji: "Emoji",
    forward: "Inoltra",
    fullscreen: "Schermo intero",
    fullscreenNot: "Chiudi schermo intero",
    imageAdd: "Inserisci immagine",
    indent: "Aumenta rientro",
    insertHTML: "Inserisci HTML",
    italic: "Corsivo",
    link: "Inserisci link",
    maintenance: "Compatta",
    maxmized: "Ingrandisci",
    minimized: "Riduci",
    more: "Altro...",
    moveDown: "Sposta sotto",
    moveUp: "Sposta sopra",
    next: "Successivo",
    orderList: "Elenco numerato",
    outdent: "Diminuisci rientro",
    pin: "Fissa",
    previous: "Precedente",
    print: "Stampa",
    quote: "Citazione",
    removeFormatting: "Rimuovi formattazione",
    removeQuote: "Rimuovi citazione",
    reply: "Rispondi",
    replyAll: "Rispondi a tutti",
    saveDraft: "Salva bozza",
    sendDebug: "Invia messaggio non visualizzabile",
    sendMail: "Invia email",
    sendByEmail: "Invia per email",
    share: "Condividi",
    showSidebar: "Mostra / nascondi sidebar",
    showSourceCode: "Mostra sorgente",
    showVCard: "Visualizza VCard",
    spam: "Marca come Spam",
    spamNot: "Marca come No Spam",
    startChat: "Inizia chat",
    startMeeting: "Inizia meeting",
    strike: "Barrato",
    subscribe: "Sottoscrivi",
    textColor: "Colore testo",
    thanks: "Ringrazia",
    understand: "Ho capito",
    underline: "Sottolineato",
    undo: "Annulla",
    unlink: "Rimuovi link",
    unorderList: "Elenco puntato",
    unSubscribe: "Elimina sottoscrizione",
  },

  calendar: {
    alarmDurations: {
      after: "dopo",
      before: "prima",
      day: "giorni",
      hour: "ore",
      minute: "minuti",
      second: "secondi",
      week: "settimane",
    },
    deleteEvent: "Cancellazione evento",
    deleteEventDsc: "Procedere con la cancellazione dell'evento selezionato?",
    deleteSeries: "Cancellazione serie",
    deleteSeriesDsc: "Procedere con la cancellazione della serie selezionata?",
    event: {
      alarmsNotPresent: "Nessun avviso",
      deleteEventOccurrenceTitle: "Eliminare evento o serie?",
      deleteEventOccurrenceDesc:
        "L'evento che vuoi eliminare fa parte di una serie. Eliminando il singolo evento gli altri presenti nella serie rimarranno invariati.",
      eventNotes: "Note dell'evento",
      eventAttendees: "Partecipanti all'evento",
      fromDay: "da",
      labelsNotPresent: "Nessuna etichetta",
      locationContextualMenuLabels: {
        zoomLabel: "Zoom",
        zoomHint: "Meeting Web",
        personalMeetingLabel: "Stanza meeting personale",
        personalMeetingHint: "Meeting Web",
        locationLabel: "Incontro",
        locationHint: "Inserisci un indirizzo o una località",
        textLabel: "Personalizzato",
        textHint: "Inserisci un testo personalizzato",
      },
      locationSelector: "Scegli il luogo dell'evento",
      locationZoomNoMeeting:
        "Una volta salvato l'evento qui sarà presente il link del meeting Zoom",
      maxAttachmentsNumberTitle: "Troppi allegati!",
      maxAttachmentsNumberDsc:
        "Puoi inserire al massimo 4 allegati. Se hai bisogno di allegare più di 4 file, ti suggeriamo di creare una cartella compressa.",
      maxLabelsNumberTitle: "Troppe etichette!",
      maxLabelsNumberDsc:
        "È stato raggiunto il numero massimo di etichette associabili a un evento. Per aggiungere una nuova etichetta devi prima rimuovere una di quelle già presenti.",
      noTitle: "Senza titolo",
      notIncludedInFreeBusy:
        "Questo calendario non è incluso nel Free/Busy. Questo implica che tu e le persone che inviti sarete mostrati come <b>disponibili</b> durante gli eventi creati in questo calendario.",
      organizerTitle: "Creato da",
      pendingMsg: "Evento in attesa di conferma",
      permissionDenied:
        "Impossibile visualizzare i dettagli dell'evento selezionato, potresti non avere i permessi necessari.",
      repeatEvent: "Questo evento fa parte di una serie",
      saveEventOccurrenceTitle: "Visualizzare evento o serie?",
      saveEventOccurrenceDesc:
        "L'evento che vuoi visualizzare o modificare fa parte di una serie. Modificando il singolo evento gli altri presenti nella serie rimarranno invariati.",
      setAlert: "Imposta avviso",
      toDay: "a",
    },
    eventRepetition: {
      WeekDayNumberInMonth_1: "Primo/a",
      WeekDayNumberInMonth_2: "Secondo/a",
      WeekDayNumberInMonth_3: "Terzo/a",
      WeekDayNumberInMonth_4: "Quarto/a",
      WeekDayNumberInMonth_5: "Quinto/a",
      never: "Mai",
      after: "Dopo;ricorrenze",
      inDate: "In data",
      end: "Termina ricorrenza",
    },
    filterView: {
      listmonth: "Agenda",
      day: "Giorno",
      month: "Mese",
      week: "Settimana",
      workWeek: "Sett. lavorativa",
      year: "Anno",
    },
    import: {
      contactsInvalid: "Non validi:",
      contactsNr: "Totale eventi da importare:",
      contactsValid: "Validi:",
      dropFiles: "Carica o rilascia qui il file da importare",
      error: "Non è stato possibile importare gli eventi",
      importing:
        "Stiamo importando <b>{{eventsNumber}}</b> eventi nel calendario: <code>{{calendarImport}}</code>",
      info: "Stai importando degli eventi nel calendario: <code>{{calendarImport}}</code><br/>È possibile importare eventi da altre app di posta utilizzando un file in formato ICS. Ad esempio, puoi esportare gli eventi da Gmail o da Outllook in formato ICS e importarli qui.<br/><b>L'importazione non sostituirà nessuno degli eventi già esistenti</b>.",
      loading: "Caricamento...",
      success: "Tutti i tuoi eventi sono stati importati con successo!",
      title: "Importa eventi",
      uploadedFile: "Caricato",
      uploadingFile: "Caricamento",
    },
    modifyCalendarModal: {
      desc: "",
      title: "Modifica calendario",
    },
    newCalendarModal: {
      desc: "",
      title: "Crea calendario",
      freeBusyInfo:
        "Se il calendario non viene incluso nel <b>Free/Busy</b>, tu e le persone che inviti sarete mostrati come <b>disponibili</b> durante gli eventi creati in questo calendario.",
    },
    newEvent: {
      attachmentsList: {
        headerItem: "Allegati",
        placeholderList: " ",
      },
      desc: "",
      dropFiles:
        "Carica o rilascia qui il file da allegare<br>(massimo 4 allegati, 3 MB ciascuno).",
      freeBusy: {
        legend: {
          event: "Evento",
          busy: "Occupato",
          waiting: "In attesa",
          availability: "Prossima disponibilità",
        },
      },
      hideDetails: "Nascondi dettagli",
      participantsList: {
        headerItem: "Partecipanti",
        answeredHeaderItem: "Con risposta",
        notAnsweredHeaderItem: "in attesa di risposta",
        placeholderList: " ",
      },
      showDetails: "Mostra dettagli",
      tabAttachments: "Allegati",
      tabDetails: "Dettagli",
      tabParticipants: "Partecipanti",
      tabSeries: "Ripetizioni",
      tabSettings: "Impostazioni",
      title: "Crea evento",
      titleEdit: {
        event: "Evento",
        series: "Serie",
      },
      titleFreebusy: "Disponibilità dei partecipanti",
    },
    nextAvailability: "Prossima disponibilità",
    searchEvents: {
      notFound: "Nessun evento trovato",
      notFoundInfo: "La ricerca non ha prodotto risultati, riprova utilizzando criteri diversi",
    },
    shareModal: {
      desc: "Stai condividendo il calendario: <code>{{calendarShare}}</code><br/>Seleziona i contatti con cui vuoi condividere il calendario e assenga loro dei permessi di gestione.",
      title: "Condividi calendario",
    },
    sidebar: {
      labels: "Etichette",
      personalCalendar: "Calendario personale",
      sharedCalendars: "Calendari condivisi",
      userCalendars: "Calendari utente",
      deleteCalendarDsc:
        "Eliminando il calendario <code>{{calendar}}</code> tutti gli eventi presenti saranno cancellati.<br/><b>L'operazione non è reversibile</b>.",
      deleteCalendarTitle: "Eliminare calendario",
    },
    subscribeModal: {
      desc: "",
      noCalendar: "Non ci sono calendari da sottoscrivere",
      title: "Sottoscrivi un calendario condiviso",
    },
    today: "Oggi",
  },

  circularLoopBar: {
    uploading: "Caricamento",
  },

  comingSoon: "Sviluppo in corso...",

  contactImport: {
    title: "Ricerca contatti in corso",
    desc: "Stiamo importando i tuoi contatti. L'operazione potrebbe richiedere del tempo, ti preghiamo di attendere.",
  },

  datasets: {
    actionsFlags: {
      "\\\\Answered": "Risposto",
      "\\\\Deleted": "Cancellato",
      "\\\\Draft": "Bozza",
      "\\\\Flagged": "Contrassegnato",
      "\\\\Seen": "Letto",
    },
    antispamFilterTypes: {
      whitelist_from: "Consenti da",
      whitelist_to: "Consenti verso",
    },
    calendarMinutesInterval: {
      15: "15 minuti",
      30: "30 minuti",
      60: "60 minuti",
    },
    calendarNewEventFreeBusy: {
      busy: "Occupato",
      free: "Disponibile",
      outofoffice: "Fuori sede",
      temporary: "Provvisorio",
    },
    calendarNewEventPartecipation: {
      ACCEPTED: "Accetta",
      DECLINED: "Rifiuta",
      TENTATIVE: "Forse",
    },
    calendarNewEventParticipationRoles: {
      CHAIR: "Presidente",
      "REQ-PARTICIPANT": "Obbligatorio",
      "OPT-PARTICIPANT": "Non obbligatorio",
      "NON-PARTICIPANT": "Per conoscenza",
    },
    calendarNewEventPriority: {
      0: "Nessuna",
      1: "Alta",
      5: "Media",
      9: "Bassa",
    },
    calendarNewEventTypes: {
      public: "Pubblico",
      confidential: "Confidenziale",
      private: "Privato",
    },
    calendarStartWeekDay: {
      saturday: "Sabato",
      sunday: "Domenica",
      monday: "Lunedi",
    },
    calendarView: {
      year: "Anno",
      month: "Mese",
      week: "Settimana",
      workWeek: "Settimana lavorativa",
      day: "Giorno",
      listmonth: "Lista",
    },
    calendarEventFilterBy: {allEvents: "Tutti", nextEvents: "Tutti i prossimi eventi"},
    calendarEventSearchIn: {title: "Titolo/etichette/luogo", all: "Contenuto intero"},
    cancelSendTimer: {
      0: "Disattivato",
      5000: "5 secondi",
      10000: "10 secondi",
      20000: "20 secondi",
      30000: "30 secondi",
    },
    contactNameFormat: {
      firstName: "Nome, Cognome",
      lastName: "Cognome, Nome",
    },
    contactsOrder: {
      firstName: "Nome",
      lastName: "Cognome",
    },
    countries: {
      AD: "Andorra",
      AE: "Emirati Arabi",
      AG: "Antigua & Barbuda",
      AI: "Anguilla",
      AL: "Albania",
      AM: "Armenia",
      AO: "Angola",
      AR: "Argentina",
      AS: "Samoa Americana",
      AT: "Austria",
      AU: "Australia",
      AW: "Aruba",
      AX: "Isole Åland",
      AZ: "Azerbaijan",
      BA: "Bosnia Herzegovina",
      BB: "Barbados",
      BD: "Bangladesh",
      BE: "Belgio",
      BF: "Burkina Faso",
      BG: "Bulgaria",
      BH: "Bahrain",
      BI: "Burundi",
      BJ: "Bénin",
      BL: "Saint Barthélemy",
      BM: "Bermuda",
      BN: "Brunei",
      BO: "Bolivia",
      BQ: "Bonaire, Sint Eustatius e Saba",
      BR: "Brasile",
      BS: "Bahamas",
      BW: "Botswana",
      BY: "Bielorussia",
      BZ: "Belize",
      CA: "Canada",
      CC: "Isole Cocos (Keeling)",
      CD: "Repubblica Democratica del Congo",
      CF: "Repubblica Centro Africana",
      CG: "Repubblica del Congo",
      CH: "Svizzera",
      CL: "Cile",
      CM: "Cameroun",
      CN: "Cina",
      CO: "Colombia",
      CR: "Costa Rica",
      CU: "Cuba",
      CV: "Capo Verde",
      CW: "Curaçao",
      CX: "Isola di Natale",
      CY: "Cipro",
      CZ: "Repubblica Ceca",
      DE: "Germania",
      DK: "Danimarca",
      DM: "Dominica",
      DO: "Repubblica Dominicana",
      EC: "Ecuador",
      EE: "Estonia",
      ES: "Spagna",
      ET: "Etiopia",
      FI: "Finlandia",
      FO: "Isole Faroe",
      FR: "Francia",
      GA: "Gabon",
      GB: "Inghilterra",
      GD: "Grenada",
      GF: "Guiana Francese",
      GG: "Guernsey",
      GI: "Gibilterra",
      GL: "Groenlandia",
      GP: "Guadeloupe",
      GQ: "Guinea Equatoriale",
      GR: "Grecia",
      GT: "Guatemala",
      GU: "Guam",
      GY: "Guyana",
      HN: "Honduras",
      HR: "Croazia",
      HT: "Haiti",
      HU: "Ungheria",
      IE: "Irlanda",
      IM: "Isola di Man",
      IS: "Islanda",
      IT: "Italia",
      JE: "Jersey",
      JM: "Jamaica",
      JP: "Giappone",
      KE: "Kenya",
      KR: "Korea del Sud",
      LI: "Lichtenstein",
      LS: "Lesotho",
      LT: "Lituania",
      LU: "Lussemburgo",
      LV: "Lettonia",
      MC: "Monaco",
      MD: "Moldavia",
      ME: "Montenegro",
      MG: "Madagascar",
      MK: "Macedonia del nord",
      MQ: "Martinica",
      MT: "Malta",
      MW: "Malawi",
      MX: "Messico",
      MZ: "Mozambico",
      NA: "Namibia",
      NI: "Nicaragua",
      NL: "Olanda",
      NO: "Norvegia",
      NZ: "Nuova Zelanda",
      PA: "Panama",
      PE: "Perú",
      PH: "Filippine",
      PL: "Polonia",
      PT: "Portogallo",
      PY: "Paraguay",
      RE: "Réunion",
      RO: "Romania",
      RS: "Serbia",
      RU: "Russia",
      RW: "Rwanda",
      SE: "Svezia",
      SG: "Singapore",
      SH: "Saint Helena",
      SI: "Slovenia",
      SJ: "Svalbard & Jan Mayen",
      SK: "Slovenia",
      SM: "San Marino",
      SO: "Somalia",
      SS: "Sudan del sud",
      SV: "El Salvador",
      TG: "Togo",
      TO: "Tonga",
      TR: "Turchia",
      TZ: "Tanzania",
      UA: "Ucraina",
      UG: "Uganda",
      US: "Stati Uniti",
      UY: "Uruguay",
      VA: "Città del Vaticano",
      VE: "Venezuela",
      VN: "Vietnam",
      XK: "Kosovo",
      YT: "Mayotte",
      ZA: "Sud Africa",
      ZM: "Zambia",
      ZW: "Zimbabwe",
    },
    deliveryNotifications: {
      always: "Chiedi sempre conferma di consegna",
      never: "Non chiedere mai conferma di consegna",
    },
    markReadAfter: {
      manually: "Manualmente",
      onOpen: "All'apertura",
      5000: "Dopo 5 secondi",
      10000: "Dopo 10 secondi",
      30000: "Dopo 30 secondi",
    },
    eventAlarmPostponeTime: {
      60: "1 minuto",
      300: "5 minuti",
      900: "15 minuti",
      1800: "30 minuti",
      3600: "1 ora",
      7200: "2 ore",
      86400: "1 giorno",
      604800: "1 settimana",
    },

    eventTimeIntervals: {
      5: "5 minuti",
      10: "10 minuti",
      15: "15 minuti",
      20: "20 minuti",
      30: "30 minuti",
    },

    calendarTaskStatus: {
      "NEEDS-ACTION": "Richiede un'azione",
      COMPLETED: "Completato il",
      PROCESS: "In esecuzione",
      CANCELLED: "Cancellato",
    },

    feedbackAreas: {
      addressbookSidebar: "Lista rubriche",
      contactList: "Lista contatti",
      contactView: "Visualizzazione contatto",
      mailSearch: "Ricerca messaggi mail",
      mailSidebar: "Lista cartelle mail",
      messageList: "Lista messaggi",
      messageView: "Visualizzazione messaggio",
      newMessage: "Composizione nuovo messaggio",
      other: "Altro...",
      settings: "Impostazioni",
    },
    filterMail: {
      all: "Tutti",
      byDate: "Data",
      byFrom: "Da",
      bySize: "Dimensione",
      bySubject: "Oggetto",
      flagged: "Contrassegnati",
      filter: "Filtri",
      orderBy: "Ordina",
      seen: "Letti",
      unseen: "Non letti",
    },
    filtersActions: {
      discard: "Cancella",
      fileinto: "Sposta messaggio in",
      fileinto_copy: "Copia messaggio in",
      keep: "Conserva messaggio",
      redirect: "Reindirizza messaggio in",
      redirect_copy: "Invia una copia a",
      reject: "Respingi con il seguente messaggio",
      addflag: "Contrassegna messaggio come",
      setkeyword: "Applica etichetta",
      stop: "Smetti di processare i filtri",
    },
    filtersDateOperators: {
      gt: "dopo",
      is: "è uguale a",
      lt: "prima",
      notis: "non è uguale a",
    },
    filtersEnvelopeSubtypes: {From: "Da", To: "A"},
    filtersDateSubTypes: {date: "Data", time: "Ora", weekday: "Giorno della settimana"},
    filtersDateWeekdays: {
      monday: "Lunedì",
      tuesday: "Martedì",
      wednesday: "Mercoledì",
      thursday: "Giovedì",
      friday: "Venerdì",
      saturday: "Sabato",
      sunday: "Domenica",
    },
    filtersRules: {
      Bcc: "Ccn",
      body: "Corpo",
      Cc: "Cc",
      currentdate: "Data di arrivo",
      envelope: "Messaggio",
      From: "Mittente",
      other: "Altra intestazione",
      size: "Dimensione",
      Subject: "Oggetto",
      To: "Destinatario",
    },
    filtersSizeMUnits: {B: "Bytes", K: "Kilobytes", M: "Megabytes"},
    filtersSizeOperators: {over: "è maggiore di", under: "è minore di"},
    filtersStringOperators: {
      contains: "contiene",
      exists: "esiste",
      is: "è uguale a",
      notcontains: "non contiene",
      notexists: "non esiste",
      notis: "non è uguale a",
    },
    fontSize: {
      extraSmall: "Molto piccolo",
      huge: "Enorme",
      large: "Grande",
      medium: "Medio",
      normal: "Normale",
      small: "Piccolo",
    },
    languages: {
      de: "Tedesco",
      en: "Inglese",
      fr: "Francese",
      gr: "Greco",
      it: "Italiano",
      nl: "Olandese",
      sv: "Svedese",
      es: "Spagnolo",
      pt: "Portoghese",
    },
    mailRetention: {
      0: "Mai",
      30: "più vecchi di 1 mese",
      90: "più vecchi di 3 mesi",
      180: "più vecchi di 6 mesi",
      365: "più vecchi di 1 anno",
      730: "più vecchi di 2 anni",
      1095: "più vecchi di 3 anni",
      1460: "più vecchi di 4 anni",
      1825: "più vecchi di 5 anni",
    },
    matchTypes: {
      allof: "Soddisfa tutti i parametri",
      anyof: "Soddisfa uno qualunque dei parametri",
    },
    newAllDayEventAlert: {
      never: "Mai",
      eventDate: "Giorno dell'evento",
      "-PT17H": "Il giorno prima, alle ore 9",
      "-P6DT17H": "Una settimana prima, alle ore 9",
    },
    newEventAlert: {
      never: "Mai",
      eventHour: "Ora evento",
      "-PT5M": "5 minuti prima",
      "-PT10M": "10 minuti prima",
      "-PT15M": "15 minuti prima",
      "-PT30M": "30 minuti prima",
      "-PT1H": "1 ora prima",
      "-PT2H": "2 ore prima",
      "-PT12H": "12 ore prima",
      "-P1D": "1 giorno prima",
      "-P7D": "1 settimana prima",
    },
    newEventRepeatDayWeek: {
      MO: "Lunedì",
      TU: "Martedì",
      WE: "Mercoledì",
      TH: "Giovedì",
      FR: "Venerdì",
      SA: "Sabato",
      SU: "Domenica",
    },
    newEventRepeatFrequency: {
      NEVER: "Mai",
      DAILY: "Ogni giorno",
      WEEKLY: "Ogni settimana",
      MONTHLY: "Ogni mese",
      YEARLY: "Ogni anno",
    },
    newEventRepeatMonths: {
      1: "Gennaio",
      2: "Febbraio",
      3: "Marzo",
      4: "Aprile",
      5: "Maggio",
      6: "Giugno",
      7: "Luglio",
      8: "Agosto",
      9: "Settembre",
      10: "Ottobre",
      11: "Novembre",
      12: "Dicembre",
    },
    orderSelector: {
      byLastname: "Cognome",
      byMail: "Email",
      byName: "Nome",
      byOrg: "Azienda",
      orderBy: "Ordina",
      showOnlyLists: "Visualizza solo liste",
    },
    readConfirmations: {
      always: "Chiedi sempre conferma di lettura",
      never: "Non chiedere mai conferma di lettura",
    },
    readingConfirmation: {
      always: "Sempre",
      ask: "Chiedi sempre",
      never: "Mai",
    },
    selectMail: {
      all: "Tutto",
      cancel: "Annulla",
      modify: "Modifica",
      none: "Deseleziona",
      select: "Seleziona",
    },
    shareOptionsCalendar: {
      None: "Nessuno",
      DAndTViewer: "Vedi data e ora",
      Viewer: "Vedi tutto",
      Responder: "Rispondi a",
      Modifier: "Modifica",
    },
    showImages: {
      always: "Sempre",
      contacts: "Contatti e fidati",
      never: "Mai",
    },
    themes: {
      dark: "Dark",
      light: "Light",
    },
    timeFormats: {
      "12h": "12h",
      "24h": "24h",
    },
    viewMode: {
      label: {
        viewColumns: "Colonne",
        viewHalf: "Anteprima",
        viewFull: "Lista",
      },
      desc: {
        viewColumns: "Layout a tre colonne con il riquadro di lettura sulla destra dello schermo",
        viewHalf:
          "Layout a due colonne con riquadro di lettura nella parte inferiore dello schermo",
        viewFull:
          "Layout a due colonne con solo la lista dei messaggi. Il riquadro di lettura verrà mostrato a pagina intera al click.",
      },
    },
  },

  dropdownMenu: {
    activesync: "Microsoft® ActiveSync",
    delete: "Elimina",
    download: "Download",
    edit: "Modifica",
    exportContacts: "Esporta contatti",
    feedback: "Feedback",
    importContacts: "Importa contatti",
    importEvents: "Importa eventi",
    news: "Novità e aggiornamenti",
    remove: "Rimuovi",
    rename: "Rinomina",
    share: "Condividi",
    shortcuts: "Scorciatoie da tastiera",
    syncNo: "Non sincronizzare",
    syncYes: "Sincronizza",
    unsubscribe: "Rim. sottoscrizione",
  },

  dropdownUser: {
    feedback: "Feedback",
    logout: "Esci",
    settings: "Impostazioni",
  },

  errors: {
    emailDomainAlreadyPresent: "Indirizzo email o dominio già presente",
    emptyField: "Campo non compilato",
    invalidEmail: "Email non valida",
    invalidEmailDomain: "Indirizzo email o dominio non valido",
    invalidPassword: "Password non valida",
    invalidPasswordFormat: "Formato non valido, inserire almeno 8 caratteri alfanumerici",
    invalidValue: "Valore non valido",
    mandatory: "Campo obbligatorio",
    notAllowedCharacter: "Carattere non consentito",
    notChanged: "Campo non modificato",
    permissionDenied: "Permesso negato",
    tooLong: "Campo troppo lungo",
  },

  feedback: {
    disclaimer:
      "Inviaci un feedback e aiutaci a migliorare il servizio.<br/>Se hai domande o problemi, relativi all'utilizzo della webmail, contatta l'assistenza.",
    labels: {
      feedbackAreas: "Su quale area vuoi lasciare un feedback?",
      note: "Lascia un messaggio (opzionale)",
    },
    msgError: {
      title: "Non è stato possibile inviare il tuo feedback",
      desc: "Per favore riprova più tardi, per noi è importante sapere cosa pensi della nostra webmail. Il tuo feedback ci aiuterà a creare un'esperienza migliore per te e per tutti i nostri utenti.",
    },
    msgSuccess: {
      title: "Grazie per il tuo feedback!",
      desc: "Apprezziamo molto il tempo che hai impiegato per aiutarci a migliorare la nostra webmail. Il tuo feedback ci aiuterà a creare un'esperienza migliore per te e per tutti i nostri utenti.",
    },
    privacy:
      "I dati raccolti verranno trattati nel rispetto della normativa vigente sulla Privacy.",
    title: "Feedback",
  },

  inputs: {
    labels: {
      addAddress: "Aggiungi indirizzo",
      addContactToAddressbook: "Aggiungi contatto alla rubrica",
      addDomain: "Aggiungi indirizzo o dominio",
      addLabel: "Nome etichetta",
      addMembers: "Aggiungi membri",
      addParticipant: "Aggiungi partecipante",
      addressbookName: "Nome rubrica",
      addUser: "Aggiungi utente",
      alert2: "Secondo avviso",
      alert: "Avviso",
      assignTask: "Assegna l'attività a",
      at: "in",
      calendar: "Calendario",
      calendarBusinessDayEndHour: "Fine giornata lavorativa",
      calendarBusinessDayStartHour: "Inizio giornata lavorativa",
      calendarColor: "Colore calendario",
      calendarMinutesInterval: "Divisione oraria",
      calendarName: "Nome calendario",
      calendarView: "Visualizzazione di default",
      company: "Società",
      companyName: "Nome",
      confidentialEvents: "Eventi confidenziali",
      confirmNewPassword: "Conferma password",
      contactNameFormat: "Visualizza per",
      contactsOrder: "Ordina contatti per",
      contains: "Contiene",
      country: "Nazione",
      dateFormat: "Formato data",
      dateInterval: "Filtra per data",
      defaultAddressbook: "Rubrica default",
      defaultCalendar: "Calendario default",
      displayName: "Nome visual.",
      email: "Email",
      encryptionMethod: "Metodo di crittografia",
      endDate: "Data fine",
      event: "Evento",
      eventDailyRepetition: "Ogni;giorno/i",
      eventDailyWorkdayRepetition: "Ogni giorno feriale",
      eventMonthlyLastDayRepetition: "Ultimo giorno del mese, ogni;mese/i",
      eventMonthlyLastWeekDayRepetition: "Ultimo/a {{WeekDay}}, ogni;mese/i",
      eventMonthlyRepetition: "Il giorno {{DayNumber}}, ogni;mese/i",
      eventMonthlyWeekDayRepetition: "{{WeekDayNumber}}, ogni;mese/i",
      eventPartecipation: "Stato partecipazione",
      eventPriority: "Priorità evento",
      eventType: "Tipo evento",
      eventWeeklyRepetition: "Ogni;settimana/e, il giorno:",
      eventYearlyLastDayRepetition: "Ultimo giorno di {{Month}}, ogni;anno/i",
      eventYearlyLastWeekDayRepetition: "Ultimo/a {{WeekDay}} di {{Month}}, ogni;anno/i",
      eventYearlyRepetition: "Il giorno {{DayNumber}} di {{Month}}, ogni;anno/i",
      eventYearlyWeekDayRepetition: "{{WeekDayNumber}} di {{Month}}, ogni;anno/i",
      exportAsLdiff: "Esporta in formato LDIF",
      exportAsVcard: "Esporta in formato VCard",
      faxHome: "Fax casa",
      faxWork: "Fax lavoro",
      filter: "Filtra",
      filterName: "Nome regola",
      firstName: "Nome",
      folderName: "Nome cartella",
      freeBusy: "Mostra come",
      from: "Da",
      fromDate: "Dal giorno",
      home: "Casa",
      hour: "Ora",
      includeFreeBusy: "Includi nel Free/Busy",
      label: "Etichetta",
      labelColor: "Colore etichetta",
      language: "Lingua",
      lastName: "Cognome",
      linkText: "Testo visualizzato",
      linkURL: "Indirizzo web (URL)",
      listName: "Nome lista",
      location: "Luogo",
      loginAddressbook: "Rubrica iniziale",
      mailAccount: "Account",
      mailRetention: "Cancellazione messaggi della cartella",
      mailRetentionDefault: "La cancellazione automatica è preimpostata a 30 giorni",
      mailRetentionDiscalimer:
        "Attenzione, i messaggi verranno cancellati automaticamente in modo definitivo senza possibilità di recupero. La cancellazione sarà operativa entro 24 ore.",
      mailRetentionHint:
        "Specifica l'intervallo di tempo, successivo alla ricezione del messaggio, per procedere con la sua cancellazione automatica.",
      markReadAfter: "Marca messaggio come letto",
      mobile: "Cellulare",
      newAddressBook: "Nuova rubrica",
      newAddressBookMobile: "Nuova rubrica",
      newAllDayEventAlert: "Alert nuovi eventi intera giornata",
      newBcc: "Aggiungi destinatari in Ccn",
      newCalendar: "Nuovo calendario",
      newEventAlert: "Alert nuovi eventi",
      newForward: "Aggiungi destinatario alla lista",
      newPassword: "Nuova password",
      nickname: "Nickname",
      object: "Oggetto",
      oldPassword: "Password attuale",
      parentFolder: "Percorso",
      password: "Password",
      personalMeetingRoom: "Link alla stanza meeting personale",
      phone: "Telefono",
      port: "Porta",
      portFor: "Porta per",
      priority: "Priorità",
      privateEvents: "Eventi privati",
      publicEvents: "Eventi pubblici",
      readingConfirmation: "Invia conferma di lettura",
      recoveryEmail: "Email di recupero",
      renameAddressbook: "Rinomina rubrica",
      repeatEvery: "Ripeti",
      reportBugNote: "Descrizione problema",
      reportBugPhoneNumber: "Numero di telefono",
      searchAddressbookToSubscribe: "Cerca un utente per vedere le sue rubriche condivise",
      searchCalendarToSubscribe: "Cerca un utente per vedere i suoi calendari condivisi",
      searchIn: "Cerca in",
      selectCalendar: "Seleziona calendario",
      selectIdentity: "Seleziona identità",
      selectList: "Seleziona lista",
      selectSnapshotDate: "Seleziona data",
      serverName: "Nome server",
      shareCalendarCalDAVURL: "CalDAV URL",
      shareCalendarWebDavICSURL: "WebDAV ICS URL",
      shareCalendarWebDavXMLURL: "WebDAV XML URL",
      shareToAddressbook: "Con chi vuoi condividere la rubrica?",
      shareToCalendar: "Con chi vuoi condividere il calendario?",
      shareToFolder: "Con chi vuoi condividere la cartella?",
      showImages: "Mostra immagini",
      signatureName: "Nome visualizzato",
      signatureText: "Testo firma",
      startDate: "Data inizio",
      team: "Team",
      templateName: "Nome",
      templateSubject: "Oggetto",
      templateText: "Testo messaggio",
      theme: "Tema",
      timeFormat: "Formato ora",
      timezone: "Time zone",
      title: "Titolo",
      to: "A",
      untilDate: "Al giorno",
      username: "Username",
      weekStart: "Inizio settimana",
      work: "Lavoro",
    },
    placeholder: {
      addressbookName: "Nome rubrica",
      birthday: "Compleanno",
      city: "Città",
      company: "Società",
      country: "Paese",
      customText: "Inserisci un testo personalizzato",
      email: "Email",
      endDate: "Data fine",
      firstName: "Nome",
      lastName: "Cognome",
      members: "Membri",
      newFolderName: "Nuovo nome cartella",
      newNameAddressbook: "Nuovo nome rubrica",
      newPassword: "Almeno 8 caratteri alfanumerici",
      note: "Note",
      password: "La tua password",
      phone: "Telefono",
      place: "Inserisci una via o un luogo",
      postCode: "CAP",
      region: "Provincia",
      role: "Ruolo",
      search: "Cerca",
      searchActivity: "Cerca attività",
      searchEvent: "Cerca evento",
      searchUser: "Cerca utente nel tuo dominio",
      select: "Seleziona",
      snooze: "Posponi avviso",
      startDate: "Data inizio",
      street: "Via",
    },
    hint: {
      cancelSendMessage:
        "Seleziona il tempo disponibile per annullare l'invio di un messaggio, se decidi di non voler inviare l'email.",
      newForward: "È possibile aggiungere fino a un massimo di {{max}} indirizzi di inoltro.",
      newBcc: "È possibile aggiungere fino a {{max}} destinatari in Ccn.",
      mailRetention:
        "Specifica l'intervallo di tempo, successivo alla ricezione del messaggio, per procedere con la sua cancellazione automatica.",
      passwordScore: {
        check: "Robustezza password",
        poor: "Password molto debole",
        easy: "Password troppo facile",
        weak: "Password troppo semplice",
        strong: "Password robusta",
        great: "Password ottima!",
      },
    },
  },

  labels: {
    attendees: "Partecipanti",
    calendarAdvancedSearch: "Dove vuoi cercare?",
    clearAdvancedFilters: "Pulisci filtri",
    clearFields: "Pulisci campi",
    default: "Predefinito",
    forDomain: "Per dominio",
    forward: "Fwd",
    holidayCalendar: "Festività",
    organizer: "Organizzatore",
    otherFilters: "Altri filtri",
    searchResults: "Risultati ricerca",
    withAllUsers: "Con tutti gli utenti",
  },

  loaderFullscreen: {
    description: "I contenuti stanno arrivando, per favore attendi!",
    descriptionEvents: "I tuoi eventi stanno arrivando, per favore attendi!",
    descriptionFolder: "Le tue cartelle stanno arrivando, per favore attendi!",
    title: "Caricamento in corso",
    titleEvent: "Caricamento evento",
  },

  mail: {
    confirmMailLabel: "OK, confermo!",
    contextualMenuLabels: {
      addAddressBook: "Aggiungi a rubrica",
      addEvent: "Crea evento",
      alarm: "Alarm",
      archive: "Archivia",
      archiveThread: "Archivia conversazione",
      backTo: "Indietro",
      cancel: "Annulla",
      close: "Chiudi",
      confirm: "Conferma",
      copyIn: "Copia in",
      copyThreadIn: "Copia conversazione",
      delete: "Elimina",
      deletePerm: "Elimina definitivamente",
      deleteThread: "Elimina conversazione",
      deleteXMessages: "Elimina {{MessagesNumber}} messaggi",
      deliveryNotification: "Conferma di consegna",
      download: "Download",
      editAsNew: "Modifica come nuovo",
      emptySpam: "Marca Spam come letto",
      emptyTrash: "Svuota cestino",
      forward: "Inoltra",
      import: "Importa messaggio",
      label: "Etichetta",
      labelsManagement: "Gestione etichette",
      labelThread: "Etichetta conversazione",
      markAllAsRead: "Marca tutti come letti",
      markAs: "Marca come",
      markThreadAs: "Marca conversazione",
      manageFolders: "Gestisci cartelle",
      modify: "Modifica",
      more: "Altro",
      moveThreadTo: "Sposta conversazione",
      moveTo: "Sposta in",
      newSubFolder: "Crea sottocartella",
      plainText: "Modalità testo semplice",
      print: "Stampa",
      priorityHigh: "Priorità alta",
      readed: "Letto",
      readedNot: "Non letto",
      readingNotification: "Conferma di lettura",
      rename: "Rinomina",
      reply: "Rispondi",
      replyToAll: "Rispondi a tutti",
      restore: "Ripristina",
      restoreThreadIn: "Ripristina conversazione",
      restoreIn: "Ripristina in",
      sendAsAttachment: "Inoltra come allegato",
      showSourceCode: "Mostra sorgente",
      spam: "Spam",
      spamNot: "No Spam",
      starred: "Contrassegna",
      starredNot: "Rimuovi contrassegno",
      thanks: "Ringrazia",
      thread: "Azioni conversazione",
    },
    deleteMailDsc:
      "Se non è attivo un sistema di archiviazione, il messaggio verrà eliminato definitivamente.<br/><b>L'operazione non è reversibile</b>.",
    deleteMailTitle: "Elimina messaggio",
    deleteMailsDsc:
      "Se non è attivo un sistema di archiviazione, i messaggi verranno eliminati definitivamente.<br/><b>L'operazione non è reversibile<b>.",
    deleteMailsTitle: "Elimina messaggi selezionati",
    dropFiles: "Rilascia qui i file da allegare",
    emptyTrashDsc:
      "Se non è attivo un sistema di archiviazione, svuotando il cestino tutti i messaggi saranno eliminati in maniera <b>irreversibile</b>.<br/>Dopo <b>30 giorni</b> i messaggi vengono eliminati automaticamente.",
    emptyTrashTitle: "Svuota cestino",
    goToOldWebmailModal: {
      description:
        "<br/>Ti invitiamo ad utilizzare da subito la nuova Webmail, la quale offre funzionalità aggiuntive come:<br/><ul><li>Gestione automatica delle identità</li><li>Rubrica e calendario condivisi</li><li>Integrazione con Zoom per video meeting</li><li>Modelli email</li><li>Ricerca in tutte le cartelle</li><li>e molto altro</li></ul>",
      title: "La vecchia Webmail non sarà più accessibile dal 31 Ottobre",
    },
    import: {
      messagesInvalid: "Non validi:",
      messagesNr: "Totale messaggi da importare:",
      messagesValid: "Validi:",
      desc: "Stai importando dei messaggi nella cartella: <code>{{folderImport}}</code><br/>È possibile importare messaggi email da altre app di posta utilizzando un file in formato eml (<strong>.eml</strong>).",
      dropFiles: "Carica o rilascia qui il file da importare",
      error: "Non è stato possibile importare i messaggi",
      importing:
        "Stiamo importando <b>{{messagesNumber}}</b> messaggi nella cartella: <code>{{folderImport}}</code>",
      loading: "Caricamento...",
      success: "Importazione avvenuta con successo!",
      title: "Importa messaggi",
      uploadedFile: "Caricato",
      uploadingFile: "Caricamento",
    },
    loading: {
      desc: "I tuoi messaggi stanno arrivando, per favore aspetta.",
      title: "Caricamento",
    },
    markSpamReadDsc:
      "Marca tutti i messaggi presenti nella cartella come letti.<br/>Dopo <b>30 giorni</b> i messaggi vengono eliminati automaticamente.",
    markSpamReadTitle: "Marca messaggi come letti",
    maxLabelsNumberTitle: "Troppe etichette!",
    maxLabelsNumberDsc:
      "È stato raggiunto il numero massimo di etichette associabili a un messaggio. Per aggiungere una nuova etichetta devi prima rimuoevere una di quelle già presenti.",
    message: {
      add: "Aggiungi",
      addToAddressBook: "Aggiungi contatto a rubrica",
      attachedMessage: "Messaggio allegato",
      attachments: "allegati",
      bugMsg: "Non visualizzi il messaggio?",
      cc: "Cc:",
      date: "Data:",
      draftsSelectedInfo: "Scegli un messaggio dalla lista e continua a scrivere.",
      downloadAll: "Scarica tutti",
      downloadAttachments: "Scarica allegati",
      editPartecipationStatusDecription: "",
      editPartecipationStatusTitle: "Modifica partecipazione",
      eventActionAccept: "Accetta",
      eventActionDecline: "Declina",
      eventActionTentative: "Forse",
      eventAddToCalendar: "Evento non presente nel calendario",
      eventAttendees: "Partecipanti",
      eventAttendeeStatusAccepted: "Evento accettato",
      eventAttendeeStatusDeclined: "Evento rifiutato",
      eventAttendeeStatusTentative: "Tentativo di partecipazione",
      eventCounterProposal: "Questo messaggio contiene una richiesta di modifica",
      eventDeleted: "Evento eliminato",
      eventInvitation: "Invito all'evento:",
      eventLocationEmpty: "Non specificato",
      eventModify: "Modifica",
      eventNeedAction: "Conferma partecipazione a questo evento",
      eventNotNeedAction: "Evento già gestito",
      eventOutDated: "L'evento è stato modificato",
      eventStatusAccepted: "Accettato",
      eventStatusDeclined: "Rifiutato",
      eventStatusTentative: "Tentativo",
      eventUpdate: "Aggiorna evento",
      external: "Esterno",
      externalLabel: "Questo indirizzo email è esterno alla tua organizzazione.",
      folderSelectedInfo: "Scegli un messaggio dalla lista e scopri il suo contenuto.",
      from: "Da:",
      hideAllAttachments: "Nascondi",
      hugeMessage:
        "Contenuto troppo grande per essere visualizzato interamente, fai clic sul link in basso per visualizzare il codice sorgente del messaggio.",
      hugeMessageNotice: "Messaggio troncato",
      inboxSelectedInfo: "Scegli un messaggio dalla lista e scopri chi ti ha scritto.",
      isMailingList: "Questo messaggio fa parte di una mailing list.",
      localAttachments: "Sono presenti altri allegati dentro l'evento",
      message: "messaggio",
      messageForwarded: "Messaggio inoltrato",
      messages: "messaggi",
      messagesQuota: "Numero messaggi:",
      newMessageinThread: "C'è un nuovo messaggio",
      noContent: "Questo messaggio è privo di contenuto.",
      notSelected: "Seleziona un messaggio",
      oneSelectMessages: "Messaggio selezionato",
      oneSelectThreads: "Conversazione selezionata",
      readNotificationLabel: "{{Sender}} ha richiesto conferma di lettura del messaggio.",
      readNotificationLabelSimple: "Richista conferma di lettura messaggio.",
      readNotificationResponse:
        "<P>Il messaggio<BR><BR>&nbsp;&nbsp;&nbsp; A:&nbsp; %TO%<BR>&nbsp;&nbsp;&nbsp; Oggetto:&nbsp; %SUBJECT%<BR>&nbsp;&nbsp;&nbsp; Inviato:&nbsp; %SENDDATE%<BR><BR>&egrave; stato letto il giorno %READDATE%.</P>",
      readNotificationSubjectPrefix: "Letto:",
      replyTo: "Rispondi a:",
      sentSelectedInfo: "Scegli un messaggio dalla lista e vedi a chi hai scritto.",
      showAllAttachments: "Mostra altri",
      showMoreThread: "Mostra altro",
      selectMessages: "Messaggi selezionati",
      selectThreads: "Conversazioni selezionate",
      sender: "Mittente:",
      spamNotSelected: "Mantieni la cartella in ordine",
      spamSelectedInfo: "Verifica i messaggi e marca lo spam come letto.",
      subject: "Oggetto:",
      to: "A:",
      trashNotSelected: "Controlla il cestino",
      trashSelectedInfo: "Puoi recuperare i messaggi dal cestino entro 30 giorni.",
      updating: "Modifica in corso",
      unsubscribedMailingList: "Ti sei rimosso da questa mailing list.",
      yesterday: "Ieri",
      wrote: "ha scritto:",
    },
    messagesList: {
      allMessagesLoaded: "Tutti i messaggi sono stati caricati",
      ctaDeletedMessages: "Compatta cartella",
      ctaSpamInfo: "Segna tutti come letti",
      ctaTrashInfo: "Svuota cestino",
      deletedMessages:
        "Sono presenti messaggi in attesa di cancellazione, compatta la cartella per completare l'operazione.",
      folderEmpty: "Questa cartella è vuota",
      folderInfo: "Avvia una conversazione o sposta un messaggio.",
      foundMessages: "Trovati",
      foundMessagesNum: "Trovati: <b>{{found}}</b> di <b>{{total}}</b>",
      moveMessage: "Sposta messaggio",
      moveMessages: "Sposta {{NumMessages}} messaggi",
      notFound: "Nessun messaggio trovato",
      notFoundInfo: "La ricerca non ha prodotto risultati, riprova utilizzando criteri diversi.",
      pullDownToRefresh: "Trascina per aggiornare",
      releaseToRefresh: "Rilascia per aggiornare",
      searchInfo: "messaggi trovati",
      searchLimited:
        "Indicizzazione in corso. La ricerca è limitata alle <b>singole cartelle</b> e ai campi <b>da</b>, <b>a</b> e <b>oggetto</b> del messaggio.",
      searchNotAvailable: "Ricerca non disponibile",
      searchNotAvailableInfo:
        "Al momento la ricerca non è disponibile, si prega di riprovare piu tardi",
      selectMessages: "Selezionati",
      showMoreThread: "Mostra altro",
      spamEmpty: "Tutto lo spam è scappato via!",
      spamInfo: "I messaggi in spam vengono eliminati automaticamente dopo 30 giorni.",
      trashEmpty: "Il cestino è vuoto",
      trashInfo: "I messaggi nel cestino vengono eliminati automaticamente dopo 30 giorni.",
      totalMessages: "Messaggi",
      totalMessagesNum: "Messaggi: <b>{{total}}</b>",
    },
    mtm: {
      archivePromo:
        "<b>Ma non finisce qui...</b><br/><br/>Il servizio di archiviazione delle email ti mette a disposizione una casella email gemella, di sola lettura, dove vengono archiviati tutti i messaggi inviati e ricevuti dagli utenti, per 10 anni senza limiti di spazio.<br/>Richiedi maggiori informazioni al tuo referente del servizio email.",
      backupSelector: "Seleziona un backup per continuare",
      description:
        "Attraverso questo servizio è possibile accedere ai backup delle tua casella email eseguiti negli ultimi 15 giorni, così da verificare lo stato dei backup o eseguire il ripristino dei messaggi.",
      title: "Benvenuto in Mail Time Machine",
    },
    newMessage: {
      addAttach: "Aggiungi allegato",
      addHTMLTitle: "Inserisci HTML",
      addImgeDsc:
        "Puoi inserire le immagini direttamente in linea, nel corpo del messaggio o allegarle al messaggio.",
      addImgeTitle: "Inserisci immagini",
      addLinkTitle: "Inserisci link",
      editLinkTitle: "Modifica link",
      advanced: "Avanzate",
      attachInfo: {
        noAttach: "Non ci sono allegati",
        attachNumber: "Allegati:",
      },
      bcc: "Ccn",
      cc: "Cc",
      cancelSend: "Invio mail cancellato correttamente",
      delete: "Elimina",
      deleted: "Messaggio eliminato correttamente",
      deleteInProgress: "Cancellazione messaggio in corso",
      discardChanges: "Scarta modifiche",
      fontSize: {
        smaller: "Molto piccolo",
        small: "Piccolo",
        normal: "Normale",
        medium: "Medio",
        big: "Grande",
        bigger: "Molto grande",
      },
      from: "Da",
      hide: "Nascondi",
      invalidMails: "Non tutti gli indirizzi email sono validi, rimuovi quelli errati e riprova",
      moreAttachments: "Altri",
      noDraftChanged: "Nessuna modifica da salvare",
      object: "Oggetto",
      saveDraftDsc:
        "Il messaggio non è stato inviato e contiene modifiche non salvate. Puoi salvarlo come bozza e riprendere a scrivere più tardi.",
      saveDraftTitle: "Salvare messaggio come bozza?",
      savedDraft: "Bozza salvata!",
      savingDraft: "Salvataggio in corso",
      sendInProgress: "Invio messaggio in corso",
      sent: "Messaggio inviato correttamente",
      sizeExceeded:
        "Allegati troppo grandi. La dimensione massima di invio è di {{messageMaxSize}} MB.",
      templateCreateModal: {
        description:
          "<br/>Crea il tuo primo modello email per facilitare la composizione di mail ricorrenti. Puoi scegliere un oggetto personalizzato ed aggiungere allegati da inviare automaticamente nel messaggio mail.",
        title: "Non hai ancora modelli email",
      },
      templateSubjectModal: {
        description:
          "Nel modello email selezionato è definito un oggetto personalizzato. Vuoi sostituire quello presente nella finestra di composizione o vuoi mantenerlo ?",
        title: "Oggetto già presente",
      },
      to: "A",
      toMore: "Altri",
      useTemplate: "Modelli",
      windowSubject: "Nuovo messaggio",
    },
    reportBug: {
      title: "Segnala messaggio",
      message: {
        issue:
          "Se non visualizzi correttamente il messaggio, puoi aiutarci a risolvere il problema e migliorare il servizio.<br/>Se hai domande o problemi relativi all'uso della webmail, contatta il tuo referente tecnico per ricevere assistenza.",
        issueFormatting:
          "Il contenuto del messaggio non viene visualizzato correttamente? Descrivi il problema, faremo tutto il possibile per risolverlo nei prossimi aggiornamenti.",
        issueBlank:
          "In caso di messaggi effettivamente privi di qualsiasi contenuto, questi vengono segnalati nell'interfaccia della webmail con un apposito avviso.<br/><br/>Se tale avviso non è presente potrebbe trattarsi di un problema di formattazione, ti invitiamo quindi a verificare la presenza dell'avviso ed eventualmente a segnalare il messaggio come <code>non correttamente formattato</code>.",
        issueAttach:
          "Il messaggio sembra essere privo di allegati? Probabilmente il mittente ha inviato il messaggio dimenticandosi di inserire gli allegati.<br/><br/><b>Chiedi al mittente di verificare e inviarti nuovamente gli allegati</b>.",
        issueOther:
          "Descrivi il problema, faremo tutto il possibile per risolverlo nei prossimi aggiornamenti.<br/>Se hai domande o problemi relativi all'uso della webmail, il tuo referente tecnico per ricevere assistenza.",
        disclaimer:
          "Inviando questo feedback, il tuo messaggio potrà essere analizzato dal nostro team di sviluppo per migliorare il servizio.<br/><br/><b>Le informazioni NON saranno condivise con terze parti ed i dati saranno trattati nel rispetto della normativa vigente sulla privacy</b>.",
      },
    },
    restoreRequest: {
      desc: "Stai richiedendo il ripristino della casella <b>{{username}}</b> con il backup datato <b>{{restore_date}}</b>.<br/> Con questa operazione andremo a ripristinare tutti i messaggi presenti nel backup indicato, senza eliminare nessun messaggio che nel frattempo è stato ricevuto o inviato dalla casella email.<br/><br/><b>L'operazione di ripristino è soggetta ad un costo.</b><br/><br/>Vuoi procedere con la richiesta? ",
      restoreRequested:
        "Abbiamo preso in carico la tua richiesta di ripristino. Verrai contattato non appena la procedura sarà stata completata",
      title: "Richiedi un ripristino",
      titleRestoreRequested: "Richiesta inviata",
      deniedTitle: "Richiesta rifiutata",
      restoreRequestDenied:
        "Questo account ha un'altra richiesta di ripristino in corso. Non è possibile richiedere più di una richiesta di ripristino per volta.",
    },
    searchMail: {
      attachments: "Allegati",
      cleanFilters: "Pulisci filtri",
      marked: "Contrassegnati",
      results: "Risultati ricerca",
      searchIn: "Cerca in",
      allFolders: "Tutte le cartelle",
      currentFolder: "Cartella corrente",
    },
    sidebar: {
      createLabel: {
        desc: "",
        title: "Crea etichetta",
      },
      createFolder: {
        desc: "",
        title: "Crea cartella",
      },
      modifyFolder: {
        desc: "",
        title: "Modifica cartella",
      },
      restoreFolder: {
        desc: "",
        title: "Ripristina cartella",
      },
      folder: "Cartella",
      folders: "Cartelle personali",
      labels: "Etichette",
      newFoderName: "Nuovo nome cartella",
      occupiedSpace: "Spazio usato",
      sharedFolders: "Cartelle condivise",
      unlimitedSpace: "Spazio illimitato",
    },
    thanksMailLabel: "OK, grazie!",
    tooManyCompositionsDsc:
      "Hai raggiunto il numero massimo di nuovi messaggi che puoi comporre contemporaneamente. Completa almeno un messaggio di quelli che stai scrivendo per avviare una nuova composizone.",
    tooManyCompositionsTitle: "Finisci di scrivere!",
    unsubscribeListDsc: "Interrompere la ricezione dei messaggi per questa mailing list?",
    unsubscribeListTitle: "Annulla iscrizione",
  },

  mailboxes: {
    archive: "Archivio",
    drafts: "Bozze",
    inbox: "Ricevuti",
    more: "Altro",
    sent: "Inviati",
    shared: "Cartelle condivise",
    spam: "Spam",
    trash: "Cestino",
  },

  navbar: {
    addressbook: "Rubrica",
    calendar: "Calendario",
    chat: "Chat",
    mail: "Mail",
    meeting: "Meeting",
    news: "Novità",
  },

  news: {
    notFound: "News non trovata",
    notFoundInfo: "La ricerca non ha prodotto risultati, riprova utilizzando criteri diversi.",
  },

  newsTags: {
    news: "Novità",
    suggestions: "Suggerimenti",
    fix: "Correzioni",
    comingSoon: "In arrivo",
    beta: "Beta",
  },

  pageLogout: {
    title: "Logout in corso",
    desc: "",
  },

  pageIndexing: {
    title: "Il tuo account è in fase di indicizzazione",
    desc: "L'operazione potrebbe richiedere del tempo, ti preghiamo di attendere.",
  },

  pageNotFound: {
    pageNotFound: "Qualcosa è andato storto",
    pageNotFoundInfo: "La pagina che stai cercando non è disponibile, non perdere la speranza!",
  },

  powered: "powered by Qboxmail",
  poweredCollaborationWith: "in collaborazione con ",

  radioButtons: {
    labels: {
      askDeliveryConfirmation: "Conferma di consegna messaggio",
      askReadConfirmation: "Conferma di lettura messaggio",
      defaultView: "Visualizzazione predefinita",
      newEventType: "Tipologia nuovi eventi",
      newEventFreeBusy: "Mostra disponibilità nuovi eventi",
      newEventTimeInterval: "Intervallo di tempo predefinito per il nuovo evento",
      other: "Altro",
      reportBugBlank: "Il messaggio appare vuoto",
      reportBugNoAttachments: "Il messaggio non ha allegati",
      reportBugNoFormatted: "Il contenuto non è formattato correttamente",
      selectIssue: "Qual è il tuo problema?",
    },
  },

  shareOptions: {
    delete: "Cancellazione",
    read: "Lettura",
    update: "Modifica",
    write: "Scrittura",
  },

  shareOptionsCalendar: {
    canCreateObjects: "Consenti inserimento eventi in questo calendario",
    canEraseObjects: "Consenti cancellazione eventi in questo calendario",
  },

  shortcuts: {
    addressbook: {
      newContact: "Nuovo contatto",
      editContact: "Modifica contatto",
      deleteContact: "Elimina contatto",
    },
    calendar: {
      newEvent: "Nuovo evento",
      editEvent: "Modifica evento",
      deleteEvent: "Elimina evento",
      moveRangeNext: "Visualizza intervallo successivo",
      moveRangePrevious: "Visualizza intervallo precedente",
    },
    general: {
      switchModuls: "Cambia moduli",
      refresh: "Ricarica pagina",
      tabForward: "Vai avanti tra gli elementi cliccabili",
      tabBack: "Torna indietro tra gli elementi cliccabili",
      closeModal: "Chiudi modali",
      openSettings: "Apri impostazioni",
      copy: "Copia elemeno selezionato",
      past: "Incolla elemeno selezionato",
      cut: "Taglia elemeno selezionato",
    },
    mail: {
      confirm: "Conferma",
      deleteMessage: "Elimina messaggio",
      deleteSelectMessage: "Elimina messaggi selezionati",
      editAsNew: "Modifica come nuovo",
      empityTrash: "Svuota cestino",
      expandThread: "Espandi thread",
      extendSelectDown: "Estendi selezione verso il basso nell'elenco dei messaggi",
      extendSelectUp: "Estendi la selezione nell'elenco dei messaggi",
      forward: "Inoltra",
      markRead: "Marca come letto/non letto",
      moveDown: "Muoviti in basso nell'elenco dei messaggi",
      moveUp: "Muoviti in alto nell'elenco dei messaggi",
      newMessage: "Nuovo messaggio",
      openSelectMessage: "Apri messaggio selezionato",
      printMessage: "Stampa messaggio",
      reduceThread: "Riduci thread",
      reply: "Rispondi",
      replyAll: "Rispondi a tutti",
      thanks: "Ringrazia",
    },
  },

  settings: {
    addressbook: {
      management: {
        automaticSave: {
          desc: "Scegliere se raccogliere tutti i contatti non presenti nelle rubriche in modo automatico.",
          title: "Salvataggio automatico",
        },
        personalAddressbooks: {
          desc: "Gestisci le tue rubriche personali e decidi se vuoi condividerle con altri utenti.",
          headerActiveSync: "Sync",
          headerItem: "Rubriche",
          placeholderList: " ",
          title: "Rubriche personali",
        },
        sharedAddressbooks: {
          desc: "Gestisci le rubriche condivise con te da altri utenti.",
          headerItem: "Rubriche sottoscritte",
          placeholderList: " ",
          title: "Rubriche condivise",
        },
        title: "Rubriche",
      },
      title: "Rubrica",
      view: {
        desc: "Gestisci le tue preferenze per la visualizzazione di contatti e rubriche.",
        title: "Visualizzazione contatti",
      },
    },
    calendar: {
      events: {
        title: "Eventi",
        desc: "Gestisci le tue preferenze per i nuovi eventi per tutti i calendari, se non è impostato un valore predefinito specifico.",
        alertTitle: "Alerts",
        alertDesc:
          "Gestisci le tue preferenze per gli avvisi per tutti i calendari, se non è impostato un valore predefinito specifico.",
        personalMeetingRoomTitle: "Stanza meeting personale",
        personalMeetingRoomDesc:
          "Genera una stanza sul tuo applicativo per le riunioni online e inserisci qui il link. Potrà poi essere selezionato come 'Luogo' nella creazione di un evento.",
      },
      invitations: {
        desc: "Scegliere se abilitare gli inviti agli eventi solo per specifici utenti.",
        title: "Inviti eventi",
        msgFromHeader: "Accetta inviti solo da",
        placeholderList: " ",
      },
      labels: {
        title: "Etichette calendario",
        titleSettingsPage: "Etichette calendario",
        desc: "Crea etichette colorate personalizzate per mantenere in ordine i tuoi eventi.",
        deleteLabelDsc: "Eliminando l'etichetta questa verrà rimossa da tutti gli eventi.",
      },
      management: {
        title: "Calendari",
        holidayCalendars: {
          title: "Calendari festività",
          desc: "Scegli i calendari delle festività che preferisci.",
          headerItem: "Calendari",
          placeholderList: " ",
        },
        personalCalendars: {
          title: "Calendari personali",
          desc: "Gestisci i tuoi calendari personali e decidi se vuoi condividerli con altri utenti.",
          headerActiveSync: "Sync",
          headerItem: "Calendari",
          placeholderList: " ",
        },
        sharedCalendars: {
          desc: "Gestisci i calendari condivisi con te da altri utenti.",
          headerActiveSync: "Sync",
          headerItem: "Calendari sottoscritti",
          placeholderList: " ",
          title: "Calendari condivisi",
        },
        includeInFreeBusy: "Includi in Free/Busy",
        showActivities: "Mostra attività",
        showAlarms: "Mostra allarmi",
        syncWithActivesync: "Sincronizza con Microsoft® Exchange ActiveSync",
        sendMeMailOnMyEdit: "Inviami una mail quando modifico il calendario",
        sendMeMailOnOtherEdit: "Inviami una mail quando qualcuno modifica il calendario",
        sendMailOnEditTo: "Quando modifico questo calendario invia una mail a",
      },
      view: {
        desc: "Gestisci le tue preferenze per la visualizzazione dei calendari.",
        showBusyOutsideWorkingHours: "Mostra come occupato fuori ore lavorative",
        showWeekNumbers: "Mostra numero settimane",
        title: "Visualizzazione calendari",
      },
      title: "Calendario",
    },
    chat: {
      title: "Chat",
      view: {
        title: "Visualizzazione",
      },
    },
    general: {
      integrations: {
        desc: "Gestisci le integrazioni con provider di servizi esterni alla webmail.",
        title: "Integrazioni",
        card: {
          zoom: {
            askSeller: "Chiedi ulteriori informazioni al tuo rivenditore",
            title: "Zoom",
            text: "Risparmia tempo durante la pianificazione delle riunioni aggiungendo i dettagli di una conferenza Zoom ad un evento.",
          },
        },
      },
      notifications: {
        title: "Notifiche",
        generalNotification: {
          desc: "Abilita le notifiche che segnalano la ricezione di un nuovo messaggio.",
          longDesc:
            "Consenti alla Webmail di mandare notifiche tramite il browser quando ricevi un nuovo messaggio. Questa impostazione non è sufficiente per ricevere le notifiche, è necessario anche abilitare le notifiche per ogni browser che intendi utilizzare.",
          title: "Impostazione generale delle notifiche",
        },
        allowedPush: {
          allowed:
            "Notifiche abilitate sul browser in uso. Per riceverle è necessario abilitarle anche nella sezione sopra.",
          default:
            "Se desideri che il browser attualmente in uso ti segnali con una notifica la ricezione di un nuovo messaggio devi abilitare le notifiche (nella sezione sopra) e poi abilitare le notifiche push nel tuo browser. Clicca sul pulsante e consenti l'invio di notifiche, oppure fai clic sull'icona a forma di lucchetto e consenti le notifiche premendo il pulsante Consenti.",
          isIos:
            "Se desideri ricevere le notifiche sul tuo dispositivo iOS (versione 16.4 e successive) è necessario aggiungere la Webmail alla schermata Home del tuo dispositivo. ",
        },
        browserNotification: {
          desc: "Verifica lo stato e gestisci le notifiche per il browser attualmente in uso.",
          title: "Stato notifiche del browser in uso",
        },
        granted: "Le notifiche del tuo browser sono configurate correttamente!",
        noPush: {
          title: "Sfortunatamente il browser Safari non supporta il sistema di notifiche.",
          titleios:
            "Sfortunatamente il sistema operativo iOS non supporta il sistema di notifiche da browser.",
          desc: "Per abilitare le notifiche usa la versione piu aggiornata di uno dei seguenti browsers",
        },
        deniedPush: {
          title: "Il tuo browser sta bloccando le notifiche push.",
          desc: "Rimuovi il blocco per attivare le notifiche push quando arriverà un nuovo messaggio.",
        },
        modal: {
          title: "Desideri consentire le notifiche push?",
          text: "Puoi sempre consentirle o bloccarle in qualsiasi momento dalle impostazioni della webmail.",
        },
      },
      parameters: {
        title: "Parametri",
        host: {
          title: "Configurazione dispositivi",
          desc: "Collega i tuoi dispositivi per ricevere e inviare email con il tuo account.",
        },
        imap: {
          title: "IMAP",
        },
        smtp: {
          title: "SMTP",
        },
      },
      profile: {
        email: "Email utente",
        generalSettings: {
          desc: "Gestisci le preferenze su lingua e ora.",
          title: "Impostazioni generali",
        },
        personalInfo: {
          desc: "Gestisci le informazioni del tuo profilo.",
          title: "Informazioni personali",
        },
        title: "Profilo",
      },
      security: {
        changepassword: {
          info: "Password di almeno 8 caratteri alfanumerici",
          desc: "Gestisci la password per accedere alla tua webmail.",
          resetpassword: "Imposta nuova password",
          resetpassworddisabled: "Il cambio password è disabilitato su questo account",
          resetpasswordexpired: "La tua password è scaduta, impostane una nuova",
          title: "Cambio password",
        },
        days: "giorno/i",
        passwordexpiration: {
          activeExpiration:
            "Per il tuo account email è attiva la scadenza automatica della password.",
          desc: "Verifica lo stato della password del tuo account.",
          expirationDate: "La password scade il",
          expirationCountdown: "La password scade tra",
          modalTitle: "La tua password sta per scadere",
          modalDesc:
            "Manca/no {{password_expiration_relative_days}} giorno/i alla scadenza della password del tuo account. Ti consigliamo di cambiarla subito.",
          title: "Scadenza password",
        },
        otp: {
          cantDisableOtp: "L'autenticazione a 2 fattori non è disattivabile su questo account",
          desc: "Gestisci l'autenticazione a due fattori per accedere alla tua webmail.",
          disableOtp: "Disattiva autenticazione a 2 fattori",
          downloadParams: "Scarica i dati di abilitazione",
          hideParams: "Nascondi parametri",
          instructionDisableOtp:
            "Inserisci il codice generato dall'applicazione nel form sottostante per disattivare l'autenticazione a 2 fattori per questo account.",
          instructionsSetOtp:
            "Scansione il QRCode con l'applicazione e inserisci il codice generato nel form sottostante. Oppure inserisci manualmente i parametri per l'attivazione.",
          labelEnterCode: "Inserisci il codice generato dall'applicazione",
          paramAccount: "Account",
          paramCode: "Codice",
          paramType: "Basato sull'ora",
          paramTypeVal: "Attivo",
          params: "Inserisci il codice manualmente",
          paramsInstruction: "Inserisci i seguenti parametri nell'app",
          setOtp: "Attiva autenticazione a 2 fattori",
          title: "Attiva OTP",
          titleDisableOtp: "Disattiva OTP",
          titleSetOtp: "Attiva OTP",
        },
        sessions: {
          browser: "Browser:",
          currentSession: "Corrente",
          device: "Dispositivo:",
          desc: "Gestisci le sessioni di accesso alla tua webmail.",
          ip: "IP:",
          os: "OS:",
          platform: "Piattaforma:",
          removeAll: "Termina tutte",
          removeSession: "Termina",
          startdate: "Inizio:",
          title: "Sessioni aperte",
        },
        title: "Sicurezza",
      },
      title: "Generali",
    },
    mail: {
      accounts: {desc: "", title: "Accounts"},
      antispam: {
        blacklist: {
          desc: "Aggiungi un indirizzo o un dominio alla lista (es. 'nome@dominio' oppure '*@dominio')",
          msgNoHeader: "Non consentire messaggi da (From)",
          title: "Black list",
        },
        deleteRuleDsc: "Elimina la regola impostata su <code>{{ruleEmail}}</code>.",
        deleteRuleTitle: "Elimina regola antispam",
        placeholderList: " ",
        title: "Antispam",
        whitelist: {
          desc: "Aggiungi un indirizzo o un dominio alla lista (es. 'name@dominio' oppure '*@dominio')",
          msgFromHeader: "Consenti messaggi da (From)",
          msgToHeader: "Consenti messaggi a (To)",
          title: "White list",
        },
      },
      autoresponder: {
        desc: "Impostare un messaggio di risposta automatica per quando sei fuori sede o non puoi rispondere ai messaggi ricevuti.<br/>Se un contatto ti inviato più messaggi, la risposta automatica verrà inviata solo una volta ogni 24 ore.",
        msg: "Messaggio",
        placholdeSubject: "Oggetto",
        placholderTextarea: "Messaggio",
        title: "Autorisponditore",
      },
      compose: {
        cancelSend: {
          desc: "Scegli il timeout per annullare l'invio di un messaggio in corso, se decidi di non voler più inviare il messaggio.",
          title: "Annulla invio email",
        },
        confirmations: {
          desc: "Gestisci le notifiche di lettura e consegna per i messaggi ricevuti e inviati.",
          title: "Conferme lettura / consegna",
        },
        title: "Composizione",
      },
      delegations: {desc: "", title: "Deleghe"},
      filters: {
        actionsTitle: "Azioni",
        activeFiltersTitle: "Regole attive",
        desc: "Crea regole specifiche per smistare i messaggi in arrivo e organizzarli come preferisci nella tua casella di posta.",
        headerItem: "Regola",
        headerStatus: "Attiva",
        hintEqualOperator:
          "Attenzione: si raccomanda l'utilizzo dell'operatore <em><b>è uguale a</b></em> / <em><b>non è uguale a</b></em> solo ad utenti esperti. Si consiglia in alternativa di utilizzare l'operatore <em><b>contiene</b></em> / <em><b>non contiene</b></em>. <br>Per utilizzare l'operatore <em><b>è uguale a</b></em> / <em><b>non è uguale a</b></em> bisogna fare corrispondere esattamente tutti gli elementi che compongono il campo. Ad esempio per indicare il <em>Mittente</em> bisogna indicare tutti i seguenti elementi: <b>descrizione &lt;indirizzo email&gt;<b>.",
        parametersTitle: "Parametri",
        placeholderList: {
          parameter: "Aggiungi un parametro alla regola",
          action: "Aggiungi un'azione alla regola",
        },
        title: "Regole",
      },
      folders: {
        compactFolder: "Rimuovi tutti i messaggi contrassegnati come cancellati dalla cartella",
        deleteFolderDsc:
          "Eliminando la cartella <code>{{folderName}}</code> verranno eliminati tutti i messaggi in esse contenuti.<br/><b>L'operazione non è reversibile</b>.",
        deleteFoldersTitle: "Elimina cartella",
        desc: "Gestisci e condividi le tue cartelle personali",
        descShared: "Gestisci le tue cartelle condivise",
        headerItem: "Cartelle",
        headerMsg: "Messaggi",
        headerPermissions: "Permessi",
        headerSelectedUsers: "Utenti selezionati",
        headerUnread: "Non letti",
        modifyFolder: "Modifica cartella",
        newFolder: "Aggiungi nuova cartella",
        retention: "Regole di cancellazione automatica impostate",
        rootFolder: "-- Radice --",
        shared: "Cartella condivisa con altri utenti",
        subscribe: "Sottoscrivi",
        tabInfo: "Informazioni cartella",
        tabShare: "Condivisione",
        title: "Cartelle",
        titleShared: "Cartelle condivise",
      },
      forward: {
        description: "Scegli gli indirizzi email a cui inoltrare i messaggi che ricevi.",
        headerItem: "Destinatari",
        placeholderList: " ",
        title: "Inoltra messaggi",
        titleSection: "Inoltra messaggi",
      },
      labels: {
        desc: "Crea etichette colorate personalizzate per tenere in ordine i tuoi messaggi.",
        headerItem: "Etichette",
        deleteLabelTitle: "Elimina etichetta",
        deleteLabelTitleDsc: "Eliminando l'etichetta questa verrà rimossa da tutti i messaggi.",
        placeholderList: " ",
        title: "Etichette mail",
      },
      reading: {
        layout: {
          desc: "Scegli come vuoi che appaia il riquadro di lettura.",
          title: "Layout",
        },
        readingSettings: {
          desc: "Imposta le tue preferenze di lettura per i messaggi.",
          title: "Impostazioni lettura",
        },
        markReadSettings: {
          desc: "Imposta quando un messaggio debba essere marcato come letto.",
          title: "Marca messaggio come letto",
        },
        title: "Visualizzazione",
      },
      signature: {
        title: "Firma",
        bcc: {
          headerItem: "Destinatari Ccn",
          placeholderList: "",
        },
        default: "Pred.",
        deleteNewSignatureModal: {
          description:
            "Il contenuto della nuova firma non è stato salvato, sarà perso se apri un'altra firma.<br/>Confermi di voler continuare?",
          title: "Cancella la nuova firma",
        },
        dropFiles: "Rilascia qui l'immagine da inserire",
        management: {
          title: "Gestione firma",
        },
        onlyNewMessages: "Non aggiungere firma alle risposte",
        placeholderList: "Aggiungi la tua prima identità",
        senderBcc: "Aggiungi mittente in Ccn",
        setAsDefault: "Imposta come mittente predefinito",
        signatures: {
          desc: "Per ogni identità (gruppi di alias) associata al tuo account puoi personalizzare la firma in calce alle email che invii e il nome visualizzato da chi riceve i tuoi messaggi. Scegli il mittente predefinito e aggiungi liste di indirizzi email in Ccn.",
          headerItemSignature: "Nome visualizzato",
          headerItemIdentity: "Identità",
          title: "Firme e identità",
        },
      },
      template: {
        addAttachment: "Seleziona un file per aggiungerlo come allegato al messaggio",
        deleteTemplateModal: {
          description:
            "Confermi di voler cancellare il messaggio selezionato ? I files allegati al messaggio verranno cancellati dai nostri sistemi.",
          title: "Cancellazione messaggio prefedinito",
        },
        title: "Modelli email",
        description:
          "Seleziona un modello email dalla lista per compilare automaticamente il nuovo messaggio in composizione",
        placeholderList: "Aggiungi il tuo primo modello email",
        placeholderSearch: "Filtra messaggi",
        searchHint:
          "Usa questo campo per filtrare la lista modelli email sottostante. Il filtro è attivo sul nome, oggetto e contenuto del messaggio.",
        templates: {
          desc: "Semplifica la composizione di email ricorrenti salvando dei modelli email da scegliere al momento della composizione della mail.",
          headerItemPreview: "Anteprima",
          headerItemSubject: "Oggetto",
          headerItemTemplate: "Nome",
          maxAttachmentsNrBasic:
            "Massimo {{attachmentNr}} allegati. Massimo {{templateSize}} MB totali. Contatta il tuo gestore dei servizi email per aumentare questi limiti.",
          maxAttachmentsNr:
            "Massimo {{attachmentNr}} allegati. Massimo {{templateSize}} MB totali.",
          maxTemplateNrReached: "È stato raggiunto il numero massimo di modelli configurabili.",
          maxTemplateNrReachedContactReseller:
            "È stato raggiunto il numero massimo di modelli configurabili. Se hai bisogno di aggiungere altri modelli, contatta il tuo gestore dei servizi email per maggiori informazioni.",
          newTemplate: "Nuovo modello",
          title: "Modelli email",
        },
      },
      title: "Mail",
    },
    meeting: {
      title: "Meeting",
      view: {
        desc: "",
        title: "Visualizzazione",
      },
    },
    news: {
      readMore: "Leggi di più",
      title: "Novità e aggiornamenti",
    },
    privacy: {
      title: "Privacy",
      cookie: {
        title: "Cookie Policy",
      },
      privacy: {
        title: "Privacy Policy",
      },
    },
    shortcuts: {
      title: "Scorciatoie da tastiera",
    },
    tasks: {
      notifications: {
        desc: "Ricevi una email quando ti viene assegnata un'attività o quando viene chiusa un'attività che hai assegnato",
        title: "Notifiche email",
      },
      labels: {
        title: "Etichette attività",
        desc: "Crea etichette colorate personalizzate per catalogare le tue attività.",
      },
      title: "Attività",
    },
    title: "Impostazioni",
    unsaved: "Ci sono modifiche non salvate",
  },
  tasks: {
    add: "Crea attività per la mia lista",
    assignedBy: "Assegnata da",
    assignedTaskLabel: "<b>{{user}}</b> ti ha assegnato una nuova attività:",
    assignedTaskTitle: "Nuova attività assegnata",
    assignedTo: "Assegnata a",
    assignTask: "Crea attività da assegnare",
    basic: {
      label:
        "La gestione delle Attività è un servizio disponibile<br />con l'aggiornamento del tuo profilo.<br /><br />L'aggiornamento include anche il Calendario condiviso<br />e video meeting integrati.",

      modalTitle: "Strumenti per ottimizzare il tuo lavoro",
      modalSubTitle: "disponibili con l'aggiornamento del profilo",
      modalFooter:
        "Il tuo referente può presentarti in dettaglio le funzionalità aggiuntive, senza impegno",

      calendarLabel: "<b>Calendario</b> condiviso.",
      tasksLabel: "<b>Attività</b> e promemoria.",
      signatureLabel: "<b>Firma</b> email centralizzata.",
      zoomLabel: "<b>Zoom</b> integrato per video meeting.",
      requestInfo: "Mi interessa",
      requestInfoConfirmation: {
        text: "Sarai contattato dal tuo referente.",
        title: "La richiesta di informazioni è stata inviata.",
      },
      requestLater: "Magari più tardi",
    },
    closedTaskLabel: "<b>{{user}}</b> ha completato un'attività:",
    closedTaskTitle: "Attività assegnata completata",
    completionDate: "Completata",
    deleteTaskModal: {
      desc: "Sei sicuro di voler cancellare l'attività selezionata? Se l'attività è stata assegnata ad altri utenti, sarà cancellata anche per loro.",
      title: "Cancellazione attività",
    },
    dueTime: {
      today: "Oggi",
      tomorrow: "Domani",
      nextWeekend: "Prossimo fine settimana",
      thisWeekend: "Questo fine settimana",
      custom: "Data e ora",
    },
    labels: "Etichette",
    deleteLabelTitle: "Elimina etichetta",
    deleteLabelDsc:
      "Questa etichetta è stata assegnata ad una o più attività. Procedere con la sua eliminazone ?",
    linkedMail: "Email collegata",
    listImagesLabels: {
      completed: {
        text: "La lista delle attività completate è vuota",
        title: "Nessuna attività completata",
      },
      overdue: {
        text: "Non hai attività scadute ancora da fare",
        title: "Ottimo lavoro",
      },
      notCompleted: {
        text: "Non hai programmato nessuna attività da fare",
        title: "Niente da fare qui",
      },
      search: {
        text: "Scrivi qualcosa per fare una ricerca",
        title: "Cerca...",
      },
      assignedToDo: {
        text: "La lista delle attività assegnate è vuota",
        title: "Non hai assegnato nessuna attività",
      },
      assignedCompleted: {
        text: "La lista delle attività assegnate completate è vuota",
        title: "Nessuna attività assegnata completata",
      },
      noResult: {
        title: "Nessun Risultato",
      },
    },
    lists: "Liste",
    modalTitle: "Dettagli attività",
    note: "Note (massimo 1000 caratteri)",
    occurrences: {
      all: "Tutte le occorrenze",
      occurrence: "Solo questa occorrenza",
    },
    openedTaskLabel: "<b>{{user}}</b> ha riaperto un'attività:",
    openedTaskTitle: "Attività assegnata riaperta",
    openMessageModal: {
      desc: "Se apri il messaggio collegato all'attività la lista delle attività verrà chiusa.",
      title: "Vuoi aprire il messaggio?",
    },
    overdueTasksPresent: "Attività scadute: {{overdueTasksPresentCount}}",
    planned: "Quando",
    repeat: "Ripeti",
    repetitions: {
      NEVER: "Mai",
      DAILY: "Quotidianamente",
      WEEKLY: "Settimanalmente",
      MONTHLY: "Mensilmente",
      YEARLY: "Annualmente",
    },
    showMyTasks: "Le mie attività",
    showAssignedTasks: "Assegnate ad altri",
    task: "Attività",
    taskFromNotification:
      "Si desidera visualizzare i dettagli dell'attività notificata e perdere i dati della nuova attività in fase di composizione?",
    title: "Attività",
    types: {
      view_todo: "Da fare",
      view_all: "Tutte",
      view_today: "Oggi",
      view_next7: "Prossimi 7 giorni",
      view_overdue: "Scadute",
      view_completed: "Completate",
    },
  },

  toast: {
    error: {
      alreadyPresent: "Attenzione, la risorsa esiste già",
      avatarTooBig: "Attenzione, dimensione avatar troppo grande",
      compact: "Errore durante la compattazione cartella",
      connectionUnavailable: "Connessione assente",
      delete: "Errore nella cancellazione",
      deleteDraft: "Errore nella cancellazione della bozza",
      emailAddressNotValid: "Indirizzo email non valido",
      enqueued: "Impostazioni in aggiornamento, riprovare",
      fetchingAttachments: "Errore durante il recupero allegati",
      filterActionsMissing: "Azioni non presenti",
      filterConditionsMissing: "Parametri non presenti",
      filterNameMissing: "Nome regola mancante",
      folderCreation: "Errore creazione nuova cartella",
      folderCreationCharNotValid:
        "Errore creazione/modifica cartella, carattere non valido ({{char}})",
      folderCreationNoName: "Errore creazione cartella, specificare un nome",
      folderDelete: "Errore eliminazione cartella",
      folderNotPresent: "Cartella non presente",
      folderRename: "Errore rinominazione cartella, cartella già presente",
      folderSubscribe: "Errore sottoscrizione cartella",
      generic: "Qualcosa è andato storto",
      invalidDateRange: "Intervallo di date non valido",
      maxMembers: "Attenzione, numero massimo di membri raggiunto",
      maxSignatureSize: "Dimensione massima della firma superata. Max {{maxSize}}",
      maxTemplateAttachmentsNumberReached: "Numero massimo di allegati superato",
      maxTemplateSize: "Attenzione, dimensione messaggio eccessiva",
      maxTemplatesNumberReached:
        "Raggiunto il limite di modelli email configurabili per questo account",
      messageCopy: "Errore durante la copia dei messaggi",
      messageMove: "Errore durante lo spostamento dei messaggi",
      messageNotFound: "Messaggio non trovato",
      messageRemove: "Errore durante la cancellazione dei messaggi",
      missingParameters: "Parametri non presenti",
      missingSettings: "Impostazioni utente non presenti",
      notifications: "Errore nella ricezione delle notifiche",
      notPermitted: "Non si hanno i permessi necessari per completare l'operazione",
      notValid: "Attenzione, valore non valido",
      onlyOneHomeAddress: "È possibile inserire un solo indirizzo di casa",
      onlyOneWorkAddress: "È possibile inserire un solo indirizzo di lavoro",
      save: "Errore durante il salvataggio",
      saveEvent:
        "C'è stato un errore, potresti non avere sufficienti permessi su questo calendario",
      saveAcl: "Errore durante il salvataggio dei permessi sulla cartella",
      saveZoomMeeting: "Non è stato possibile creare il meeting sulla piattaforma Zoom",
      savingDraft: "È in corso un salvataggio bozza, riprova al termine",
      searchNotAvailable: "Ricerca al momento non disponibile",
      sendingMessage: "Errore durante l'invio del messaggio",
      serverDisconnection: "Server in aggiornamento, riprova più tardi!",
      sessionExpired: "Sessione scaduta",
      smtpBlockedByAntispam: "Messaggio non inviato: bloccato da antispam",
      smtpBlockedByAntivirus: "Messaggio non inviato: bloccato da antivirus",
      smtpDisabled: "Messaggio non inviato: SMTP disattivato su questo account",
      smtpQuotaExceeded: "Messaggio non inviato: superamento quota invio messaggi",
      requestLimit: "Limite di richieste raggiunto, riprova più tardi.",
      requestError: "Si è verificato un errore durante la richiesta, riprovare più tardi",
      updateFolders: "Si è verificato un errore durante l'aggiornamento delle cartelle",
      updateMessageEvent: "Errore nella ricezione dell'evento aggiornato",
      updatingParentFlags: "Errore nell'aggiornamento dei flags del messaggio",
    },
    info: {
      newVersionAvailable: {
        desc: "L'operazione non è distruttiva, le tue impostazioni rimarranno invariate.",
        title:
          "Nuove funzionalità disponibili, ricarica la pagina per aggiornare la webmail all'ultima versione.",
      },
      serverReconnected: "Webmail di nuovo online",
      sourceMail: "Sorgente mail copiata negli appunti",
    },
    progress: {
      newFolder: "Creazione nuova cartella in corso...",
      operationInProgress: "Operazione in corso...",
    },
    success: {
      compact: "Cartella compattata con successo",
      copiedLink: "Link copiato negli appunti",
      copiedMail: "Mail copiata con successo",
      copiedMailAddress: "Indirizzo mail copiato negli appunti",
      copiedText: "Testo copiato negli appunti",
      createFolder: "Cartella creata con successo",
      delete: "Eliminazione avvenuta con successo",
      disabledOtp: "OTP disattivato con successo",
      enabledOtp: "OTP attivato con successo",
      movedMail: "Mail spostata con successo",
      notificationEnabled: "Notifiche abilitate con successo",
      otpDisabled: "OTP disattivato con successo",
      otpEnable: "OTP attivato con successo",
      save: "Salvataggio avvenuto con successo",
      saveAcl: "Permessi modificati con successo",
      saveDraft: "Bozza salvata con successo",
      saveFolder: "Cartella modificata con successo",
      sentMail: "Mail inviata con successo",
      subscribeFolder: "Sottoscrizione modificata con successo",
      updateMessageEvent: "Stato evento aggiornato",
    },
    warning: {
      forwardSet: "È stato configurato almeno un inoltro su questo account",
      notificationNotSupported: "Attenzione, il browser in uso non supporta le notifiche",
    },
  },

  toggles: {
    labels: {
      allDayEvent: "Tutto il giorno",
      autoSaveContact: "Salva automaticamente i destinatari mail non presenti in rubrica",
      denyInvites: "Impedisci inviti ad appuntamenti",
      enableAutorespopnd: "Abilita autorisponditore",
      enableAutorespopndInterval: "Abilita intervallo",
      enableBrowserNotification: "Abilita le notifiche del browser",
      enableDateSearch: "Abilita la ricerca per data",
      enableFullBody: "Cerca anche nel corpo del messaggio",
      enableNotification: "Abilita le notifiche",
      keepCopy: "Mantieni copia del messaggio in locale",
      showPriority: "Mostra priorità messaggi ricevuti",
      showThreads: "Mostra mail come conversazioni",
      subscribeFolder: "Sottoscrivi cartella",
      tasksEmailNotifications: "Abilita notifiche email",
    },
    hint: {
      enableFullBody:
        "La ricerca nel corpo del messaggio è disponibile solo per singola cartella. Seleziona una cartella per abilitarla.",
    },
  },

  wizard: {
    layout: {
      desc: "Personalizza la tua Webmail scegliendo le impostazioni di visualizzazione che prefresici.",
      title: "Opzioni visualizzazione",
    },
    wizardData: {
      desc: "Personalizza il tuo profilo aggiungendo un’immagine e completando i dati mancanti.",
      title: "Completa profilo",
    },
  },
};
