/*********************************************************************************************************
 * English Copyright (C) 2017-2019 by Qboxmail Srl
 *
 * All rights reserved. No part of this publication may be reproduced, distributed, or transmitted in any
 * form or by any means, including photocopying, recording, or other electronic or mechanical
 * methods, without the prior written permission of the publisher, except in the case of brief quotations
 * embodied in critical reviews and certain other noncommercial uses permitted by copyright law. For
 * permission requests, write to the publisher at the address below.
 *
 * Qboxmail Srl - IT02338120971
 * https://www.qboxmail.it - info@qboxmail.it
 *
 * Italiano Copyright (C) 2017-2019 by Qboxmail Srl
 *
 * Tutti i diritti riservati. Nessuna parte di questa pubblicazione può essere riprodotta, memorizzata in
 * sistemi di recupero o trasmessa in qualsiasi forma o attraverso qualsiasi mezzo elettronico, meccanico,
 * mediante fotocopiatura, registrazione o altro, senza l'autorizzazione del possessore del copyright salvo
 * nel caso di brevi citazioni a scopo critico o altri usi non commerciali consentiti dal copyright. Per le
 * richieste di autorizzazione, scrivere all'editore al seguente indirizzo.
 *
 * Qboxmail Srl - IT02338120971
 * https://www.qboxmail.it - info@qboxmail.it
 *********************************************************************************************************/

export default {
  addressbook: {
    contact: {
      oneSelectContacts: "Geselecteerde contacten",
      oneSelectLists: "Geselecteerde lijst",
      notSelected: "Selecteer een contact",
      sectionLabels: {
        address: "Address",
        company: "Bedrijf",
        email: "Email",
        info: "Info",
        telephone: "telefoon",
        homeUrl: "Persoonlijke website",
        workUrl: "Bedrijfswebsite",
      },
      sections: {
        cell: "Mobiel",
        home: "Thuis",
        homeFax: "Fax thuis",
        work: "Werk",
        workFax: "Fax werk",
        title: "Rol",
        company: "Bedrijf",
        note: "Opmerkingen",
        bday: "Verjaardag",
      },
      selectContacts: "Geselecteerde contacten",
      selectLists: "Geselecteerde lijsten",
      selectedInfo: "Selecteer een contact uit de lijst om de details te bekijken.",
    },
    contactsList: {
      emptyContacts: "Dit adresboek is leeg",
      emptyContactsInfo: "Voeg een contact aan het adresboek",
      emptyLists: "Er zijn geen lijsten",
      emptyListsInfo: "Een nieuwe lijst toevoegen",
      foundContacts: "Gevonden",
      notFound: "Geen contact gevonden",
      notFoundInfo:
        "De zoekopdracht heeft geen resultaat opgeleverd, probeer het opnieuw met andere criteria.",
      totalContacts: "Contacten",
    },
    tabs: {
      contacts: "Contacten",
      lists: "Lijsten",
    },
    contextualMenuLabels: {
      address: "Adres",
      birthday: "Verjaardag",
      cancel: "Annuleren",
      cell: "Mobiel",
      delete: "Verwijderen",
      downloadVCard: "VCard Downloaden",
      email: "E-mail",
      newContact: "Nieuw contact",
      createList: "Maak lijst",
      newList: "Nieuwe lijst",
      note: "Notitie",
      phone: "Telefoon",
      shareVCard: "Delen",
      showVCard: "Vcard weergeven",
      sendAsAttachment: "Verzend per e-mail",
      sendMail: "E-mail verzenden",
      url: "URL",
      info: "Info",
      title: "Rol",
      company: "Bedrijf",
      home: "Thuis",
      homeFax: "Fax thuis",
      work: "Werk",
      workFax: "Fax werk",
      nickname: "Bijnaam",
      displayName: "Naam weergeven",
      companyName: "Naam",
      homeUrl: "Persoonlijke website",
      workUrl: "Bedrijfswebsite",
      team: "Team",
      merge: "Samenvoegen",
    },
    deleteContactDsc:
      "Door het verwijderen van het contact <code>{{contact}}</code> worden alle gerelateerde gegevens ook verwijderd. <br/><b>Dit is onomkeerbaar</b>.",
    deleteContactDscList:
      "Door het verwijderen van het geselecteerde contact worden alle gerelateerde gegevens ook verwijderd. <br/><b>Dit is onomkeerbaar</b>.",
    deleteContactTitle: "Verwijder contact",

    deleteContactsDsc:
      "Door het verwijderen van de geselecteerde contacten worden alle gerelateerde gegevens ook verwijderd. <br/><b>Dit is onomkeerbaar</b>.",
    deleteContactsTitle: "Verwijder contacten",

    deleteListDsc:
      "Door het verwijderen van de lijst <code>{{contact}}</code> worden alle gerelateerde gegevens ook verwijderd. <br/><b>Dit is onomkeerbaar</b>.",
    deleteListTitle: "Verwijder lijst",

    editContactModal: {
      title: "Contact bewerken",
    },
    editListModal: {
      title: "Lijst bewerken",
    },
    exportAddressBookModal: {
      desc: "Je exporteert het adresboek: <code>{{addressbookExport}}</code><br/>In welk formaat wil je de lijst exporteren?",
      title: "Exporteer adresboek",
    },
    import: {
      contactsInvalid: "Niet geldig:",
      contactsNr: "Totaal aantal te importeren contacten:",
      contactsValid: "Geldig:",
      desc: "Je importeert contacten in het adresboek:: <code>{{addressbookImport}}</code><br/>Je kan contacten uit andere e-mailprogramma's importeren met behulp van een vCard (<strong>.vcf</strong>) of <strong>.ldif</strong> bestandsformaat.\u000AJe kunt bijvoorbeeld contactpersonen exporteren vanuit Gmail of vanuit Outlook en ze importeren.\u000AImporteren vervangt géén bestaande contacten.",
      dropFiles: "Upload of plaats hier het bestand dat moet worden geïmporteerd",
      error: "Contacten konden niet worden geïmporteerd",
      importing:
        "We importeren <b>{{contactsNumber}}</b> afspraken in de agenda: <code>{{addressbookImport}}</code>",
      loading: "Laden...",
      success: "Import succesvol!",
      title: "Contacten importeren",
      uploadedFile: "Geüpload",
      uploadingFile: "Uploaden...",
    },
    list: {
      desc: "Door een lijst met contactpersonen aan te maken, is het mogelijk om e-mails naar veel mensen tegelijk te sturen. Je kunt tot 150 leden toevoegen door ze te kiezen uit de contacten in het geselecteerde adresboek.</br></br><b>Opmerking</b>: Het is niet mogelijk om e-mailadressen toe te voegen die niet in het geselecteerde adresboek staan. Voeg eerst de contactpersonen toe aan het adresboek en voeg ze vervolgens toe aan de lijst.",
      members: "Lijst leden",
    },
    messages: {
      newContactAddressBookBody:
        "Je kan geen contact toevoegen in <b>Bedrijfscontacten</b>. Kies een persoonlijk of gedeeld adresboek.",
      newContactAddressBookTitle: "Kies een adresboek",
      resetListBody:
        "De leden van de lijst zijn gerelateerd aan het geselecteerde adresboek. Deze wijziging zal de ledenlijst resetten. Wil je doorgaan?",
      resetListTitle: "Leden verwijderen",
    },
    modifyAddressBookModal: {
      desc: "",
      title: "Adresboek bewerken",
    },
    newAddressBookModal: {
      desc: "",
      title: "Adresboek toevoegen",
    },
    newContactModal: {
      title: "Contact toevoegen",
    },
    newListModal: {
      title: "Lijst toevoegen",
    },
    shareModal: {
      desc: "Je deelt het adresboek: <code>{{addressbookShare}}</code><br/>Selecteer de contacten waarmee je het adresboek wil delen en laat ze het adresboek beheren.",
      title: "Adresboek delen",
    },
    sidebar: {
      allContacts: "Alle contacten",
      deleteAddressbookDsc:
        "Als je het adresboek <code>{{addressbook}}</code> verwijdert, worden alle contactpersonen verwijderd.<br/><b>Dit is onomkeerbaar</b>.",
      deleteAddressbookTitle: "Adresboek verwijderen",
      globalAddressbook: "Zakelijke contacten",
      personalAddressbook: "Persoonlijke contacten",
      sharedAddressbooks: "Gedeelde adresboeken",
      userAddressbooks: "Adresboek van de gebruiker",
    },
    subscribeModal: {
      desc: "",
      noAddressbook: "Er zijn geen adresboeken gevonden",
      title: "Abonneren op een gedeeld adresboek",
    },
  },

  app: {
    addressbook: "Adresboek",
    calendar: "Agenda",
    chat: "Chat",
    meeting: "Vergadering",
    mtm: "Mail Time Machine",
    of: "of",
    webmail: "Webmail",
    modal: {
      updateAvailable: {
        title: "Update beschikbaar",
        description:
          "Er is een <b>nieuwe versie van Webmail</b> beschikbaar.<br/>Ververs de pagina voor een update, je instellingen blijven ongewijzigd.<br/><br/>De applicatie wordt automatisch bijgewerkt tussen:",
      },
    },
  },

  avatarEditorModal: {
    photoTitle: "Maak een foto",
    title: "Avatar wijzigen",
    zoom: "Zoom -/+",
  },

  banner: {
    info: {
      mailRetention: "Berichten in deze map worden na 30 dagen automatisch verwijderd.",
    },
    warning: {
      labelCalendarUpdate:
        "Houd er rekening mee dat als een label wordt hernoemd, het niet langer zichtbaar is in de evenementen waar het wordt gebruikt.",
      labelMailUpdate:
        "Houd er rekening mee dat als een label wordt hernoemd, het niet langer zichtbaar is in de e-mails waarin het wordt gebruikt.",
      labelTaskUpdate:
        "Houd er rekening mee dat als een label wordt hernoemd, het niet langer zichtbaar is in de activiteiten waar het wordt gebruikt.",
      mailRetention:
        "Let op, berichten die je automatisch laat verwijderen, worden definitief verwijderd, zonder de mogelijkheid voor herstel.<br><b>De annulering wordt binnen 24 uur verwerkt.</b>",
    },
  },

  buttons: {
    accept: "Accepteren",
    add: "Toevoegen",
    addAction: "Actie toevoegen",
    addAddressbook: "Addresboek",
    addAsAttachment: "Toevoegen",
    addAttachments: "Voeg bijlagen toe",
    addCalendar: "Agenda",
    addField: "Veld toevoegen",
    addHolidayCalendar: "Vakantie agenda",
    addInline: "In de regel toevoegen",
    addLabel: "Label toevoegen",
    addParameter: "Parameter toevoegen",
    addSignature: "Handtekening toevoegen",
    addToList: "Aan lijst toevoegen",
    allow: "Allow",
    apply: "Toepassen",
    assign: "Toewijzen",
    backAddressbook: "Sluiten",
    backTo: "Vorige",
    cancel: "Annuleren",
    changeImage: "Afbeelding wijzigen",
    changePassword: "Wachtwoord wijzigen",
    checkFreeBusy: "Beschikbaarheid controleren",
    close: "Sluiten",
    comeBackLater: "Kom later terug",
    configure: "Configureren",
    confirm: "Bevestigen",
    copied: "Gekopieerd",
    copy: "Kopiëren",
    copyLink: "Link kopiëren",
    createFolder: "Nieuwe map",
    decline: "Afwijzen",
    delete: "Verwijderen",
    deleteDraft: "Concept verwijderen",
    details: "Details",
    disable: "Uitschakelen",
    disabled: "Uitgeschakeld",
    disableOTP: "OTP uitschakelen",
    download: "Downloaden",
    edit: "Bewerken",
    editLabel: "Label wijzigen",
    editSignature: "Handtekening wijzigen",
    empty: "Leeg",
    enable: "Inschakelen",
    event: "Afspraak",
    export: "Exporteren",
    generateNewPassword: "Nieuw wachtwoord genereren",
    generateRandomPassword: "Random wachtwoord genereren",
    goToCalendar: "Ga naar de agenda",
    goToEventDay: "Ga naar evenementdag",
    goToMail: "Terug naar e-mail",
    goToOldWebmail: "Terug naar de oude webmail",
    goToSettings: "Ga naar de instellingen pagina",
    hide: "Verbergen",
    ignore: "Negeren",
    import: "Importeren",
    insertHTML: "HTML invoegen",
    keep: "Bewaar",
    label: "Label",
    later: "Later",
    learnMore: "Lees meer",
    leftRotate: "90 graden naar links draaien",
    loadImage: "Afbeelding uploaden",
    loading: "Laden",
    logout: "Uitloggen",
    makePhoto: "Maak een foto",
    markRead: "Gelezen",
    markSeen: "Gezien",
    markUnread: "Ongelezen",
    message: "Bericht",
    modify: "Bewerken",
    new: "Nieuw",
    newContact: "Nieuwe contact",
    newEvent: "Nieuwe afspraak",
    newMessage: "Nieuw bericht",
    newSignature: "Nieuwe handtekening",
    newTask: "Nieuwe taak",
    newWebmail: "Nieuwe Webmail",
    next: "Volgende",
    noThanks: "Nee, bedankt",
    occurrence: "Incident",
    ok: "Ok",
    oldWebmail: "Oude Webmail",
    openMap: "Openen",
    otherOptions: "Overige opties",
    override: "Overschrijven",
    participate: "Doe mee",
    postpone: "Uitstellen",
    reloadPage: "Pagina opnieuw laden",
    removeImage: "Afbeelding verwijderen",
    rename: "Hernoemen",
    reorder: "Opnieuw rangschikken",
    reorderEnd: "Einde",
    report: "Rapport",
    restore: "Vraag voor herstel",
    retryImport: "Opnieuw",
    save: "Opslaan",
    saveDraft: "Concept opslaan en sluiten",
    saveNextAvailability: "Voorgestelde beschikbaarheid opslaan",
    search: "Zoeken",
    send: "Verzenden",
    series: "Series",
    setOtp: "OTP instellen",
    share: "Delen",
    show: "Weergeven",
    showAll: "Toon alles",
    showMore: "Laat meer zien",
    showToDo: "Toon te doen",
    showUrlsAddressbook: "Adresboek URL's tonen",
    showUrlsCalendar: "Agenda URL's tonen",
    snooze: "Uitstellen",
    starred: "Markeren",
    subscribe: "Abonneren",
    subscribeAddressbook: "Abonneren op adresboek",
    subscribeCalendar: "Abonneren op agenda",
    tentative: "Misschien",
    understand: "Ik begrijp het",
    unlink: "Link verwijderen",
    unsetOtp: "OTP uitschakelem",
    unsubscribe: "Uitschrijven",
    unsubscribeList: "Abonnement annuleren",
    update: "Bijwerken",
    updateFilter: "Filter bijwerken",
    defaultImg: "Gebruik standaard afbeelding",
    viewMap: "Kaart bekijken",
  },

  buttonIcons: {
    activeSync: "Synchroniseren met behulp van Microsoft® Exchange ActiveSync",
    activeSyncNot: "Microsoft® Exchange ActiveSync uitzetten",
    alignCenter: "Midden centreren",
    alignLeft: "Links uitlijnen",
    alignRight: "Rechts uitlijnen",
    backgroundColor: "Achtergrondkleur",
    backTo: "Terug",
    bold: "Dikgedrukt",
    cannedMsg: "Canned messages",
    close: "Sluiten",
    confirm: "Bevestigen",
    createTask: "Create Task",
    delete: "Verwijderen",
    download: "Downloaden",
    downloadVCard: "Download VCard",
    edit: "Bewerken",
    emoji: "Emoji",
    forward: "Doorsturen",
    fullscreen: "Volledig scherm",
    fullscreenNot: "Niet volledig scherm",
    imageAdd: "Afbeelding toevoegen",
    indent: "Meer inspringen",
    insertHTML: "HTML invoegen",
    italic: "Schuingedrukt",
    link: "Link invoegen",
    maintenance: "Compacte",
    maxmized: "Vergroten",
    minimized: "Verkleinen",
    more: "Meer",
    moveDown: "Naar beneden verplaatsen",
    moveUp: "Naar boven verplaatsen",
    next: "Volgende",
    orderList: "Lijst rankschikken",
    outdent: "Minder inspringen",
    pin: "Vastzetten",
    previous: "Vorige",
    print: "Afdrukken",
    quote: "Citaat",
    removeFormatting: "Opmaak verwijderen",
    removeQuote: "Citaat verwijderen",
    reply: "Reageren",
    replyAll: "Reageren op iedereen",
    saveDraft: "Concept opslaan",
    sendDebug: "Bericht verzenden dat niet kan worden bekeken",
    sendMail: "E-mail verzenden",
    sendByEmail: "Verzend per e-mail",
    share: "Delen",
    showSidebar: "Toon / verberg zijbalk",
    showSourceCode: "Broncode tonen",
    showVCard: "Vcard tonen",
    spam: "Markeren als spam",
    spamNot: "Markeren als veilig",
    startChat: "Chat starten",
    startMeeting: "Afspraak starten",
    strike: "Doorstrepen",
    subscribe: "Inschrijven",
    textColor: "Tekstkleur",
    thanks: "Bedankt",
    underline: "Onderstrepen",
    understand: "Ik begrijp het",
    undo: "Ongedaan maken",
    unlink: "Link verwijderen",
    unorderList: "Lijst niet ranschikken",
    unSubscribe: "Uitschrijven",
  },
  calendar: {
    alarmDurations: {
      after: "na",
      before: "voor",
      day: "dagen",
      hour: "uren",
      minute: "minuten",
      second: "seconden",
      week: "weken",
    },
    deleteEvent: "Afspraak verwijderen",
    deleteEventDsc: "Wil je doorgaan met het verwijderen van deze afspraak?",
    deleteSeries: "Serie verwijderen",
    deleteSeriesDsc: "Doorgaan met het verwijderen van de geselecteerde serie?",
    event: {
      alarmsNotPresent: "Geen meldingen",
      deleteEventOccurrenceTitle: "Alleen deze tijdstip verwijderen of de hele reeks?",
      deleteEventOccurrenceDesc:
        "De afspraak die je wil verwijderen is een terugkerende afspraak. Het verwijderen van één tijdstip laat toekomstige gebeurtenissen ongewijzigd.",
      eventNotes: "Evenement notities",
      eventAttendees: "Evenement deelnemers",
      fromDay: "van",
      labelsNotPresent: "Geen label",
      locationContextualMenuLabels: {
        zoomLabel: "Zoom",
        zoomHint: "Web meeting",
        personalMeetingLabel: "Persoonlijke vergaderruimte",
        personalMeetingHint: "Web meeting",
        locationLabel: "1 op 1 Meeting",
        locationHint: "Adres of plaats opgeven",
        textLabel: "Aangepast",
        textHint: "Geef je eigen eigen tekst op",
      },
      locationSelector: "Selecteer event locatie",
      locationZoomNoMeeting:
        "Op het moment dat het event is opgeslagen, wordt de link van de Zoom meeting hier zichtbaar.",
      maxAttachmentsNumberTitle: "Te veel bijlagen!",
      maxAttachmentsNumberDsc:
        "U kunt maximaal 4 bijlagen invoeren. Als u meer dan 4 bestanden wilt bijvoegen, raden we u aan een gecomprimeerde map te maken.",
      maxLabelsNumberTitle: "Te veel labels",
      maxLabelsNumberDsc:
        "Je hebt het maximale aantal labels bereikt dat aan een evenement kan worden gekoppeld. Om een nieuw label toe te voegen, moet je eerst een van de reeds aanwezige labels verwijderen.",
      noTitle: "Ongetiteld",
      notIncludedInFreeBusy:
        "Deze agenda is niet inbegrepen in Free/Busy. Dit betekent dat jij en de mensen die je uitnodigt als <b>beschikbaar</b> worden weergegeven tijdens de evenementen die in deze agenda zijn aangemaakt.",
      organizerTitle: "Gemaakt door",
      pendingMsg: "Wachtend op bevestiging",
      permissionDenied:
        "U kunt de details van het geselecteerde evenement niet bekijken, u beschikt mogelijk niet over de benodigde machtigingen.",
      repeatEvent: "Deze afspraak is deel van een reeks",
      saveEventOccurrenceTitle: "Deze afspraak of de hele reeks tonen?",
      saveEventOccurrenceDesc:
        "De afspraak die je wil bewerken is een terugkerende afspraak. Het wijzigen van één tijdstip laat toekomstige gebeurtenissen ongewijzigd.",
      setAlert: "Alarm instellen",
      toDay: "tot",
    },
    eventRepetition: {
      WeekDayNumberInMonth_1: "Eerste",
      WeekDayNumberInMonth_2: "Tweede",
      WeekDayNumberInMonth_3: "Derde",
      WeekDayNumberInMonth_4: "Vierde",
      WeekDayNumberInMonth_5: "Vijfde",
      never: "Nooit",
      after: "Na;herhalingen",
      inDate: "Op datum",
      end: "Einde herhaling",
    },
    filterView: {
      listmonth: "Agenda",
      day: "Dag",
      month: "Maand",
      week: "Week",
      workWeek: "Werkweek",
      year: "Jaar",
    },
    import: {
      contactsInvalid: "Niet geldig:",
      contactsNr: "Totaal aantal evenementen om te importeren:",
      contactsValid: "Goedgekeurd:",
      dropFiles: "Upload bestanden of sleep ze hiernaartoe",
      error: "Afspraken konden niet worden geïmporteerd",
      importing:
        "We importeren <b>{{eventsNumber}}</b> afspraken naar: <code>{{calendarImport}}</code>",
      info: "Je importeert afspraken naar de agenda: <code>{{calendarImport}}</code><br/>Je kan afspraken importeren uit andere e-mailapps in een ICS-bestandsformaat. <br/><b>De import vervangt geen bestaande afspraken</b>.",
      loading: "Laden...",
      success: "Al je afspraken zijn succesvol geïmporteerd!",
      title: "Afspraken importeren",
      uploadedFile: "Geüpload",
      uploadingFile: "Uploaden...",
    },
    modifyCalendarModal: {
      desc: "",
      title: "Bewerk agenda",
    },
    newCalendarModal: {
      desc: "",
      title: "Maak agenda",
      freeBusyInfo:
        "Als de kalender niet is opgenomen in <b>Free/Busy</b>, worden jij en de mensen die je uitnodigt weergegeven als <b>beschikbaar</b> tijdens de evenementen die in deze kalender zijn aangemaakt.",
    },
    newEvent: {
      attachmentsList: {
        headerItem: "Bijlagen",
        placeholderList: " ",
      },
      desc: "",
      dropFiles: "Upload bestanden of sleep ze hiernaartoe<br>(maximaal 4 bijlagen, elk 3 MB)",
      freeBusy: {
        legend: {
          event: "Afspraak",
          busy: "Bezig",
          waiting: "Wachten",
          availability: "Volgende beschikbaarheid",
        },
      },
      hideDetails: "Deelnemers verbergen",
      participantsList: {
        headerItem: "Deelnemers",
        answeredHeaderItem: "Beantwoord",
        notAnsweredHeaderItem: "Wachten op een antwoord...",
        placeholderList: " ",
      },
      showDetails: "Details tonen",
      tabAttachments: "Bijlagen",
      tabDetails: "Details",
      tabParticipants: "Deelnemers",
      tabSeries: "Herhalingen",
      tabSettings: "Instellingen",
      title: "Afspraak maken",
      titleEdit: {
        event: "Afspraak",
        series: "Series",
      },
      titleFreebusy: "Beschikbaarheid van deelnemers",
    },
    nextAvailability: "Volgende beschikbaarheid",
    searchEvents: {
      notFound: "Geen afspraken gevonden",
      notFoundInfo:
        "De zoekopdracht heeft geen resultaten opgeleverd, probeer het opnieuw met andere criteria.",
    },
    shareModal: {
      desc: "Je deelt de agenda: <code>{{{{calendarShare}}}}</code><br/>Selecteer de contactpersonen waarmee je de agenda wil delen en sta ze toe deze te beheren.",
      title: "Agenda delen",
    },
    sidebar: {
      labels: "Labels",
      personalCalendar: "Persoonlijke agenda",
      sharedCalendars: "Gedeelde agenda's",
      userCalendars: "Gebruikersagenda's",
      deleteCalendarDsc:
        "Door de kalender <code>{{calendar}}</code> te verwijderen, worden alle opgenomen gebeurtenissen verwijderd. <br/><b>Dit is inomkeerbaar</b>.",
      deleteCalendarTitle: "Agenda verwijderen",
    },
    subscribeModal: {
      desc: "",
      noCalendar: "Er zijn geen agenda's om op te abonneren",
      title: "Abonneren op een gedeelde kalender",
    },
    today: "Vandaag",
  },

  circularLoopBar: {
    uploading: "Uploaden...",
  },

  comingSoon: "Ontwikkeling in uitvoering...",

  contactImport: {
    title: "Contacten zoeken",
    desc: "We importeren je oude contacten. Dat kan even duren...",
  },

  datasets: {
    actionsFlags: {
      "\\\\Answered": "Beantwoord",
      "\\\\Deleted": "Verwijderd",
      "\\\\Draft": "Concept",
      "\\\\Flagged": "Gemarkeerd",
      "\\\\Seen": "Gelezen",
    },
    antispamFilterTypes: {
      whitelist_from: "Toestaan van",
      whitelist_to: "Toestaan naar",
    },
    calendarMinutesInterval: {
      15: "15 minuten",
      30: "30 minuten",
      60: "60 minuten",
    },
    calendarNewEventFreeBusy: {
      busy: "Bezet",
      free: "Beschikbaar",
      outofoffice: "Buiten kantoor",
      temporary: "Tijdelijk",
    },
    calendarNewEventPartecipation: {
      ACCEPTED: "Accepteren",
      DECLINED: "Afwijzen",
      TENTATIVE: "Misschien",
    },
    calendarNewEventParticipationRoles: {
      CHAIR: "Voorzitter",
      "REQ-PARTICIPANT": "Gevraagd",
      "OPT-PARTICIPANT": "Niet gevraagd",
      "NON-PARTICIPANT": "Ter informatie",
    },
    calendarNewEventPriority: {
      0: "Geen",
      1: "Hoog",
      5: "Middel",
      9: "Laag",
    },
    calendarNewEventTypes: {
      public: "Openbaar",
      confidential: "Vertrouwelijk",
      private: "Privé",
    },
    calendarStartWeekDay: {
      saturday: "Zaterdag",
      sunday: "Zondag",
      monday: "Maandag",
    },
    calendarView: {
      year: "Jaar",
      month: "Maand",
      week: "Week",
      workWeek: "Werkweek",
      day: "Dag",
      listmonth: "Lijst",
    },
    calendarEventFilterBy: {
      allEvents: "Alle",
      nextEvents: "Alle volgende afspraken",
    },
    calendarEventSearchIn: {
      title: "Titel/label/plaats",
      all: "Gehele inhoud",
    },
    cancelSendTimer: {
      0: "Uitgeschakeld",
      5000: "5 seconden",
      10000: "10 seconden",
      20000: "20 seconden",
      30000: "30 seconden",
    },
    contactNameFormat: {
      firstName: "Voornaam, Achternaam",
      lastName: "Achternaam, Voornaam",
    },
    contactsOrder: {
      firstName: "Voornaam",
      lastName: "Achternaam",
    },
    countries: {
      AD: "Andorra",
      AE: "United Arab Emirates",
      AG: "Antigua & Barbuda",
      AI: "Anguilla",
      AL: "Albania",
      AM: "Armenia",
      AO: "Angola",
      AR: "Argentina",
      AS: "American Samoa",
      AT: "Austria",
      AU: "Australia",
      AW: "Aruba",
      AX: "Åland Islands",
      AZ: "Azerbaijan",
      BA: "Bosnia and Herzegovina",
      BB: "Barbados",
      BD: "Bangladesh",
      BE: "Belgium",
      BF: "Burkina Faso",
      BG: "Bulgaria",
      BH: "Bahrain",
      BI: "Burundi",
      BJ: "Bénin",
      BL: "Saint Barthélemy",
      BM: "Bermuda",
      BN: "Brunei",
      BO: "Bolivia",
      BQ: "Bonaire, Sint Eustatius and Saba",
      BR: "Brasil",
      BS: "Bahamas",
      BW: "Botswana",
      BY: "Belarus",
      BZ: "Belize",
      CA: "Canada",
      CC: "Cocos (Keeling) Islands",
      CD: "Democratic Republic of the Congo",
      CF: "Central African Republic",
      CG: "Republic of the Congo",
      CH: "Switzerland",
      CL: "Chile",
      CM: "Cameroun",
      CN: "China",
      CO: "Colombia",
      CR: "Costa Rica",
      CU: "Cuba",
      CV: "Cabo Verde",
      CW: "Curaçao",
      CX: "Christmas Island",
      CY: "Cyprus",
      CZ: "Czech Republic",
      DE: "Germany",
      DK: "Denmark",
      DM: "Dominica",
      DO: "Dominican Republic",
      EC: "Ecuador",
      EE: "Estonia",
      ES: "Spain",
      ET: "Ethiopia",
      FI: "Finland",
      FO: "Faroe Islands",
      FR: "France",
      GA: "Gabon",
      GB: "United Kingdom",
      GD: "Grenada",
      GF: "French Guiana",
      GG: "Guernsey",
      GI: "Gibraltar",
      GL: "Greenland",
      GP: "Guadeloupe",
      GQ: "Equatorial Guinea",
      GR: "Greece",
      GT: "Guatemala",
      GU: "Guam",
      GY: "Guyana",
      HN: "Honduras",
      HR: "Croatia",
      HT: "Haiti",
      HU: "Hungary",
      IE: "Ireland",
      IM: "Isle of Man",
      IS: "Island",
      IT: "Italy",
      JE: "Jersey",
      JM: "Jamaica",
      JP: "Japan",
      KE: "Kenya",
      KR: "South Korea",
      LI: "Lichtenstein",
      LS: "Lesotho",
      LT: "Lithuania",
      LU: "Luxembourg",
      LV: "Latvia",
      MC: "Monaco",
      MD: "Moldova",
      ME: "Montenegro",
      MG: "Madagascar",
      MK: "North Macedonia",
      MQ: "Martinique",
      MT: "Malta",
      MW: "Malawi",
      MX: "Mexico",
      MZ: "Mozambique",
      NA: "Namibia",
      NI: "Nicaragua",
      NL: "Netherlands",
      NO: "Norway",
      NZ: "New Zealand",
      PA: "Panama",
      PE: "Perú",
      PH: "Philippines",
      PL: "Poland",
      PT: "Portugal",
      PY: "Paraguay",
      RE: "Réunion",
      RO: "Romania",
      RS: "Serbia",
      RU: "Russia",
      RW: "Rwanda",
      SE: "Sweden",
      SG: "Singapore",
      SH: "Saint Helena",
      SI: "Slovenia",
      SJ: "Svalbard & Jan Mayen",
      SK: "Slovakia",
      SM: "San Marino",
      SO: "Somalia",
      SS: "South Sudan",
      SV: "El Salvador",
      TG: "Togo",
      TO: "Tonga",
      TR: "Turkey",
      TZ: "Tanzania",
      UA: "Ukraine",
      UG: "Uganda",
      US: "United States of America",
      UY: "Uruguay",
      VA: "Città del Vaticano",
      VE: "Venezuela",
      VN: "Vietnam",
      XK: "Kosovo",
      YT: "Mayotte",
      ZA: "South Africa",
      ZM: "Zambia",
      ZW: "Zimbabwe",
    },
    deliveryNotifications: {
      always: "Vraag altijd om een leveringsbevestiging",
      never: "Vraag nooit om een leveringsbevestiging",
    },
    markReadAfter: {
      manually: "Handmatig",
      onOpen: "Wanneer het bericht is geopened",
      5000: "Na 5 seconden",
      10000: "Na 10 seconden",
      30000: "Na 30 seconden",
    },
    eventAlarmPostponeTime: {
      60: "voor 1 minuut",
      300: "voor 5 minuten",
      900: "voor 15 minuten",
      1800: "voor 30 minuten",
      3600: "voor 1 uur",
      7200: "voor 2 uur",
      86400: "voor 1 dag",
      604800: "voor 1 week",
    },

    eventTimeIntervals: {
      5: "5 minuten",
      10: "10 minuten",
      15: "15 minuten",
      20: "20 minuten",
      30: "30 minuten",
    },

    calendarTaskStatus: {
      "NEEDS-ACTION": "Actie nodig",
      COMPLETED: "Afgehandeld",
      PROCESS: "In bewerking",
      CANCELLED: "Geannuleerd",
    },

    feedbackAreas: {
      addressbookSidebar: "Lijst met adresboeken",
      contactList: "Contactenlijst",
      contactView: "Contactweergave",
      mailSearch: "Zoek berichten",
      mailSidebar: "Mappenlijst",
      messageList: "Berichtenlijst",
      messageView: "Berichtweergave",
      newMessage: "Nieuw bericht opstellen",
      other: "Meer",
      settings: "Instellingen",
    },
    filterMail: {
      all: "Alles",
      byDate: "Datum",
      byFrom: "Van",
      bySize: "Grootte",
      bySubject: "Onderwerp",
      flagged: "Gemarkeerd",
      filter: "Filters",
      orderBy: "Sorteer op",
      seen: "Gelezen",
      unseen: "Ongelezen",
    },
    filtersActions: {
      discard: "Weggooien",
      addflag: "Markeer bericht als",
      setkeyword: "Label toevoegen",
      fileinto: "Verplaats het bericht naar",
      fileinto_copy: "Kopieer bericht naar",
      keep: "Bericht bewaren",
      redirect: "Bericht doorverwijzen naar",
      redirect_copy: "Stuur een kopie naar",
      reject: "Weigeren met het volgende bericht",
      stop: "Stop de verwerking van filters",
    },
    filtersDateOperators: {
      gt: "Na",
      is: "Is gelijk aan",
      lt: "Voor",
      notis: "is niet gelijk aan",
    },
    filtersEnvelopeSubtypes: {From: "Van", To: "Tot"},
    filtersDateSubTypes: {date: "Datum", time: "Tijd", weekday: "Weekdag"},
    filtersDateWeekdays: {
      monday: "Maandag",
      tuesday: "Dinsdag",
      wednesday: "Woensdag",
      thursday: "Donderdag",
      friday: "Vrijdag",
      saturday: "Zaterdag",
      sunday: "Zondag",
    },
    filtersRules: {
      Bcc: "Bcc",
      body: "Body",
      Cc: "Cc",
      currentdate: "Datum",
      envelope: "Bericht",
      From: "Afzender",
      other: "Andere",
      size: "Grootte",
      Subject: "Onderwerp",
      To: "Ontvanger",
    },
    filtersSizeMUnits: {B: "Bytes", K: "Kilobytes", M: "Megabytes"},
    filtersSizeOperators: {over: "is groter dan", under: "is kleiner dan"},
    filtersStringOperators: {
      contains: "bevat",
      exists: "bestaat",
      is: "is gelijk aan",
      notcontains: "bevat niet",
      notexists: "bestaat niet",
      notis: "is niet gelijk aan",
    },
    fontSize: {
      extraSmall: "Extra klein",
      huge: "Reusachtig",
      large: "Groot",
      medium: "Medium",
      normal: "Normaal",
      small: "Klein",
    },
    languages: {
      de: "Duits",
      en: "Engels",
      fr: "Frans",
      gr: "Grieks",
      it: "Italiaans",
      nl: "Dutch",
      sv: "Zweeds",
      es: "Spaans",
      pt: "Portugees",
    },
    mailRetention: {
      0: "Nooit",
      30: "ouder dan 1 maand",
      90: "ouder dan 3 maanden",
      180: "ouder dan 6 maanden",
      365: "ouder dan 1 jaar",
      730: "ouder dan 2 jaar",
      1095: "ouder dan 3 jaar",
      1460: "ouder dan 4 jaar",
      1825: "ouder dan 5 jaar",
    },
    matchTypes: {
      allof: "Match op alle parameters",
      anyof: "Match op ten minste één parameter",
    },
    newAllDayEventAlert: {
      never: "Nooit",
      eventDate: "Afspraakdatum",
      "-PT17H": "1 dag van tevoren, om 9 uur",
      "-P6DT17H": "1 week van tevoren, om 9 uur",
    },
    newEventAlert: {
      never: "Nooit",
      eventHour: "Begintijd",
      //P[n]Y[n]M[n]DT[n]H[n]M[n]S
      "-PT5M": "5 minuten voor",
      "-PT10M": "10 minuten voor",
      "-PT15M": "15 minuten voor",
      "-PT30M": "30 minuten voor",
      "-PT1H": "1 uur voor",
      "-PT2H": "2 uur voor",
      "-PT12H": "12 uur voor",
      "-P1D": "1 dag voor",
      "-P7D": "1 week voor",
    },
    newEventRepeatDayWeek: {
      MO: "Maandag",
      TU: "Donderdag",
      WE: "Woensdag",
      TH: "Donderdag",
      FR: "Vrijdag",
      SA: "Zaterdag",
      SU: "Zondag",
    },
    newEventRepeatFrequency: {
      NEVER: "Nooit",
      DAILY: "Dagelijks",
      WEEKLY: "Wekelijks",
      MONTHLY: "Maandelijks",
      YEARLY: "Jaarlijks",
    },
    newEventRepeatMonths: {
      1: "januari",
      2: "februari",
      3: "maart",
      4: "april",
      5: "mei",
      6: "juni",
      7: "juli",
      8: "augustus",
      9: "september",
      10: "october",
      11: "november",
      12: "december",
    },
    orderSelector: {
      byLastname: "Achternaam",
      byMail: "E-mailadres",
      byName: "Voornaam",
      byOrg: "Bedrijf",
      orderBy: "Sorteren op",
      showOnlyLists: "Toon alleen lijsten",
    },
    readConfirmations: {
      always: "Altijd om leesbevestiging vragen",
      never: "Nooit om leesbevestiging vragen",
    },
    readingConfirmation: {
      always: "Altijd",
      ask: "Altijd vragen",
      never: "Nooit",
    },
    selectMail: {
      all: "Alles",
      cancel: "Annuleren",
      modify: "Bewerken",
      none: "Deselecteer",
      select: "Selecteer",
    },
    shareOptionsCalendar: {
      None: "Geen toegang",
      DAndTViewer: "Datum en tijd tonen",
      Viewer: "Alles inzien",
      Responder: "Reageren op",
      Modifier: "Aanpassen",
    },
    showImages: {
      always: "Altijd",
      contacts: "Contacten en vertrouwden",
      never: "Nooit",
    },
    themes: {
      dark: "Donker",
      light: "Licht",
    },
    timeFormats: {
      "12h": "12h",
      "24h": "24h",
    },
    viewMode: {
      label: {
        viewColumns: "Kolommen",
        viewHalf: "Voorbeeld",
        viewFull: "Lijst",
      },
      desc: {
        viewColumns: "Toon het drie kolommen layout met de reading pane rechta op het scherm.",
        viewHalf: "Toon het twee kolommen layout met de reading pane onderaan op het scherm.",
        viewFull:
          "Toon het twee kolommen layout met alleen een berichtenlijst. De reading pane wordt getoond door te klikken op een bericht.",
      },
    },
  },

  dropdownMenu: {
    activesync: "Microsoft® ActiveSync",
    delete: "Verwijderen",
    download: "Downloaden",
    edit: "Bewerken",
    exportContacts: "Contacten exporteren",
    feedback: "Feedback",
    importContacts: "Contacten importeren",
    importEvents: "Afspraken importeren",
    news: "News & Updates",
    remove: "Verwijderen",
    rename: "Hernoemen",
    share: "Delen",
    shortcuts: "Sneltoetsen",
    syncNo: "Niet synchroniseren",
    syncYes: "Synchroniseren",
    unsubscribe: "Uitschrijven",
  },
  dropdownUser: {
    feedback: "Feedback",
    logout: "Afmelden",
    settings: "Instellingen",
  },

  errors: {
    emailDomainAlreadyPresent: "E-mailadres of domein bestaan al",
    emptyField: "Veld is leeg",
    invalidEmail: "Geen geldig e-mailadres",
    invalidEmailDomain: "E-mailadres of domein zijn niet geldig",
    invalidPassword: "Ongeldig wachtwoord",
    invalidPasswordFormat: "Ongeldig wachtwoord, voer ten minste 8 alfanumerieke tekens in.",
    invalidValue: "Geen geldige waarde",
    mandatory: "Verlpicht veld",
    notAllowedCharacter: "Niet toegestaan karakter",
    notChanged: "Niet gewijzigd veld",
    permissionDenied: "Toestemming geweigerd",
    tooLong: "Te lang veld",
  },

  feedback: {
    disclaimer:
      "Stuur ons je feedback zodat wij onze dienst kunnen verbeteren.<br/>Heb je hulp nodig of heb je vragen, stuur deze dan naar onze support.",
    labels: {
      feedbackAreas: "Waar wil je feedback op achterlaten?",
      note: "Laat een bericht achter (optioneel)",
    },
    msgError: {
      title: "Je feedback kan niet verzonden worden.",
      desc: "Probeer het later nog eens, het is belangrijk voor ons om te weten wat je van onze webmail vindt. Je feedback zal ons helpen om een betere ervaring te creëren voor jou en al onze gebruikers. ",
    },
    msgSuccess: {
      title: "Bedankt voor je feedback!",
      desc: "Wij waarderen de tijd die je hebt genomen om ons te helpen onze webmail te verbeteren. Je feedback zal ons helpen om een betere ervaring voor jou en voor al onze gebruikers te creëren.",
    },
    privacy:
      "De verzamelde gegevens zullen worden verwerkt in overeenstemming met de huidige privacywetgeving.",
    title: "Feedback",
  },

  inputs: {
    labels: {
      addAddress: "Adres toevoegen",
      addContactToAddressbook: "Contact toevoegen aan adresboek",
      addDomain: "Adres of domein toevoegen",
      addLabel: "Label naam",
      addMembers: "Leden toevoegen",
      addParticipant: "Deelnemer toevoegen",
      addressbookName: "Adresboek",
      addUser: "Gebruiker toevoegen",
      alert2: "Tweede herinnering",
      alert: "Herinnering",
      assignTask: "Taak toewijzen aan",
      at: "om",
      calendar: "Agenda",
      calendarBusinessDayEndHour: "Einde werkdag",
      calendarBusinessDayStartHour: "Start werkdag",
      calendarColor: "Agenda kleur",
      calendarMinutesInterval: "Agenda interval",
      calendarName: "Agenda naam",
      calendarView: "Standaardweergave",
      company: "Bedrijf",
      companyName: "Naam",
      confidentialEvents: "Vertrouwelijke afspraken",
      confirmNewPassword: "Wachtwoord bevestigen",
      contactNameFormat: "Geef weer",
      contactsOrder: "Sorteervolgorde contacten",
      contains: "Bevat",
      country: "Land",
      dateFormat: "Datumindeling",
      dateInterval: "Date interval",
      defaultAddressbook: "Standaard adresboek",
      defaultCalendar: "Standaard agenda",
      displayName: "Weergavenaam",
      email: "E-mail",
      encryptionMethod: "Encryptie methode",
      endDate: "Einddatum",
      event: "Afspraak",
      eventDailyRepetition: "Iedere;dag/en",
      eventDailyWorkdayRepetition: "Elke dag van de week",
      eventMonthlyLastDayRepetition: "Laatste dag van de maand, iedere;maand/en",
      eventMonthlyLastWeekDayRepetition: "Laatste {{WeekDay}}, iedere;maand/en",
      eventMonthlyRepetition: "Op {{DayNumber}}, iedere;maand/en",
      eventMonthlyWeekDayRepetition: "Op {{WeekDayNumber}}, iedere;maand/en",
      eventPartecipation: "Aanwezigheidsstatus",
      eventPriority: "Afspraak prioriteit",
      eventType: "Afspraak categorie",
      eventWeeklyRepetition: "Iedere;week, op:",
      eventYearlyLastDayRepetition: "Laatste dag van {{Month}}, ieder;jaar",
      eventYearlyLastWeekDayRepetition: "Laatste {{WeekDay}} van {{Month}}, ieder;jaar",
      eventYearlyRepetition: "Op {{DayNumber}} van {{Month}}, ieder;year",
      eventYearlyWeekDayRepetition: "Op {{WeekDayNumber}} van {{Month}}, ieder;jaar",
      exportAsLdiff: "Exporteren in LDIF formaat",
      exportAsVcard: "Exporteren in VCard formaat",
      faxHome: "Fax thuis",
      faxWork: "Fax werk",
      filter: "Filteren op",
      filterName: "Regelnaam",
      firstName: "Voornaam",
      folderName: "Mapnaam",
      freeBusy: "Weergeven als",
      from: "Van",
      fromDate: "Van datum",
      home: "Thuis",
      hour: "Tijd",
      includeFreeBusy: "Laat Free/Busy zien",
      label: "Label",
      labelColor: "Label kleur",
      language: "Taal",
      lastName: "Achternaam",
      linkText: "Weergegeven tekst",
      linkURL: "Webadres (URL)",
      listName: "Lijst naam",
      location: "Locatie",
      loginAddressbook: "Standaard adresboek",
      mailAccount: "Account",
      mailRetention: "Berichten uit deze map verwijderen",
      mailRetentionDefault:
        "De standaard instelling voor het automatische verwijderen van berichten staat op 30 dagen.",
      mailRetentionDiscalimer:
        "Let op, berichten worden automtisch en definitief verwijderd. Een herstel is niet mogelijk. Je annulering wordt binnen 24 uur uitgevoerd.",
      mailRetentionHint:
        "Specificeer de tijd interval, na ontvangst van een bericht, waarna het automatisch wordt verwijderd.",
      markReadAfter: "Markeer bericht als gelezen",
      mobile: "Mobiel",
      newAddressBook: "Nieuw adresboek",
      newAddressBookMobile: "Nieuw adresboek",
      newAllDayEventAlert: "Nieuwe afspraken voor de hele dag",
      newBcc: "Voeg Bcc-ontvangers toe",
      newCalendar: "Nieuwe agenda",
      newEventAlert: "Nieuwe afspraak melding",
      newForward: "Ontvanger toevoegen aan lijst",
      newPassword: "Nieuw wachtwoord",
      nickname: "Roepnaam",
      object: "Onderwerp",
      oldPassword: "Huidig wachtwoord",
      parentFolder: "Omhoog",
      password: "Wachtwoord",
      personalMeetingRoom: "Link naar persoonlijke vergaderruimte",
      phone: "Telefoon",
      port: "Poort",
      portFor: "Poort voor",
      priority: "Priority",
      privateEvents: "Privé afspraken",
      publicEvents: "Openbare afspraken",
      readingConfirmation: "Leesbevestiging versturen",
      recoveryEmail: "Herstel e-mailadres",
      renameAddressbook: "Adresboek hernoemen",
      repeatEvery: "Herhalen",
      reportBugNote: "Probleem omschrijving",
      reportBugPhoneNumber: "Telefoonnummer",
      searchAddressbookToSubscribe: "Een gebruiker zoeken om zijn gedeelde adresboeken te zien",
      searchCalendarToSubscribe: "Een gebruiker zoeken om zijn gedeelde agenda's te zien",
      searchIn: "Zoeken",
      selectCalendar: "Agenda kiezen",
      selectIdentity: "Identiteit kiezen",
      selectList: "Lijst kiezen",
      selectSnapshotDate: "Kies datum",
      serverName: "Server name",
      shareCalendarCalDAVURL: "CalDAV URL",
      shareCalendarWebDavICSURL: "WebDAV ICS URL",
      shareCalendarWebDavXMLURL: "WebDAV XML URL",
      shareToAddressbook: "Met wie wil je het adresboek delen?",
      shareToCalendar: "Met wie wil je de agenda delen?",
      shareToFolder: "Met wie wil je de map delen?",
      showImages: "Laat afbeeldingen zien",
      signatureName: "Weergavenaam",
      signatureText: "Handtekening tekst",
      startDate: "Startdatum",
      team: "Team",
      templateName: "Weergavenaam",
      templateSubject: "Onderwerp",
      templateText: "Berichttekst",
      theme: "Thema",
      timeFormat: "Tijdsindeling",
      timezone: "Tijdzone",
      title: "Titel",
      to: "Aan",
      untilDate: "Einddatum",
      username: "Gebruikersnaam",
      weekStart: "Eerste dag van de week",
      work: "Werk",
    },
    placeholder: {
      addressbookName: "Naam van het adresboek",
      birthday: "Verjaardag",
      city: "Stad",
      company: "Bedrijf",
      country: "Land",
      customText: "Geef een eigen tekst op",
      email: "E-mail",
      endDate: "Einddatum",
      firstName: "Voornaam",
      lastName: "Achternaam",
      members: "Leden",
      newFolderName: "Nieuwe mapnaam",
      newNameAddressbook: "Nieuwe naam voor het adresboek",
      newPassword: "Ten minste 8 alfanumerieke tekens",
      note: "Notitie",
      password: "Je wachtwoord",
      phone: "Telefoon",
      place: "Straat of plaats invoeren",
      postCode: "Postcode",
      region: "Regio",
      role: "Rol",
      search: "Zoeken",
      searchActivity: "Activiteit zoeken",
      searchEvent: "Afspraken zoeken",
      searchUser: "Zoek naar gebruiker in uw domein",
      select: "Selecteren",
      snooze: "Alarm uitstellen",
      startDate: "Startdatum",
      street: "Straat",
    },
    hint: {
      cancelSendMessage:
        "Selecteer de tijd waar het mogelijk is om een bericht na het verzenden te heroepoen, wanneer je beslist om een bericht toch niet te versturen.",
      newForward: "Je kan maximaal {{max}} forwarder aanmaken.",
      newBcc: "Je kunt maximaal {{max}} Bcc-ontvangers toevoegen.",
      mailRetention:
        "Specificeer de tijd interval, na ontvangst van een bericht, waarna het automatisch wordt verwijderd",
      passwordScore: {
        check: "Sterkte wachtwoord",
        poor: "Zeer zwak wachtwoord",
        easy: "Wachtwoord is makkelijk te raden",
        weak: "Wachtwoord is zwak",
        strong: "Wachtwoord is sterk",
        great: "Perfect wachtwoord!",
      },
    },
  },

  labels: {
    attendees: "Deelnemers",
    calendarAdvancedSearch: "Waar wil je zoeken?",
    clearAdvancedFilters: "Filters leegmaken",
    clearFields: "Velden leegmaken",
    default: "Default",
    forDomain: "voor domein",
    forward: "Fwd",
    holidayCalendar: "Vakantie",
    organizer: "Organisator",
    otherFilters: "Andere filters",
    searchResults: "Zoekresultaten",
    withAllUsers: "Met alle gebruikers",
  },

  loaderFullscreen: {
    descriptionEvents: "Je events worden geladen...",
    description: "De inhoud wordt geladen...",
    descriptionFolder: "Je mappen worden geladen...",
    title: "Laden...",
    titleEvent: "Event laden",
  },

  mail: {
    confirmMailLabel: "Bevestigen",
    contextualMenuLabels: {
      addAddressBook: "Toevoegen aan adresboek",
      addEvent: "Afspraak toevoegen",
      alarm: "Melding",
      archive: "Archief",
      archiveThread: "Archief conversatie",
      backTo: "Terug",
      cancel: "Annuleren",
      close: "Sluiten",
      confirm: "Bevestigen",
      copyIn: "Kopiëren naar",
      copyThreadIn: "Conversatie kopiëren ",
      delete: "Verwijderen",
      deletePerm: "Permanent verwijderen",
      deleteThread: "Conversatie verwijderen",
      deleteXMessages: "{{MessagesNumber}} berichten verwijderen",
      deliveryNotification: "Leveringsbevestiging",
      download: "Downloaden",
      editAsNew: "Als nieuw bericht bewerken",
      emptySpam: "Markeren als spam",
      emptyTrash: "Prullenbak legen",
      forward: "Doorsturen",
      import: "Mail importeren",
      label: "Label",
      labelsManagement: "Labels beheren",
      labelThread: "Conversatie labelen",
      markAllAsRead: "Alles markeren als gelezen",
      markAs: "Markeren als",
      markThreadAs: "Conversatie markeren",
      manageFolders: "Mappen beheren",
      modify: "Bewerken",
      more: "Meer",
      moveThreadTo: "Conversatie verplaatsen",
      moveTo: "Verplaatsen naar",
      newSubFolder: "Submap toevoegen",
      plainText: "Platte tekst",
      print: "Afdrukken",
      priorityHigh: "Hoge prioriteit",
      readed: "Gelezen",
      readedNot: "Ongelezen",
      readingNotification: "Leesbevestiging",
      rename: "Hernoemen",
      reply: "Antwoorden",
      replyToAll: "Allen beantwoorden",
      restore: "Herstellen",
      restoreThreadIn: "Conversatie herstellen",
      restoreIn: "Herstellen in",
      sendAsAttachment: "Doorsturen als bijlage",
      showSourceCode: "Broncode tonen",
      spam: "Spam",
      spamNot: "Geen spam",
      starred: "Gemarkeerd",
      starredNot: "Niet gemarkeerd",
      thanks: "Bedankt",
      thread: "Acties",
    },
    deleteMailDsc: "Als je geen ander opslagsysteem hebt wordt het bericht permanent verwijderd.",
    deleteMailTitle: "Bericht verwijderen",
    deleteMailsDsc: "Na 30 dagen worden de berichten in deze map automatisch verwijderd.",
    deleteMailsTitle: "Geselecteerde berichten verwijderen",
    dropFiles: "Sleep bestanden om toe te voegen hiernaartoe",
    emptyTrashDsc: "Na 30 dagen worden de berichten in deze map automatisch verwijderd",
    emptyTrashTitle: "Prullenbak legen",
    goToOldWebmailModal: {
      description:
        "<br/>We nodigen je uit om gelijk over te gaan naar de nieuwe Webmail. Maak zo gebruik van deze extra functies: <br/> <ul> <li> Automatische identiteiten beheer </li> <li> Shared adresbook en kalender </ li > <li> Zoom integratie voor video meetings </li> <li> Vooraf ingestelde berichten </li> <li> Alle mappen doorzoeken </li> <li> en nog veel meer </li> </ul> ",
      title: "De oude Webmail is na 31 oktober niet meer beschikbaar",
    },
    import: {
      messagesInvalid: "Niet geldig:",
      messagesNr: "Totaal aantal berichten om te importeren:",
      messagesValid: "Goedgekeurd:",
      desc: "Je importeert berichten in de map: <code>{{folderImport}}</code><br/>Je kunt berichten van andere mailprogramma's importeren door een .eml bestand te gebruiken (<strong>.eml</strong>).",
      dropFiles: "Upload of plaats hier het bestand dat moet worden geïmporteerd",
      error: "Berichten konden niet worden geimporteerd",
      importing:
        "We zijn <b>{{messagesNumber}}</b> berichten aan het importeren in de map folder: <code>{{folderImport}}</code>",
      loading: "Laden...",
      success: "Importeren gelukt",
      title: "Berichten importeren",
      uploadedFile: "Geupload",
      uploadingFile: "Uploaden...",
    },
    loading: {
      desc: "Je berichten komen eraan, even geduld.",
      title: "Laden",
    },
    markSpamReadDsc:
      "Alle berichten in deze map markeren als gelezen. Berichten in deze map worden na 30 dagen automatisch verwijderd.",
    markSpamReadTitle: "Berichten markeren als gelezen",
    maxLabelsNumberTitle: "Te veel labels!",
    maxLabelsNumberDsc:
      "Je hebt het maximale aantal labels bereikt dat aan een bericht kan worden gekoppeld. Om een nieuw label toe te voegen moet je eerst een van de reeds aanwezige labels verwijderen.",
    message: {
      add: "Add",
      addToAddressBook: "Contact toevoegen aan adresboek",
      attachedMessage: "Toegevoegd bericht",
      attachments: "bijlagen",
      bugMsg: "Kun je het bericht niet zien?",
      cc: "Cc:",
      date: "Date:",
      draftsSelectedInfo: "Kies een bericht en ga door met schrijven.",
      downloadAll: "Alles downloaden",
      downloadAttachments: "Bijlagen downloaden",
      editPartecipationStatusDecription: "",
      editPartecipationStatusTitle: "Aanwezigheid veranderen",
      eventActionAccept: "Accepteren",
      eventActionDecline: "Weigeren",
      eventActionTentative: "Misschien",
      eventAddToCalendar: "Deze afspraak staat niet in je agenda",
      eventAttendees: "Aanwezigen:",
      eventAttendeeStatusAccepted: "Geaccepteerd",
      eventAttendeeStatusDeclined: "Geweigerd",
      eventAttendeeStatusTentative: "Voorlopig aanwezig",
      eventCounterProposal: "Dit bericht bevat een tegenvoorstel voor de afspraak",
      eventDeleted: "Afspraak verwijderd",
      eventInvitation: "Uitnodiging:",
      eventLocationEmpty: "Niet bekend",
      eventModify: "Bewerken",
      eventNeedAction: "Dit bericht bevat een nieuwe afspraak",
      eventNotNeedAction:
        "Dit bericht bevat een uitnodiging voor een afspraak die je al hebt beantwoord",
      eventOutDated: "Deze afspraak is bewerkt",
      eventStatusAccepted: "Geaccepteerd",
      eventStatusDeclined: "Geweigerd",
      eventStatusTentative: "Voorlopig",
      eventUpdate: "Afspraak bijwerken",
      external: "Extern",
      externalLabel: "Dit e-mailadres is van buiten uw organisatie.",
      folderSelectedInfo: "Kies een bericht en zie de inhoud.",
      from: "From:",
      hideAllAttachments: "Verbergen",
      hugeMessage:
        "De inhoud is te groot om deze compleet te tonen, klikop de link hieronder om de bron van het bericht te bekijken.",
      hugeMessageNotice: "Bericht ingekort",
      inboxSelectedInfo: "Selecteer een bericht uit de lijst en zie wie de afzender is.",
      isMailingList: "This message is from a mailing list.",
      localAttachments: "Er zijn extra bijlagen binnen het event",
      message: "bericht",
      messageForwarded: "Doorgestuurd bericht",
      messages: "berichten",
      messagesQuota: "Gebruikt limiet voor berochten:",
      newMessageinThread: "Er is een nieuw bericht",
      noContent: "Dit bericht is leeg.",
      notSelected: "Selecteer een bericht",
      oneSelectMessages: "Geselecteerd bericht",
      oneSelectThreads: "Geselecteerde conversatie",
      readNotificationLabel: "{{Sender}} vraagt een leesbevestiging voor dit bericht.",
      readNotificationLabelSimple: "Leesbevestiging gevraagd",
      readNotificationResponse:
        "<P>Bericht<BR><BR>&nbsp;&nbsp;&nbsp; A:&nbsp; %TO%<BR>&nbsp;&nbsp;&nbsp; Onderwerp:&nbsp; %SUBJECT%<BR>&nbsp;&nbsp;&nbsp; Verzonden:&nbsp; %SENDDATE%<BR><BR>is gelezen op %READDATE%.</P>",
      readNotificationSubjectPrefix: "Lees:",
      replyTo: "Reageren op:",
      sender: "Sender:",
      sentSelectedInfo: "Kies een bericht uit de lijst en zie wie de afzender is.",
      showAllAttachments: "Meer tonen",
      showMoreThread: "Meer tonen",
      selectMessages: "Geselecteerde berichten",
      selectThreads: "Geselecteerde conversaties",
      spamNotSelected: "Map controleren",
      spamSelectedInfo: "Berichten controleren en spam als gelezen markeren.",
      subject: "Subject:",
      to: "Aan:",
      trashNotSelected: "Controleer de prullenbak",
      trashSelectedInfo: "Je kan binnen 30 dagen berichten uit de prullenbak halen.",
      updating: "Bezig met bewerken",
      unsubscribedMailingList: "Je hebt jezelf van de mailing lijst verwijderd.",
      yesterday: "Gisteren",
      wrote: "schrijft:",
    },
    messagesList: {
      allMessagesLoaded: "Alle berichten zijn ingeladen",
      ctaDeletedMessages: "Folder inklappen",
      ctaSpamInfo: "Alles als gelezen markeren",
      ctaTrashInfo: "Prullenbak is leeg",
      deletedMessages:
        "Er zijn berichten welke zijn klaar staan om verwijderen te worden. Maak de folder dicht om het proces uit te voeren.",
      folderEmpty: "Deze map is leeg",
      folderInfo: "Start een gesprek of verplaats een bericht.",
      foundMessages: "Gevonden",
      foundMessagesNum: "Gevonden: <b>{{found}}</b> van <b>{{total}}</b>",
      moveMessage: "Bericht verplaatsen",
      moveMessages: "{{NumMessages}} berichten verplaatsen",
      notFound: "Geen berichten gevonden",
      notFoundInfo:
        "De zoekopdracht heeft geen resultaten opgeleverd, probeer het opnieuw op met andere criteria.",
      pullDownToRefresh: "Sleep om te verversen",
      releaseToRefresh: "Laat los om te verversen",
      searchInfo: "berichten gevonden",
      searchLimited:
        "Indexering in uitvoering. De zoekfunctie is gelimiteerd tot een <b>enkele folder</b> in combinatie met de <b>van</b>, <b>naar</b> en <b>onderwerp</b> velden van een bericht.",
      searchNotAvailable: "Zoekfunctie is niet beschikbaar",
      searchNotAvailableInfo:
        "De zoekfunctie is momenteel niet beschikbaar, probeer het later nog een keer",
      selectMessages: "Geselecteerd",
      showMoreThread: "Meer tonen",
      spamEmpty: "Geen spam aanwezig!",
      spamInfo: "Berichten gemarkeerd als spam worden na 30 dagen automatisch verwijderd.",
      trashEmpty: "De prullenbak is leeg.",
      trashInfo: "Berichten in de prullenbak worden na 30 dagen automatisch verwijderd.",
      totalMessages: "Berichten",
      totalMessagesNum: "Berichten: <b>{{total}}</b>",
    },
    mtm: {
      archivePromo:
        "<b> Maar dat is not niet alles ... </b> <br/> <br/> De e-mailarchief service biedt je een tweede, read-only mailbox, waar je verzonden en ontvangen berichten van de afgelopen 10 jaar kan terugvinden. Er is geen limiet voor de opslagruimte.",
      backupSelector: "Selecteer een backup om verder te gaan",
      description:
        "Met deze dienst is het mogelijk om backups van de afgelopen 15 dagen te raadplegen. Controleer de status van je backups of herstel berichten.",
      title: "Welkom bij de Mail Time Machine",
    },
    newMessage: {
      addAttach: "Bijlagen toevoegen",
      addHTMLTitle: "HTML invoegen",
      addImgeDsc:
        "Je kan afbeeldingen direct inline invoegen, in de tekst van het bericht of ze bij het bericht voegen als bijlage.",
      addImgeTitle: "Afbeelding toevoegen",
      addLinkTitle: "Link invoegen",
      editLinkTitle: "Link bewerken",
      advanced: "Geavanceerd",
      attachInfo: {
        noAttach: "Er zijn geen bijlagen",
        attachNumber: "Bijlagen:",
      },
      bcc: "Bcc",
      cc: "Cc",
      cancelSend: "Verzend van de e-mail is geannuleerd",
      delete: "Verwijderen",
      deleted: "Bericht verwijderd",
      deleteInProgress: "Bericht aan het verwijderen...",
      discardChanges: "Wijzigingen verwerpen",
      fontSize: {
        smaller: "Kleiner",
        small: "Klein",
        normal: "Normaal",
        medium: "Middel",
        big: "Groot",
        bigger: "Groter",
      },
      from: "Van",
      hide: "Verbergen",
      invalidMails: "Ongeldig e-mailadres gevonden. Controleer het adres en probeer het opnieuw.",
      moreAttachments: "Overigen",
      noDraftChanged: "Geen wijzigingen om op te slaan",
      object: "Onderwerp",
      saveDraftDsc:
        "Het bericht is nog niet verzonden en bevat niet-opgeslagen wijzigingen. Je kan het bericht als concept opslaan en later verder schrijven.",
      saveDraftTitle: "Wil je het bericht opslaan als concept?",
      savedDraft: "Concept opgeslagen",
      savingDraft: "Aan het opslaan...",
      sendInProgress: "Aan het verzenden...",
      sent: "Bericht succesvol verzonden",
      sizeExceeded: "Bijlagen zijn te groot. Het maximum is {{messageMaxSize}} MB.",
      templateCreateModal: {
        description:
          "<br/>Maak je eerste standaardantwoord en beantwoord frequente onderwerpen nog makkelijker. Het is mogelijk om je eigen e-mailonderwerp en bijlagen te kiezen welke automatisch met het bericht worden verstuurd.",
        title: "Je hebt momenteel nog geen standaardantwoorden",
      },
      templateSubjectModal: {
        description:
          "De gekozen standaardantwoord heeft een eigen onderwerpsregel. Wil je het onderwerp uit je bericht vervangen of behouden?",
        title: "Onderwerp bestaat al",
      },
      to: "Aan",
      toMore: "Anderen",
      useTemplate: "Standaardantwoord",
      windowSubject: "Nieuw berichten",
    },
    reportBug: {
      title: "Bericht rapporteren",
      message: {
        issue:
          "Als u het bericht niet correct ziet, kunt u ons helpen het probleem op te lossen en de service te verbeteren.<br/>Als u vragen of problemen heeft met betrekking tot het gebruik van webmail, neem dan contact op met uw technische referent voor assistentie.",
        issueFormatting:
          "Wordt de inhoud van het bericht niet correct weergegeven? U beschrijft het probleem, we zullen er alles aan doen om het in de volgende updates op te lossen.",
        issueBlank:
          "Wanneer de berichten geen inhoud bevatten, worden deze in de webmailinterface aangegeven met een speciale banner.<br/><br/>Als deze banner niet aanwezig is, kan dit een formatteringsprobleem zijn, dus <b>controleer de aanwezigheid van de banner</b> en rapporteer het bericht mogelijk als <code>niet correct opgemaakt</code>.",
        issueAttach:
          "Lijkt het bericht vrij van bijlagen? Waarschijnlijk heeft de afzender het bericht verzonden en is hij vergeten de bijlagen in te voegen.<br/><br/><b>Vraag de afzender dit te verifiëren en stuur de bijlagen opnieuw naar jou</b>.",
        issueOther:
          "U beschrijft het probleem, we zullen er alles aan doen om het in de volgende updates op te lossen.<br/>Als u vragen of problemen heeft met betrekking tot het gebruik van webmail, neem dan contact op met uw technische referent voor assistentie.",
        disclaimer:
          "Door deze feedback te verzenden, kan uw bericht worden geanalyseerd door ons ontwikkelingsteam om de service te verbeteren.<br/><br/><b>De informatie wordt NIET gedeeld met derden en de gegevens worden verwerkt in overeenstemming met de huidige wetgeving over privacy</b>.",
      },
    },
    restoreRequest: {
      desc: "U heeft verzocht om het herstel van de mailbox <b>{{username}}</b> met de back-up van <b>{{restore_date}}</b>.<br/>Met deze bewerking zullen we alle berichten herstellen aanwezig in de aangegeven back-up, zonder enig bericht te verwijderen dat in de tussentijd is ontvangen of verzonden vanuit de mailbox.<br/><br/><b>De hersteloperatie is onderhevig aan kosten.</b><br/ ><br/>Wilt u doorgaan met het verzoek?",
      restoreRequested:
        "We hebben je herstelverzoek ontvangen. Er wordt contact met u opgenomen zodra de procedure is afgerond.",
      title: "Een herstel aanvragen",
      titleRestoreRequested: "Request sent",
      deniedTitle: "Verzoek afgewezen",
      restoreRequestDenied:
        "Er is nog een herstelverzoek in behandeling voor dit account. Het is niet mogelijk om meer dan één herstelverzoek tegelijk aan te vragen.",
    },
    searchMail: {
      attachments: "Bijlages",
      cleanFilters: "Filters uitschakelen",
      marked: "Gemarkeerd",
      results: "Zoekresultaten",
      searchIn: "Zoeken in",
      allFolders: "Alle mappen",
      currentFolder: "Huidige map",
    },
    sidebar: {
      createLabel: {
        desc: "",
        title: "Label maken",
      },
      createFolder: {
        desc: "",
        title: "Map maken",
      },
      modifyFolder: {
        desc: "",
        title: "Map bewerken",
      },
      restoreFolder: {
        desc: "",
        title: "Map herstellen",
      },
      folder: "Mappen",
      folders: "Persoonlijke mappen",
      labels: "Labels",
      newFoderName: "Nieuwe map",
      occupiedSpace: "Gebruikte ruimte",
      sharedFolders: "Gedeelde mappen",
      unlimitedSpace: "Onbeperkte ruimte",
    },
    thanksMailLabel: "Oké, bedankt!",
    tooManyCompositionsDsc:
      "Je hebt het maximale aantal nieuwe berichten dat je tegelijkertijd kunt schrijven bereikt. Verstuur ten minste één van de berichten om een nieuw bericht te kunnen starten.",
    tooManyCompositionsTitle: "Maak een bericht af",
    unsubscribeListDsc: "Wil je geen berichten meer ontvangen?",
    unsubscribeListTitle: "Uitschrijven",
  },

  mailboxes: {
    archive: "Archive",
    drafts: "Concepten",
    inbox: "Inbox",
    more: "Meer",
    sent: "Verzonden",
    shared: "Gedeelde mappen",
    spam: "Spam",
    trash: "Prullenbak",
  },

  navbar: {
    addressbook: "Contacten",
    calendar: "Agenda",
    chat: "Chat",
    mail: "E-mail",
    meeting: "Vergadering",
    news: "Nieuws",
  },

  news: {
    notFound: "Nieuws niet gevonden",
    notFoundInfo: "Geen resultaten voor je zoekopdracht, probeer een ander zoekwoord.",
  },

  newsTags: {
    news: "Nieuws",
    suggestions: "Tips",
    fix: "Fix",
    comingSoon: "Binnenkort",
    beta: "Beta",
  },

  pageLogout: {
    title: "Bezig met uitloggen...",
    desc: "",
  },

  pageIndexing: {
    title: "Je account wordt geïndexeerd",
    desc: "Dit kan even duren...",
  },

  pageNotFound: {
    pageNotFound: "Er ging iets mis",
    pageNotFoundInfo: "De pagina die je zoekt kan niet worden gevonden",
  },

  powered: "mogelijk gemaakt met E-mail",
  poweredCollaborationWith: "in samenwerking met",

  radioButtons: {
    labels: {
      askDeliveryConfirmation: "Ontvangstbevestiging vragen",
      askReadConfirmation: "Leesbevestiging vragen",
      defaultView: "Standaard lay-out",
      newEventType: "Nieuw afspraak categorie",
      newEventFreeBusy: "Toon beschikbaarheid voor nieuwe afspraken",
      newEventTimeInterval: "Standaard tijd interval voor nieuwe afspraken",
      other: "Anders",
      reportBugBlank: "Het bericht is leeg",
      reportBugNoAttachments: "Het bericht heeft geen bijlagen",
      reportBugNoFormatted: "De inhoud is niet goed opgemaakt",
      selectIssue: "Welk soort probleem heb je?",
    },
  },

  shareOptions: {
    delete: "Verwijderen",
    read: "Lezen",
    update: "Bewerken",
    write: "Schrijven",
  },

  shareOptionsCalendar: {
    canCreateObjects: "Sta het invoegen van afspraken in deze agenda toe",
    canEraseObjects: "Sta het verwijderen van afspraken in deze agenda toe",
  },

  shortcuts: {
    addressbook: {
      newContact: "Nieuw contact",
      editContact: "Contact bewerken",
      deleteContact: "Contact verwijderen",
    },
    calendar: {
      newEvent: "Nieuwe afspraak",
      editEvent: "Afspraak bewerken",
      deleteEvent: "Afspraak verwijderen",
      moveRangeNext: "Volgende periode bekijken",
      moveRangePrevious: "Vorige periode bekijken",
    },
    general: {
      switchModuls: "Wissel modules",
      refresh: "Pagina verversen",
      tabForward: "Ga vooruit tussen de aanklikbare elementen",
      tabBack: "Verplaats terug tussen de aanklikbare elementen",
      closeModal: "Venster sluiten",
      openSettings: "Open instellingen",
      copy: "Geselecteerd item kopiëren",
      past: "Geselecteerd item plakken",
      cut: "Geselecteerd item knippen",
    },
    mail: {
      confirm: "Bevestigen",
      deleteMessage: "Bericht verwijderen",
      deleteSelectMessage: "Gekozen bericht verwijderen",
      editAsNew: "Bewerken als nieuw bericht",
      empityTrash: "Prullenbak leegmaken",
      expandThread: "Gesprek uitklappen",
      extendSelectDown: "Selectie naar onder uitbreiden",
      extendSelectUp: "Selectie naar boven uitbreiden",
      forward: "Doorsturen",
      markRead: "Markeren als gelezen/ongelezen",
      moveDown: "Omlaag verplaatsen",
      moveUp: "Omhoog verplaatsen",
      newMessage: "Nieuw bericht",
      openSelectMessage: "Open gekozen bericht",
      printMessage: "Bericht afdrukken",
      reduceThread: "Gesprek verkleinen",
      reply: "Beantwoorden",
      replyAll: "Beantwoord alle",
      thanks: "Bedankt",
    },
  },

  settings: {
    addressbook: {
      management: {
        automaticSave: {
          desc: "Kies deze optie wanneer je niet met een vaste contactenlijst wil of moet werken.",
          title: "Automatisch opslaan",
        },
        personalAddressbooks: {
          desc: "Beheer je persoonlijke adresboeken en bepaal zelf of je deze wil delen met andere gebruikers.",
          headerActiveSync: "Sync",
          headerItem: "Adresboek",
          placeholderList: " ",
          title: "Persoonlijk adresboek",
        },
        sharedAddressbooks: {
          desc: "Beheer adresboeken die je gedeeld hebt met andere gebruikers.",
          headerItem: "Geabonneerd adresboek",
          placeholderList: " ",
          title: "Gedeeld adresboek",
        },
        title: "Adresboeken",
      },
      title: "Contacten",
      view: {
        desc: "Beheer je voorkeuren voor de contacten en adresboek weergave.",
        title: "Contacten weergeven",
      },
    },
    calendar: {
      events: {
        title: "Afspraken",
        desc: "Beheer je voorkeuren voor nieuwe afspraken binnen alle kalenders, wanneer deze niet met een bepaald standaard zijn ingesteld.",
        alertTitle: "Meldingen",
        alertDesc:
          "Beheer je voorkeuren voor nieuwe afspraken binnen alle kalenders, wanneer deze niet met een bepaald standaard zijn ingesteld.",
        personalMeetingRoomTitle: "Persoonlijke vergaderruimte",
        personalMeetingRoomDesc:
          "Genereer een ruimte in je online vergaderapplicatie en voer de link hier in. Deze kan dan worden geselecteerd als 'Locatie' bij het maken van een evenement.",
      },
      invitations: {
        desc: "Kies deze optie wanneer je uitnodigingen alleen voor geselecteerde gebruikers wil toestaan.",
        title: "Uitnodigingen voor afspraak",
        msgFromHeader: "Alleen uitnodigen toestaan van",
        placeholderList: " ",
      },
      labels: {
        title: "Agenda labels",
        titleSettingsPage: "Agenda labels",
        desc: "Kies je eigen kleuren voor de labels van je activiteiten.",
        deleteLabelDsc:
          "Wanneer je een label verwijderd, wordt het label ook van alle kalender activiteiten verwijderd.",
      },
      management: {
        title: "Agenda's",
        holidayCalendars: {
          title: "Vakantie agenda's",
          desc: "Kies de vakantie agenda's van je eigen voorkeur.",
          headerItem: "Agenda's",
          placeholderList: " ",
        },
        personalCalendars: {
          title: "Persoonlijke agenda's",
          desc: "Beheer je persoon kalenders en bepaal of je deze wil delen met andere gebruikers.",
          headerActiveSync: "Sync",
          headerItem: "Agenda's",
          placeholderList: " ",
        },
        sharedCalendars: {
          desc: "Beheer de kalenders welke gedeeld zijn met anderen.",
          headerActiveSync: "Sync",
          headerItem: "Agenda inschrijvingen",
          placeholderList: " ",
          title: "Gedeelde agenda's",
        },
        includeInFreeBusy: "Laat Free/Busy zien",
        showActivities: "Laat activiteiten zien",
        showAlarms: "Laat alarmen zien",
        syncWithActivesync: "Synchroniseren met behulp van Microsoft® Exchange ActiveSync",
        sendMeMailOnMyEdit: "Stuur mij een e-mail als ik de kalender wijzig",
        sendMeMailOnOtherEdit: "Stuur mij een e-mail wanneer iemand de kalender wijzigt",
        sendMailOnEditTo: "Wanneer ik wijziginen aanbreng een mail sturen naar",
      },
      view: {
        desc: "Beheer de instellingen voor de weergave van je kalender.",
        showBusyOutsideWorkingHours: "Toon als bezet buiten werktijd",
        showWeekNumbers: "Laat weeknummer zien",
        title: "Agenda weergeven",
      },
      title: "Agenda",
    },
    chat: {
      title: "Chat",
      view: {
        title: "Weergeven",
      },
    },
    general: {
      integrations: {
        desc: "Beheer de integraties met service providers buiten webmail.",
        title: "Integraties",
        card: {
          zoom: {
            askSeller: "Vraag je e-mailaanbieder voor meer informatie",
            title: "Zoom",
            text: "Bespaar tijd bij het plannen van meetings door de unieke Zoom conferentie details aan je e-mail toe te voegen.",
          },
        },
      },
      notifications: {
        title: "Pushmeldingen",
        generalNotification: {
          desc: "Schakelt meldingen in die de ontvangst van een nieuw bericht aangeven.",
          longDesc:
            "Sta Webmail toe om meldingen via uw browser te versturen wanneer u een nieuw bericht ontvangt. Deze instelling is niet voldoende om meldingen te ontvangen, u moet ook meldingen inschakelen voor elke browser die u wilt gebruiken.",
          title: "Algemene instelling van meldingen",
        },
        allowedPush: {
          allowed:
            "Meldingen ingeschakeld op de gebruikte browser. Om ze te ontvangen, moeten ze ook ingeschakeld zijn in de bovenstaande sectie.",
          default:
            "Als u wilt dat uw huidige browser u een melding geeft wanneer u een nieuw bericht ontvangt, moet u meldingen inschakelen (in het gedeelte hierboven) en vervolgens pushmeldingen in uw browser inschakelen. Klik op de knop en sta meldingen toe, of klik op het slotpictogram en sta meldingen toe door op de knop Toestaan te drukken.",
          isIos:
            "Als u meldingen wilt ontvangen op uw iOS-apparaat (versie 16.4 en hoger), moet u Webmail toevoegen aan het startscherm van uw apparaat.",
        },
        browserNotification: {
          desc: "Controleer de status en beheer meldingen voor de browser die momenteel in gebruik is.",
          title: "Status van meldingen van de gebruikte browser",
        },
        granted: "Uw browsermeldingen zijn correct geconfigureerd!",
        noPush: {
          title: "Helaas ondersteunt de Safari-browser het notificatiesysteem niet..",
          titleios: "Helaas ondersteunt het iOS-besturingssysteem geen browsermeldingen.",
          desc: "Gebruik de meest recente versie van een van de volgende browsers om meldingen in te schakelen",
        },
        deniedPush: {
          title: "Je browser blokkeert pushmeldingen.",
          desc: "Verwijder deze blokkering om pushmeldingen te activeren wanneer er een nieuw bericht binnenkomt.",
        },
        modal: {
          title: "Wilt u pushmeldingen toestaan?",
          text: "Je kunt ze altijd toestaan of blokkeren via de webmailinstellingen.",
        },
      },
      parameters: {
        title: "Parameters",
        host: {
          title: "E-mailconfiguratie",
          desc: "Verbind je e-mailprogramma's waarmee je de berichten van je e-mailaccount wil lezen en verzenden.",
        },
        imap: {
          title: "IMAP",
        },
        smtp: {
          title: "SMTP",
        },
      },
      profile: {
        email: "E-mail van de gebruiker",
        generalSettings: {
          desc: "Beheer de taal- en tijdinstellingen.",
          title: "Algemene instellingen",
        },
        personalInfo: {
          desc: "Beheer uw profielgegevens.",
          title: "Persoonlijke gegevens",
        },
        title: "Profiel",
      },
      security: {
        changepassword: {
          info: "Wachtwoord van ten minste 8 alfanumerieke tekens",
          desc: "Beheer het wachtwoord voor toegang tot je webmail.",
          resetpassword: "Nieuw wachtwoord instellen",
          resetpassworddisabled: "Je kunt het wachtwoord voor dit account niet wijzigen",
          resetpasswordexpired: "Je wachtwoord is verlopen, maak een nieuwe",
          title: "Wachtwoord wijzigen",
        },
        days: "dag/en",
        passwordexpiration: {
          activeExpiration: "Automatische wachtwoordverloop is ingeschakeld voor uw e-mailaccount.",
          desc: "Controleer de status van uw accountwachtwoord.",
          expirationDate: "Het wachtwoord verloopt op",
          expirationCountdown: "Het wachtwoord verloopt over",
          modalTitle: "Uw wachtwoord verloopt bijna",
          modalDesc:
            "Er zijn nog {{password_expiration_relative_days}} dag/en over voordat uw accountwachtwoord verloopt. We raden u aan deze meteen te wijzigen.",
          title: "Wachtwoord verlopen",
        },
        otp: {
          cantDisableOtp:
            "Tweevoudige authenticatie kan niet uitgeschakeld worden voor dit account",
          desc: "Beheer tweefactorauthenticatie om toegang te krijgen tot uw webmail.",
          disableOtp: "Tweevoudige authenticatie uitschakelen",
          downloadParams: "Download activation data",
          hideParams: "Parameters verbergen",
          instructionDisableOtp:
            "Voer de gegenereerde code in om tweevoudige authenticatie uit te schakelen.",
          instructionsSetOtp:
            "Scan de QRcode met de applicatie en voer de gegenereerde code hieronder in. Of voer de parameters voor handmatige activering in.",
          labelEnterCode: "Vul code in die gegenereerd is door de applicatie",
          paramAccount: "Account",
          paramCode: "Code",
          paramType: "Tijdgevoelig",
          paramTypeVal: "Actief",
          params: "Code handmatig invullen",
          paramsInstruction: "Voer de volgende waardes in",
          setOtp: "Tweevoudige authenticatie aanzetten",
          title: "OTP instellen",
          titleDisableOtp: "OTP uitzetten",
          titleSetOtp: "OTP aanzetten",
        },
        sessions: {
          browser: "Browser:",
          currentSession: "Huidig",
          device: "Apparaat:",
          desc: "Beheer de actieve sessie van je webmail.",
          ip: "IP:",
          os: "OS:",
          platform: "Platform:",
          removeAll: "Alles verwijderen",
          removeSession: "Verwijderen",
          startdate: "Start:",
          title: "Actieve sessies",
        },
        title: "Beveiliging",
      },
      title: "Algemeen",
    },
    mail: {
      accounts: {desc: "", title: "Accounts"},
      antispam: {
        blacklist: {
          desc: "Voeg adres of domein toe aan de lijst (es. 'name@domain' or '*@domain')",
          msgNoHeader: "Berichten wijgeren van",
          title: "Blacklist",
        },
        deleteRuleDsc: "Regel verwijderen: <code>{{ruleEmail}}</code>.",
        deleteRuleTitle: "Antispam-regel verwijderen",
        placeholderList: " ",
        title: "Antispam",
        whitelist: {
          desc: "Voeg adres of domein toe aan de lijst (es. 'name@domain' or '*@domain')",
          msgFromHeader: "Berichten toestaan van",
          msgToHeader: "Berichten toestaan naar",
          title: "Whitelist",
        },
      },
      autoresponder: {
        desc: "Verstuur een automatische antwoord wanneer je niet op kantoor bent of je niet in staat bent om je e-mails te beantwoorden.<br/>Wanneer iemand je meerdere berichten stuurt, dan wordt de automatische antwoord maar 1 keer in 24 uur verstuurd.",
        msg: "Bericht",
        placholdeSubject: "Onderwerp",
        placholderTextarea: "Bericht inhoud",
        title: "Automatische antwoorden",
      },
      compose: {
        cancelSend: {
          desc: "Kies een tijlimiet waarin je de verzending van een bericht kan annuleren. Deze functie is erg handig voor het geval dat jij je na het verzenden bedenkt.",
          title: "E-mail verzending annuleren",
        },
        confirmations: {
          desc: "Beheer lees/ontvangst bevestigingen voor de berichten die verstuurd en ontvangst.",
          title: "Lees/ontvangst bevestiging",
        },
        title: "Samenstelling",
      },
      delegations: {desc: "", title: "Delegeren"},
      filters: {
        actionsTitle: "Acties",
        activeFiltersTitle: "Actieve regels",
        desc: "Maak specifieke regels aan die bepalen hoe inkomende berichten in je mailbox worden onderverdeelt.",
        headerItem: "Regel",
        headerStatus: "Actief",
        hintEqualOperator:
          "Let op: het gebruik van de operator <em><b>is gelijk aan</b></em> / <em><b>is niet gelijk aan</b></em> wordt alleen aanbevolen aan ervaren gebruikers. Als alternatief wordt aanbevolen om de operator <em><b>bevat</b></em> / <em><b>bevat niet</b></em> te gebruiken. <br>Om de operator <em><b>is gelijk aan</b></em> / <em><b>is niet gelijk aan</b></em> te gebruiken, moeten alle elementen overeenkomen die het veld vormen. Om bijvoorbeeld de <em>Afzender</em> aan te geven, moet u alle volgende elementen opgeven: <b>beschrijving &lt;e-mailadres&gt;<b>.",
        parametersTitle: "Parameters",
        placeholderList: {
          parameter: "Parameter toevoegen aan het regel",
          action: "Actie toevoegen aan het regel",
        },

        title: "Regels",
      },
      folders: {
        compactFolder: "Verwijder alle berichten die zich in de prullenbak bevinden.",
        deleteFolderDsc:
          "Als je de map <code>{{folderName}}</code> verwijdert, worden alle berichten in die map verwijderd.<br/><b>Dit is onomkeerbaar</b>.",
        deleteFoldersTitle: "Mappen verwijderen",
        desc: "Beheer en deel je persoonlijke mappen",
        descShared: "Gedeelde mappen beheren",
        headerItem: "Mappen",
        headerMsg: "Berichten",
        headerPermissions: "Permissies",
        headerSelectedUsers: "Geselecteerde gebruikers",
        headerUnread: "Ongelezen",
        modifyFolder: "Map aanpassen",
        newFolder: "Nieuwe map toevoegen",
        retention: "Automatic deletion rules set",
        rootFolder: "-- Hoofdmap --",
        shared: "Met andere gebruikers delen",
        subscribe: "Inschrijven",
        tabInfo: "Mapinfo",
        tabShare: "Map delen",
        title: "Mappen",
        titleShared: "Gedeelde mappen",
      },
      forward: {
        description: "Kies het e-mailadres waarheen je de e-mailberichten wil doorsturen.",
        headerItem: "Ontvangers",
        placeholderList: " ",
        title: "Berichten doorsturen",
        titleSection: "Berichten doorsturen",
      },
      labels: {
        desc: "Kies je eigen kleuren voor de verschillende labels om zo nog beter je berichten in te delen.",
        headerItem: "Labels",
        deleteLabelTitle: "label verwijderen",
        deleteLabelTitleDsc: "Als u het label verwijdert, wordt het uit alle berichten verwijderd.",
        placeholderList: " ",
        title: "E-maillabels",
      },
      reading: {
        layout: {
          desc: "Kies hier hoe waar de reading pane moet worden getoond.",
          title: "Indeling",
        },
        markReadSettings: {
          desc: "Geef hier op wanneer een bericht als gelezen moet worden gemarkeerd.",
          title: "Markeer het bericht als gelezen",
        },
        readingSettings: {
          desc: "Configureer hier hoe je berichten wil lezen.",
          title: "Leesinstellingen",
        },
        title: "Weergeven",
      },
      signature: {
        title: "handtekening",
        bcc: {
          headerItem: "Bcc-ontvangers",
          placeholderList: "",
        },
        default: "Standaard",
        deleteNewSignatureModal: {
          description:
            "De inhoud van de nieuwe handtekening is nog niet opgeslagen. De wijzigingen gaan verloren wanneer je een andere handtekening opent.<br/>Wil je verder gaan?",
          title: "Nieuwe handtekening verwijderen",
        },
        dropFiles: "Plaats hier een afbeeling om deze toe te voegen",
        management: {
          title: "Handetekeningen beheren",
        },
        onlyNewMessages: "Geen handtekening bij antwoorden invoegen",
        placeholderList: "Je eerste indentiteit toevoegen",
        senderBcc: "Verzendadres in in Bcc",
        setAsDefault: "Als standaard Verzendadres instellen",
        signatures: {
          desc: "Voor elke identiteit (groep aliassen) die aan uw account is gekoppeld, kunt u de handtekening aanpassen onderaan de e-mails die u verzendt, en de naam die wordt weergegeven door degenen die uw berichten ontvangen. Kies de standaardafzender en voeg e-mailadreslijsten toe in Bcc.",
          headerItemSignature: "Weergavenaam",
          headerItemIdentity: "Identiteit",
          title: "Handetekeningen en identiteiten",
        },
      },
      template: {
        addAttachment: "Selecteer een bestand en voeg het toe als bijlage aan het bericht.",
        deleteTemplateModal: {
          description:
            "Wil je deze standaardantwoord verwijderen? De bestanden welke aan dit bericht zijn gekoppeld worden samen met het bericht uit het systeem verwijderd.",
          title: "Standaardantwoord verwijderen",
        },
        title: "Standaardantwoorden",
        description:
          "Selecteer een standaardantwoord uit de lijst en de inhoud wordt automatisch ingevuld bij het opzetten van een bericht.",
        placeholderList: "Je eerste standaardantwoord toevoegen",
        placeholderSearch: "Berichten filteren",
        searchHint:
          "Gebruik dit veld voor het filteren van de lijst met standaardantwoorden. De filterfunctie werkt op basis van de naam, het onderwerp en de inhoud van het bericht.",
        templates: {
          desc: "Maak eenvoudig herhalende berichten aan behulp van standaardantwoorden. Standaardantwoorden die je eerder hebt opgeslagen zijn beschkbaar bij het opstellen van een e-mailbericht.",
          headerItemPreview: "Voorbeeld",
          headerItemSubject: "Onderwerp",
          headerItemTemplate: "Naam",
          maxAttachmentsNrBasic:
            "Maximaal {{attachmentNr}} bijlagen. Maximaal {{templateSize}} MB in totaal. Neem contact op met uw e-mailserviceprovider om deze limieten te verhogen.",
          maxAttachmentsNr:
            "Maximaal {{attachmentNr}} bijlagen. Maximaal {{templateSize}} MB in totaal.",
          maxTemplateNrReached: "Het maximale aantal configureerbare e-mailsjablonen is bereikt.",
          maxTemplateNrReachedContactReseller:
            "Het maximale aantal configureerbare e-mailsjablonen is bereikt. Als u meer e-mailsjablonen wilt toevoegen, neem dan contact op met uw e-mailserviceprovider voor meer informatie.",
          newTemplate: "Nieuw bericht",
          title: "Standaardantwoorden",
        },
      },
      title: "E-mail",
    },
    meeting: {
      title: "Vergadering",
      view: {
        desc: "",
        title: "Weergeven",
      },
    },
    news: {
      readMore: "Lees meer",
      title: "News & Updates",
    },
    privacy: {
      title: "Privacy",
      cookie: {
        title: "Cookie Policy",
      },
      privacy: {
        title: "Privacy Policy",
      },
    },
    shortcuts: {
      title: "Sneltoetsen",
    },
    tasks: {
      notifications: {
        desc: "Ontvang een e-mail wanneer een taak aan jou is toegewezen of wanneer een taak die je hebt toegewezen is gesloten",
        title: "E-mail notificaties",
      },
      labels: {
        title: "Taken labels",
        desc: "Kies je eigen kleuren voor de labels van je taken.",
      },
      title: "Taken",
    },
    title: "Instellingen",
    unsaved: "Er zijn niet-opgeslagen wijzigingen",
  },

  tasks: {
    add: "Taak maken voor mijn lijst",
    assignedBy: "Opgedragen door",
    assignedTaskLabel: "<b>{{user}}</b> heeft u een nieuwe taak toegewezen:",
    assignedTaskTitle: "Nieuwe taak toegewezen",
    assignedTo: "Toegewezen aan",
    assignTask: "Taak maken om toegewezen te krijgen",
    basic: {
      label:
        "De takenmanagement service is beschikbaar <br />na een account upgrade.<br /><br />Het upgrade is inclusieve de gedeelde kalender<br /> en de video meeting integratie.",
      modalTitle: "Tools die je het werk makkelijker maken",
      modalSubTitle: "beschikbaar na een account upgrade",
      modalFooter:
        "Ons technisch personeen kan je de extra kenmerken vrijblijvend presenteren of uitleggen.",

      calendarLabel: "Gedeelde <b>kalender</b>.",
      tasksLabel: "<b>Taken</b> en herinneringen.",
      signatureLabel: "Gecentraliseerde e-mail <b>handtekening</b>.",
      zoomLabel: "Built-in <b>Zoom</b> voor video meetings.",
      requestInfo: "Ik heb interesse",
      requestInfoConfirmation: {
        text: "Je wordt gecontacteerd door een technische medewerker.",
        title: "Je aanvraag voor informatie is verzonden.",
      },
      requestLater: "Misschien later",
    },
    closedTaskLabel: "<b>{{user}}</b> heeft een taak voltooid:",
    closedTaskTitle: "Toegewezen taak voltooid",
    completionDate: "Datum voltooid",
    deleteTaskModal: {
      desc: "Weet u zeker dat u de geselecteerde taak wilt verwijderen? Als de taak is toegewezen aan andere gebruikers, wordt deze ook voor hen verwijderd.",
      title: "Taak verwijderen",
    },
    dueTime: {
      today: "Vandaag",
      tomorrow: "Morgen",
      nextWeekend: "vVolgend weekend",
      thisWeekend: "Dit weekend",
      custom: "Datum en tijd",
    },
    labels: "Labels",
    deleteLabelTitle: "Label verwijdere",
    deleteLabelDsc:
      "Dit label wordt gebruikt voor één of meerdere activiteiten. Wil je doorgaan met verwijderen?",
    linkedMail: "Gekoppelde e-mail",
    listImagesLabels: {
      completed: {
        text: "De lijst met voltooide taken is leeg",
        title: "Geen taken voltooid",
      },
      overdue: {
        text: "Je hebt momenteel geen verlopen taken",
        title: "Goed bezig",
      },
      notCompleted: {
        text: "Je hebt op dit moment geen geplande taken",
        title: "Hier is niets te doen",
      },
      search: {
        text: "Begin te typen om zo te zoeken",
        title: "Zoeken...",
      },
      assignedToDo: {
        text: "De lijst met toegewezen taken is leeg",
        title: "U heeft geen activiteiten toegewezen",
      },
      assignedCompleted: {
        text: "De lijst met voltooide toegewezen taken is leeg",
        title: "Geen toegewezen taken voltooid",
      },
      noResult: {
        title: "Geen resultaten gevonden",
      },
    },
    lists: "Lijsten",
    modalTitle: "Taakdetails",
    note: "Notities (Maximaal 1000 tekens)",
    occurrences: {
      all: "Alle gebeurtenissen",
      occurrence: "Alleen deze keer",
    },
    openedTaskLabel: "<b>{{user}}</b> heeft een voltooide taak heropend:",
    openedTaskTitle: "Toegewezen taak opnieuw geopend",
    openMessageModal: {
      desc: "Als u het aan de taak gekoppelde bericht opent, wordt de takenlijst gesloten.",
      title: "Wil je het bericht openen?",
    },
    overdueTasksPresent: "Achterstallige taken: {{overdueTasksPresentCount}}",
    planned: "Wanneer",
    repeat: "Herhalen",
    repetitions: {
      NEVER: "Nooit",
      DAILY: "Dagelijks",
      WEEKLY: "Weekelijks",
      MONTHLY: "Maandelijks",
      YEARLY: "Jaarlijks",
    },
    showMyTasks: "Mijn taken",
    showAssignedTasks: "Toegewezen aan anderen",
    task: "Taak",
    taskFromNotification:
      "Wilt u de details van de aangemelde taak bekijken en de gegevens kwijtraken van de nieuwe taak die wordt samengesteld?",
    title: "Taken",
    types: {
      view_todo: "Te doen",
      view_all: "Alle",
      view_today: "Vandaag",
      view_next7: "De volgende 7 dagen",
      view_overdue: "Te laat",
      view_completed: "Afgerond",
    },
  },

  toast: {
    error: {
      alreadyPresent: "Waarschuwing, de bron bestaat al",
      avatarTooBig: "Waarschuwing, de avatar is te groot",
      compact: "Fout bij verkleinen van de map",
      connectionUnavailable: "Geen verbinding beschikbaar",
      delete: "Fout bij verwijderen",
      deleteDraft: "Fout bij het verwijderen van het concept",
      emailAddressNotValid: "E-mailadres is niet geldig",
      enqueued: "Instellingen worden bijgewerkt, probeer het later nog eens",
      fetchingAttachments: "Fout bij het ophalen van bijlages",
      filterActionsMissing: "Acties niet aanwezig",
      filterConditionsMissing: "Parameters ontbreken",
      filterNameMissing: "Regelnaam ontbreekt",
      folderCreation: "Fout bij het aanmaken van een nieuwe map",
      folderCreationCharNotValid:
        "Fout bij het maken/hernoemen van een map, karakter niet geldig ({{char}})",
      folderCreationNoName: "Fout bij het maken van de map, geef een geldige naam op",
      folderDelete: "Fout bij het verwijderen van de map",
      folderNotPresent: "Map niet aanwezig",
      folderRename: "Fout bij het hernoemen van de map, de gekozen naam komt al voor",
      folderSubscribe: "Er ging iets fout bij het inschrijven",
      generic: "Er ging iets mis",
      invalidDateRange: "Datumbereik is niet geldig",
      maxMembers: "Waarschuwing, maximaal aantal leden bereikt",
      maxSignatureSize: "Maximale grootte handtekening overschreden. Max {{maxSize}}",
      maxTemplateAttachmentsNumberReached:
        "Het limiet voor bijlagen voor deze standaardantwoord is breikt",
      maxTemplateSize: "Waarschuwing, deze standaa is te groot",
      maxTemplatesNumberReached:
        "Het limit voor standaardantwoorden, dat voor dit account is geconfigureerd, is bereikt",
      messageCopy: "Fout bij het kopiëren van berichten",
      messageMove: "Fout bij het verplaatsen van berichten",
      messageNotFound: "Bericht niet gevonden",
      messageRemove: "Fout bij het verwijderen van berichten",
      missingParameters: "Ontbrekende parameters",
      missingSettings: "Ontbrekende gebruikersinstellingen",
      notifications: "Fout bij het ontvangen van meldingen",
      notPermitted: "Bediening niet toegestaan",
      notValid: "Waarschuwing, ongeldige waarde",
      onlyOneHomeAddress: "Je kunt slechts één thuisadres invoeren",
      onlyOneWorkAddress: "Je kunt slechts één werkadres invoeren",
      save: "Fout bij het opslaan",
      saveAcl: "Fout bij het opslaan van map-machtigingen",
      saveEvent: "Er is een fout ontstaan, je hebt niet voldoende rechten voor deze kalender",
      saveZoomMeeting: "Kan de vergadering niet maken op het Zoom-platform",
      savingDraft: "Concept wordt opgeslagen",
      searchNotAvailable: "Zoeken is momenteel niet mogelijk",
      sendingMessage: "Fout bij het afleveren van berichten",
      serverDisconnection: "Server wordt bijgewerkt, probeer het later nog eens!",
      sessionExpired: "Sessie verlopen",
      smtpBlockedByAntispam: "Bericht is niet verzonden: geblokkeerd door de antispam filter",
      smtpBlockedByAntivirus: "Bericht is niet verzonden: geblokkeerd door de antivirus filter",
      smtpDisabled: "Bericht is niet verzonden: SMTP is voor dit account uitgeschkeld",
      smtpQuotaExceeded: "Bericht niet verzonden: verzonden bericht quota overschreden.",
      requestLimit: "Maximum aantal aanvragen overschreden, probeer het later nog eens.",
      requestError: "Er is een fout opgetreden, probeer het later nog eens.",
      updateFolders: "Er is een fout opgetreden bij het bijwerken van mappen",
      updateMessageEvent: "Fout bij het updaten van de status van het evenement",
      updatingParentFlags: "Fout bij het bijwerken van berichtenvlaggen",
    },
    info: {
      newVersionAvailable: {
        desc: "De handeling is veilig, je instellingen zullen niet worden gewijzigd.",
        title:
          "Nieuwe functies zijn beschikbaar, vernieuw deze pagina om je webmail bij te werken.",
      },
      serverReconnected: "Webmail weer online",
      sourceMail: "E-mailbron gekopieerd naar klembord",
    },
    progress: {
      newFolder: "Er worden nieuwe mappen aangemaakt...",
      operationInProgress: "In uitvoering...",
    },
    success: {
      compact: "Map met succes gecomprimeerd",
      copiedLink: "Link gekopieerd naar klembord",
      copiedMail: "Bericht succesvol gekopieerd",
      copiedMailAddress: "E-mailadres gekopieerd naar klembord",
      copiedText: "Tekst gekopieerd naar het klembord",
      createFolder: "Folder is gemaakt",
      delete: "Succesvol verwijderd",
      disabledOtp: "OTP succesvol uitgezet",
      enabledOtp: "OTP succesvol aangezet",
      movedMail: "Bericht is verplaatst",
      notificationEnabled: "Browsermeldingen succesvol ingeschakeld",
      otpDisabled: "OTP succesvol uitgezet",
      otpEnable: "OTP succesvol aangezet",
      save: "Succesvol opgeslagen",
      saveAcl: "Toestemmingen succesvol opgeslagen",
      saveDraft: "Map succesvol bijgewerkt",
      saveFolder: "Map is succesvol geüpdatet",
      sentMail: "Bericht succesvol verzonden",
      subscribeFolder: "Abonnement succesvol bijgewerkt",
      updateMessageEvent: "Afspraakstatus bijgewerkt",
    },
    warning: {
      forwardSet: "Tenminste één forwarder moet ingeschakeld zijn voor dit account",
      notificationNotSupported: "Waarschuwing, uw browser ondersteunt geen meldingen",
    },
  },

  toggles: {
    labels: {
      allDayEvent: "Hele dag",
      autoSaveContact:
        "Sla automatisch alle ontvangers op die niet in je adresboeken aanwezig zijn.",
      denyInvites: "Uitnodigingen voor afspraken voorkomen",
      enableAutorespopnd: "Autoresponder inschakelen",
      enableAutorespopndInterval: "Datumbereik inschakelen",
      enableBrowserNotification: "Browser notificaties inschakelen",
      enableDateSearch: "Zoeken op datum inschakelen",
      enableFullBody: "Zoeken op inhoud inschakelen",
      enableNotification: "Browser notificaties inschakelen",
      keepCopy: "Bewaar een lokale kopie van het bericht",
      showPriority: "Toon ontvangen berichtprioriteit",
      showThreads: "Toon berichten als conversatie",
      subscribeFolder: "Abonneer op map",
      tasksEmailNotifications: "E-mailmeldingen inschakelen",
    },
    hint: {
      enableFullBody:
        "De full body zoekfunctie is alleen mogelijk binnen een enkele map. Select een map om deze te gebruiken.",
    },
  },

  wizard: {
    layout: {
      desc: "Wijzig je Webmail door je eigen instellingen te kiezen.",
      title: "Jouw instellingen",
    },
    wizardData: {
      desc: "Pas uw profiel aan door een afbeelding toe te voegen en de ontbrekende gegevens aan te vullen",
      title: "Profiel voltooien",
    },
  },
};
