/*********************************************************************************************************
 * English Copyright (C) 2017-2019 by Qboxmail Srl
 *
 * All rights reserved. No part of this publication may be reproduced, distributed, or transmitted in any
 * form or by any means, including photocopying, recording, or other electronic or mechanical
 * methods, without the prior written permission of the publisher, except in the case of brief quotations
 * embodied in critical reviews and certain other noncommercial uses permitted by copyright law. For
 * permission requests, write to the publisher at the address below.
 *
 * Qboxmail Srl - IT02338120971
 * https://www.qboxmail.it - info@qboxmail.it
 *
 * Italiano Copyright (C) 2017-2019 by Qboxmail Srl
 *
 * Tutti i diritti riservati. Nessuna parte di questa pubblicazione può essere riprodotta, memorizzata in
 * sistemi di recupero o trasmessa in qualsiasi forma o attraverso qualsiasi mezzo elettronico, meccanico,
 * mediante fotocopiatura, registrazione o altro, senza l'autorizzazione del possessore del copyright salvo
 * nel caso di brevi citazioni a scopo critico o altri usi non commerciali consentiti dal copyright. Per le
 * richieste di autorizzazione, scrivere all'editore al seguente indirizzo.
 *
 * Qboxmail Srl - IT02338120971
 * https://www.qboxmail.it - info@qboxmail.it
 *********************************************************************************************************/

export default {
  addressbook: {
    contact: {
      oneSelectContacts: "Contato selecionado",
      oneSelectLists: "Lista selecionada",
      notSelected: "Selecionar um contato",
      sectionLabels: {
        address: "Address",
        company: "Empresa",
        email: "Email",
        info: "Informações",
        telephone: "Telefone",
        homeUrl: "Sítio Web pessoal",
        workUrl: "Sítio Web da empresa",
      },
      sections: {
        cell: "Celular",
        home: "Casa",
        homeFax: "Fax residencial",
        work: "Trabalho",
        workFax: "Fax profissional",
        title: "Função",
        company: "Empresa",
        note: "Notas",
        bday: "Aniversário",
      },
      selectContacts: "Contatos selecionados",
      selectLists: "Listas seleccionadas",
      selectedInfo: "Selecione um contato para ver os detalhes.",
    },
    contactsList: {
      emptyContacts: "Esta lista de contatos está vazia",
      emptyContactsInfo: "Adicionar um contato a lista de contatos",
      emptyLists: "Não existem listas",
      emptyListsInfo: "Adicionar uma nova lista",
      foundContacts: "Encontrado",
      notFound: "Nenhum contato encontrado",
      notFoundInfo:
        "A busca não produziu nenhum resultado, tente novamente usando diferentes critérios",
      totalContacts: "Contatos",
    },
    tabs: {
      contacts: "Contatos",
      lists: "Listas",
    },
    contextualMenuLabels: {
      address: "Endereço",
      birthday: "Data de nascimento",
      cancel: "Cancelar",
      cell: "Celular",
      delete: "Deletar",
      downloadVCard: "Baixar VCard",
      email: "Email",
      newContact: "Novo contato",
      createList: "Criar lista",
      newList: "Nova lista",
      note: "Nota",
      phone: "Telefone",
      shareVCard: "Compartilhar",
      showVCard: "Mostrar VCard",
      sendAsAttachment: "Enviar por email",
      sendMail: "Enviar email",
      url: "URL",
      info: "Info",
      title: "Função",
      company: "Empresa",
      home: "Casa",
      homeFax: "Fax residencial",
      work: "Trabalho",
      workFax: "Fax profissional",
      nickname: "Apelido",
      displayName: "Nome de exibição",
      companyName: "Nome",
      homeUrl: "Sítio Web pessoal",
      workUrl: "Sítio Web da empresa",
      team: "Equipa",
      merge: "Fundir",
    },
    deleteContactDsc:
      "Deletando o contato <code>{{contact}}</code> todas as informações relacionadas também serão deletadas.<br/><b>A operação não é reversível</b>.",
    deleteContactDscList:
      "Deletando o contato selecionado, todas as informações relacionadas também serão deletadas.<br/><b>A operação não é reversível</b>.",
    deleteContactTitle: "Deletar contato",

    deleteContactsDsc:
      "Deletando os contatos selecionados, todas as suas informações também serão deletadas.<br/><b>A operação não é reversível</b>.",
    deleteContactsTitle: "Deletar contatos",

    deleteListDsc:
      "Deletando a lista <code>{{contact}}</code> todas as informações relacionadas também serão deletadas.<br/><b>A operação não é reversível</b>.",
    deleteListTitle: "Deletar lista",

    editContactModal: {
      title: "Editar contato",
    },
    editListModal: {
      title: "Editar lista",
    },
    exportAddressBookModal: {
      desc: "Você está exportando a lista de contatos: <code>{{addressbookExport}}</code><br/>Por favor, escolha o formato para exportar todos os contatos presentes",
      title: "Exportar lista de contatos",
    },
    import: {
      contactsInvalid: "Não é valido:",
      contactsNr: "Total de contatos a serem importados:",
      contactsValid: "Válido:",
      desc: "Você está importando contatos para a lista de contatos: <code>{{addressbookImport}}</code><br/>Você pode importar contatos de outros aplicativos de email usando um VCard ou (<strong>.vcf</strong>) ou <strong>.ldif</strong> em formato de arquivo.\u000APor exemplo, você pode exportar contatos do Gmail ou Outlook e importá-los para o Qboxmail.\u000A A importação não vai substituir nenhum contato existente.",
      dropFiles: "Carregue ou arraste aqui os arquivos a serem importados",
      error: "Contato não pode ser importado",
      importing:
        "Estamos importando <b>{{contactsNumber}}</b> eventos no calendário: <code>{{addressbookImport}}</code>",
      loading: "Carregando...",
      success: "Importação concluída com sucesso!",
      title: "Importar contatos",
      uploadedFile: "Carregadas",
      uploadingFile: "Carregando",
    },
    list: {
      desc: "Ao criar uma lista de contactos, é possível enviar mensagens de correio eletrónico a muitas pessoas ao mesmo tempo. Podem ser adicionados até 150 membros, escolhendo-os entre os contactos do livro de endereços selecionado.</br></br><b>Nota</b>: Não é possível adicionar endereços de correio eletrónico que não constem do livro de endereços selecionado. Primeiro, adicione os contactos ao livro de endereços e, em seguida, adicione-os à lista.",
      members: "Membros da lista",
    },
    messages: {
      newContactAddressBookBody:
        "Você não pode adicionar um contato em <b>Contatos corporativos</b>.<br/>Selecione uma agenda pessoal ou compartilhe a lista de contatos",
      newContactAddressBookTitle: "Selecione a lista de contatos",
      resetListBody:
        "Os membros da lista são relacionados a lista de contatos selecionada. Esta mudança vai reconfigurar a lista de membros, deseja continuar?",
      resetListTitle: "Eliminação de membros",
    },
    modifyAddressBookModal: {
      desc: "",
      title: "Editar catálogo de endereços",
    },
    newAddressBookModal: {
      desc: "",
      title: "Adicionar catálogo de endereços",
    },
    newContactModal: {
      title: "Adicionar contato",
    },
    newListModal: {
      title: "Adicionar lista",
    },
    shareModal: {
      desc: "Você está compartilhando a lista de contatos: <code>{{addressbookShare}}</code><br/>Selecione os contatos com os quais você gostaria de compartilhar a lista de contatos e permiti-los gerenciar.",
      title: "Compartilhar lista de contatos",
    },
    sidebar: {
      allContacts: "Todos os contatos",
      deleteAddressbookDsc:
        "A eliminação do livro de endereços <code>{{{addressbook}}</code> elimina todos os contactos incluídos.<br/><b>A operação não é reversível</b>.",
      deleteAddressbookTitle: "Deletar lista de contatos",
      globalAddressbook: "Contatos corporativos",
      personalAddressbook: "Contatos pessoais",
      sharedAddressbooks: "Lista de contatos compartilhada",
      userAddressbooks: "Lista de contatos do usuário",
    },
    subscribeModal: {
      desc: "",
      noAddressbook: "Não há lista de contatos a ser subscrita",
      title: "Subscrever uma lista de contatos partilhado",
    },
  },

  app: {
    addressbook: "Lista de contatos",
    calendar: "Calendário",
    chat: "Conversas",
    meeting: "Reunião",
    mtm: "Mail Time Machine",
    of: "De",
    webmail: "Correio Eletrônico",
    modal: {
      updateAvailable: {
        title: "Atualização disponível",
        description:
          "Uma <b>nova versão do Webmail</b> está disponível.<br/>Clique para recarregar e atualizar, suas configurações permanecerão inalteradas.<br/><br/>O aplicativo será atualizado automaticamente entre:",
      },
    },
  },

  avatarEditorModal: {
    photoTitle: "Tirar foto",
    title: "Editar Avatar",
    zoom: "Zoom -/+",
  },

  banner: {
    info: {
      mailRetention: "As mensagens nesta pasta são excluídas automaticamente após 30 dias.",
    },
    warning: {
      labelCalendarUpdate:
        "Observe que se uma etiqueta for renomeada, ela não ficará mais visível nos eventos em que é usada.",
      labelMailUpdate:
        "Observe que se uma etiqueta for renomeada, ela não ficará mais visível nos emails em que é usada.",
      labelTaskUpdate:
        "Observe que se uma etiqueta for renomeada, ela não ficará mais visível nas atividades em que é usada.",
      mailRetention:
        "Atenção, as mensagens serão excluídas automaticamente de forma definitiva sem possibilidade de recuperação.<br><b>O cancelamento entrará em vigor em 24 horas.</b>",
    },
  },

  buttons: {
    accept: "Aceitar",
    add: "Adicionar",
    addAction: "Adicionar ação",
    addAddressbook: "Lista de contatos",
    addAsAttachment: "Anexar",
    addAttachments: "Adicionar Anexos",
    addCalendar: "Calendário",
    addField: "Adicionar campo",
    addHolidayCalendar: "Calendário de férias",
    addInline: "Adicionar à fila",
    addLabel: "Adicionar etiqueta",
    addParameter: "Adicionar parâmetro",
    addSignature: "Adiconar assinatura",
    addToList: "Adicionar à lista",
    allow: "Permitir",
    apply: "Aplicar",
    assign: "Atribuir",
    backAddressbook: "Fechar",
    backTo: "Voltar",
    cancel: "Cancelar",
    changeImage: "Mudar imagem",
    changePassword: "Mudar senha",
    checkFreeBusy: "Verificar disponibilidade",
    close: "Fechar",
    comeBackLater: "Retornar mais tarde",
    configure: "Configurar",
    confirm: "Confirmar",
    copied: "Copiado",
    copy: "Cópia",
    copyLink: "Copiar link",
    createFolder: "Nova pasta",
    decline: "Recusar",
    delete: "Deletar",
    deleteDraft: "Deletar rascunho",
    details: "Detalhes",
    disable: "Disable",
    disabled: "Desativar",
    disableOTP: "Desativar OTP",
    download: "Baixar",
    edit: "Editar",
    editLabel: "Editar etiqueta",
    editSignature: "Ediatr assinatura",
    empty: "Vazio",
    enable: "Habilitar",
    event: "Evento",
    export: "Exportar",
    generateNewPassword: "Gerar nova senha",
    generateRandomPassword: "Gerar senha aleatória",
    goToCalendar: "Ir para o calendário",
    goToEventDay: "Ir ao dia do evento",
    goToMail: "Retornar ao email",
    goToOldWebmail: "Ir para o webmail antigo",
    goToSettings: "Vá para a página de configurações",
    hide: "Esconder",
    ignore: "Ignorar",
    import: "Importar",
    insertHTML: "Inserir HTML",
    keep: "Guarda",
    label: "Etiqueta",
    later: "Mais tarde",
    learnMore: "Saber mais",
    leftRotate: "Girar 90 graus anti-horário",
    loadImage: "Carregar imagem",
    loading: "Carregando",
    logout: "Encerrar seção",
    makePhoto: "Tirar foto",
    markRead: "Ler",
    markSeen: "Marcar",
    markUnread: "Não lido",
    message: "Mensagem",
    modify: "Editar",
    new: "Novo",
    newContact: "Novo contato",
    newEvent: "Novo evento",
    newMessage: "Nova mensagem",
    newSignature: "Nova assinatura",
    newTask: "Nova tarefa",
    newWebmail: "Novo Webmail",
    next: "Próximo",
    noThanks: "Não, obrigado",
    occurrence: "Ocorrência",
    ok: "Ok",
    oldWebmail: "Webmail antigo",
    openMap: "Abrir no mapa",
    otherOptions: "Outras opções",
    override: "Sobrepor",
    participate: "Participe",
    postpone: "Adiar",
    reloadPage: "Recarregar página",
    removeImage: "Remover imagem",
    rename: "Renomear",
    reorder: "Reordenar",
    reorderEnd: "Fim do reordenamento",
    report: "Reportar",
    restore: "Peça para restaurar",
    retryImport: "Tentar novamente",
    save: "Salvar",
    saveDraft: "Salvar rascunho e fechar",
    saveNextAvailability: "Salvar disponibilidade sugerida",
    search: "Buscar",
    send: "Enviar",
    series: "Séries",
    setOtp: "Configurar OTP",
    share: "Compartilhar",
    show: "Mostrar",
    showAll: "Mostre tudo",
    showMore: "Mostre mais",
    showToDo: "Mostre a fazer",
    showUrlsAddressbook: "Mostrar URLS da lista de contatos",
    showUrlsCalendar: "Mostrar URLS do calendário",
    snooze: "Adiar",
    starred: "Estrela",
    subscribe: "Inscrever",
    subscribeAddressbook: "Subscrever lista de contatos",
    subscribeCalendar: "Subscrever calendário",
    tentative: "Talvez",
    understand: "Eu entendi",
    unlink: "Remover link",
    unsetOtp: "Desabilitar OTP",
    unsubscribe: "Cancelar inscrição",
    unsubscribeList: "Cancel subscription",
    update: "Atualizar",
    updateFilter: "Atualizar filtro",
    defaultImg: "Usar imagem padrão",
    viewMap: "Ver mapa",
  },

  buttonIcons: {
    activeSync: "Sincronizar usando Microsoft® Exchange ActiveSync",
    activeSyncNot: "Desativar Microsoft® Exchange ActiveSync",
    alignCenter: "Alinhar centro",
    alignLeft: "Alinhar à esquerda",
    alignRight: "Alinhar à direta",
    backgroundColor: "Cor de fundo",
    backTo: "Voltar",
    bold: "Negrito",
    cannedMsg: "Canned messages",
    close: "Fechar",
    confirm: "Confirmar",
    createTask: "Create Task",
    delete: "Deletar",
    download: "Baixar",
    downloadVCard: "Baixar VCard",
    edit: "Editar",
    emoji: "Emoji",
    forward: "Encaminhar",
    fullscreen: "Tela cheia",
    fullscreenNot: "Modo janela",
    imageAdd: "Adicionar imagem",
    indent: "Aumentar recuo",
    insertHTML: "Inserir HTML",
    italic: "Itálico",
    link: "Inserir link",
    maintenance: "Compacta",
    maxmized: "Aumentar",
    minimized: "Reduzir",
    more: "Mais",
    moveDown: "Mover para baixo",
    moveUp: "Mover para cima",
    next: "Próximo",
    orderList: "Ordenar lista",
    outdent: "Diminuir recuo",
    pin: "Marcar",
    previous: "Anterior",
    print: "Imprimir",
    quote: "Citação",
    removeFormatting: "Remover formatação",
    removeQuote: "Remover citação",
    reply: "Responder",
    replyAll: "Responder a todos",
    saveDraft: "Salvar rascunho",
    sendDebug: "Mendar mensagem que não pode ser visualizada",
    sendMail: "Enviar email",
    sendByEmail: "Enviar por email",
    share: "Compartilhar",
    showSidebar: "Mostrar/Esconder barra lateral",
    showSourceCode: "Mostrar código fonte",
    showVCard: "Mostrar VCard",
    spam: "Marcar como Spam",
    spamNot: "Marcar como não sendo Spam",
    startChat: "Começar conversa",
    startMeeting: "Começar reunião",
    strike: "Atingir",
    subscribe: "Se inscrever",
    textColor: "Cor do texto",
    thanks: "Obrigado",
    underline: "Sublinhar",
    understand: "Eu entendi",
    undo: "Desfazer",
    unlink: "Remover link",
    unorderList: "Desordenar lista",
    unSubscribe: "Cancelar inscrição",
  },

  calendar: {
    alarmDurations: {
      after: "depois",
      before: "antes",
      day: "dias",
      hour: "horas",
      minute: "minutos",
      second: "segundos",
      week: "semanas",
    },
    deleteEvent: "Eliminar evento",
    deleteEventDsc: "Continuar com a eliminação do evento selecionado?",
    deleteSeries: "Eliminar séries",
    deleteSeriesDsc: "Continuar com a eliminação da série selecionada?",
    event: {
      alarmsNotPresent: "Sem alertas",
      deleteEventOccurrenceTitle: "Deletar evento ou série?",
      deleteEventOccurrenceDesc:
        "O evento que você quer deletar tem várias ocorrências. Deletar esta ocorrência deixara as outras inalteradas",
      eventNotes: "Notas do evento",
      eventAttendees: "Participantes do evento",
      fromDay: "De",
      labelsNotPresent: "Sem etiqueta",
      locationContextualMenuLabels: {
        zoomLabel: "Zoom",
        zoomHint: "Reunião na Web",
        personalMeetingLabel: "Sala de reuniões pessoal",
        personalMeetingHint: "Reunião na Web",
        locationLabel: "Reunião presencial",
        locationHint: "Definir um endereço ou local",
        textLabel: "Personalizado",
        textHint: "Inserir um texto personalizado",
      },
      locationSelector: "Selecione o local do evento",
      locationZoomNoMeeting:
        "Depois que o evento for salvo, o link da reunião do Zoom estará presente aqui",
      maxAttachmentsNumberTitle: "Muitos anexos!",
      maxAttachmentsNumberDsc:
        "Você pode inserir até 4 anexos. Caso precise anexar mais de 4 arquivos, sugerimos que crie uma pasta compactada.",
      maxLabelsNumberTitle: "Excesso de etiquetas!",
      maxLabelsNumberDsc:
        "Você atingiu o número máximo de etiquetas que podem ser associadas a um evento. Para adicionar novas etiquetas você deve primeiro remover uma das já existentes.",
      noTitle: "Sem título",
      notIncludedInFreeBusy:
        "Este calendário não está incluído no Free/Busy. Isto implica que o utilizador e as pessoas que convidar serão mostrados como <b>disponíveis</b> durante os eventos criados neste calendário.",
      organizerTitle: "Criado por",
      pendingMsg: "Evento esperando confirmação",
      permissionDenied:
        "Incapaz de visualizar os detalhes do evento selecionado, você pode não ter as permissões necessárias.",
      repeatEvent: "Esse evento faz parte dos eventos recorrentes",
      saveEventOccurrenceTitle: "Mostrar eventos ou eventos recorrentes?",
      saveEventOccurrenceDesc:
        "O evento que você quer visualizar ou editar tem várias ocorrências. Editar uma única ocorrência deixará as demais inalteradas",
      setAlert: "Definir alerta",
      toDay: "Para",
    },
    eventRepetition: {
      WeekDayNumberInMonth_1: "Primeiro",
      WeekDayNumberInMonth_2: "Segundo",
      WeekDayNumberInMonth_3: "Terceiro",
      WeekDayNumberInMonth_4: "Quarto",
      WeekDayNumberInMonth_5: "Quinto",
      never: "Nunca",
      after: "Depois;recorrência",
      inDate: "Na data",
      end: "Fim da repetição",
    },
    filterView: {
      listmonth: "Agenda",
      day: "Dia",
      month: "Mês",
      week: "Semana",
      workWeek: "Semana de trabalho",
      year: "Ano",
    },
    import: {
      contactsInvalid: "Não válido:",
      contactsNr: "Total de eventos a serem importados:",
      contactsValid: "Válido:",
      dropFiles: "Carregue ou arraste aqui os arquivos a serem importados",
      error: "Evento não pode ser importado",
      importing:
        "Estamos importando <b>{{eventsNumber}}</b> eventos no calendário: <code>{{calendarImport}}</code>",
      info: "Você está importando eventos no calendário: <code>{{calendarImport}}</code><br/>Você pode importar eventos de outros aplicativos usando um arquivo de formato ICS. Por exemplo, você pode exportar eventos do Gmail ou Outlook em formato ICS e importá-los aqui..<br/><b>A importação não substituirá nenhum dos eventos existentes</b>.",
      loading: "Carregando...",
      success: "Todos os eventos foram importados com sucesso!",
      title: "Importar eventos",
      uploadedFile: "Carregadas",
      uploadingFile: "Carregando",
    },
    modifyCalendarModal: {
      desc: "",
      title: "Editar calendário",
    },
    newCalendarModal: {
      desc: "",
      title: "Adicionar calendário",
      freeBusyInfo:
        "Se o calendário não estiver incluído em <b>Free/Busy</b>, o utilizador e as pessoas que convidar serão mostrados como <b>disponíveis</b> durante os eventos criados neste calendário.",
    },
    newEvent: {
      attachmentsList: {
        headerItem: "Anexos",
        placeholderList: " ",
      },
      desc: "",
      dropFiles: "Carregue ou arraste aqui arquivos para anexar<br>(máximo 4 anexos, 3 MB cada)",
      freeBusy: {
        legend: {
          event: "Eventos confidenciais",
          busy: "Ocupado",
          waiting: "Esperando",
          availability: "Próxima disponibilidade",
        },
      },
      hideDetails: "Esconder detalhes",
      participantsList: {
        headerItem: "Participantes",
        answeredHeaderItem: "Respondido",
        notAnsweredHeaderItem: "Esperando resposta",
        placeholderList: " ",
      },
      showDetails: "Mostrar detalhes",
      tabAttachments: "Anexos",
      tabDetails: "Detalhes",
      tabParticipants: "Participantes",
      tabSeries: "Repetições",
      tabSettings: "Configurações",
      title: "Criar evento",
      titleEdit: {
        event: "Evento",
        series: "Séries",
      },
      titleFreebusy: "Disponibilidade dos participantes",
    },
    nextAvailability: "Próxima disponibilidade",
    searchEvents: {
      notFound: "Nenhum evento encontrado",
      notFoundInfo:
        "A busca não produziu nenhum resultado, tente novamente usando diferentes critérios",
    },
    shareModal: {
      desc: "Você está compartilhando o calendário: <code>{{calendarShare}}</code><br/>Selecione os contatos com os quais você deseja compartilhar o calendário e permita-os gerenciar.",
      title: "Compartilhar calendário",
    },
    sidebar: {
      labels: "Etiquetas",
      personalCalendar: "Calendário pessoal",
      sharedCalendars: "Calendários compartilhados",
      userCalendars: "Calendários do usuário",
      deleteCalendarDsc:
        "Ao eliminar o calendário <code>{{calendar}}</code> todos os eventos incluídos serão eliminados.<br/><b>A operação não é reversível</b>.",
      deleteCalendarTitle: "Deletar calendário",
    },
    subscribeModal: {
      desc: "",
      noCalendar: "Não há calendários para se inscrever",
      title: "Subscrever um calendário partilhado",
    },
    today: "Hoje",
  },

  circularLoopBar: {
    uploading: "Carregando",
  },

  comingSoon: "Desenvolvimento em andamento...",

  contactImport: {
    title: "Buscando contatos",
    desc: "Estamos importanto seus contatos antigos. Isso pode levar algum tempo, por favor espere.",
  },

  datasets: {
    actionsFlags: {
      "\\\\Answered": "Respondido",
      "\\\\Deleted": "Deletado",
      "\\\\Draft": "Rascunho",
      "\\\\Flagged": "Marcado",
      "\\\\Seen": "Ler",
    },
    antispamFilterTypes: {
      whitelist_from: "Permitir de",
      whitelist_to: "Permitir para",
    },
    calendarMinutesInterval: {
      15: "15 minutos",
      30: "30 minutos",
      60: "60 minutos",
    },
    calendarNewEventFreeBusy: {
      busy: "Ocupado",
      free: "Disponível",
      outofoffice: "Fora do escritório",
      temporary: "Temporário",
    },
    calendarNewEventPartecipation: {
      ACCEPTED: "Aceitar",
      DECLINED: "Rejeitar",
      TENTATIVE: "Talvez",
    },
    calendarNewEventParticipationRoles: {
      CHAIR: "Chairman",
      "REQ-PARTICIPANT": "Pedidos",
      "OPT-PARTICIPANT": "Não pedidos",
      "NON-PARTICIPANT": "Por motivos de informação",
    },
    calendarNewEventPriority: {
      0: "Nenhum",
      1: "Alto",
      5: "Médio",
      9: "Baixo",
    },
    calendarNewEventTypes: {
      public: "Público",
      confidential: "Confidencial",
      private: "Privado",
    },
    calendarStartWeekDay: {
      saturday: "Sábado",
      sunday: "Domingo",
      monday: "Segunda-feira",
    },
    calendarView: {
      year: "Ano",
      month: "Mês",
      week: "Semana",
      workWeek: "Semana de trabalho",
      day: "Dia",
      listmonth: "Lista",
    },
    calendarEventFilterBy: {
      allEvents: "Todos",
      nextEvents: "Todos os próximos eventos",
    },
    calendarEventSearchIn: {
      title: "Título/Etiqueta/Local",
      all: "Conteúdo completo",
    },
    cancelSendTimer: {
      0: "Desativado",
      5000: "5 segundos",
      10000: "10 segundos",
      20000: "20 segundos",
      30000: "30 segundos",
    },
    contactNameFormat: {
      firstName: "Nome, Sobrenome",
      lastName: "Sobrenome, Nome",
    },
    contactsOrder: {
      firstName: "Nome",
      lastName: "Sobrenome",
    },
    countries: {
      AD: "Andorra",
      AE: "United Arab Emirates",
      AG: "Antigua & Barbuda",
      AI: "Anguilla",
      AL: "Albania",
      AM: "Armenia",
      AO: "Angola",
      AR: "Argentina",
      AS: "American Samoa",
      AT: "Austria",
      AU: "Australia",
      AW: "Aruba",
      AX: "Åland Islands",
      AZ: "Azerbaijan",
      BA: "Bosnia and Herzegovina",
      BB: "Barbados",
      BD: "Bangladesh",
      BE: "Belgium",
      BF: "Burkina Faso",
      BG: "Bulgaria",
      BH: "Bahrain",
      BI: "Burundi",
      BJ: "Bénin",
      BL: "Saint Barthélemy",
      BM: "Bermuda",
      BN: "Brunei",
      BO: "Bolivia",
      BQ: "Bonaire, Sint Eustatius and Saba",
      BR: "Brasil",
      BS: "Bahamas",
      BW: "Botswana",
      BY: "Belarus",
      BZ: "Belize",
      CA: "Canada",
      CC: "Cocos (Keeling) Islands",
      CD: "Democratic Republic of the Congo",
      CF: "Central African Republic",
      CG: "Republic of the Congo",
      CH: "Switzerland",
      CL: "Chile",
      CM: "Cameroun",
      CN: "China",
      CO: "Colombia",
      CR: "Costa Rica",
      CU: "Cuba",
      CV: "Cabo Verde",
      CW: "Curaçao",
      CX: "Christmas Island",
      CY: "Cyprus",
      CZ: "Czech Republic",
      DE: "Germany",
      DK: "Denmark",
      DM: "Dominica",
      DO: "Dominican Republic",
      EC: "Ecuador",
      EE: "Estonia",
      ES: "Spain",
      ET: "Ethiopia",
      FI: "Finland",
      FO: "Faroe Islands",
      FR: "France",
      GA: "Gabon",
      GB: "United Kingdom",
      GD: "Grenada",
      GF: "French Guiana",
      GG: "Guernsey",
      GI: "Gibraltar",
      GL: "Greenland",
      GP: "Guadeloupe",
      GQ: "Equatorial Guinea",
      GR: "Greece",
      GT: "Guatemala",
      GU: "Guam",
      GY: "Guyana",
      HN: "Honduras",
      HR: "Croatia",
      HT: "Haiti",
      HU: "Hungary",
      IE: "Ireland",
      IM: "Isle of Man",
      IS: "Island",
      IT: "Italy",
      JE: "Jersey",
      JM: "Jamaica",
      JP: "Japan",
      KE: "Kenya",
      KR: "South Korea",
      LI: "Lichtenstein",
      LS: "Lesotho",
      LT: "Lithuania",
      LU: "Luxembourg",
      LV: "Latvia",
      MC: "Monaco",
      MD: "Moldova",
      ME: "Montenegro",
      MG: "Madagascar",
      MK: "North Macedonia",
      MQ: "Martinique",
      MT: "Malta",
      MW: "Malawi",
      MX: "Mexico",
      MZ: "Mozambique",
      NA: "Namibia",
      NI: "Nicaragua",
      NL: "Netherlands",
      NO: "Norway",
      NZ: "New Zealand",
      PA: "Panama",
      PE: "Perú",
      PH: "Philippines",
      PL: "Poland",
      PT: "Portugal",
      PY: "Paraguay",
      RE: "Réunion",
      RO: "Romania",
      RS: "Serbia",
      RU: "Russia",
      RW: "Rwanda",
      SE: "Sweden",
      SG: "Singapore",
      SH: "Saint Helena",
      SI: "Slovenia",
      SJ: "Svalbard & Jan Mayen",
      SK: "Slovakia",
      SM: "San Marino",
      SO: "Somalia",
      SS: "South Sudan",
      SV: "El Salvador",
      TG: "Togo",
      TO: "Tonga",
      TR: "Turkey",
      TZ: "Tanzania",
      UA: "Ukraine",
      UG: "Uganda",
      US: "United States of America",
      UY: "Uruguay",
      VA: "Città del Vaticano",
      VE: "Venezuela",
      VN: "Vietnam",
      XK: "Kosovo",
      YT: "Mayotte",
      ZA: "South Africa",
      ZM: "Zambia",
      ZW: "Zimbabwe",
    },
    deliveryNotifications: {
      always: "Sempre pedir confirmação de recebimento",
      never: "Nunca pedir confirmação de recebimento",
    },
    markReadAfter: {
      manually: "Manualmente",
      onOpen: "Quando a mensagem está aberta",
      5000: "Após 5 segundos",
      10000: "Após 10 segundos",
      30000: "Após 30 segundos",
    },
    eventAlarmPostponeTime: {
      60: "por 1 minuto",
      300: "por 5 minutos",
      900: "por 15 minutos",
      1800: "por 30 minutos",
      3600: "por 1 hora",
      7200: "por 2 horas",
      86400: "por 1 dia",
      604800: "por 1 semana",
    },

    eventTimeIntervals: {
      5: "5 minutos",
      10: "10 minutos",
      15: "15 minutos",
      20: "20 minutos",
      30: "30 minutos",
    },

    calendarTaskStatus: {
      "NEEDS-ACTION": "Necessita ação",
      COMPLETED: "Finalizado",
      PROCESS: "Em andamento",
      CANCELLED: "Cancelado",
    },

    feedbackAreas: {
      addressbookSidebar: "Listagem de listas de contatos",
      contactList: "Lista de contatos",
      contactView: "Exibição do contato",
      mailSearch: "Procurar mensagem",
      mailSidebar: "Lista de pastas",
      messageList: "Lista de mensagens",
      messageView: "Exibição da mensagem",
      newMessage: "Nova composição de mensagens",
      other: "Mais",
      settings: "Configurações",
    },
    filterMail: {
      all: "Todos",
      byDate: "Data",
      byFrom: "De",
      bySize: "Tamanho",
      bySubject: "Assunto",
      flagged: "Marcado",
      filter: "Filtros ativos",
      orderBy: "Ordenar por",
      seen: "Lido",
      unseen: "Não lido",
    },
    filtersActions: {
      discard: "Remover",
      addflag: "Marcar mensagem como",
      setkeyword: "Adicionar etiqueta",
      fileinto: "Mover mensagem para",
      fileinto_copy: "Copiar mensagem para",
      keep: "Guardar mensagem",
      redirect: "Redirecionar mensagem para",
      redirect_copy: "Mandar cópia para",
      reject: "Rejeitar com a seguinte mensagem",
      stop: "Parar filtragem",
    },
    filtersDateOperators: {
      gt: "Depois",
      is: "é igual a",
      lt: "Antes de",
      notis: "não é igual a",
    },
    filtersEnvelopeSubtypes: {From: "De", To: "Para"},
    filtersDateSubTypes: {
      date: "Data",
      time: "Hora",
      weekday: "Dia da semana",
    },
    filtersDateWeekdays: {
      monday: "Segunda-feira",
      tuesday: "Terça-feira",
      wednesday: "Quarta-feira",
      thursday: "Quinta-feira",
      friday: "Sexta-feira",
      saturday: "Sábado",
      sunday: "Domingo",
    },
    filtersRules: {
      Bcc: "Cco",
      body: "Corpo",
      Cc: "Cc",
      currentdate: "Data de entrada",
      envelope: "Mensagem",
      From: "Origem",
      other: "Outros responsáveis",
      size: "Tamanho",
      Subject: "Assunto",
      To: "Destino",
    },
    filtersSizeMUnits: {B: "Bytes", K: "Kilobytes", M: "Megabytes"},
    filtersSizeOperators: {over: "é mais que", under: "é menos que"},
    filtersStringOperators: {
      contains: "contém",
      exists: "existe",
      is: "é igual a",
      notcontains: "não contém",
      notexists: "não existe",
      notis: "não é igual a",
    },
    fontSize: {
      extraSmall: "Muito pequeno",
      huge: "Enorme",
      large: "Ampla",
      medium: "Médio",
      normal: "Normal",
      small: "Pequeno",
    },
    languages: {
      de: "Alemão",
      en: "Inglês",
      fr: "Francês",
      gr: "Grego",
      it: "Italiano",
      nl: "Holandês",
      sv: "Suéco",
      es: "Espanhol",
      pt: "Português",
    },
    mailRetention: {
      0: "Nunca",
      30: "mais de 1 mês",
      90: "mais de 3 meses",
      180: "mais de 6 meses",
      365: "mais de 1 ano",
      730: "mais de 2 anos",
      1095: "mais de 3 anos",
      1460: "mais de 4 anos",
      1825: "mais de 5 anos",
    },
    matchTypes: {
      allof: "Satisfaz todos os parâmetros",
      anyof: "Satisfaz pelo menos um parâmetro",
    },
    newAllDayEventAlert: {
      never: "Nunca",
      eventDate: "Data do evento",
      "-PT17H": "Um dia antes, às 9h",
      "-P6DT17H": "Uma semana antes, às 9h",
    },
    newEventAlert: {
      never: "Nunca",
      eventHour: "Na hora de início do evento",
      //P[n]Y[n]M[n]DT[n]H[n]M[n]S
      "-PT5M": "5 minutos antes",
      "-PT10M": "10 minutos antes",
      "-PT15M": "15 minutos antes",
      "-PT30M": "30 minutos antes",
      "-PT1H": "1 hora antes",
      "-PT2H": "2 horas antes",
      "-PT12H": "12 horas antes",
      "-P1D": "1 dia antes",
      "-P7D": "1 semana antes",
    },
    newEventRepeatDayWeek: {
      MO: "Segunda-feira",
      TU: "Terça-feira",
      WE: "Quarta-feira",
      TH: "Quinta-feira",
      FR: "Sexta-feira",
      SA: "Sábado",
      SU: "Domingo",
    },
    newEventRepeatFrequency: {
      NEVER: "Nunca",
      DAILY: "Diariamente",
      WEEKLY: "Semanalmente",
      MONTHLY: "Mensalmente",
      YEARLY: "Anualmente",
    },
    newEventRepeatMonths: {
      1: "Janeiro",
      2: "Fevereiro",
      3: "Março",
      4: "Abril",
      5: "Maio",
      6: "Junho",
      7: "Julho",
      8: "Agosto",
      9: "Setembro",
      10: "Outubro",
      11: "Novembro",
      12: "Dezembro",
    },
    orderSelector: {
      byLastname: "Sobrenome",
      byMail: "Email",
      byName: "Nome",
      byOrg: "Companhia",
      orderBy: "Ordenar por",
      showOnlyLists: "Mostrar apenas listas",
    },
    readConfirmations: {
      always: "Sempre pedir confirmação de leitura",
      never: "Nunca pedir confirmação de leitura",
    },
    readingConfirmation: {
      always: "Sempre",
      ask: "Sempre pedir",
      never: "Nunca",
    },
    selectMail: {
      all: "Tudo",
      cancel: "Cancelar",
      modify: "Editar",
      none: "Deselecionar",
      select: "Selecionar",
    },
    shareOptionsCalendar: {
      None: "Nenhum",
      DAndTViewer: "Ver data e hora",
      Viewer: "Ver tudo",
      Responder: "Responder para",
      Modifier: "Modificar",
    },
    showImages: {
      always: "Sempre",
      contacts: "Contatos e de confiança",
      never: "Nunca",
    },
    themes: {
      dark: "Escuro",
      light: "Claro",
    },
    timeFormats: {
      "12h": "12h",
      "24h": "24h",
    },
    viewMode: {
      label: {
        viewColumns: "Colunas",
        viewHalf: "Visualização",
        viewFull: "Lista",
      },
      desc: {
        viewColumns: "Mostrar layout de três colunas com painel de leitura à direita da tela.",
        viewHalf: "Mostrar layout de duas colunas com painel de leitura na parte inferior da tela.",
        viewFull:
          "Mostrar layout de duas colunas apenas com lista de mensagens. O painel de leitura mostrará a página inteira ao clicar.",
      },
    },
  },

  dropdownMenu: {
    activesync: "Microsoft® ActiveSync",
    delete: "Deletar",
    download: "Baixar",
    edit: "Editar",
    exportContacts: "Exportar contatos",
    feedback: "Feedback",
    importContacts: "Importar contatos",
    importEvents: "Importar eventos",
    news: "News & Updates",
    remove: "Remover",
    rename: "Renomear",
    share: "Compartilhar",
    shortcuts: "Atalhos",
    syncNo: "Não sincronizar",
    syncYes: "Sincronizar",
    unsubscribe: "Cancelar inscrição",
  },

  dropdownUser: {
    feedback: "Feedback",
    logout: "Terminar sessão",
    settings: "Configurações",
  },

  errors: {
    emailDomainAlreadyPresent: "Endereço de email ou domínio já presente",
    emptyField: "Campo em branco",
    invalidEmail: "Email inválido",
    invalidEmailDomain: "Endereço de email ou domínio inválido",
    invalidPassword: "Senha inválida",
    invalidPasswordFormat: "Formato inválido, inserir ao menos 8 caracteres alfanuméricos",
    invalidValue: "Valor inválido",
    mandatory: "Campo obrigatório",
    notAllowedCharacter: "Caracter inválido",
    notChanged: "Campo inalterado",
    permissionDenied: "Permissão negada",
    tooLong: "Campo muito longo",
  },

  feedback: {
    disclaimer:
      "Envie um feedback e nos ajude a melhorar o serviço.<br/>Para qualquer dúvida ou problema relacionado ao uso do webmail, entre em contato com o suporte.",
    labels: {
      feedbackAreas: "Em qual área você deseja deixar sua sugestão?",
      note: "Deixe uma mensagem (opcional)",
    },
    msgError: {
      title: "Sua sugestão não pode ser enviada",
      desc: "Por favor, tente novamente mais tarde, é importante para nós sabermos o que você acha do nosso webmail. Suas críticas e sugestões nos ajudarão a criar uma experiência melhor para todos os nossos usuários.",
    },
    msgSuccess: {
      title: "Muito obrigado pela sua resposta!",
      desc: "Nós agradecemos o tempo que você investiu nos ajudando a melhorar nosso correio eletrônico. Suas críticas e sugestões nos ajudarão a criar uma experiência melhor para todos os nossos usuários.",
    },
    privacy:
      "As informações coletadas serão processadas confidencialmente e levando em consideração toda a legislação de confidencialidade vigente.",
    title: "Críticas e sugestões",
  },

  inputs: {
    labels: {
      addAddress: "Adicionar endereço",
      addContactToAddressbook: "Adicionar contacto ao livro de endereços",
      addDomain: "Adicionar endereço ou domínio",
      addLabel: "Nome da etiqueta",
      addMembers: "Adicionar membros",
      addParticipant: "Adicionar participantes",
      addressbookName: "Lista de contatos",
      addUser: "Adicionar usuário",
      alert2: "Segundo Alerta",
      alert: "Alerta",
      assignTask: "Atribuir tarefa a",
      at: "Às",
      calendar: "Calendário",
      calendarBusinessDayEndHour: "Dia de trabalho final",
      calendarBusinessDayStartHour: "Dia de trabalho inicial",
      calendarColor: "Cor do calendário",
      calendarMinutesInterval: "Tempo de intervalo do calendário",
      calendarName: "Nome do calendário",
      calendarView: "Visualização padrão",
      company: "Empresa",
      companyName: "Nome",
      confidentialEvents: "Eventos confidenciais",
      confirmNewPassword: "Confirmar senha",
      contactNameFormat: "Ver por",
      contactsOrder: "Ordenar os contactos por",
      contains: "Contém",
      country: "País",
      dateFormat: "Formato da data",
      dateInterval: "Intervalo de datas",
      defaultAddressbook: "Lista de contatos padrão",
      defaultCalendar: "Calendário padrão",
      displayName: "Nome do dispositivo",
      email: "Email",
      encryptionMethod: "Encryption method",
      endDate: "Data final",
      event: "Evento",
      eventDailyRepetition: "Todos;os dias",
      eventDailyWorkdayRepetition: "Cada dia da semana",
      eventMonthlyLastDayRepetition: "Último dia do mês, todos;os meses",
      eventMonthlyLastWeekDayRepetition: "Último {{WeekDay}}, todos;os meses",
      eventMonthlyRepetition: "No {{DayNumber}}, todo;mês",
      eventMonthlyWeekDayRepetition: "No {{WeekDayNumber}}, todo;mês",
      eventPartecipation: "Status de participação",
      eventPriority: "Prioridade do evento",
      eventType: "Tipo de evento",
      eventWeeklyRepetition: "Todo;mês, no:",
      eventYearlyLastDayRepetition: "Último dia de {{Month}}, todo;ano",
      eventYearlyLastWeekDayRepetition: "Último {{WeekDay}} do {{Month}}, todos;os anos",
      eventYearlyRepetition: "Em {{DayNumber}} de {{Month}}, todos;os anos",
      eventYearlyWeekDayRepetition: "No {{WeekDayNumber}} de {{Month}}, todos;os anos",
      exportAsLdiff: "Eportar em formato LDIF",
      exportAsVcard: "Exportar em formato VCard",
      faxHome: "Fax residencial",
      faxWork: "Fax profissional",
      filter: "Filtrar por",
      filterName: "Nome da regra",
      firstName: "Nome",
      folderName: "Nome da pasta",
      freeBusy: "Mostrar como",
      from: "De",
      fromDate: "A partir da data",
      home: "Casa",
      hour: "Hora",
      includeFreeBusy: "Incluir em Free/Busy",
      label: "Etiqueta",
      labelColor: "Cor de etiqueta",
      language: "Idioma",
      lastName: "Sobrenome",
      linkText: "Texto exibidot",
      linkURL: "Endereço da Web (URL)",
      listName: "Lista de nomes",
      location: "Localização",
      loginAddressbook: "Lista de contatos inicial",
      mailAccount: "Conta",
      mailRetention: "Excluir mensagens da pasta",
      mailRetentionDefault: "A exclusão da mensagem é definida automaticamente para 30 dias",
      mailRetentionDiscalimer:
        "Atenção, as mensagens serão excluídas automaticamente de forma definitiva sem possibilidade de recuperação. O cancelamento será operacional dentro de 24 horas.",
      mailRetentionHint:
        "Especifique o intervalo de tempo, após o recebimento da mensagem, para prosseguir com a exclusão automática.",
      markReadAfter: "Marcar mensagem como lida",
      mobile: "Celular",
      newAddressBook: "Nova agenda",
      newAddressBookMobile: "Nova agenda",
      newAllDayEventAlert: "Novo alerta de eventos de dia todo",
      newBcc: "Adicionar destinatários Cco",
      newCalendar: "Novo calendário",
      newEventAlert: "Novo alerta de eventos",
      newForward: "Adicionar destinatário à lista",
      newPassword: "Nova senha",
      nickname: "Apelido",
      object: "Assunto",
      oldPassword: "Senha atual",
      parentFolder: "Caminho",
      password: "Password",
      personalMeetingRoom: "Ligação à sala de reuniões pessoal",
      phone: "Telefone",
      port: "Port",
      portFor: "Port for",
      priority: "Prioridade",
      privateEvents: "Eventos privados",
      publicEvents: "Eventos públicos",
      readingConfirmation: "Enviar confirmação de leitura",
      recoveryEmail: "Email de recuperação",
      renameAddressbook: "Renomear lista de contatos",
      repeatEvery: "Repetir",
      reportBugNote: "Descrição do problema",
      reportBugPhoneNumber: "Número do telefone",
      searchAddressbookToSubscribe:
        "Procure um usuário para ver seus catálogos de endereços partilhados",
      searchCalendarToSubscribe: "Pesquise um usuário para ver seus calendários partilhados",
      searchIn: "Buscar em",
      selectCalendar: "Selecionar calendário",
      selectIdentity: "Selecionar identidade",
      selectList: "Selecionar lista",
      selectSnapshotDate: "Escolha a data",
      serverName: "Nome do servidor",
      shareCalendarCalDAVURL: "CalDAV URL",
      shareCalendarWebDavICSURL: "WebDAV ICS URL",
      shareCalendarWebDavXMLURL: "WebDAV XML URL",
      shareToAddressbook: "Com quem você deseja compartilhar a lista de contatos?",
      shareToCalendar: "Com quem você deseja compartilhar o calendário?",
      shareToFolder: "Com quem você deseja compartilhar a pasta?",
      showImages: "Mostrar imagem",
      signatureName: "Nome de exibição",
      signatureText: "Texto de assinatura",
      startDate: "Data de início",
      team: "Equipe",
      templateName: "Nome",
      templateSubject: "Sujeito",
      templateText: "Corpo da mensagem",
      theme: "Tema",
      timeFormat: "Formato de hora",
      timezone: "Fuso horário",
      title: "Título",
      to: "Para",
      untilDate: "Até a data",
      username: "Username",
      weekStart: "Primeiro dia da semana",
      work: "Trabalho",
    },
    placeholder: {
      addressbookName: "Nome da lista de contatos",
      birthday: "Data de nascimento",
      city: "Cidade",
      company: "Empresa",
      country: "País",
      customText: "Insira um texto personalizado",
      email: "Email",
      endDate: "Data final",
      firstName: "Nome",
      lastName: "Sobrenome",
      members: "Membros",
      newFolderName: "Nome da nova pasta",
      newNameAddressbook: "Nome da nova lista de contatos",
      newPassword: "Pelos menos 8 caracteres alfanuméricos",
      note: "Nota",
      password: "Sua senha",
      phone: "Telefone",
      place: "Digite uma rua ou lugar",
      postCode: "Código postal",
      region: "Região",
      role: "Função",
      search: "Buscar",
      searchActivity: "Buscar atividade",
      searchEvent: "Buscar evento",
      searchUser: "Pesquisar usuário em seu domínio",
      select: "Selecionar",
      snooze: "Adiar alerta",
      startDate: "Start date",
      street: "Rua",
    },
    hint: {
      cancelSendMessage:
        "Selecione o tempo disponível para retirar uma mensagem durante o envio, se decidir que não deseja enviar o e-mail.",
      newForward: "Você pode adicionar até o máximo de {{max}} endereço de encaminhamento.",
      newBcc: "Você pode adicionar até {{max}} destinatários com Cco.",
      mailRetention:
        "Especifique o intervalo de tempo, após o recebimento da mensagem, para prosseguir com a exclusão automática",
      passwordScore: {
        check: "Força da senha",
        poor: "Senha muito ruim",
        easy: "Senha muito fácil",
        weak: "Senha muito fraca",
        strong: "Senha forte",
        great: "Senha ótima!",
      },
    },
  },

  labels: {
    attendees: "Participantes",
    calendarAdvancedSearch: "Onde você quer buscar?",
    clearAdvancedFilters: "Limpar filtros",
    clearFields: "Limpar campos",
    default: "Padrão",
    forDomain: "On domain",
    forward: "Fwd",
    holidayCalendar: "Feriado",
    organizer: "Organizador",
    otherFilters: "Outros filtros",
    searchResults: "Resultados da busca",
    withAllUsers: "Com todos os usuários",
  },

  loaderFullscreen: {
    descriptionEvents: "Seus eventos estão chegando, por favor aguarde.",
    description: "Os conteúdos estão chegando, por favor espere.",
    descriptionFolder: "Suas pastas estão chegando, por favor espere,",
    title: "Carregando",
    titleEvent: "Carregando evento",
  },

  mail: {
    confirmMailLabel: "Ok, eu confirmo!",
    contextualMenuLabels: {
      addAddressBook: "Adicionar à lista de contatos",
      addEvent: "Adicionar evento",
      alarm: "Alarme",
      archive: "Arquivo",
      archiveThread: "Tópico de arquivo",
      backTo: "Voltar",
      cancel: "Cancelar",
      close: "Fechar",
      confirm: "Confirmar",
      copyIn: "Copiar em",
      copyThreadIn: "Copiar tópico",
      delete: "Deletar",
      deletePerm: "Deletar permanentemente",
      deleteThread: "Deletar tópico",
      deleteXMessages: "Apagar {{MessagesNumber}} mensagens",
      deliveryNotification: "Confirmação de entrega",
      download: "Baixar",
      editAsNew: "Editar como novo",
      emptySpam: "Marcar Spam como lido",
      emptyTrash: "Esvaziar lixeira",
      forward: "Encaminhar",
      import: "Importar email",
      label: "Etiqueta",
      labelsManagement: "Gerenciar etiquetas",
      labelThread: "Tópico da etiqueta",
      markAllAsRead: "Marcar tudo como lido",
      markAs: "Marcar como",
      markThreadAs: "Marcar tópico",
      manageFolders: "Gerenciar pastas",
      modify: "Editar",
      more: "Mais",
      moveThreadTo: "Mais tópicos",
      moveTo: "Mover para",
      newSubFolder: "Adcionar sub-pasta",
      plainText: "Modo de texto sem formatação",
      print: "Imprimir",
      priorityHigh: "Alta prioridade",
      readed: "Lido",
      readedNot: "Não lido",
      readingNotification: "Confirmação de leitura",
      rename: "Renomear",
      reply: "Responder",
      replyToAll: "Responder a todos",
      restore: "Restaurar",
      restoreThreadIn: "Restaurar tópico",
      restoreIn: "Restaurar em",
      sendAsAttachment: "Encaminhar como anexo",
      showSourceCode: "Mostrar code de origem",
      spam: "Spam",
      spamNot: "Não é Spam",
      starred: "Favorito",
      starredNot: "Desmarcar como favorito",
      thanks: "Obrigado",
      thread: "Ações de tópico",
    },
    deleteMailDsc:
      "Se um sistema de armazenamento não está ativo, a mensagem será permanentemente deletada.<br/><b>A operação não é reversível</b>.",
    deleteMailTitle: "Deletar mensagem",
    deleteMailsDsc:
      "Se um sistema de armazenamento não está ativo, a mensagem será permanentemente deletada.<br/><b>A operação não é reversível<b>.",
    deleteMailsTitle: "Deletar mensagens selecionadas",
    dropFiles: "Solte aqui os arquivos para anexar",
    emptyTrashDsc:
      "Se um sistema de armazenamento não está ativo, esvaziando a lixeira todas as mensagens serão eliminadas <b>irreversivelmente</b>.<br/>Após <b>30 dias</b> todas as mensagens são deletadas automaticamente.",
    emptyTrashTitle: "Esvaziar lixeira",
    goToOldWebmailModal: {
      description:
        "<br/>Convidamos você a usar imediatamente o novo Webmail, que oferece recursos adicionais, como: <br/> <ul> <li> Gerenciamento automático de identidade </li> <li> Agenda e catálogo de endereços compartilhados </li> <li> Integração de zoom para videoconferências </li> <li> Mensagens predefinidas </li> <li> Pesquise todas as pastas </li> <li> e mais recursos </li> </ul> ",
      title: "O antigo Webmail não estará mais acessível a partir de 31 de outubro",
    },
    import: {
      messagesInvalid: "Inválido:",
      messagesNr: "Total de mensagens a serem importadas:",
      messagesValid: "Válido:",
      desc: "Você está importando mensagens na pasta: <code>{{folderImport}}</code><br/>Você pode importar mensagens de outros aplicativos de email usando arquivos eml (<strong>.eml</strong>).",
      dropFiles: "Carregue ou arraste aqui os arquivos a serem importados",
      error: "A mensagem não pode ser importada",
      importing:
        "Estamos importando <b>{{messagesNumber}}</b> mensagens na pasta: <code>{{folderImport}}</code>",
      loading: "Carregando...",
      success: "Importado com sucesso!",
      title: "Importar mensagens",
      uploadedFile: "Carregadas",
      uploadingFile: "Carregando",
    },
    loading: {
      desc: "Suas mensagens estão chegando, por favor aguarde.",
      title: "Carregando",
    },
    markSpamReadDsc:
      "Marcar todas as mensagens na pasta como lidas.<br/>Após <b>30 dias</b> as mensagens serão deletadas automaticamente.",
    markSpamReadTitle: "Marcar mensagens como lidas",
    maxLabelsNumberTitle: "Número excessivo de etiquetas!",
    maxLabelsNumberDsc:
      "Você atingiu o número máximo de etiquetas que podem ser associadas a uma mensagem. Para adicionar uma nova etiqueta você deve remover uma dentre as já existentes.",
    message: {
      add: "Adicionar",
      addToAddressBook: "Adicionar contato à lista de contatos",
      attachedMessage: "Anexar mensagem",
      attachments: "Anexos",
      bugMsg: "Não consegue visualizar a mensagem?",
      cc: "Cc:",
      date: "Data:",
      draftsSelectedInfo: "Selecione uma mensagem da lista e continue para escrever",
      downloadAll: "Baixar tudo",
      downloadAttachments: "Baixar anexos",
      editPartecipationStatusDecription: "",
      editPartecipationStatusTitle: "Editar status dos participantes",
      eventActionAccept: "Aceitar",
      eventActionDecline: "Rejeitar",
      eventActionTentative: "Talvez",
      eventAddToCalendar: "Esse evento não está presente no seu calendário",
      eventAttendees: "Participantes",
      eventAttendeeStatusAccepted: "Evento aceito",
      eventAttendeeStatusDeclined: "Evento rejeitado",
      eventAttendeeStatusTentative: "Participação incerta",
      eventCounterProposal: "Essa mensagem contém uma contra-proposta para o evento",
      eventDeleted: "Evento deletado",
      eventInvitation: "Confite de evento:",
      eventLocationEmpty: "Não especificado",
      eventModify: "Editar status dos participantes",
      eventNeedAction: "Confirmar participação no evento",
      eventNotNeedAction: "Evento já ocorrido",
      eventOutDated: "O evento foi modificado",
      eventStatusAccepted: "Aceito",
      eventStatusDeclined: "Rejeitado",
      eventStatusTentative: "Provisório",
      eventUpdate: "Atualizar evento",
      external: "Externo",
      externalLabel: "Este endereço de e-mail é de fora da sua organização.",
      folderSelectedInfo: "Selecione uma mensagem da lista e descubra quem lhe escreveu.",
      from: "De:",
      hideAllAttachments: "Esconder",
      hugeMessage:
        "Conteúdo muito grande para ser exibido inteiramente, clique no link abaixo para visualizar o código fonte da mensagem.",
      hugeMessageNotice: "Mensagem truncada",
      inboxSelectedInfo: "Selecione uma mensagem da lista e veja a quem você escreveu.",
      isMailingList: "Esta mensagem é de uma lista de discussão.",
      localAttachments: "Existem anexos adicionais dentro do evento",
      message: "Mensagem",
      messageForwarded: "Mensagem encaminhada",
      messages: "Mensagens",
      messagesQuota: "Cota de mensagens usada:",
      newMessageinThread: "Você tem uma nova mensagem",
      noContent: "Esta mensagem não tem conteúdo.",
      notSelected: "Selecione uma mensagem",
      oneSelectMessages: "Mensagem selecionada",
      oneSelectThreads: "Tópico selecionado",
      readNotificationLabel: "{{Sender}} pediu confirmação de letura para esta mensagem.",
      readNotificationLabelSimple: "Confirmação de leitura da mensagem pedida.",
      readNotificationResponse:
        "<P>Mensagem<BR><BR>&nbsp;&nbsp;&nbsp; A:&nbsp; %TO%<BR>&nbsp;&nbsp;&nbsp; Assunto:&nbsp; %SUBJECT%<BR>&nbsp;&nbsp;&nbsp; Enviada :&nbsp; %SENDDATE%<BR><BR>foi lido no dia %READDATE%.</P>",
      readNotificationSubjectPrefix: "Ler:",
      replyTo: "Responder para:",
      sender: "Remetente:",
      sentSelectedInfo: "Selecione uma mensagem da lista e veja a quem você escreveu.",
      showAllAttachments: "Mostrar outros",
      showMoreThread: "Mostrar mais",
      selectMessages: "Mensagens selecionadas",
      selectThreads: "Tópico selecionado",
      spamNotSelected: "Manter a pasta em ordem",
      spamSelectedInfo: "Verificar mensagens e marcar spam como lidos.",
      subject: "Assunto:",
      to: "Para:",
      trashNotSelected: "Verificar lixeira",
      trashSelectedInfo: "Você pode recuperar mensagens da lixeira em 30 dias.",
      updating: "Edição em andamento",
      unsubscribedMailingList: "Você se removeu desta lista de discussão.",
      yesterday: "Ontem",
      wrote: "escrito:",
    },
    messagesList: {
      allMessagesLoaded: "Todas as mensagens foram carregadas",
      ctaDeletedMessages: "Compact folder",
      ctaSpamInfo: "Marcar tudo como lido",
      ctaTrashInfo: "Esvaziar lixeira",
      deletedMessages:
        "Existem mensagens aguardando exclusão, compacte a pasta para concluir a operação.",
      folderEmpty: "Esta pasta está vazia",
      folderInfo: "Começar conversa ou mover uma mensagem.",
      foundMessages: "Encontrado",
      foundMessagesNum: "Encontrado: <b>{{found}}</b> de <b>{{total}}</b>",
      moveMessage: "Mover mensagem",
      moveMessages: "Mover {{NumMessages}} mensagens",
      notFound: "Nenhuma mensagem encontrada",
      notFoundInfo:
        "A pesquisa não produziu resultados, tente novamente usando diferentes critérios",
      pullDownToRefresh: "Arraste para atualizar",
      releaseToRefresh: "Solte para atualizar",
      searchInfo: "Mensagem encontrada",
      searchLimited:
        "Indexação em andamento. A pesquisa está limitada às <b>pastas únicas</b> e aos campos <b>de</b>, <b>para</b> e <b>assunto</b> de a mensagem.",
      searchNotAvailable: "Pesquisa não disponível",
      searchNotAvailableInfo: "A pesquisa está indisponível no momento, tente novamente mais tarde",
      selectMessages: "Selecionada",
      showMoreThread: "Mostrar mais",
      spamEmpty: "Todos os Spams desapareceram!",
      spamInfo: "Mensagens na caixa de spam são automaticamente deletadas após 30 dias.",
      trashEmpty: "A lixeira está vazia",
      trashInfo: "Mensagens na lixeira são deletadas automaticamente depois de 30 dias.",
      totalMessages: "Mensagens",
      totalMessagesNum: "Mensagens: <b>{{total}}</b>",
    },
    mtm: {
      archivePromo:
        "<b> Mas isso não é tudo... </b> <br/> <br/> O serviço de arquivo de e-mail fornece uma caixa de correio gêmea, somente leitura, onde todas as mensagens enviadas e recebidas são armazenadas pelos usuários, por 10 anos sem limites de espaço.",
      backupSelector: "Selecione um backup para continuar",
      description:
        "Usando este serviço você pode acessar os backups de sua caixa postal feitos nos últimos 15 dias, verificar o status de seus backups ou restaurar mensagens.",
      title: "Bem-vindo Mail Time Machine",
    },
    newMessage: {
      addAttach: "Adicionar anexo",
      addHTMLTitle: "Inserir HTML",
      addImgeDsc:
        "Você pode inserir imagens diretamente entre as linhas no corpo da mensagem ou anexá-las à mensagem.",
      addImgeTitle: "Inserir imagem",
      addLinkTitle: "Inserir link",
      editLinkTitle: "Editar link",
      advanced: "Avançado",
      attachInfo: {
        noAttach: "Não há anexos",
        attachNumber: "Anexos:",
      },
      bcc: "Cco",
      cc: "Cc",
      cancelSend: "Envio de email cancelado com sucesso",
      delete: "Deletar",
      deleted: "Mensagem deletada com sucesso",
      deleteInProgress: "Deletando mensagem",
      discardChanges: "Descartar alterações",
      fontSize: {
        smaller: "Menor",
        small: "Pequeno",
        normal: "Normal",
        medium: "Médio",
        big: "Grande",
        bigger: "Maior",
      },
      from: "De",
      hide: "Esconder",
      invalidMails:
        "Um endereço de email é inválido, verifique os endereços de email e tente novamente",
      moreAttachments: "Outros",
      noDraftChanged: "Sem alterações para salvar",
      object: "Assunto",
      saveDraftDsc:
        "A mensagem não foi enviada e contém alterações não salvas. Você pode salvá-la como rascunho e continuar escrevendo mais tarde",
      saveDraftTitle: "Salvar mensagem como rascunho?",
      savedDraft: "Rascunho salvo!",
      savingDraft: "Salvando",
      sendInProgress: "Envio de mensagem em andamento",
      sent: "Mensagem enviada com sucesso",
      sizeExceeded:
        "Anexo muito grande. O tamanho máximo de arquivo opara envio é de {{messageMaxSize}} MB.",
      templateCreateModal: {
        description:
          "<br/>Crie sua primeira mensagem predeterminada para facilitar a composição de e-mails recorrentes. Você pode escolher um assunto personalizado e adicionar anexos para serem enviados automaticamente na mensagem de e-mail.",
        title: "Você ainda não tem mensagens predeterminadas",
      },
      templateSubjectModal: {
        description:
          "Um objeto personalizado é definido na mensagem predefinida selecionada. Deseja substituir aquele na janela de composição ou deseja mantê-lo?",
        title: "Assunto já presente",
      },
      to: "Para",
      toMore: "Outros",
      useTemplate: "Mensagem enlatada",
      windowSubject: "Nova mensagem",
    },
    reportBug: {
      title: "Denunciar mensagem",
      message: {
        issue:
          "Caso você não veja a mensagem corretamente, você pode nos ajudar a resolver o problema e melhorar o serviço.<br/>Se você tiver alguma dúvida ou problema em relação ao uso do webmail, entre em contato com seu representante técnico para obter assistência.",
        issueFormatting:
          "O conteúdo da mensagem não é exibido corretamente? Você descreve o problema, faremos todo o possível para corrigi-lo nas próximas atualizações.",
        issueBlank:
          "Quando as mensagens estão desprovidas de qualquer conteúdo, estas são indicadas na interface do Webmail com um banner especial.<br/><br/>Se este banner não estiver presente, pode ser um problema de formatação, então <b>verifique a presença do banner</b> e talvez reporte a mensagem como <code>não formatada corretamente</code>.",
        issueAttach:
          "A mensagem parece estar livre de anexos? Provavelmente o remetente enviou a mensagem esquecendo-se de inserir os anexos.<br/><br/><b>Peça ao remetente para verificar e reenviar os anexos para você</b>. ",
        issueOther:
          "Você descreve o problema, faremos todo o possível para corrigi-lo nas próximas atualizações.<br/>Se você tiver alguma dúvida ou problema em relação ao uso do webmail, entre em contato com seu representante técnico para obter assistência.",
        disclaimer:
          "Enviando este feedback, sua mensagem poderá ser analisada por nossa equipe de desenvolvimento para melhorar o serviço.<br/><br/><b>As informações NÃO serão compartilhadas com terceiros e os dados serão processados de acordo com as atuais legislação sobre privacidade</b>.",
      },
    },
    restoreRequest: {
      desc: "Você solicitou a restauração da caixa de correio <b>{{username}}</b> com o backup datado de <b>{{restore_date}}</b>.<br/>Com esta operação, restauraremos todos os mensagens presentes no backup indicado, sem excluir nenhuma mensagem entretanto recebida ou enviada da caixa postal.<br/><br/><b>A operação de restauração está sujeita a um custo.</b><br/><br/>Deseja prosseguir com a solicitação?",
      restoreRequested:
        "Recebemos sua solicitação de restauração. Você será contatado assim que o procedimento for concluído.",
      title: "Solicitar uma restauração",
      titleRestoreRequested: "Request sent",
      deniedTitle: "Solicitação rejeitada",
      restoreRequestDenied:
        "Esta conta tem outra solicitação de restauração em andamento. Não é possível solicitar mais de uma solicitação de restauração por vez.",
    },
    searchMail: {
      attachments: "Anexos",
      cleanFilters: "Limpar filtros",
      marked: "Favorito",
      results: "Procurar Resultados",
      searchIn: "Procure em",
      allFolders: "Todas as pastas",
      currentFolder: "Pasta atual",
    },
    sidebar: {
      createLabel: {
        desc: "",
        title: "Criar Etiqueta",
      },
      createFolder: {
        desc: "",
        title: "Criar pasta",
      },
      modifyFolder: {
        desc: "",
        title: "Editar pasta",
      },
      restoreFolder: {
        desc: "",
        title: "Restaurar pasta",
      },
      folder: "Pastas",
      folders: "Pastas pessoais",
      labels: "Etiquetas",
      newFoderName: "Nome da nova pasta",
      occupiedSpace: "Espaço utilizado",
      sharedFolders: "Pastas compartilhadas",
      unlimitedSpace: "Espaço ilimitado",
    },
    thanksMailLabel: "Ok, obrigado!",
    tooManyCompositionsDsc:
      "Você atingiu o número máximo de novas mensagens que você pode escrever ao mesmo tempo.Termine pelo menos uma mensagem dentre as mensagens que você está escrevendo para iniciar uma nova.",
    tooManyCompositionsTitle: "Escrita terminada!",
    unsubscribeListDsc: "Parar de receber mensagens para esta lista de discussão?",
    unsubscribeListTitle: "Cancelar assinatura",
  },

  mailboxes: {
    archive: "Arquivo",
    drafts: "Rascunhos",
    inbox: "Caixa de entrada",
    more: "Mais",
    sent: "Enviada",
    shared: "Pastas compartilhadas",
    spam: "Spam",
    trash: "Lixeira",
  },

  navbar: {
    addressbook: "Contatos",
    calendar: "Calendário",
    chat: "Conversas",
    mail: "Email",
    meeting: "Reunião",
    news: "Novidades",
  },

  news: {
    notFound: "Notícias não encontradas",
    notFoundInfo:
      "A pesquisa não produziu resultados, tente novamente usando critérios diferentes.",
  },

  newsTags: {
    news: "Novidades",
    suggestions: "Dicas",
    fix: "Reparar",
    comingSoon: "Em breve",
    beta: "Beta",
  },

  pageLogout: {
    title: "Encerrando seção",
    desc: "",
  },

  pageIndexing: {
    title: "Sua conta está indexada",
    desc: "Esta operação pode demorar algum tempo, por favor, espere.",
  },

  pageNotFound: {
    pageNotFound: "Algo deu errado",
    pageNotFoundInfo:
      "A página que você está procurando não está disponível, não perca as esperanças!",
  },

  powered: "impulsionado por Qboxmail",
  poweredCollaborationWith: "em colaboração com ",

  radioButtons: {
    labels: {
      askDeliveryConfirmation: "Confirmação de entrega de mensagem",
      askReadConfirmation: "Confirmação de leitura de mensagem",
      defaultView: "Exibição padrão",
      newEventType: "Tipo de novos eventos",
      newEventFreeBusy: "Mostrar novos eventos disponíveis",
      newEventTimeInterval: "Novo intervalo de tempo padrão do evento",
      other: "De outros",
      reportBugBlank: "A mensagem aparece em branco",
      reportBugNoAttachments: "A mensagem não tem anexos",
      reportBugNoFormatted: "O conteúdo não está formatado corretamente",
      selectIssue: "Qual é o seu problema?",
    },
  },

  shareOptions: {
    delete: "Eliminação",
    read: "Lendo",
    update: "Editando",
    write: "Escrevendo",
  },

  shareOptionsCalendar: {
    canCreateObjects: "Permitir inserção de eventos no calendário",
    canEraseObjects: "Permitir exclusão de eventos do calendário",
  },

  shortcuts: {
    addressbook: {
      newContact: "Novo contato",
      editContact: "Editar contato",
      deleteContact: "Deletar contato",
    },
    calendar: {
      newEvent: "Novo evento",
      editEvent: "Editar evento",
      deleteEvent: "Deletar evento",
      moveRangeNext: "Visualizar próximo intervalo",
      moveRangePrevious: "Visualizar intervalo anterior",
    },
    general: {
      switchModuls: "Mudar módulos",
      refresh: "Atualizar página",
      tabForward: "Avançar entre os elementos clicáveis",
      tabBack: "Volte entre os elementos clicáveis",
      closeModal: "Fechar módulo",
      openSettings: "Abrir configurações",
      copy: "Copiar itens selecionados",
      past: "Colar itens selecionados",
      cut: "Recortar itens selecionados",
    },
    mail: {
      confirm: "Confirmar",
      deleteMessage: "Deletar mensagem",
      deleteSelectMessage: "Deletar mensagens selecionadas",
      editAsNew: "Editar como novo",
      empityTrash: "Esvaziar lixeira",
      expandThread: "Expandir tópico",
      extendSelectDown: "Extender seleção para baixo na lista de mensagens",
      extendSelectUp: "Extender seleção para cima na lista de mensagens",
      forward: "Encaminhar",
      markRead: "Marcar como lida/não lida",
      moveDown: "Mover para baixo na lista de mensagens",
      moveUp: "Mover para cima na lista de mensagens",
      newMessage: "Nova mensagem",
      openSelectMessage: "Abrir mensagem selecionada",
      printMessage: "Imprimir mensagem",
      reduceThread: "Reduzir tópico",
      reply: "Responder",
      replyAll: "Responder à todos",
      thanks: "Obrigado",
    },
  },

  settings: {
    addressbook: {
      management: {
        automaticSave: {
          desc: "Escolha se coletar todos os contatos não presentes em seus catálogos de endereços de forma automática.",
          title: "Salvar automaticamente",
        },
        personalAddressbooks: {
          desc: "Gerencie seus catálogos de endereços pessoais e decida se deseja compartilhá-los com outro usuário.",
          headerActiveSync: "Sync",
          headerItem: "Lista de contatos",
          placeholderList: " ",
          title: "Lista de contatos pessoal",
        },
        sharedAddressbooks: {
          desc: "Gerencie catálogos de endereços compartilhados com você por outros usuários.",
          headerItem: "Lista de contatos inscrita",
          placeholderList: " ",
          title: "Compartilhar lista de contatos",
        },
        title: "Listas de contatos",
      },
      title: "Contatos",
      view: {
        desc: "Gerencie suas preferências de visualização de contatos e catálogos de endereços.",
        title: "Visualizar contatos",
      },
    },
    calendar: {
      events: {
        title: "Eventos",
        desc: "Gerencie suas preferências para novos eventos para todos os calendários, se não for definido um padrão específico.",
        alertTitle: "Alertas",
        alertDesc:
          "Gerencie suas preferências de alertas de eventos para todos os calendários, se não for definido um padrão específico.",
        personalMeetingRoomTitle: "Sala de reuniões pessoal",
        personalMeetingRoomDesc:
          "Crie uma sala na sua aplicação de reuniões em linha e introduza a ligação aqui. Pode então ser selecionada como 'Localização' ao criar um evento.",
      },
      invitations: {
        desc: "Escolha se deseja habilitar convites de eventos apenas para os usuários que você deseja.",
        title: "Convites eventos",
        msgFromHeader: "Permitir convites apenas de",
        placeholderList: " ",
      },
      labels: {
        title: "Etiquetas calendário",
        titleSettingsPage: "Etiquetas calendário",
        desc: "Crie etiquetas coloridas personalizadas para manter seus eventos em ordem.",
        deleteLabelDsc: "A exclusão do marcador o removerá de todos os eventos da agenda.",
      },
      management: {
        title: "Calendários",
        holidayCalendars: {
          title: "Calendário de férias",
          desc: "Escolha os calendários de feriados de sua preferência.",
          headerItem: "Calendários",
          placeholderList: " ",
        },
        personalCalendars: {
          title: "Calendário pessoal",
          desc: "Gerencie seus calendários pessoais e decida se deseja compartilhá-los com outro usuário.",
          headerActiveSync: "Sync",
          headerItem: "Calendários",
          placeholderList: " ",
        },
        sharedCalendars: {
          desc: "Gerenciar calendários compartilhados com você por outros usuários.",
          headerActiveSync: "Sync",
          headerItem: "Calendários inscritos",
          placeholderList: " ",
          title: "Calendários compartilhados",
        },
        includeInFreeBusy: "Incluir em Free/Busy",
        showActivities: "Mostrar atividades",
        showAlarms: "Mostrar alarmes",
        syncWithActivesync: "Sincronizar usando Microsoft® Exchange ActiveSync",
        sendMeMailOnMyEdit: "Mandar-me um email quando eu modificar o calendário",
        sendMeMailOnOtherEdit: "Mandar-me um email quando alguém modificar o calendário",
        sendMailOnEditTo: "Quando eu modificar, mandar um email para",
      },
      view: {
        desc: "Gerencie suas preferências para visualização de calendários.",
        showBusyOutsideWorkingHours: "Mostrar como ocupado fora do horário de trabalho",
        showWeekNumbers: "Mostrar número da semana",
        title: "Visualizar calendários",
      },
      title: "Calendário",
    },
    chat: {
      title: "Conversas",
      view: {
        title: "Visualizar",
      },
    },
    general: {
      integrations: {
        desc: "Gerenciar integrações com provedores de serviços fora do webmail.",
        title: "Integrações",
        card: {
          zoom: {
            askSeller: "Peça mais informações ao seu revendedor",
            title: "Zoom",
            text: "Economize tempo ao agendar reuniões adicionando detalhes exclusivos da conferência Zoom a um evento.",
          },
        },
      },
      notifications: {
        title: "Notificações via push",
        generalNotification: {
          desc: "Activa as notificações que indicam a recepção de uma nova mensagem.",
          longDesc:
            "Permitir que o Webmail envie notificações através do seu browser quando receber uma nova mensagem. Esta definição não é suficiente para receber notificações, é necessário activar também as notificações para cada browser que pretenda utilizar.",
          title: "Definição geral das notificações",
        },
        allowedPush: {
          allowed:
            "As notificações estão activadas no navegador utilizado. Para as receber, devem também estar activadas na secção acima.",
          default:
            "Se pretender que o seu browser actual o notifique com uma notificação quando receber uma nova mensagem, tem de activar as notificações (na secção acima) e, em seguida, activar as notificações push no seu browser. Clique no botão e permita as notificações, ou clique no ícone de cadeado e permita as notificações premindo o botão Permitir.",
          isIos:
            "Se pretender receber notificações no seu dispositivo iOS (versão 16.4 e superior), tem de adicionar o Webmail ao ecrã inicial do seu dispositivo.",
        },
        browserNotification: {
          desc: "Verificar o estado e gerir as notificações para o browser actualmente em utilização.",
          title: "Estado das notificações do browser em utilização",
        },
        granted: "As notificações do seu navegador estão configuradas corretamente!",
        noPush: {
          title: "Infelizmente, o navegador Safari não suporta o sistema de notificação.",
          titleios:
            "Infelizmente, o sistema operacional iOS não suporta notificações do navegador.",
          desc: "Para ativar as notificações, use a versão mais atualizada de um dos seguintes navegadores",
        },
        deniedPush: {
          title: "Seu navegador está bloqueando as notificações push.",
          desc: "Remova este bloco para ativar notificações push quando uma nova mensagem chegar.",
        },
        modal: {
          title: "Deseja permitir notificações push?",
          text: "Você sempre pode permitir ou bloqueá-los a qualquer momento nas configurações do webmail.",
        },
      },
      parameters: {
        title: "Parâmetros",
        host: {
          title: "Configuração de dispositivos",
          desc: "Conecte seus dispositivos para receber e enviar e-mails com sua conta.",
        },
        imap: {
          title: "IMAP",
        },
        smtp: {
          title: "SMTP",
        },
      },
      profile: {
        email: "Email do usuário",
        generalSettings: {
          desc: "Gerencie preferências sobre idioma e tempo.",
          title: "Configurações gerais",
        },
        personalInfo: {
          desc: "Gerencie suas informações de perfil.",
          title: "Informações pessoais",
        },
        title: "Perfil",
      },
      security: {
        changepassword: {
          info: "Senha com pelo menos 8 caracteres alfanuméricos",
          desc: "Gerenciar senha para acessar seu webmail.",
          resetpassword: "Configurar nova senha",
          resetpassworddisabled: "Mudança de senha está desativada nesta conta",
          resetpasswordexpired: "Sua senha expirou, configure uma nova senha",
          title: "Mudar senha",
        },
        days: "dia/s",
        passwordexpiration: {
          activeExpiration:
            "A expiração automática de senha está habilitada para sua conta de e-mail.",
          desc: "Verifique o status da senha da sua conta.",
          expirationDate: "A senha expira em",
          expirationCountdown: "A senha expira em",
          modalTitle: "Sua senha está prestes a expirar",
          modalDesc:
            "Faltam {{password_expiration_relative_days}} dia/s para a expiração da senha da sua conta. Recomendamos que você altere imediatamente.",
          title: "Expiração da senha",
        },
        otp: {
          cantDisableOtp: "Autentificação de dois fatores não pode ser desabilitada nesta conta",
          desc: "Gerencie a autenticação de dois fatores para acessar seu webmail.",
          disableOtp: "Desabilitar autentificação de dois fatores",
          downloadParams: "Download activation data",
          hideParams: "Ocultar parâmetros",
          instructionDisableOtp:
            "Informar o código gerado pelo aplicativo na forma abaixo para desabilitar autentificação de dois fatores para essa conta.",
          instructionsSetOtp:
            "Escaneie o QRCode pelo aplicativo e informe o código gerado no fomato abaixo. Ou informe os parâmetros para ativar  manualmente.",
          labelEnterCode: "Informe o código gerado pelo aplicativo",
          paramAccount: "Conta",
          paramCode: "Código",
          paramType: "Base de tempo",
          paramTypeVal: "Ativo",
          params: "Informe o código manualmente",
          paramsInstruction: "Informe os seguintes parâmetros no aplicativo",
          setOtp: "Habilitar autentificação de dois fatores",
          title: "Configurar OTP",
          titleDisableOtp: "Desabilitar OTP",
          titleSetOtp: "Habilitar OTP",
        },
        sessions: {
          browser: "Navegador:",
          currentSession: "Atual",
          device: "Aparelho:",
          desc: "Manage access sessions to your webmail.",
          ip: "IP:",
          os: "OS:",
          platform: "Platform:",
          removeAll: "Remover tudo",
          removeSession: "Remover",
          startdate: "Iniciar:",
          title: "Abrir seção",
        },
        title: "Segurança",
      },
      title: "Geral",
    },
    mail: {
      accounts: {desc: "", title: "Contas"},
      antispam: {
        blacklist: {
          desc: "Adicionar endereço ou domínio à lista (ex. 'nome@domínio' ou '*@domínio')",
          msgNoHeader: "Não permitir mensagens de",
          title: "Lista negra",
        },
        deleteRuleDsc: "Deletar conjunto de regras de <code>{{ruleEmail}}</code>.",
        deleteRuleTitle: "Deletar regra antispam",
        placeholderList: " ",
        title: "Antispam",
        whitelist: {
          desc: "Adicionar endereço ou domínio à lista (ex. 'nome@domínio' ou '*@domínio')",
          msgFromHeader: "Permitir mensagens de",
          msgToHeader: "Permitir mensagens para",
          title: "Lista branca",
        },
      },
      autoresponder: {
        desc: "Defina uma mensagem de resposta automática para quando você estiver fora do escritório ou não puder responder às mensagens recebidas.<br/>Se um contato tiver enviado várias mensagens para você, a resposta automática será enviada apenas uma vez a cada 24 horas.",
        msg: "Mensagem",
        placholdeSubject: "Assunto",
        placholderTextarea: "Texto da mensagem",
        title: "Autoresposta",
      },
      compose: {
        cancelSend: {
          desc: "Escolha o tempo limite para cancelar o envio de uma mensagem em andamento, se decidir que não deseja mais enviar a mensagem.",
          title: "Cancelar enviar e-mail",
        },
        confirmations: {
          desc: "Gerencie a notificação de leitura e entrega de suas mensagens recebidas e enviadas.",
          title: "Confirmação de leitura / entrega",
        },
        title: "Composição",
      },
      delegations: {desc: "", title: "Delegação"},
      filters: {
        actionsTitle: "Ações",
        activeFiltersTitle: "Regras ativas",
        desc: "Crie regras específicas para classificar as mensagens recebidas e organizá-las como quiser em sua caixa de correio.",
        headerItem: "Regra",
        headerStatus: "Ativo",
        hintEqualOperator:
          "Atenção: o uso do operador <em><b>é igual a</b></em> / <em><b>não é igual a</b></em> é recomendado apenas para usuários experientes. Como alternativa, é recomendável usar o operador <em><b>contém</b></em> / <em><b>não contém</b></em>. <br>Para usar o operador <em><b>é igual a</b></em> / <em><b>não é igual a</b></em>, você deve corresponder a todos os elementos que compõem o campo. Por exemplo, para indicar a <em>Origem</em> deve indicar todos os seguintes elementos: <b>descrição &lt;endereço de email&gt;<b>.",
        parametersTitle: "Parâmetros",
        placeholderList: {
          parameter: "Adicionar parâmetros à regra",
          action: "Adicionar ação à regra",
        },

        title: "Regras",
      },
      folders: {
        compactFolder: "Remover todas as mensagens marcadas como excluídas da pasta",
        deleteFolderDsc:
          "A exclusão da pasta <code>{{folderName}}</code> excluirá todas as mensagens nela contidas.<br/><b>A operação não é reversível</b>.",
        deleteFoldersTitle: "Deletar pastas",
        desc: "Gerenciar e compartilhar suas pastas pessoais",
        descShared: "Gerenciar suas pastas compartilhadas",
        headerItem: "Pastas",
        headerMsg: "Mensagens",
        headerPermissions: "Permissões",
        headerSelectedUsers: "Usuários selecionados",
        headerUnread: "Não lido",
        modifyFolder: "Editar pasta",
        newFolder: "Adicionar nova pasta",
        retention: "Conjunto de regras de exclusão automática",
        rootFolder: "-- Origem --",
        shared: "Compartilhado com outros usuários",
        subscribe: "Inscrever",
        tabInfo: "Informações da pasta",
        tabShare: "Compartilhar pasta",
        title: "Pastas",
        titleShared: "Pastas compartilhadas",
      },
      forward: {
        description:
          "Escolha os endereços de e-mail para os quais encaminhar as mensagens recebidas.",
        headerItem: "Destinatários",
        placeholderList: " ",
        title: "Encaminhar mensagens",
        titleSection: "Encaminhar mensagens",
      },
      labels: {
        desc: "Crie etiquetas coloridas personalizadas para manter suas mensagens de e-mail em ordem.",
        headerItem: "Etiquetas",
        deleteLabelTitle: "Deletar etiqueta",
        deleteLabelTitleDsc: "A eliminação da etiqueta remove-a de todas as mensagens.",
        placeholderList: " ",
        title: "Etiquetas email",
      },
      reading: {
        layout: {
          desc: "Escolha como você deseja que o painel de leitura apareça.",
          title: "Disposição",
        },
        markReadSettings: {
          desc: "Definir quando uma mensagem deve ser marcada como lida.",
          title: "Marcar mensagem como lida",
        },
        readingSettings: {
          desc: "Defina sua preferência de leitura para mensagens.",
          title: "Configurações de leitura",
        },
        title: "Visualizar",
      },
      signature: {
        title: "Assinatura",
        bcc: {
          headerItem: "Destinatários Cco",
          placeholderList: "",
        },
        default: "Default",
        deleteNewSignatureModal: {
          description:
            "O conteúdo da nova assinatura não foi salvo, será perdido se você abrir outra.<br/>Deseja continuar?",
          title: "Excluir nova assinatura",
        },
        dropFiles: "Arraste aqui uma imagem para adicioná-la",
        management: {
          title: "Gestão de assinaturas",
        },
        onlyNewMessages: "Não adicione assinatura nas respostas",
        placeholderList: "Adicione sua primeira identidade",
        senderBcc: "Adicionar remetente a Cco",
        setAsDefault: "Definir como remetente padrão",
        signatures: {
          desc: "Para cada identidade (grupo de pseudónimos) associada à sua conta, pode personalizar a assinatura na parte inferior das mensagens de correio eletrónico que envia e o nome apresentado por aqueles que recebem as suas mensagens. Escolha o remetente predefinido e adicione listas de endereços de correio eletrónico em Cco.",
          headerItemSignature: "Nome de exibição",
          headerItemIdentity: "Identidade",
          title: "Assinaturas e identidades",
        },
      },
      template: {
        addAttachment: "Selecione um arquivo para adicioná-lo como anexo à mensagem",
        deleteTemplateModal: {
          description:
            "Confirmar para excluir a mensagem selecionada? Os arquivos anexados à mensagem também serão excluídos de nossos sistemas.",
          title: "Excluir mensagem predefinida",
        },
        title: "Mensagens predefinidas",
        description:
          "Selecione uma mensagem predefinida da lista para preencher automaticamente a nova mensagem de composição",
        placeholderList: "Adicione sua primeira mensagem enlatada",
        placeholderSearch: "Filtrar mensagens",
        searchHint:
          "Use este campo para filtrar a lista de mensagens predefinidas abaixo. O filtro funciona no nome, assunto e conteúdo da mensagem.",
        templates: {
          desc: "Simplifique a composição de e-mails recorrentes salvando mensagens predefinidas para escolher ao compor o e-mail.",
          headerItemPreview: "Visualizar",
          headerItemSubject: "Sujeito",
          headerItemTemplate: "Nome",
          maxAttachmentsNrBasic:
            "Máximo de {{attachmentNr}} anexos. Máximo de {{templateSize}} MB no total. Entre em contato com seu provedor de serviços de e-mail para aumentar esses limites.",
          maxAttachmentsNr:
            "Máximo de {{attachmentNr}} anexos. Máximo de {{templateSize}} MB no total.",
          maxTemplateNrReached: "O número máximo de modelos de e-mail configuráveis foi atingido.",
          maxTemplateNrReachedContactReseller:
            "O número máximo de modelos de e-mail configuráveis foi atingido.Se você precisar adicionar mais modelos de e-mail, entre em contato com seu provedor de serviços de e-mail para obter mais informações.",
          newTemplate: "Nova mensagem",
          title: "Mensagens predefinidas",
        },
      },
      title: "Email",
    },
    meeting: {
      title: "Reunião",
      view: {
        desc: "",
        title: "Visualizar",
      },
    },
    news: {
      readMore: "Leia mais",
      title: "News & Updates",
    },
    privacy: {
      title: "Privacy",
      cookie: {
        title: "Cookie Policy",
      },
      privacy: {
        title: "Privacy Policy",
      },
    },
    shortcuts: {
      title: "Atalhos",
    },
    tasks: {
      notifications: {
        desc: "Receba um e-mail quando uma tarefa for atribuída a você ou quando uma tarefa que você atribuiu for encerrada",
        title: "Notificações por e-mail",
      },
      labels: {
        title: "Etiquetas de tarefa",
        desc: "Crie etiquetas coloridas personalizadas para catalogar suas tarefas.",
      },
      title: "Tarefa",
    },
    title: "Configurações",
    unsaved: "Existem alterações não salvas",
  },

  tasks: {
    add: "Criar tarefa para minha lista",
    assignedBy: "Assinado por",
    assignedTaskLabel: "<b>{{user}}</b> atribuiu a você uma nova tarefa:",
    assignedTaskTitle: "Nova tarefa atribuída",
    assignedTo: "Atribuído a",
    assignTask: "Criar tarefa a ser atribuída",
    basic: {
      label:
        "O gerenciamento de tarefas é um serviço disponível<br />quando você atualiza seu perfil.<br /><br />A atualização também inclui um calendário<br />compartilhado e videoconferência integrada.",
      modalTitle: "Ferramentas para otimizar seu trabalho",
      modalSubTitle: "disponível com atualização de perfil",
      modalFooter:
        "O seu referente pode apresentar-lhe detalhadamente as funcionalidades adicionais, sem compromisso",

      calendarLabel: "<b>Agenda</b> compartilhada.",
      tasksLabel: "<b>Tarefas</b> e lembretes.",
      signatureLabel: "<b>Assinatura</b> e-mail centralizado.",
      zoomLabel: "<b>Zoom</b> integrado para videoconferência.",
      requestInfo: "Estou interessado",
      requestInfoConfirmation: {
        text: "Você será contatado pelo seu referente.",
        title: "O pedido de informação foi enviado.",
      },
      requestLater: "Talvez mais tarde",
    },
    closedTaskLabel: "<b>{{user}}</b> concluiu uma tarefa:",
    closedTaskTitle: "Tarefa atribuída concluída",
    completionDate: "Concluídas",
    deleteTaskModal: {
      desc: "Tem certeza de que deseja excluir a tarefa selecionada? Se a tarefa tiver sido atribuída a outros usuários, ela também será excluída para eles.",
      title: "Excluir tarefa",
    },
    dueTime: {
      today: "Hoje",
      tomorrow: "Amanhã",
      nextWeekend: "Próximo fim de semana",
      thisWeekend: "Este fim de semana",
      custom: "Data e hora",
    },
    labels: "Etiquetas",
    deleteLabelTitle: "Excluir etiqueta",
    deleteLabelDsc:
      "Essa etiqueta foi atribuída a uma ou mais atividades. Prosseguir com a sua eliminação?",
    linkedMail: "Correio eletrónico ligado",
    listImagesLabels: {
      completed: {
        text: "A lista de tarefas concluídas está vazia",
        title: "Nenhuma tarefa concluída",
      },
      overdue: {
        text: "Você ainda não tem tarefas atrasadas para fazer",
        title: "Bom trabalho",
      },
      notCompleted: {
        text: "Você não planejou nenhuma tarefa para fazer",
        title: "Nada para fazer aqui",
      },
      search: {
        text: "Escreva algo para fazer uma pesquisa",
        title: "Busca...",
      },
      assignedToDo: {
        text: "A lista de tarefas atribuídas está vazia",
        title: "Você não atribuiu nenhuma atividade",
      },
      assignedCompleted: {
        text: "A lista de tarefas atribuídas concluídas está vazia",
        title: "Nenhuma tarefa atribuída concluída",
      },
      noResult: {
        title: "Nenhum resultado encontrado",
      },
    },
    lists: "Listas",
    modalTitle: "Detalhes da tarefa",
    note: "Notas (máximo de 1000 caracteres)",
    occurrences: {
      all: "Todas as ocorrências",
      occurrence: "Somente esta ocorrência",
    },
    openedTaskLabel: "<b>{{user}}</b> reabriu uma tarefa concluída:",
    openedTaskTitle: "Tarefa atribuída reaberta",
    openMessageModal: {
      desc: "Se abrir a mensagem ligada à tarefa, a lista de tarefas será fechada.",
      title: "Deseja abrir a mensagem?",
    },
    overdueTasksPresent: "Tarefas atrasadas: {{overdueTasksPresentCount}}",
    planned: "Quando",
    repeat: "Repetir",
    repetitions: {
      NEVER: "Nunca",
      DAILY: "Diariamente",
      WEEKLY: "Semanalmente",
      MONTHLY: "Mensalmente",
      YEARLY: "Anualmente",
    },
    showMyTasks: "Minhas tarefas",
    showAssignedTasks: "Atribuído a outros",
    task: "Tarefa",
    taskFromNotification:
      "Deseja visualizar os detalhes da tarefa notificada e perder os dados da nova tarefa que está sendo composta?",
    title: "Tarefas",
    types: {
      view_todo: "Para fazer",
      view_all: "Todas",
      view_today: "Hoje",
      view_next7: "Próximos 7 dias",
      view_overdue: "Atrasadas",
      view_completed: "Concluídas",
    },
  },

  toast: {
    error: {
      alreadyPresent: "Atenção, o recurso já existe",
      avatarTooBig: "Atenção, tamanho do avatar muito grande",
      compact: "Erro ao compactar a pasta",
      connectionUnavailable: "Sem conexão disponível",
      delete: "Erro ao deletar",
      deleteDraft: "Erro ao deletar rascunho",
      emailAddressNotValid: "O endereço de email não é válido",
      enqueued: "Atualizando configurações, tente novamente",
      fetchingAttachments: "Erro ao anexar",
      filterActionsMissing: "Ação inexistente",
      filterConditionsMissing: "Parâmetro inexistente",
      filterNameMissing: "Nome da regra ausente",
      folderCreation: "Erro ao criar uma nova pasta",
      folderCreationCharNotValid: "Erro ao criar/renomear uma pasta, caractere inválido ({{char}})",
      folderCreationNoName: "Erro ao criar pasta, você precisa informar um nome válido",
      folderDelete: "Erro ao deletar pasta",
      folderNotPresent: "Pasta inexistente",
      folderRename: "Erro ao renomear pasta, pasta já existe",
      folderSubscribe: "Erro ao subscrever pasta",
      generic: "Algo deu errado",
      invalidDateRange: "Período inválido",
      maxMembers: "Atenção, número máximo de membros atingido",
      maxSignatureSize: "Tamanho máximo da assinatura excedido. Máximo {{maxSize}}",
      maxTemplateAttachmentsNumberReached:
        "O limite de anexos para esta mensagem predeterminada foi atingido",
      maxTemplateSize: "Aviso, o tamanho da mensagem predefinida é muito grande",
      maxTemplatesNumberReached:
        "O limite de mensagens predefinidas que podem ser configuradas para esta conta foi atingido",
      messageCopy: "Erro ao copiar mensagem",
      messageMove: "Erro ao mover mensagem",
      messageNotFound: "Mensagem não encontrada",
      messageRemove: "Erro ao remover mensagem",
      missingParameters: "Parâmetros faltando",
      missingSettings: "Configurações do usuário ausentes",
      notifications: "Erro ao receber notificações",
      notPermitted: "Operação não permitida",
      notValid: "Atenção, valor inválido",
      onlyOneHomeAddress: "Você pode informar apenas um endereço residencial",
      onlyOneWorkAddress: "Você pode informar apenas um endereço profissional",
      save: "Erro ao salvar",
      saveAcl: "Erro ao salvar permissões de pasta",
      saveEvent: "Ocorreu um erro. Talvez você não tenha permissões suficientes nesta agenda",
      saveZoomMeeting: "Não é possível criar a reunião na plataforma Zoom",
      savingDraft: "Salvando rascunho, por favor tente novamente ao final",
      searchNotAvailable: "Pesquisa não disponível no momento",
      sendingMessage: "Erro na entrega da mensagem",
      serverDisconnection: "Servidor sendo atualizado, por favor tente novamente mais tarde!",
      sessionExpired: "Sua sessão expirou",
      smtpBlockedByAntispam: "Mensagem não enviada: bloqueada pelo antispam",
      smtpBlockedByAntivirus: "Mensagem não enviada: bloqueada por antivírus",
      smtpDisabled: "Mensagem não enviada: SMTP desativado nesta conta",
      smtpQuotaExceeded: "Mensagem não enviada: cota de envio de mensagens excedida",
      requestLimit: "Número limite de pedidos excedido, tente novamente mais tarde",
      requestError: "Ocorreu um erro no pedido, tente novamente mais tarde",
      updateFolders: "Ocorreu um erro na atualização dos arquivos",
      updateMessageEvent: "Erro ao obter atualização dos status do evento",
      updatingParentFlags: "Erro ao atualizar os indicadores da mensagem",
    },
    info: {
      newVersionAvailable: {
        desc: "Esta operação é segura, suas configurações não serão modificadas",
        title:
          "Novos recursos estão disponíveis, recarregue a página para atualizar o correio eletrônico para a última versão",
      },
      serverReconnected: "Correio eletrônico online de volta",
      sourceMail: "Fonte do email copiado para área de transferência",
    },
    progress: {
      newFolder: "Criando nova pasta",
      operationInProgress: "Operação em andamento",
    },
    success: {
      compact: "Pasta compactada com sucesso",
      copiedLink: "Link copiado para área de transferência",
      copiedMail: "Mensagem copiada com sucesso",
      copiedMailAddress: "Endereço de email copiado para área de transferência",
      copiedText: "Texto copiado para a área de transferência",
      createFolder: "Pasta criada com sucesso",
      delete: "Deletado com sucesso",
      disabledOtp: "Desativação de OTP ocorrida com sucesso",
      enabledOtp: "Ativação de OTP ocorrida com sucesso",
      movedMail: "Mensagem movida com sucesso",
      notificationEnabled: "Notificações do navegador activadas com sucesso",
      otpDisabled: "OTP desabilitado com sucesso",
      otpEnable: "OTP habilitado com sucesso",
      save: "Salvo com sucesso",
      saveAcl: "Permissões salvas com sucesso",
      saveDraft: "Rascunho salvo com sucesso",
      saveFolder: "Pasta atualizada com sucesso",
      sentMail: "Mensagem enviada com sucesso",
      subscribeFolder: "Inscrição atualizada com sucesso",
      updateMessageEvent: "Status de evento atualizado",
    },
    warning: {
      forwardSet: "Pelo menos um encaminhamento foi configurado nesta conta",
      notificationNotSupported: "Aviso, o seu browser não suporta notificações",
    },
  },

  toggles: {
    labels: {
      allDayEvent: "Dia inteiro",
      autoSaveContact:
        "Salvar automaticamente todos os destinatários que não constem na sua lista de contatos",
      denyInvites: "Prevenir convites para compromissos",
      enableAutorespopnd: "Ativar autoresposta",
      enableAutorespopndInterval: "Ativar faixa de data",
      enableBrowserNotification: "Ativar notificações do navegador",
      enableDateSearch: "Ativar busca de datas",
      enableFullBody: "Ativar pesquisa completa",
      enableNotification: "Ativar notificações do navegador",
      keepCopy: "Manter localmente uma cópia da mensagem",
      showPriority: "Mostrar prioridade da mensagem recebida",
      showThreads: "Mostrar mensagem como tópico",
      subscribeFolder: "Subscrever pasta",
      tasksEmailNotifications: "Ativar notificações por e-mail",
    },
    hint: {
      enableFullBody:
        "A pesquisa de corpo inteiro está disponível apenas para uma única pasta. Selecione uma pasta para habilitá-la.",
    },
  },

  wizard: {
    layout: {
      desc: "Customizar seu correio eletrônico escolhendo as suas preferências de configurações de visualização",
      title: "Opções de visualização",
    },
    wizardData: {
      desc: "Customizar seu perfil adicionando imagens e preenchendo dados que estão faltando",
      title: "Completar perfil",
    },
  },
};
