/*********************************************************************************************************
 * English Copyright (C) 2017-2019 by Qboxmail Srl
 *
 * All rights reserved. No part of this publication may be reproduced, distributed, or transmitted in any
 * form or by any means, including photocopying, recording, or other electronic or mechanical
 * methods, without the prior written permission of the publisher, except in the case of brief quotations
 * embodied in critical reviews and certain other noncommercial uses permitted by copyright law. For
 * permission requests, write to the publisher at the address below.
 *
 * Qboxmail Srl - IT02338120971
 * https://www.qboxmail.it - info@qboxmail.it
 *
 * Italiano Copyright (C) 2017-2019 by Qboxmail Srl
 *
 * Tutti i diritti riservati. Nessuna parte di questa pubblicazione può essere riprodotta, memorizzata in
 * sistemi di recupero o trasmessa in qualsiasi forma o attraverso qualsiasi mezzo elettronico, meccanico,
 * mediante fotocopiatura, registrazione o altro, senza l'autorizzazione del possessore del copyright salvo
 * nel caso di brevi citazioni a scopo critico o altri usi non commerciali consentiti dal copyright. Per le
 * richieste di autorizzazione, scrivere all'editore al seguente indirizzo.
 *
 * Qboxmail Srl - IT02338120971
 * https://www.qboxmail.it - info@qboxmail.it
 *********************************************************************************************************/

export default {
  addressbook: {
    contact: {
      oneSelectContacts: "Vald kontakt",
      oneSelectLists: "Vald lista",
      notSelected: "Välj en kontakt",
      sectionLabels: {
        address: "Address",
        company: "Företag",
        email: "Email",
        info: "Info",
        telephone: "Telefon",
        homeUrl: "Personlig webbplats",
        workUrl: "Företagets webbplats",
      },
      sections: {
        cell: "Mobil",
        home: "Hem",
        homeFax: "Fax hem",
        work: "Arbete",
        workFax: "Fax arbete",
        title: "Roll",
        company: "Företag",
        note: "Noter",
        bday: "Födelsedag",
      },
      selectContacts: "Valda kontakter",
      selectLists: "Valda listor",
      selectedInfo: "Välj en kontakt från listan för att se detaljerna.",
    },
    contactsList: {
      emptyContacts: "Denna adressbok är tom",
      emptyContactsInfo: "Lägg till en kontakt i adressboken",
      emptyLists: "Det finns inga listor",
      emptyListsInfo: "Lägg till en ny lista",
      foundContacts: "Hittades",
      notFound: "Inga kontakter hittade",
      notFoundInfo: "Sökningen gav inga resultat, försök igen med andra kriterier.",
      totalContacts: "Kontakter",
    },
    tabs: {
      contacts: "Kontakter",
      lists: "Listor",
    },
    contextualMenuLabels: {
      address: "Adress",
      birthday: "Födelsedag",
      cancel: "Avbryt",
      cell: "Mobil",
      delete: "Radera",
      downloadVCard: "Ladda ner VCard",
      email: "E-post",
      newContact: "Ny kontakt",
      createList: "Skapa lista",
      newList: "Ny lista",
      note: "Anteckning",
      phone: "Telefon",
      shareVCard: "Dela",
      showVCard: "Visa VCard",
      sendAsAttachment: "Skicka via e-post",
      sendMail: "Skicka e-post",
      url: "URL",
      info: "Info",
      title: "Roll",
      company: "Företag",
      home: "Hem",
      homeFax: "Fax hem",
      work: "Arbete",
      workFax: "Fax arbete",
      nickname: "Smeknamn",
      displayName: "Visa namn",
      companyName: "Namn",
      homeUrl: "Personlig webbplats",
      workUrl: "Företagets webbplats",
      team: "Team",
      merge: "Sammanslagning",
    },
    deleteContactDsc:
      "Genom att ta bort kontakten <code>{{contact}}</code> raderas all relaterad information också. <br/><b>Åtgärden är inte reversibel</b>.",
    deleteContactDscList:
      "Genom att ta bort vald kontakt kommer alla information att raderas också. <br/><b>Åtgärden är inte reversibel</b>.",
    deleteContactTitle: "Radera kontakt",

    deleteContactsDsc:
      "Genom att radera utvalda kontakter kommer alla deras information att raderas också. <br/><b>Åtgärden är inte reversibel</b>.",
    deleteContactsTitle: "Radera kontakter",

    deleteListDsc:
      "Genom att radera listan <code>{{contact}}</code> raderas all relaterad information också. <br/><b>Åtgärden är inte reversibel</b>.",
    deleteListTitle: "Radera lista",

    editContactModal: {
      title: "Redigera kontakt",
    },
    editListModal: {
      title: "Redigera lista",
    },
    exportAddressBookModal: {
      desc: "Du exporterar adressboken: <code>{{addressbookExport}}</code><br/> Välj format för att exportera alla närvarande kontakter",
      title: "Exportera adressbok",
    },
    import: {
      contactsInvalid: "Inte giltig:",
      contactsNr: "Totalt antal kontakter som ska importeras:",
      contactsValid: "Giltig:",
      desc: "Du importerar kontakter till adressboken: <code>{{addressbookImport}}</code><br/>Du kan importera kontakter från andra e-postprogram med ett vCard (<strong>.vcf</strong>) eller <strong>.ldif</strong> filformat.\u000AExempel kan du exportera kontakter från Gmail eller från Outlook och importera dem här.\u000AImporten kommer inte att ersätta någon av de befintliga kontakterna.",
      dropFiles: "Ladda upp eller släpp filen som ska importeras, här",
      error: "Kontakter kunde inte importeras",
      importing:
        "Vi importerar <b>{{contactsNumber}}</b> händelsen till kalendern: <code>{{addressbookImport}}</code>",
      loading: "Läser in...",
      success: "Importering framgångsrik!",
      title: "Importera kontakter",
      uploadedFile: "Uppladdad",
      uploadingFile: "Laddar upp",
    },
    list: {
      desc: "Genom att skapa en kontaktlista är det möjligt att skicka e-post till många personer samtidigt. Upp till 150 medlemmar kan läggas till genom att välja dem från kontakterna i den valda adressboken.</br></br><b>Obs</b>: Det går inte att lägga till e-postadresser som inte finns i den valda adressboken. Lägg först till kontakterna i adressboken och lägg sedan till dem i listan.",
      members: "Lista medlemmar",
    },
    messages: {
      newContactAddressBookBody:
        "Du kan inte lägga till en kontakt i <b>Företagskontakter</b>. <br/>Välj en personlig eller delad adressbok.",
      newContactAddressBookTitle: "Välj adressbok",
      resetListBody:
        "Listans medlemmar är relaterade till den valda adressboken. Denna ändring återställer medlemslistan. Fortsätt?",
      resetListTitle: "Radering av medlemmar",
    },
    modifyAddressBookModal: {
      desc: "",
      title: "Redigera adressbok",
    },
    newAddressBookModal: {
      desc: "",
      title: "Lägg till adressbok",
    },
    newContactModal: {
      title: "Lägg till kontakt",
    },
    newListModal: {
      title: "Lägg till lista",
    },
    shareModal: {
      desc: "Du delar adressboken: <code>{{addressbookShare}}</code><br/>Välj de kontakter du vill dela adressboken med och låta dem hantera.",
      title: "Dela adressbok",
    },
    sidebar: {
      allContacts: "Alla kontakter",
      deleteAddressbookDsc:
        "Om du raderar adressboken <code>{{addressbook}}</code> raderas alla kontakter som ingår.<br/> <b> Åtgärden är inte reversibel </b>.",
      deleteAddressbookTitle: "Radera adressbok",
      globalAddressbook: "Företagskontakter",
      personalAddressbook: "Personliga kontakter",
      sharedAddressbooks: "Delade adressböcker",
      userAddressbooks: "Användarens adressbok",
    },
    subscribeModal: {
      desc: "",
      noAddressbook: "Det finns inga adressböcker som kan prenumereras",
      title: "Prenumerera på en delad adressbok",
    },
  },

  app: {
    addressbook: "Adressbok",
    calendar: "Kalender",
    chat: "Chatt",
    meeting: "Möte",
    mtm: "Mail Time Machine",
    of: "av",
    webmail: "Webmail",
    modal: {
      updateAvailable: {
        title: "Uppdatering tillgänglig",
        description:
          "En <b>ny version av Webmail</b> är tillgänglig.<br/>Klicka för att ladda om och uppdatera, dina inställningar förblir oförändrade.<br/><br/>Applikationen uppdateras automatiskt mellan:",
      },
    },
  },

  avatarEditorModal: {
    photoTitle: "Ta en bild",
    title: "Redigera avatar",
    zoom: "Zooma -/+",
  },

  banner: {
    info: {
      mailRetention: "Meddelanden i den här mappen raderas automatiskt efter 30 dagar.",
    },
    warning: {
      labelCalendarUpdate:
        "Observera att om en etikett byter namn kommer den inte längre att synas i händelserna där den används.",
      labelMailUpdate:
        "Observera att om en etikett byter namn kommer den inte längre att synas i e-postmeddelandena där den används.",
      labelTaskUpdate:
        "Observera att om en etikett byter namn kommer den inte längre att synas i de aktiviteter där den används.",
      mailRetention:
        "Observera, meddelanden raderas automatiskt definitivt utan möjlighet till återställning. <b>Avbokningen kommer att träda i kraft inom 24 timmar.</b>",
    },
  },

  buttons: {
    accept: "Acceptera",
    add: "Lägg till",
    addAction: "Lägg till åtgärd",
    addAddressbook: "Adressbok",
    addAsAttachment: "Bifoga",
    addAttachments: "Lägga till bilagor",
    addCalendar: "Kalender",
    addField: "Lägg till fält",
    addHolidayCalendar: "HögtidsKalender",
    addInline: "Lägg till i rad",
    addLabel: "Lägg till etikett",
    addParameter: "Lägg till parameter",
    addSignature: "Lägg till signatur",
    addToList: "Lägg till i lista",
    allow: "Tillåt",
    apply: "Tillämpa",
    assign: "Tilldela",
    backAddressbook: "Stäng",
    backTo: "Tillbaka",
    cancel: "Avbryt",
    changeImage: "Ändra bild",
    changePassword: "Ändra lösenord",
    checkFreeBusy: "Kontrollera tillgänglighet",
    close: "Stäng",
    comeBackLater: "Kom tillbaka senare",
    configure: "Konfigurera",
    confirm: "Bekräfta",
    copied: "Kopierade",
    copy: "Kopiera",
    copyLink: "Kopiera länk",
    createFolder: "Ny mapp",
    decline: "Neka",
    delete: "Radera",
    deleteDraft: "Radera utkast",
    details: "Detaljer",
    disable: "Disable",
    disabled: "Inaktivera",
    disableOTP: "Inaktivera OTP",
    download: "Ladda ner",
    edit: "Redigera",
    editLabel: "Redigera etikett",
    editSignature: "Redigera signatur",
    empty: "Töm",
    enable: "Aktivera",
    event: "Händelse",
    export: "Exportera",
    generateNewPassword: "Skapa ett nytt lösenord",
    generateRandomPassword: "Skapa ett slumpmässigt lösenord",
    goToCalendar: "Gå till kalendern",
    goToEventDay: "Gå till eventdagen",
    goToMail: "Återgå till e-post",
    goToOldWebmail: "Gå till den gamla webbmailen",
    goToSettings: "Gå till sidan Inställningar",
    hide: "Dölj",
    ignore: "Ignorera",
    import: "Importera",
    insertHTML: "Infoga HTML",
    keep: "Ha kvar",
    label: "Etikett",
    later: "Senare",
    learnMore: "Läs mer",
    leftRotate: "Vänster rotera 90 grader",
    loadImage: "Ladda upp bild",
    loading: "Läser in",
    logout: "Logga ut",
    makePhoto: "Ta en bild",
    markRead: "Läs",
    markSeen: "Sett",
    markUnread: "Oläst",
    message: "Meddelande",
    modify: "Redigera",
    new: "Ny",
    newContact: "Ny kontakt",
    newEvent: "Ny händelse",
    newMessage: "Nytt meddelande",
    newSignature: "Ny signatur",
    newTask: "Ny uppgift",
    newWebmail: "Ny Webmail",
    next: "Nästa",
    noThanks: "Nej, tack",
    occurrence: "Förekomst",
    ok: "Ok",
    oldWebmail: "Gammal webbmail",
    openMap: "Öppna i karta",
    otherOptions: "Andra alternativ",
    override: "Åsidosätta",
    participate: "Delta",
    postpone: "Skjuta upp",
    reloadPage: "Ladda om sida",
    removeImage: "Ta bort bild",
    rename: "Döp om",
    reorder: "Ändra ordning",
    reorderEnd: "Slutför ordning",
    report: "Rapport",
    retryImport: "Försök igen",
    restore: "Be om återställning",
    save: "Spara",
    saveDraft: "Spara utkast och stäng",
    saveNextAvailability: "Spara föreslagen tillgänglighet",
    search: "Sök",
    send: "Skicka",
    series: "Serier",
    setOtp: "Ställ in OTP",
    share: "Dela",
    show: "Visa",
    showAll: "Visa allt",
    showMore: "Visa mer",
    showToDo: "Visa att göra",
    showUrlsAddressbook: "Visa adressboks-webbadresser",
    showUrlsCalendar: "Visa kalender-webbadresser",
    snooze: "Skjut upp",
    starred: "Stjärnmärk",
    subscribe: "Prenumerera",
    subscribeAddressbook: "Prenumerera på adressbok",
    subscribeCalendar: "Prenumerera på kalender",
    tentative: "Kanske",
    understand: "Jag förstår",
    unlink: "Ta bort länken",
    unsetOtp: "Inaktivera OTP",
    unsubscribe: "Avprenumerera",
    unsubscribeList: "Avsluta prenumeration",
    update: "Uppdatera",
    updateFilter: "Uppdatera filter",
    defaultImg: "Använd standardbild",
    viewMap: "Visa karta",
  },

  buttonIcons: {
    activeSync: "Synkronisera med Microsoft® Exchange ActiveSync",
    activeSyncNot: "Inaktivera Microsoft® Exchange ActiveSync",
    alignCenter: "Justera centrerat",
    alignLeft: "Justera vänster",
    alignRight: "Justera höger",
    backgroundColor: "Bakgrundsfärg",
    backTo: "Tillbaka",
    bold: "Fet",
    cannedMsg: "Standardmeddelanden",
    close: "Stäng",
    confirm: "Bekräfta",
    createTask: "Skapa uppgift",
    delete: "Radera",
    download: "Ladda ner",
    downloadVCard: "Ladda ner VCard",
    edit: "Redigera",
    emoji: "Emoji",
    forward: "Vidarebefodra",
    fullscreen: "Fullskärm",
    fullscreenNot: "Fönsterläge",
    imageAdd: "Lägg till bild",
    indent: "Öka indrag",
    insertHTML: "Infoga HTML",
    italic: "Kursiv",
    link: "Infoga länk",
    maintenance: "Kompakt",
    maxmized: "Förstora",
    minimized: "Förminska",
    more: "Mer",
    moveDown: "Flytta ner",
    moveUp: "Flytta upp",
    next: "Nästa",
    orderList: "Ordnad lista",
    outdent: "Minska indraget",
    pin: "Fäst",
    previous: "Tidigare",
    print: "Skriv ut",
    quote: "Citat",
    removeFormatting: "Ta bort formatering",
    removeQuote: "Ta bort citat",
    reply: "Svara",
    replyAll: "Svara alla",
    saveDraft: "Spara utkast",
    sendDebug: "Skicka meddelande som inte kan visas",
    sendMail: "Skicka e-post",
    sendByEmail: "Skicka via e-post",
    share: "Dela",
    showSidebar: "Visa / dölja sidofältet",
    showSourceCode: "Visa källkod",
    showVCard: "Visa VCard",
    spam: "Markera som skräppost",
    spamNot: "Markera som inte skräppost",
    startChat: "Starta chatt",
    startMeeting: "Börja möte",
    strike: "Genomstrykning",
    subscribe: "Prenumerera",
    textColor: "Text färg",
    thanks: "Tack",
    underline: "Understrykning",
    understand: "Jag förstår",
    undo: "Ångra",
    unlink: "Ta bort länken",
    unorderList: "O-ordnad lista",
    unSubscribe: "Avprenumerera",
  },

  calendar: {
    alarmDurations: {
      after: "efter",
      before: "innan",
      day: "dagar",
      hour: "timmar",
      minute: "minuter",
      second: "sekunder",
      week: "Veckor",
    },
    deleteEvent: "Radera händelse",
    deleteEventDsc: "Vill du fortsätta att radera den valda händelsen?",
    deleteSeries: "Radera serie",
    deleteSeriesDsc: "Fortsätta med raderingen av den utvalda serien?",
    event: {
      alarmsNotPresent: "Inga varningar",
      deleteEventOccurrenceTitle: "Radera händelse eller serie?",
      deleteEventOccurrenceDesc:
        "Den händelse du vill ta bort har återkommande händelser. Borttagning av den enskilda händelsen kommer att göra att påverka dom andra.",
      eventNotes: "Händelseanteckningar",
      eventAttendees: "Eventdeltagare",
      fromDay: "från",
      labelsNotPresent: "Inga etiketter",
      locationContextualMenuLabels: {
        zoomLabel: "Zoom",
        zoomHint: "Webbmöte",
        personalMeetingLabel: "Personligt mötesrum",
        personalMeetingHint: "Webbmöte",
        locationLabel: "Personligt möte",
        locationHint: "Ange en adress eller plats",
        textLabel: "Beställnings",
        textHint: "Infoga en anpassad text",
      },
      locationSelector: "Välj evenemangsplats",
      locationZoomNoMeeting: "När händelsen har sparats kommer Zoom-möteslänken att finnas här",
      maxAttachmentsNumberTitle: "För många bilagor!",
      maxAttachmentsNumberDsc:
        "Du kan ange upp till 4 bilagor. Om du behöver bifoga fler än 4 filer föreslår vi att du skapar en zippad mapp.",
      maxLabelsNumberTitle: "För många etiketter!",
      maxLabelsNumberDsc:
        "Du har nått det maximala antalet etiketter som kan kopplas till en händelse. För att lägga till en ny etikett måste du först ta bort en av de som redan finns.",
      noTitle: "Ofrälse",
      notIncludedInFreeBusy:
        "Denna kalender ingår inte i Free/Busy. Detta innebär att du och de personer du bjuder in kommer att visas som <b>lediga</b> under de händelser som skapas i denna kalender.",
      organizerTitle: "Skapad av",
      pendingMsg: "Händelse som väntar på bekräftelse",
      permissionDenied:
        "Det går inte att se detaljerna för den valda händelsen, du kanske inte har de nödvändiga behörigheterna.",
      repeatEvent: "Denna händelse är en del av återkommande händelser",
      saveEventOccurrenceTitle: "Visa händelsen eller återkommande händelser?",
      saveEventOccurrenceDesc:
        "Den händelse du vill visa eller redigera har återkommande händelser. Att redigera den enskilda händelsen kommer inte att påvera dom andra.",
      setAlert: "Ställ in varning",
      toDay: "till",
    },
    eventRepetition: {
      WeekDayNumberInMonth_1: "Första",
      WeekDayNumberInMonth_2: "Andra",
      WeekDayNumberInMonth_3: "Tredje",
      WeekDayNumberInMonth_4: "Fjärde",
      WeekDayNumberInMonth_5: "Femte",
      never: "Aldrig",
      after: "Efter;återkommanden",
      inDate: "På datum",
      end: "Avsluta repetition",
    },
    filterView: {
      listmonth: "Dagordning",
      day: "Dag",
      month: "Månad",
      week: "Vecka",
      workWeek: "Arbetsvecka",
      year: "År",
    },
    import: {
      contactsInvalid: "Inte giltig:",
      contactsNr: "Totalt antal händelser som ska importeras:",
      contactsValid: "Giltig:",
      dropFiles: "Ladda upp eller släpp filen som ska importeras, här",
      error: "Händelser kunde inte importeras",
      importing:
        "Vi importerar händelsen <b>{{eventsNumber}}</b> i kalendern: <code>{{calendarImport}}</code> ",
      info: "Du importerar händelser till kalendern: <code>{{calendarImport}}</code> <br/> Du kan importera händelser från andra e-postprogram med ett ICS-filformat. Du kan till exempel exportera händelser från Gmail eller från Outlook i ICS-format och importera dem till Qboxmail. <br/> <b>Importen kommer inte att ersätta någon av de befintliga händelserna</b>.",
      loading: "Läser in...",
      success: "Alla dina händelser har importerats framgångsrikt!",
      title: "Importera händelser",
      uploadedFile: "Uppladdad",
      uploadingFile: "Uppladdning",
    },
    modifyCalendarModal: {
      desc: "",
      title: "Redigera kalender",
    },
    newCalendarModal: {
      desc: "",
      title: "Lägg till kalender",
      freeBusyInfo:
        "Om kalendern inte ingår i <b>Free/Busy</b> kommer du och de personer du bjuder in att visas som <b>lediga</b> under de händelser som skapas i denna kalender.",
    },
    newEvent: {
      attachmentsList: {
        headerItem: "Bilagor",
        placeholderList: "",
      },
      desc: "",
      dropFiles:
        "Ladda upp eller släpp filen som ska bifogas, här<br>(max 4 bilagor, 3 MB vardera)",
      freeBusy: {
        legend: {
          event: "Händelse",
          busy: "Upptagen",
          waiting: "Väntar",
          availability: "Nästa tillgänglighet",
        },
      },
      hideDetails: "Göm detaljer",
      participantsList: {
        headerItem: "Deltagare",
        answeredHeaderItem: "Besvarad",
        notAnsweredHeaderItem: "Väntar på ett svar",
        placeholderList: "",
      },
      showDetails: "Visa detaljer",
      tabAttachments: "Bilagor",
      tabDetails: "Detaljer",
      tabParticipants: "Deltagare",
      tabSeries: "Upprepningar",
      tabSettings: "Inställningar",
      title: "Skapa händelse",
      titleEdit: {
        event: "Händelse",
        series: "Serier",
      },
      titleFreebusy: "Deltagarnas tillgänglighet",
    },
    nextAvailability: "Nästa tillgänglighet",
    searchEvents: {
      notFound: "Inga händelser hittade",
      notFoundInfo: "Sökningen gav inga resultat, försök igen med andra kriterier.",
    },
    shareModal: {
      desc: "Du delar kalendern: <code>{{calendarShare}}</code> <br/> Välj de kontakter du vill dela kalendern med och låta dem hantera. ",
      title: "Dela kalender",
    },
    sidebar: {
      labels: "Etiketter",
      personalCalendar: "Personlig kalender",
      sharedCalendars: "Delade kalendrar",
      userCalendars: "Användares kalendrar",
      deleteCalendarDsc:
        "Genom att radera kalendern <code>{{calendar}}</code> raderas alla inkluderade händelser. <br/> <b>Åtgärden är inte reversibel</b>.",
      deleteCalendarTitle: "Radera kalender",
    },
    subscribeModal: {
      desc: "",
      noCalendar: "Det finns inga kalendrar att prenumerera på",
      title: "Prenumerera på en delad kalender",
    },
    today: "Idag",
  },

  circularLoopBar: {
    uploading: "Laddar upp",
  },

  comingSoon: "Under utveckling...",

  contactImport: {
    title: "Söker efter kontakter",
    desc: "Vi importerar dina gamla kontakter. Det kan ta lite tid, vänta.",
  },

  datasets: {
    actionsFlags: {
      "\\\\Answered": "Besvarad",
      "\\\\Deleted": "Raderad",
      "\\\\Draft": "Utkast",
      "\\\\Flagged": "Flaggad",
      "\\\\Seen": "Läst",
    },
    antispamFilterTypes: {
      whitelist_from: "Tillåt från",
      whitelist_to: "Tillåt till",
    },
    calendarMinutesInterval: {
      15: "15 minuter",
      30: "30 minuter",
      60: "60 minuter",
    },
    calendarNewEventFreeBusy: {
      busy: "Upptagen",
      free: "Ledig",
      outofoffice: "Inte på kontoret",
      temporary: "Tillfällig",
    },
    calendarNewEventPartecipation: {
      ACCEPTED: "Acceptera",
      DECLINED: "Neka",
      TENTATIVE: "Kanske",
    },
    calendarNewEventParticipationRoles: {
      CHAIR: "Ordförande",
      "REQ-PARTICIPANT": "Begärt",
      "OPT-PARTICIPANT": "Ej begärt",
      "NON-PARTICIPANT": "För informationsändamål",
    },
    calendarNewEventPriority: {
      0: "Ingen",
      1: "Hög",
      5: "Medium",
      9: "Låg",
    },
    calendarNewEventTypes: {
      public: "Offentlig",
      confidential: "Konfidentiell",
      private: "Privat",
    },
    calendarStartWeekDay: {
      saturday: "Lördag",
      sunday: "Söndag",
      monday: "Måndag",
    },
    calendarView: {
      year: "År",
      month: "Månad",
      week: "Vecka",
      workWeek: "Arbetsvecka",
      day: "Dag",
      listmonth: "Lista",
    },
    calendarEventFilterBy: {
      allEvents: "Alla",
      nextEvents: "Alla nästa händelser",
    },
    calendarEventSearchIn: {
      title: "Titel/etiketter/plats",
      all: "Fullt innehåll",
    },
    cancelSendTimer: {
      0: "Inaktiverad",
      5000: "5 sekunder",
      10000: "10 sekunder",
      20000: "20 sekunder",
      30000: "30 sekunder",
    },
    contactNameFormat: {
      firstName: "Förnamn, Efternamn",
      lastName: "Efternamn, Förnamn",
    },
    contactsOrder: {
      firstName: "Förnamn",
      lastName: "Efternamn",
    },
    countries: {
      AD: "Andorra",
      AE: "United Arab Emirates",
      AG: "Antigua & Barbuda",
      AI: "Anguilla",
      AL: "Albania",
      AM: "Armenia",
      AO: "Angola",
      AR: "Argentina",
      AS: "American Samoa",
      AT: "Austria",
      AU: "Australia",
      AW: "Aruba",
      AX: "Åland Islands",
      AZ: "Azerbaijan",
      BA: "Bosnia and Herzegovina",
      BB: "Barbados",
      BD: "Bangladesh",
      BE: "Belgium",
      BF: "Burkina Faso",
      BG: "Bulgaria",
      BH: "Bahrain",
      BI: "Burundi",
      BJ: "Bénin",
      BL: "Saint Barthélemy",
      BM: "Bermuda",
      BN: "Brunei",
      BO: "Bolivia",
      BQ: "Bonaire, Sint Eustatius and Saba",
      BR: "Brasil",
      BS: "Bahamas",
      BW: "Botswana",
      BY: "Belarus",
      BZ: "Belize",
      CA: "Canada",
      CC: "Cocos (Keeling) Islands",
      CD: "Democratic Republic of the Congo",
      CF: "Central African Republic",
      CG: "Republic of the Congo",
      CH: "Switzerland",
      CL: "Chile",
      CM: "Cameroun",
      CN: "China",
      CO: "Colombia",
      CR: "Costa Rica",
      CU: "Cuba",
      CV: "Cabo Verde",
      CW: "Curaçao",
      CX: "Christmas Island",
      CY: "Cyprus",
      CZ: "Czech Republic",
      DE: "Germany",
      DK: "Denmark",
      DM: "Dominica",
      DO: "Dominican Republic",
      EC: "Ecuador",
      EE: "Estonia",
      ES: "Spain",
      ET: "Ethiopia",
      FI: "Finland",
      FO: "Faroe Islands",
      FR: "France",
      GA: "Gabon",
      GB: "United Kingdom",
      GD: "Grenada",
      GF: "French Guiana",
      GG: "Guernsey",
      GI: "Gibraltar",
      GL: "Greenland",
      GP: "Guadeloupe",
      GQ: "Equatorial Guinea",
      GR: "Greece",
      GT: "Guatemala",
      GU: "Guam",
      GY: "Guyana",
      HN: "Honduras",
      HR: "Croatia",
      HT: "Haiti",
      HU: "Hungary",
      IE: "Ireland",
      IM: "Isle of Man",
      IS: "Island",
      IT: "Italy",
      JE: "Jersey",
      JM: "Jamaica",
      JP: "Japan",
      KE: "Kenya",
      KR: "South Korea",
      LI: "Lichtenstein",
      LS: "Lesotho",
      LT: "Lithuania",
      LU: "Luxembourg",
      LV: "Latvia",
      MC: "Monaco",
      MD: "Moldova",
      ME: "Montenegro",
      MG: "Madagascar",
      MK: "North Macedonia",
      MQ: "Martinique",
      MT: "Malta",
      MW: "Malawi",
      MX: "Mexico",
      MZ: "Mozambique",
      NA: "Namibia",
      NI: "Nicaragua",
      NL: "Netherlands",
      NO: "Norway",
      NZ: "New Zealand",
      PA: "Panama",
      PE: "Perú",
      PH: "Philippines",
      PL: "Poland",
      PT: "Portugal",
      PY: "Paraguay",
      RE: "Réunion",
      RO: "Romania",
      RS: "Serbia",
      RU: "Russia",
      RW: "Rwanda",
      SE: "Sweden",
      SG: "Singapore",
      SH: "Saint Helena",
      SI: "Slovenia",
      SJ: "Svalbard & Jan Mayen",
      SK: "Slovakia",
      SM: "San Marino",
      SO: "Somalia",
      SS: "South Sudan",
      SV: "El Salvador",
      TG: "Togo",
      TO: "Tonga",
      TR: "Turkey",
      TZ: "Tanzania",
      UA: "Ukraine",
      UG: "Uganda",
      US: "United States of America",
      UY: "Uruguay",
      VA: "Città del Vaticano",
      VE: "Venezuela",
      VN: "Vietnam",
      XK: "Kosovo",
      YT: "Mayotte",
      ZA: "South Africa",
      ZM: "Zambia",
      ZW: "Zimbabwe",
    },
    deliveryNotifications: {
      always: "Be alltid om leveransbekräftelse",
      never: "Be aldrig om leveransbekräftelse",
    },
    markReadAfter: {
      manually: "Manuellt",
      onOpen: "När meddelandet är öppet",
      5000: "Efter 5 sekunder",
      10000: "Efter 10 sekunder",
      30000: "Efter 30 sekunder",
    },
    eventAlarmPostponeTime: {
      60: "i 1 minut",
      300: "i 5 minuter",
      900: "i 15 minuter",
      1800: "i 30 minuter",
      3600: "i 1 timme",
      7200: "i 2 timmar",
      86400: "i 1 dag",
      604800: "i 1 vecka",
    },

    eventTimeIntervals: {
      5: "i 5 minuter",
      10: "i 10 minuter",
      15: "i 15 minuter",
      20: "i 20 minuter",
      30: "i 30 minuter",
    },

    calendarTaskStatus: {
      "NEEDS-ACTION": "Behöver åtgärd",
      COMPLETED: "Slutförd",
      PROCESS: "Pågår",
      CANCELLED: "Avbruten",
    },

    feedbackAreas: {
      addressbookSidebar: "Adressbokslista",
      contactList: "Kontaktlista",
      contactView: "Kontaktvisning",
      mailSearch: "Sök meddelanden",
      mailSidebar: "Mapplista",
      messageList: "Meddelandelista",
      messageView: "Meddelandevisning",
      newMessage: "Nytt meddelande",
      other: "Mer",
      settings: "Inställningar",
    },
    filterMail: {
      all: "Allt",
      byDate: "Datum",
      byFrom: "Från",
      bySize: "Storlek",
      bySubject: "Ämne",
      flagged: "Markerad",
      filter: "Filter",
      orderBy: "Sortera efter",
      seen: "Läst",
      unseen: "Oläst",
    },
    filtersActions: {
      discard: "Ta bort",
      addflag: "Markera meddelande som",
      setkeyword: "Lägg till etikett",
      fileinto: "Flytta meddelande i",
      fileinto_copy: "Kopiera meddelande i",
      keep: "Behåll meddelandet",
      redirect: "Omdirigera meddelande till",
      redirect_copy: "Skicka kopia till",
      reject: "Avvisa med följande meddelande",
      stop: "Sluta bearbeta filter",
    },
    filtersDateOperators: {
      gt: "Efter",
      is: "är lika med",
      lt: "Före",
      notis: "är inte lika med",
    },
    filtersEnvelopeSubtypes: {From: "Från", To: "Till"},
    filtersDateSubTypes: {date: "Datum", time: "Tid", weekday: "Veckodag"},
    filtersDateWeekdays: {
      monday: "Måndag",
      tuesday: "Tisdag",
      wednesday: "Onsdag",
      thursday: "Torsdag",
      friday: "Fredag",
      saturday: "Lördag",
      sunday: "Söndag",
    },
    filtersRules: {
      Bcc: "Hemlig kopia (Bcc)",
      body: "Kropp",
      Cc: "Kopia (Cc)",
      currentdate: "Incheckningsdatum",
      envelope: "Meddelande",
      From: "Skicka",
      other: "Alternativ rubrik",
      size: "Storlek",
      Subject: "Ämne",
      To: "Mottagare",
    },
    filtersSizeMUnits: {B: "Bytes", K: "Kilobytes", M: "Megabytes"},
    filtersSizeOperators: {over: "är större än", under: "är mindre än"},
    filtersStringOperators: {
      contains: "Innehåller",
      exists: "existerar",
      is: "är lika med",
      notcontains: "inte innehålla",
      notexists: "finns inte",
      notis: "är inte lika med",
    },
    fontSize: {
      extraSmall: "Extra liten",
      huge: "Enorm",
      large: "Stor",
      medium: "Medium",
      normal: "Vanligt",
      small: "Liten",
    },
    languages: {
      de: "Tysk",
      en: "Engelska",
      fr: "Franska",
      gr: "Grekisk",
      it: "Italienska",
      nl: "Dutch",
      sv: "Svenska",
      es: "Spanska",
      pt: "Portugisiska",
    },
    mailRetention: {
      0: "Aldrig",
      30: "äldre än 1 månad",
      90: "äldre än 3 månader",
      180: "äldre än 6 månader",
      365: "äldre än 1 år",
      730: "äldre än 2 år",
      1095: "äldre än 3 år",
      1460: "äldre än 4 år",
      1825: "äldre än 5 år",
    },
    matchTypes: {
      allof: "Tillfredsställ alla parametrar",
      anyof: "Tillfredsställ minst en parameter",
    },
    newAllDayEventAlert: {
      never: "Aldrig",
      eventDate: "Händelsedatum",
      "-PT17H": "En dag innan, kl. 9",
      "-P6DT17H": "En vecka innan, kl. 9",
    },
    newEventAlert: {
      never: "Aldrig",
      eventHour: "Starttid för evenemang",
      //P[n]Y[n]M[n]DT[n]H[n]M[n]S
      "-PT5M": "5 minuter före",
      "-PT10M": "10 minuter före",
      "-PT15M": "15 minuter före",
      "-PT30M": "30 minuter före",
      "-PT1H": "1 timme före",
      "-PT2H": "2 timmar innan",
      "-PT12H": "12 timmar före",
      "-P1D": "1 dag innan",
      "-P7D": "1 vecka innan",
    },
    newEventRepeatDayWeek: {
      MO: "Måndag",
      TU: "Tisdag",
      WE: "Onsdag",
      TH: "Torsdag",
      FR: "Fredag",
      SA: "Lördag",
      SU: "Söndag",
    },
    newEventRepeatFrequency: {
      NEVER: "Aldrig",
      DAILY: "Dagligen",
      WEEKLY: "Veckovis",
      MONTHLY: "Månadsvis",
      YEARLY: "Årligen",
    },
    newEventRepeatMonths: {
      1: "Januari",
      2: "Februari",
      3: "Mars",
      4: "April",
      5: "Maj",
      6: "Juni",
      7: "Juli",
      8: "Augusti",
      9: "September",
      10: "Oktober",
      11: "November",
      12: "December",
    },
    orderSelector: {
      byLastname: "Efternamn",
      byMail: "E-post",
      byName: "Förnamn",
      byOrg: "Företag",
      orderBy: "Sortera efter",
      showOnlyLists: "Visa endast listor",
    },
    readConfirmations: {
      always: "Be alltid om läsbekräftelse",
      never: "Be aldrig om läsbekräftelse",
    },
    readingConfirmation: {
      always: "Alltid",
      ask: "Fråga alltid",
      never: "Aldrig",
    },
    selectMail: {
      all: "Alla",
      cancel: "Avbryt",
      modify: "Redigera",
      none: "Avmarkera",
      select: "Välj",
    },
    shareOptionsCalendar: {
      None: "Ingen",
      DAndTViewer: "Visa datum och tid",
      Viewer: "Visa alla",
      Responder: "Svara",
      Modifier: "Ändra",
    },
    showImages: {
      always: "Alltid",
      contacts: "Kontakter och betrodda",
      never: "Aldrig",
    },
    themes: {
      dark: "Mörk",
      light: "Ljus",
    },
    timeFormats: {
      "12h": "12h",
      "24h": "24h",
    },
    viewMode: {
      label: {
        viewColumns: "Kolumner",
        viewHalf: "Förhandsvisa",
        viewFull: "Lista",
      },
      desc: {
        viewColumns: "Visa tre kolumners layout med läsrutan till höger på skärmen.",
        viewHalf: "Visa två kolumners layout med läsrutan längst ner på skärmen.",
        viewFull:
          "Visa två kolumners layout med bara meddelandelista. Läsfönstret visar hela sidan vid klick.",
      },
    },
  },

  dropdownMenu: {
    activesync: "Microsoft® ActiveSync",
    delete: "Radera",
    download: "Ladda ner",
    edit: "Redigera",
    exportContacts: "Exportera kontakter",
    feedback: "Feedback",
    importContacts: "Importera kontakter",
    importEvents: "Importera händelser",
    news: "News & Updates",
    remove: "Avlägsna",
    rename: "Döp om",
    share: "Dela",
    shortcuts: "Tangentbordsgenvägar",
    syncNo: "Synkronisera inte",
    syncYes: "Synkronisera",
    unsubscribe: "Avprenumerera",
  },

  dropdownUser: {
    feedback: "Feedback",
    logout: "Logga ut",
    settings: "Inställningar",
  },

  errors: {
    emailDomainAlreadyPresent: "E-postadress eller domän finns redan",
    emptyField: "Tomt fält",
    invalidEmail: "Ogiltig e-post",
    invalidEmailDomain: "E-postadressen eller domänen är inte giltig",
    invalidPassword: "Ogiltigt lösenord",
    invalidPasswordFormat: "Ogiltigt format, ange minst 8 alfanumeriska tecken",
    invalidValue: "Ogiltigt värde",
    mandatory: "Obligatoriskt fält",
    notAllowedCharacter: "Otillåtet tecken",
    notChanged: "Oändrat fält",
    permissionDenied: "Åtkomst nekad",
    tooLong: "För långt fält",
  },

  feedback: {
    disclaimer:
      "Skicka feedback och hjälp oss att förbättra tjänsten.<br/>Kontakta supporten för eventuella frågor eller problem, relaterade till användningen av webbmail.",
    labels: {
      feedbackAreas: "På vilket område du vill lämna feedback?",
      note: "Lämna ett meddelande (valfritt)",
    },
    msgError: {
      title: "Din feedback kunde inte skickas",
      desc: "Försök igen senare, det är viktigt för oss att veta vad du tycker om vår webbmail. Din feedback kommer att hjälpa oss skapa en bättre upplevelse för dig och alla våra användare.",
    },
    msgSuccess: {
      title: "Tack för din feedback!",
      desc: "Vi uppskattar verkligen tiden du tog för att hjälpa oss förbättra vår webbmail. Din feedback kommer att hjälpa oss skapa en bättre upplevelse för dig och för alla våra användare.",
    },
    privacy:
      "De insamlade uppgifterna kommer att behandlas i enlighet med den nuvarande lagstiftningen om integritet.",
    title: "Feedback",
  },

  inputs: {
    labels: {
      addAddress: "Lägg till adress",
      addContactToAddressbook: "Lägg till kontakt i adressboken",
      addDomain: "Lägg till adress eller domän",
      addLabel: "Etikettnamn",
      addMembers: "Lägg till medlemmar",
      addParticipant: "Lägg till deltagare",
      addressbookName: "Adressbok",
      addUser: "Lägg till användare",
      alert2: "Andra varning",
      alert: "Varna",
      assignTask: "Tilldela uppgift till",
      at: "vid",
      calendar: "Kalender",
      calendarBusinessDayEndHour: "Arbetsdagens slut",
      calendarBusinessDayStartHour: "Arbetsdagens start",
      calendarColor: "Kalenderfärg",
      calendarMinutesInterval: "Kalender tidsintervall",
      calendarName: "Kalendernamn",
      calendarView: "Standardläge",
      company: "Företag",
      companyName: "Namn",
      confidentialEvents: "Konfidentiella händelser",
      confirmNewPassword: "Bekräfta lösenord",
      contactNameFormat: "Visa efter",
      contactsOrder: "Sortera kontakter efter",
      contains: "Innehåller",
      country: "Land",
      dateFormat: "Datumformat",
      dateInterval: "Date interval",
      defaultAddressbook: "Standard adressbok",
      defaultCalendar: "Standardkalender",
      displayName: "Visnings Namn",
      email: "E-post",
      encryptionMethod: "Krypteringsmetod",
      endDate: "Slutdatum",
      event: "Händelse",
      eventDailyRepetition: "Varje;dag/ar",
      eventDailyWorkdayRepetition: "Varje veckodag",
      eventMonthlyLastDayRepetition: "Sista dagen i månaden, varje;månad/er",
      eventMonthlyLastWeekDayRepetition: "Senaste {{WeekDay}}, varje;månad/er",
      eventMonthlyRepetition: "Den {{DayNumber}} varje;månad/er",
      eventMonthlyWeekDayRepetition: "Den {{WeekDayNumber}} varje;månad/er",
      eventPartecipation: "Deltagarestatus",
      eventPriority: "Händelseprioritet",
      eventType: "Händelsetyp",
      eventWeeklyRepetition: "Varje;vecka/or, den:",
      eventYearlyLastDayRepetition: "Sista dagen i {{Month}}, varje;år",
      eventYearlyLastWeekDayRepetition: "Sista {{WeekDay}} av {{Month}}, varje;år",
      eventYearlyRepetition: "Den {{DayNumber}} av {{Month}}, varje;år",
      eventYearlyWeekDayRepetition: "Den {{WeekDayNumber}} av {{Month}} varje;år",
      exportAsLdiff: "Exportera i LDIF-format",
      exportAsVcard: "Exportera i VCard-format",
      faxHome: "Fax hem",
      faxWork: "Fax arbete",
      filter: "Filtrera efter",
      filterName: "Regelnamn",
      firstName: "Förnamn",
      folderName: "Mapp namn",
      freeBusy: "Visa som",
      from: "Från",
      fromDate: "Från datum",
      home: "Hem",
      hour: "Tid",
      includeFreeBusy: "Inkludera i Free/Busy",
      label: "Etikett",
      labelColor: "Etikettfärg",
      language: "Språk",
      lastName: "Efternamn",
      linkText: "Visad text",
      linkURL: "Webbadress (URL)",
      listName: "Namnlista",
      location: "Plats",
      loginAddressbook: "Initiell adressbok",
      mailAccount: "Konto",
      mailRetention: "Ta bort mappens meddelanden",
      mailRetentionDefault: "Radering av meddelanden ställs automatiskt in på 30 dagar",
      mailRetentionDiscalimer:
        "Observera, meddelanden raderas automatiskt definitivt utan möjlighet till återställning. Avbokningen kommer att träda i kraft inom 24 timmar.",
      mailRetentionHint:
        "Ange tidsintervallet, efter att du tagit emot meddelandet, för att fortsätta med automatisk radering.",
      markReadAfter: "Markera meddelandet som läst",
      mobile: "Mobil",
      newAddressBook: "Ny adressbok",
      newAddressBookMobile: "Ny adressbok",
      newAllDayEventAlert: "Ny varning vid heldagshändelse",
      newBcc: "Lägg till mottagare av hemlig kopia (Bcc)",
      newCalendar: "Ny kalender",
      newEventAlert: "Varning om nya händelser",
      newForward: "Lägg till mottagare i listan",
      newPassword: "Nytt lösenord",
      nickname: "Smeknamn",
      object: "Ämne",
      oldPassword: "Nuvarande lösenord",
      parentFolder: "Sökväg",
      password: "Password",
      personalMeetingRoom: "Länk till personligt mötesrum",
      phone: "Telefon",
      port: "Port",
      portFor: "Port for",
      priority: "Priority",
      privateEvents: "Privata händelser",
      publicEvents: "Offentliga händelser",
      readingConfirmation: "Skicka läsbekräftelse",
      recoveryEmail: "Återställnings e-post",
      renameAddressbook: "Byt namn på adressbok",
      repeatEvery: "Upprepa",
      reportBugNote: "Problembeskrivning",
      reportBugPhoneNumber: "Telefonnummer",
      searchAddressbookToSubscribe: "Sök efter en användare för att se deras delade adressböcker",
      searchCalendarToSubscribe: "Sök efter en användare för att se deras delade kalendrar",
      searchIn: "Sök i",
      selectCalendar: "Välj kalender",
      selectIdentity: "Välj identitet",
      selectList: "Välj lista",
      selectSnapshotDate: "Välj datum",
      serverName: "Server namn",
      shareCalendarCalDAVURL: "CalDAV URL",
      shareCalendarWebDavICSURL: "WebDAV ICS URL",
      shareCalendarWebDavXMLURL: "WebDAV XML URL",
      shareToAddressbook: "Med vem du vill dela adressboken?",
      shareToCalendar: "Med vem du vill dela kalendern?",
      shareToFolder: "Vem du vill dela mappen med?",
      showImages: "Visa bilder",
      signatureName: "Visningsnamn",
      signatureText: "Signaturtext",
      startDate: "Startdatum",
      team: "Team",
      templateName: "Namn",
      templateSubject: "Ämne",
      templateText: "Meddelandetext",
      theme: "Tema",
      timeFormat: "Tidsformat",
      timezone: "Tidszon",
      title: "Titel",
      to: "Till",
      untilDate: "Fram till dagen",
      username: "Username",
      weekStart: "Veckans första dag",
      work: "Arbete",
    },
    placeholder: {
      addressbookName: "Adressboknamn",
      birthday: "Födelsedag",
      city: "Stad",
      company: "Företag",
      country: "Land",
      customText: "Ange en anpassad text",
      email: "E-post",
      endDate: "Slutdatum",
      firstName: "Förnamn",
      lastName: "Efternamn",
      members: "Medlemmar",
      newFolderName: "Nytt mappnamn",
      newNameAddressbook: "Nytt adressboknamn",
      newPassword: "Minst åtta alfanumeriska tecken",
      note: "Anteckning",
      password: "Ditt password",
      phone: "Telefon",
      place: "Ange en gata eller plats",
      postCode: "Postnummer",
      region: "Område",
      role: "Roll",
      search: "Sök",
      searchActivity: "Sökaktivitet",
      searchEvent: "Sök händelse",
      searchUser: "Sök efter användare på din domän",
      select: "Välj",
      snooze: "Skjut upp larm",
      startDate: "Start datum",
      street: "Gata",
    },
    hint: {
      cancelSendMessage:
        "Välj den tid som är tillgänglig för att dra tillbaka ett meddelande under sändningen, om du bestämmer dig för att du inte vill skicka e-postmeddelandet.",
      newForward: "Du kan lägga till upptill {{max}} vidarebefodringsadresser.",
      newBcc: "Du kan lägga till upp till {{max}} mottagare av hemlig kopia (Bcc).",
      mailRetention:
        "Ange tidsintervallet, efter att du tagit emot meddelandet, för att fortsätta med automatisk radering",
      passwordScore: {
        check: "Lösenordsstyrka",
        poor: "Mycket dåligt lösenord",
        easy: "Lösenordet är för enkelt",
        weak: "Lösenordet är för svagt",
        strong: "Starkt lösenord",
        great: "Bra lösenord!",
      },
    },
  },

  labels: {
    attendees: "Deltagare",
    calendarAdvancedSearch: "Var vill du söka?",
    clearAdvancedFilters: "Rensa filter",
    clearFields: "Rensa fält",
    default: "Standard",
    forDomain: "På domän",
    forward: "Fwd",
    holidayCalendar: "Högtider",
    organizer: "organisatör",
    otherFilters: "Other filters",
    searchResults: "Sökresultat",
    withAllUsers: "Med alla användare",
  },

  loaderFullscreen: {
    descriptionEvents: "Dina händelser kommer, vänligen vänta.",
    description: "Innehållet är på väg, vänta.",
    descriptionFolder: "Dina mappar är på väg, vänta.",
    title: "Läser in",
    titleEvent: "Laddar händelse",
  },

  mail: {
    confirmMailLabel: "OK, jag bekräftar!",
    contextualMenuLabels: {
      addAddressBook: "Lägg till i adressbok",
      addEvent: "Lägg till händelse",
      alarm: "Larm",
      archive: "Arkivera",
      archiveThread: "Arkivera tråd:",
      backTo: "Tillbaka",
      cancel: "Avbryt",
      close: "Stäng",
      confirm: "Bekräfta",
      copyIn: "Kopiera till",
      copyThreadIn: "Kopiera tråd",
      delete: "Radera",
      deletePerm: "Radera permanent",
      deleteThread: "Ta bort tråd",
      deleteXMessages: "Radera {{MessagesNumber}} meddelanden",
      deliveryNotification: "Leveransbekräftelse",
      download: "Ladda ner",
      editAsNew: "Redigera som nytt",
      emptySpam: "Mark skräppost läst",
      emptyTrash: "Töm papperskorgen",
      forward: "Vidarebefodra",
      import: "Importera e-post",
      label: "Etikett",
      labelsManagement: "Hantera etiketter",
      labelThread: "Etiketttråd",
      markAllAsRead: "Markera allt som läst",
      markAs: "Markera som",
      markThreadAs: "Markera tråd",
      manageFolders: "Hantera mappar",
      modify: "Redigera",
      more: "Mer",
      moveThreadTo: "Flytta tråd",
      moveTo: "Flytta till",
      newSubFolder: "Lägg till undermapp",
      plainText: "Vanligt textläge",
      print: "Skriv ut",
      priorityHigh: "Hög prioritet",
      readed: "Läs",
      readedNot: "Oläs",
      readingNotification: "Bekräftelse av läsning",
      rename: "Döp om",
      reply: "Svara",
      replyToAll: "Svara alla",
      restore: "Återställ",
      restoreThreadIn: "Återställ tråd",
      restoreIn: "Återställ till",
      sendAsAttachment: "Vidarebefordra som bilaga",
      showSourceCode: "Visa källkod",
      spam: "Spam",
      spamNot: "Ej spam",
      starred: "Stjärnmärk",
      starredNot: "Ta bort stjärna",
      thanks: "Tacka",
      thread: "Trådåtgärder",
    },
    deleteMailDsc:
      "Om ett lagringssystem inte är aktivt kommer meddelandet att raderas permanent.<br/><b>Åtgärden är inte reversibel</b>.",
    deleteMailTitle: "Radera meddelande",
    deleteMailsDsc:
      "Om ett lagringssystem inte är aktivt raderas meddelandena permanent. <br/><b>Åtgärden är inte reversibel <b>.",
    deleteMailsTitle: "Radera valda meddelanden",
    dropFiles: "Släpp filerna att bifoga här",
    emptyTrashDsc:
      "Om ett lagringssystem inte är aktivt vid tömning av papperskorgen, kommer alla meddelanden att tas bort <b>oåterkallerligt</b>.<br/> Efter<b>30 dagar</b> raderas meddelandena automatiskt. ",
    emptyTrashTitle: "Töm papperskorgen",
    goToOldWebmailModal: {
      description:
        "<br/>Vi inbjuder dig att omedelbart använda den nya webbmailen, som erbjuder ytterligare funktioner som: <br/> <ul> <li> Automatisk identitetshantering </li> <li> Delad adressbok och kalender </ li > <li> Zoomintegration för videomöten </li> <li> Fördefinierade meddelanden </li> <li> Sök i alla mappar </li> <li> och fler funktioner </li> </ul>",
      title:
        "Den gamla webbmailen kommer inte längre att vara tillgänglig från och med den 31 oktober",
    },
    import: {
      messagesInvalid: "Inte giltig:",
      messagesNr: "Totalt antal meddelande som ska importeras:",
      messagesValid: "Giltig:",
      desc: "Du importerar meddelanden i mappen: <code>{{folderImport}}</code><br/> Du kan importera meddelanden från andra e-postprogram med en eml-fil (<strong>.eml</strong>).",
      dropFiles: "Ladda upp eller släpp här filen som ska importeras",
      error: "Meddelanden kunde inte importeras",
      importing:
        "Vi importerar <b>{{messagesNumber}}</b> meddelanden i mappen: <code>{{folderImport}}</code> ",
      loading: "Läser in...",
      success: "Importera framgångsrik!",
      title: "Importera meddelanden",
      uploadedFile: "Uppladdad",
      uploadingFile: "Laddar upp",
    },
    loading: {
      desc: "Dina meddelanden kommer, vänta.",
      title: "Läser in",
    },
    markSpamReadDsc:
      "Markera alla meddelanden i mappen som lästa. <br/>Efter<b>30 dagar</b> raderas meddelandena automatiskt. ",
    markSpamReadTitle: "Markera meddelanden som lästa",
    maxLabelsNumberTitle: "För många etiketter!",
    maxLabelsNumberDsc:
      "Du har nått det maximala antalet etiketter som kan kopplas till ett meddelande. För att lägga till en ny etikett måste du först ta bort en av de som redan finns.",
    message: {
      add: "Lägg till",
      addToAddressBook: "Lägg till kontakt i adressboken",
      attachedMessage: "Bifogat meddelande",
      attachments: "bilagor",
      bugMsg: "Ser du inte meddelandet?",
      cc: "Kopia (Cc):",
      date: "Datum:",
      draftsSelectedInfo: "Välj ett meddelande från listan och fortsätt att skriva.",
      downloadAll: "Ladda ner allt",
      downloadAttachments: "Ladda ner bilagor",
      editPartecipationStatusDecription: "",
      editPartecipationStatusTitle: "Redigera deltagarestatus",
      eventActionAccept: "Acceptera",
      eventActionDecline: "Neka",
      eventActionTentative: "Preliminär",
      eventAddToCalendar: "Den här händelsen finns inte i din kalender",
      eventAttendees: "Deltagare:",
      eventAttendeeStatusAccepted: "Händelse accepterad",
      eventAttendeeStatusDeclined: "Händelse avvisad",
      eventAttendeeStatusTentative: "Preliminär för deltagande",
      eventCounterProposal: "Det här meddelandet innehåller ett motförslag för händelsen",
      eventDeleted: "Händelse raderad",
      eventInvitation: "Händelseinbjudan:",
      eventLocationEmpty: "Ej angivet",
      eventModify: "Redigera",
      eventNeedAction: "Det här meddelandet innehåller en ny händelse",
      eventNotNeedAction: "Det här meddelandet innehåller en händelse som du redan har behandlat",
      eventOutDated: "Den här händelsen har ändrats",
      eventStatusAccepted: "Accepterad",
      eventStatusDeclined: "Nekad",
      eventStatusTentative: "Preliminär",
      eventUpdate: "Uppdatera händelse",
      external: "Extern",
      externalLabel: "Den här e-postadressen kommer utanför din organisation.",
      folderSelectedInfo: "Välj ett meddelande från listan och upptäck innehållet.",
      from: "Från:",
      hideAllAttachments: "Dölj",
      hugeMessage:
        "Innehåll för stort för att visas helt, klicka på länken nedan för att se meddelandekällkoden.",
      hugeMessageNotice: "Meddelandet trunkerat",
      inboxSelectedInfo:
        "Välj ett meddelande från listan och ta reda på vem som har skrivit till dig.",
      isMailingList: "Det här meddelandet kommer från en e-postlista.",
      localAttachments: "Det finns ytterligare bilagor i evenemanget",
      message: "meddelande",
      messageForwarded: "Vidarebefordrat meddelande",
      messages: "meddelanden",
      messagesQuota: "Använda meddelandekvot:",
      newMessageinThread: "Det finns ett nytt meddelande",
      noContent: "This message has no content.",
      notSelected: "Välj ett meddelande",
      oneSelectMessages: "Valt meddelande",
      oneSelectThreads: "Vald tråd",
      readNotificationLabel: "{{Sender}} frågade efter läsbekräftelse för meddelandet.",
      readNotificationLabelSimple: "Frågade om läsningsbekräftelse för meddelande.",
      readNotificationResponse:
        "<P>Meddelande<BR><BR>&nbsp;&nbsp;&nbsp; A:&nbsp; %TO%<BR>&nbsp;&nbsp;&nbsp; Ämne:&nbsp; %SUBJECT%<BR>&nbsp;&nbsp;&nbsp; Skickat:&nbsp; %SENDDATE%<BR><BR>det lästes den %READDATE%.</P>",
      readNotificationSubjectPrefix: "Läs:",
      replyTo: "Svara till:",
      sender: "Avsändare:",
      sentSelectedInfo: "Välj ett meddelande från listan och se vem du skrev till.",
      showAllAttachments: "Visa andra",
      showMoreThread: "Visa mer",
      selectMessages: "Valda meddelanden",
      selectThreads: "Vald tråd",
      spamNotSelected: "Håll mappen ren",
      spamSelectedInfo: "Kontrollera meddelanden och markera skräppost som läst.",
      subject: "Ämne:",
      to: "Till:",
      trashNotSelected: "Kontrollera papperskorgen",
      trashSelectedInfo: "Du kan återställa meddelanden från papperskorgen inom 30 dagar.",
      updating: "Redigering pågår",
      unsubscribedMailingList: "Du tog bort dig själv från den här e-postlistan.",
      yesterday: "Igår",
      wrote: "skrev:",
    },
    messagesList: {
      allMessagesLoaded: "Alla meddelanden har laddats upp",
      ctaDeletedMessages: "Rensa borttagna",
      ctaSpamInfo: "Markera allt som läst",
      ctaTrashInfo: "Töm papperskorgen",
      deletedMessages:
        "Det finns meddelanden som väntar på radering, rensa borttagna i mappen för att slutföra operationen.",
      folderEmpty: "Denna mapp är tom",
      folderInfo: "Starta en konversation eller flytta ett meddelande.",
      foundMessages: "Hittades",
      foundMessagesNum: "Hittades: <b>{{found}}</b> av <b>{{total}}</b>",
      moveMessage: "Flytta meddelande",
      moveMessages: "Flytta {{NumMessages}} meddelanden",
      notFound: "Inga meddelanden hittades",
      notFoundInfo: "Sökningen gav inte resultat, försök igen med olika kriterier.",
      pullDownToRefresh: "Drag för att uppdatera",
      releaseToRefresh: "Släpp för att uppdatera",
      searchInfo: "meddelanden hittade",
      searchLimited:
        "Indexering pågår. Sökningen är begränsad till <b>enskilda mappar</b> och fälten <b>från</b>, <b>till</b> och <b>ämne</b> i meddelandet.",
      searchNotAvailable: "Sökning är inte tillgänglig",
      searchNotAvailableInfo: "Sökningen är för närvarande inte tillgänglig, försök igen senare",
      selectMessages: "Vald",
      showMoreThread: "Visa mer",
      spamEmpty: "All skräppost har sprungit bort!",
      spamInfo: "Meddelanden i skräppost raderas automatiskt efter 30 dagar.",
      trashEmpty: "Papperskorgen är tom",
      trashInfo: "Meddelanden i papperskorgen raderas automatiskt efter 30 dagar.",
      totalMessages: "Meddelanden",
      totalMessagesNum: "Meddelanden: <b>{{total}}</b>",
    },
    mtm: {
      archivePromo:
        "<b> Men det är inte allt ... </b> <br/> <br/> E-postarkivtjänsten ger dig en dubbel, skrivskyddad brevlåda, där alla skickade och mottagna meddelanden lagras av användare i 10 år utan utrymmesbegränsningar.",
      backupSelector: "Välj en säkerhetskopia för att fortsätta",
      description:
        "Med den här tjänsten kan du komma åt säkerhetskopiorna av din brevlåda som gjorts under de senaste 15 dagarna, kontrollera statusen för dina säkerhetskopior eller återställa meddelanden.",
      title: "Välkommen till Mail Time Machine",
    },
    newMessage: {
      addAttach: "Bifoga fil",
      addHTMLTitle: "Infoga HTML",
      addImgeDsc:
        "Du kan infoga bilder direkt inline, i meddelandets kropp eller bifoga dem till meddelandet.",
      addImgeTitle: "Infoga bilder",
      addLinkTitle: "Infoga länk",
      editLinkTitle: "Redigera länk",
      advanced: "Avancerad",
      attachInfo: {
        noAttach: "Det finns inga bilagor",
        attachNumber: "Bilagor:",
      },
      bcc: "Bcc",
      cc: "Cc",
      cancelSend: "E-postsändningen avbröts",
      delete: "Radera",
      deleted: "Meddelandet har raderats framgångsrikt",
      deleteInProgress: "Radering av meddelandet pågår",
      discardChanges: "Ignorera ändringar",
      fontSize: {
        smaller: "Mindre",
        small: "Liten",
        normal: "Normal",
        medium: "Medium",
        big: "Stor",
        bigger: "Större",
      },
      from: "Från",
      hide: "Dölj",
      invalidMails: "Ogiltig e-postadress finns, kolla adresser och försök igen",
      moreAttachments: "Övriga",
      noDraftChanged: "Ingen ändring att spara",
      object: "Ämne",
      saveDraftDsc:
        "Meddelandet har inte skickats och innehåller ändringar som inte är sparade. Du kan spara det som ett utkast och fortsätta skriva senare.",
      saveDraftTitle: "Spara meddelande som utkast?",
      savedDraft: "Utkast sparat!",
      savingDraft: "Sparar utkast...",
      sendInProgress: "Skickar meddelande...",
      sent: "Meddelandet skickades utan problem",
      sizeExceeded: "Bilagor för stora. Den maximala sändningsstorleken är {{messageMaxSize}} MB.",
      templateCreateModal: {
        description:
          "<br/>Skapa ditt första standardmeddelande för att göra det enklare att skriva återkommande e-postmeddelanden. Du kan välja ett anpassat ämne och lägga till bilagor som skickas automatiskt i e-postmeddelandet.",
        title: "Du har inga e-postmallar än",
      },
      templateSubjectModal: {
        description:
          "Ett anpassat objekt definieras i det valda standardmeddelandet. Vill du ersätta den i skrivfönstret eller vill du behålla den?",
        title: "Ämnet redan använt",
      },
      to: "Till",
      toMore: "Övriga",
      useTemplate: "Konserverat meddelande",
      windowSubject: "Nytt meddelande",
    },
    reportBug: {
      title: "Rapportera meddelande",
      message: {
        issue:
          "Om du inte ser meddelandet korrekt kan du hjälpa oss att lösa problemet och förbättra tjänsten.<br/>Om du har några frågor eller problem angående användningen av webbmail, kontakta din tekniska referent för hjälp.",
        issueFormatting:
          "Visas inte meddelandeinnehållet korrekt? Du beskriver problemet, vi kommer att göra allt vi kan för att fixa det i nästa uppdatering.",
        issueBlank:
          "När meddelandena saknar innehåll, indikeras dessa i webbmailgränssnittet med en speciell banner.<br/><br/>Om denna banner inte finns kan det vara ett formateringsproblem, så <b>kontrollera efter förekomsten av bannern</b> och kanske rapportera meddelandet som <code>inte korrekt formaterat</code>.",
        issueAttach:
          "Verkar meddelandet vara fritt från bilagor? Förmodligen skickade avsändaren meddelandet och glömde att infoga bilagorna.<br/><br/><b>Be avsändaren att verifiera och skicka om bilagorna till dig</b>.",
        issueOther:
          "Du beskriver problemet, vi kommer att göra allt vi kan för att åtgärda det i nästa uppdatering.<br/>Om du har några frågor eller problem angående användningen av webbmail, kontakta din tekniska referent för hjälp.",
        disclaimer:
          "Genom att skicka denna feedback kan ditt meddelande analyseras av vårt utvecklingsteam för att förbättra tjänsten.<br/><br/><b>Informationen kommer INTE att delas med tredje part och uppgifterna kommer att behandlas i enlighet med gällande lagstiftning på Sekretess</b>.",
      },
    },
    restoreRequest: {
      desc: "Du har begärt återställning av postlådan <b>{{username}}</b> med säkerhetskopian daterad <b>{{restore_date}}</b>.<br/>Med den här åtgärden återställer vi alla meddelanden finns i den angivna säkerhetskopian, utan att radera något meddelande som under tiden har tagits emot eller skickats från brevlådan.<br/><br/><b>Återställningsåtgärden är kostnadsbelagd.</b><br/ ><br/>Vill du fortsätta med begäran?",
      restoreRequested:
        "Vi har tagit emot din begäran om återställning. Du kommer att kontaktas så snart proceduren är klar.",
      title: "Begär en återställning",
      titleRestoreRequested: "Förfrågan skickad",
      deniedTitle: "Förfrågan nekad",
      restoreRequestDenied:
        "Det finns en väntande återställningsbegäran för det här kontot. Det är inte möjligt att begära mer än en återställning varje gång.",
    },
    searchMail: {
      attachments: "Bilagor",
      cleanFilters: "Rengör filter",
      marked: "Stjärnmärkt",
      results: "Sökresultat",
      searchIn: "Sök i",
      allFolders: "Alla mappar",
      currentFolder: "Nuvarande mapp",
    },
    sidebar: {
      createLabel: {
        desc: "",
        title: "Skapa etikett",
      },
      createFolder: {
        desc: "",
        title: "Skapa mapp",
      },
      modifyFolder: {
        desc: "",
        title: "Redigera mapp",
      },
      restoreFolder: {
        desc: "",
        title: "Återställ mapp",
      },
      folder: "Mappar",
      folders: "Personliga mappar",
      labels: "Etiketter",
      newFoderName: "Nytt mappnamn",
      occupiedSpace: "Använt utrymme",
      sharedFolders: "Delade mappar",
      unlimitedSpace: "Obegränsat utrymme",
    },
    thanksMailLabel: "OK tack!",
    tooManyCompositionsDsc:
      "Du har nått det maximala antalet nya meddelanden som du kan skriva samtidigt. Fyll i minst ett meddelande från de du skriver för att starta en ny komposition.",
    tooManyCompositionsTitle: "Slutför skrivning!",
    unsubscribeListDsc: "Sluta ta emot meddelanden för den här e-postlistan?",
    unsubscribeListTitle: "Avsluta prenumeration",
  },

  mailboxes: {
    archive: "Arkiv",
    drafts: "Utkast",
    inbox: "Inkorg",
    more: "Mer",
    sent: "Skickat",
    shared: "Delade mappar",
    spam: "Spam",
    trash: "Skräp",
  },

  navbar: {
    addressbook: "Kontakter",
    calendar: "Kalender",
    chat: "Chatt",
    mail: "E-Post",
    meeting: "Möte",
    news: "Nyheter",
  },

  news: {
    notFound: "Nyheter hittades inte",
    notFoundInfo: "Sökningen gav inga resultat, försök igen med andra kriterier.",
  },

  newsTags: {
    news: "Nyheter",
    suggestions: "Tips",
    fix: "Fixa",
    comingSoon: "Kommer snart",
    beta: "Beta",
  },

  pageLogout: {
    title: "Loggar ut...",
    desc: "",
  },

  pageIndexing: {
    title: "Ditt konto indexeras",
    desc: "Åtgärden kan ta lite tid, vänta.",
  },

  pageNotFound: {
    pageNotFound: "Något gick fel",
    pageNotFoundInfo: "Sidan du letar efter är inte tillgänglig, tappa inte hoppet!",
  },

  powered: "drivs av Qboxmail",
  poweredCollaborationWith: "i samarbete med ",

  radioButtons: {
    labels: {
      askDeliveryConfirmation: "Bekräftelse av leveransmeddelande",
      askReadConfirmation: "Bekräftelse av läsningsmeddelande",
      defaultView: "Standardlayout",
      newEventType: "Ny händelsetyp",
      newEventFreeBusy: "Visa tillgänglighet för nya evenemang",
      newEventTimeInterval: "Nytt standardtidsintervall för händelse",
      other: "Övrig",
      reportBugBlank: "Meddelandet visas tomt",
      reportBugNoAttachments: "Meddelandet har inga bilagor",
      reportBugNoFormatted: "Innehållet är inte korrekt formaterat",
      selectIssue: "Vad är ditt problem?",
    },
  },

  shareOptions: {
    delete: "Radera",
    read: "Läsa",
    update: "Redigera",
    write: "Skriva/Ändra",
  },

  shareOptionsCalendar: {
    canCreateObjects: "Tillåt att infoga händelser i den här kalendern",
    canEraseObjects: "Tillåt att ta bort händelser i den här kalendern",
  },

  shortcuts: {
    addressbook: {
      newContact: "Ny kontakt",
      editContact: "Redigera kontakt",
      deleteContact: "Radera kontakt",
    },
    calendar: {
      newEvent: "Ny händelse",
      editEvent: "Redigera händelse",
      deleteEvent: "Radera händelse",
      moveRangeNext: "Visa nästa intervall",
      moveRangePrevious: "Visa tidigare intervall",
    },
    general: {
      switchModuls: "Växla moduler",
      refresh: "Uppdatera sida",
      tabForward: "Gå framåt bland de klickbara elementen",
      tabBack: "Flytta tillbaka bland de klickbara elementen",
      closeModal: "Stäng modulär ruta",
      openSettings: "Öppna Inställningar",
      copy: "Kopiera valt objekt",
      past: "Klistra in valt objekt",
      cut: "Klipp ut valt objekt",
    },
    mail: {
      confirm: "Bekräfta",
      deleteMessage: "Radera meddelande",
      deleteSelectMessage: "Radera valda meddelanden",
      editAsNew: "Redigera som nytt",
      empityTrash: "Töm papperskorgen",
      expandThread: "Expandera tråd",
      extendSelectDown: "Utöka valet nedåt på meddelandelistan",
      extendSelectUp: "Utöka valet upp på meddelandelistan",
      forward: "Vidarebefodra",
      markRead: "Markera som läst/oläst",
      moveDown: "Flytta ner på meddelandelistan",
      moveUp: "Gå upp på meddelandelistan",
      newMessage: "Nytt meddelande",
      openSelectMessage: "Öppna valt meddelande",
      printMessage: "Skriv ut meddelande",
      reduceThread: "Reducera tråd",
      reply: "Svara",
      replyAll: "Svara alla",
      thanks: "Tack",
    },
  },

  settings: {
    addressbook: {
      management: {
        automaticSave: {
          desc: "Välj om du automatiskt vill spara alla kontakter som inte finns i dina adressböcker.",
          title: "Spara Automatiskt",
        },
        personalAddressbooks: {
          desc: "Hantera dina personliga adressböcker och bestäm om du vill dela dem med annan användare.",
          headerActiveSync: "Sync",
          headerItem: "Adressbok",
          placeholderList: "",
          title: "Personlig adressbok",
        },
        sharedAddressbooks: {
          desc: "Hantera adressböcker som delas med dig av andra användare.",
          headerItem: "Prenumererad adressbok",
          placeholderList: "",
          title: "Delad adressbok",
        },
        title: "Adressböcker",
      },
      title: "Kontakter",
      view: {
        desc: "Hantera dina inställningar för kontakter och visualisering av adressböcker.",
        title: "Visning kontakter",
      },
    },
    calendar: {
      events: {
        title: "Händelser",
        desc: "Hantera dina inställningar för nya händelser för alla kalendrar, om det inte är satt till en specifik standard.",
        alertTitle: "Larm",
        alertDesc:
          "Hantera dina inställningar för händelsevarningar för alla kalendrar, om det inte är satt till en specifik standard.",
        personalMeetingRoomTitle: "Personligt mötesrum",
        personalMeetingRoomDesc:
          "Skapa ett rum i din online-mötesapplikation och ange länken här. Det kan sedan väljas som 'Plats' när du skapar ett evenemang.",
      },
      invitations: {
        desc: "Välj om du bara vill aktivera händelserinbjudningar för användare du vill ha.",
        title: "Händelserinbjudningar",
        msgFromHeader: "Tillåt bara inbjudningar från",
        placeholderList: "",
      },
      labels: {
        title: "Kalenderetiketter",
        titleSettingsPage: "Kalenderetiketter",
        desc: "Skapa anpassade färgade etiketter för att hålla dina evenemang i ordning.",
        deleteLabelDsc: "Om du tar bort etiketten tas den bort från alla kalenderhändelser.",
      },
      management: {
        title: "Kalendrar",
        holidayCalendars: {
          title: "Högtids kalendrar",
          desc: "Välj den högtidskalender du föredrar.",
          headerItem: "Kalendrar",
          placeholderList: " ",
        },
        personalCalendars: {
          title: "Personliga kalendrar",
          desc: "Hantera dina personliga kalendrar och bestäm om du vill dela dem med andra användare.",
          headerActiveSync: "Sync",
          headerItem: "Kalendrar",
          placeholderList: "",
        },
        sharedCalendars: {
          desc: "Hantera kalendrar som delas med dig av andra användare.",
          headerActiveSync: "Sync",
          headerItem: "Prenumererade kalendrar",
          placeholderList: "",
          title: "Delade kalendrar",
        },
        includeInFreeBusy: "Inkludera i Free/Busy",
        showActivities: "Visa aktiviteter",
        showAlarms: "Visa larm",
        syncWithActivesync: "Synkronisera med Microsoft® Exchange ActiveSync",
        sendMeMailOnMyEdit: "Skicka ett e-postmeddelande när jag ändrar kalendern",
        sendMeMailOnOtherEdit: "Skicka mig ett e-postmeddelande när någon ändrar kalendern",
        sendMailOnEditTo: "När jag ändrar skicka ett e-postmeddelande till",
      },
      view: {
        desc: "Hantera dina inställningar för visualisering av kalendrar.",
        showBusyOutsideWorkingHours: "Visa som upptagen utanför arbetstid",
        showWeekNumbers: "Visa veckonummer",
        title: "Visning kalender",
      },
      title: "Kalender",
    },
    chat: {
      title: "Chatt",
      view: {
        title: "Visning",
      },
    },
    general: {
      integrations: {
        desc: "Hantera integrationer med tjänsteleverantörer utanför webbmailen.",
        title: "Integrationer",
        card: {
          zoom: {
            askSeller: "Fråga din återförsäljare för mer information",
            title: "Zoom",
            text: "Spara tid när du planerar möten och lägg till unika Zoom-konferansdetaljer till en händelse.",
          },
        },
      },
      notifications: {
        title: "Pushnotifikationer",
        generalNotification: {
          desc: "Aktiverar meddelanden som visar att ett nytt meddelande har mottagits.",
          longDesc:
            "Tillåt Webmail att skicka meddelanden via webbläsaren när du får ett nytt meddelande. Den här inställningen räcker inte för att få meddelanden, du måste också aktivera meddelanden för varje webbläsare som du tänker använda.",
          title: "Allmän inställning av meddelanden",
        },
        allowedPush: {
          allowed:
            "Meddelanden är aktiverade i den webbläsare som används. För att ta emot dem måste de också vara aktiverade i avsnittet ovan.",
          default:
            "Om du vill att din nuvarande webbläsare ska meddela dig när du får ett nytt meddelande måste du aktivera meddelanden (i avsnittet ovan) och sedan aktivera push-notiser i din webbläsare. Klicka på knappen och tillåt meddelanden, eller klicka på låsikonen och tillåt meddelanden genom att trycka på knappen Tillåt.",
          isIos:
            "Om du vill få meddelanden på din iOS-enhet (version 16.4 och senare) måste du lägga till Webmail på enhetens startskärm.",
        },
        browserNotification: {
          desc: "Kontrollera status och hantera meddelanden för den webbläsare som för närvarande används.",
          title: "Status för meddelanden för den webbläsare som används",
        },
        granted: "Din webbläsarmeddelanden är korrekt konfigurerade!",
        noPush: {
          title: "Tyvärr stöder inte webbläsaren Safari aviseringssystemet.",
          titleios: "Tyvärr stöder inte iOS-operativsystemet webbläsaraviseringar.",
          desc: "För att aktivera aviseringar använder du den mest uppdaterade versionen av en av följande webbläsare",
        },
        deniedPush: {
          title: "Din webbläsare blockerar push-aviseringar.",
          desc: "Ta bort denna blockering för att aktivera push-aviseringar när ett nytt meddelande inkommer.",
        },
        modal: {
          title: "Vill du tillåta push-aviseringar?",
          text: "Du kan alltid tillåta eller blockera dem när som helst från webbmailinställningar.",
        },
      },
      parameters: {
        title: "Parametrar",
        host: {
          title: "Enhetskonfiguration",
          desc: "Anslut dina enheter för att ta emot och skicka e-post med ditt konto.",
        },
        imap: {
          title: "IMAP",
        },
        smtp: {
          title: "SMTP",
        },
      },
      profile: {
        email: "Användare e-post",
        generalSettings: {
          desc: "Hantera preferenser för språk och tid.",
          title: "Allmänna Inställningar",
        },
        personalInfo: {
          desc: "Hantera din profilinformation.",
          title: "Personlig information",
        },
        title: "Profil",
      },
      security: {
        changepassword: {
          info: "Lösenord som är minst 8 alfanumeriska tecken",
          desc: "Hantera lösenord för att komma åt din webbmail.",
          resetpassword: "Ställ in nytt lösenord",
          resetpassworddisabled: "Lösenordsändring är inaktiverad på det här kontot",
          resetpasswordexpired: "Ditt lösenord har löpt ut, ställ in ett nytt",
          title: "Ändra lösenord",
        },
        days: "dag/dagar",
        passwordexpiration: {
          activeExpiration: "Automatiskt lösenordsförfall är aktiverat för ditt e-postkonto.",
          desc: "Kontrollera statusen för ditt kontolösenord.",
          expirationDate: "Lösenordet upphör att gälla",
          expirationCountdown: "Lösenordet upphör att gälla om",
          modalTitle: "Ditt lösenord är på väg att upphöra",
          modalDesc:
            "Det är {{password_expiration_relative_days}} dag/dagar kvar tills ditt kontolösenord går ut. Vi rekommenderar att du ändrar det direkt.",
          title: "Lösenordets utgång",
        },
        otp: {
          cantDisableOtp: "Tvåfaktorsautentisering kan inte inaktiveras på det här kontot",
          desc: "Hantera tvåfaktorautentisering för att komma åt din webbmail.",
          disableOtp: "Inaktivera tvåfaktorautentisering",
          downloadParams: "Download activation data",
          hideParams: "Dölj parametrar",
          instructionDisableOtp:
            "Ange koden som genereras av applikationen i formuläret nedan för att inaktivera tvåfaktorautentisering för det här kontot.",
          instructionsSetOtp:
            "Skanna QRCode med applikationen och ange koden som genereras i formuläret nedan. Eller ange parametrarna för manuell aktivering.",
          labelEnterCode: "Ange kod genererad av applikationen",
          paramAccount: "Konto",
          paramCode: "Kod",
          paramType: "Tidsbaserad",
          paramTypeVal: "Aktiv",
          params: "Ange kod manuellt",
          paramsInstruction: "Ange följande parametrar i applikationen",
          setOtp: "Aktivera tvåfaktorautentisering",
          title: "Ställ in OTP",
          titleDisableOtp: "Inaktivera OTP",
          titleSetOtp: "Aktivera OTP",
        },
        sessions: {
          browser: "Webbläsare",
          currentSession: "Aktuell",
          device: "Enhet:",
          desc: "Hantera åtkomstsessioner till din webbmail.",
          ip: "IP:",
          os: "OS",
          platform: "Platform:",
          removeAll: "Ta bort alla",
          removeSession: "Ta bort",
          startdate: "Start:",
          title: "Öppna sessioner",
        },
        title: "Säkerhet",
      },
      title: "Allmän",
    },
    mail: {
      accounts: {desc: "", title: "Konton"},
      antispam: {
        blacklist: {
          desc: "Lägg till adress eller domän till listan (ex. 'namn@domän' or '*@domän')",
          msgNoHeader: "Tillåt inte meddelanden från",
          title: "Svartlista",
        },
        deleteRuleDsc: "Radera regel inställd till <code>{{ruleEmail}}</code>.",
        deleteRuleTitle: "Radera antispamregel",
        placeholderList: "",
        title: "Anti-Spam",
        whitelist: {
          desc: "Lägg till adress eller domän till listan (ex. 'namn@domän' or '*@domän')",
          msgFromHeader: "Tillåt meddelanden från",
          msgToHeader: "Tillåt meddelanden till",
          title: "Vitlista",
        },
      },
      autoresponder: {
        desc: "Ställ in ett automatiskt svarmeddelande för när du inte är på kontoret eller inte kan svara på mottagna meddelanden. <br/> Om en kontakt har skickat flera meddelanden skickas det automatiska svaret bara en gång var 24 timmar.",
        msg: "Meddelande",
        placholdeSubject: "Ämne",
        placholderTextarea: "Meddelandetext",
        title: "Autosvar",
      },
      compose: {
        cancelSend: {
          desc: "Välj tidsgräns för att avbryta skickandet av ett meddelande som pågår, om du bestämmer dig för att du inte vill skicka meddelandet längre.",
          title: "Avbryt skickad e-post",
        },
        confirmations: {
          desc: "Hantera läsnings- och leveransmeddelande för dina mottagna och skickade meddelanden.",
          title: "Läsning/leverans bekräftelse",
        },
        title: "Komposition",
      },
      delegations: {desc: "", title: "Delegation"},
      filters: {
        actionsTitle: "Åtgärder",
        activeFiltersTitle: "Aktiva regler",
        desc: "Skapa specifika regler för att sortera inkommande meddelanden och organisera dem som du vill i din brevlåda.",
        headerItem: "Regel",
        headerStatus: "Aktivt",
        hintEqualOperator:
          "Observera: användningen av operatorn <em><b>är lika med</b></em> / <em><b>är inte lika med</b></em> rekommenderas endast för expertanvändare. Alternativt rekommenderas att använda operatorn <em><b>innehåller</b></em> / <em><b>inte innehålla</b></em>. <br>För att använda operatorn <em><b>är lika med</b></em> / <em><b>är inte lika med</b></em> måste du matcha alla element som utgör fältet. Till exempel, för att ange <em>skicka</em> måste du ange alla följande element: <b>beskrivning &lt;e-postadress&gt;<b>.",
        parametersTitle: "Parametrar",
        placeholderList: {
          parameter: "Lägg till parameter i regeln",
          action: "Lägg till åtgärder i regeln",
        },

        title: "Regler",
      },
      folders: {
        compactFolder: "Ta bort alla meddelanden som är markerade som raderade från mappen",
        deleteFolderDsc:
          "Om du raderar mappen <code>{{folderName}}</code> raderas alla meddelanden i den. <br/><b>Åtgärden är inte reversibel</b>.",
        deleteFoldersTitle: "Radera mappar",
        desc: "Hantera och dela dina personliga mappar",
        descShared: "Hantera dina delade mappar",
        headerItem: "Mappar",
        headerMsg: "Meddelanden",
        headerPermissions: "Permissions",
        headerSelectedUsers: "Utvalda användare",
        headerUnread: "Oläst",
        modifyFolder: "Redigera mapp",
        newFolder: "Lägg till ny mapp",
        retention: "Regler för automatisk borttagning",
        rootFolder: "- Rot -",
        shared: "Delas med andra användare",
        subscribe: "Prenumerera",
        tabInfo: "Mappinformation",
        tabShare: "Dela mapp",
        title: "Mappar",
        titleShared: "Delade mappar",
      },
      forward: {
        description: "Välj e-postadresserna dit du vill vidarebefordra meddelandena till.",
        headerItem: "Mottagare",
        placeholderList: "",
        title: "Vidarebefordra meddelanden",
        titleSection: "Vidarebefordra meddelanden",
      },
      labels: {
        desc: "Skapa anpassade färgade etiketter för att hålla dina e-postmeddelanden organiserade.",
        headerItem: "Etiketter",
        deleteLabelTitle: "Radera etikett",
        deleteLabelTitleDsc: "Om du raderar etiketten tas den bort från alla meddelanden.",
        placeholderList: "",
        title: "Etiketter",
      },
      reading: {
        layout: {
          desc: "Välj hur du vill att läsrutan ska visas.",
          title: "Layout",
        },
        markReadSettings: {
          desc: "Ställ in när ett meddelande ska markeras som läst.",
          title: "Markera meddelandet som läst",
        },
        readingSettings: {
          desc: "Ställ in dina läspreferenser för meddelanden.",
          title: "Läsnings inställningar",
        },
        title: "Visning",
      },
      signature: {
        title: "Signatur",
        bcc: {
          headerItem: "Hemlig kopia-mottagare",
          placeholderList: "",
        },
        default: "Standard",
        deleteNewSignatureModal: {
          description:
            "Innehållet i den nya signaturen har inte sparats, den kommer att gå förlorat om du öppnar en annan. <br/> Vill du fortsätta ?",
          title: "Radera ny signatur",
        },
        dropFiles: "Släpp bilden här för att lägga till",
        management: {
          title: "Signaturhantering",
        },
        onlyNewMessages: "Lägg inte till signatur på svar",
        placeholderList: "Add your first identity",
        senderBcc: "Lägg till avsändare i Hemlig kopia (Bcc)",
        setAsDefault: "Ställ in som standardavsändare",
        signatures: {
          desc: "För varje identitet (grupp av alias) som är kopplad till ditt konto kan du anpassa signaturen längst ned i e-postmeddelandena du skickar och namnet som visas av de som tar emot dina meddelanden. Välj standardavsändare och lägg till e-postadresslistor i hemlig kopia.",
          headerItemSignature: "Visningsnamn",
          headerItemIdentity: "Identitet",
          title: "Signaturer och identiteter",
        },
      },
      template: {
        addAttachment: "Välj en fil för att lägga till den som en bilaga till meddelandet",
        deleteTemplateModal: {
          description:
            "Är du säker på att du vill ta bort det valda meddelandet? Filerna som bifogas meddelandet kommer också att raderas från våra system.",
          title: "Ta bort standardmeddelande",
        },
        title: "Standardmeddelande",
        description:
          "Välj ett standardmeddelande från listan för att automatiskt fylla i det nya meddelandet",
        placeholderList: "Lägg till ditt första standardmeddelande",
        placeholderSearch: "Filtrera meddelanden",
        searchHint:
          "Använd det här fältet för att filtrera listan över standardmeddelanden nedan. Filtret fungerar på meddelandets namn, ämne och innehåll.",
        templates: {
          desc: "Förenkla att skriva återkommande e-postmeddelanden genom att spara standardmeddelanden att välja mellan när du skriver e-postmeddelandet.",
          headerItemPreview: "Förhandsvisning",
          headerItemSubject: "Ämne",
          headerItemTemplate: "Namn",
          maxAttachmentsNrBasic:
            "Max {{attachmentNr}} bilagor. Max {{templateSize}} MB totalt. Kontakta din e-postleverantör för att öka dessa gränser.",
          maxAttachmentsNr: "Max {{attachmentNr}} bilagor. Max {{templateSize}} MB totalt.",
          maxTemplateNrReached: "Det maximala antalet konfigurerbara e-postmallar har uppnåtts.",
          maxTemplateNrReachedContactReseller:
            "Det maximala antalet konfigurerbara e-postmallar har uppnåtts. Om du behöver lägga till fler e-postmallar, kontakta din e-postleverantör för mer information.",
          newTemplate: "Nytt meddelande",
          title: "Standardmeddelanden",
        },
      },
      title: "E-Post",
    },
    meeting: {
      title: "Möte",
      view: {
        desc: "",
        title: "Visa",
      },
    },
    news: {
      readMore: "Läs mer",
      title: "News & Updates",
    },
    privacy: {
      title: "Privacy",
      cookie: {
        title: "Cookie Policy",
      },
      privacy: {
        title: "Privacy Policy",
      },
    },
    shortcuts: {
      title: "Tangentbordsgenvägar",
    },
    tasks: {
      notifications: {
        desc: "Få ett e-postmeddelande när en uppgift tilldelas dig eller när en uppgift du har tilldelat stängs",
        title: "E-post notifikationer",
      },
      labels: {
        title: "Uppgifter etiketter",
        desc: "Skapa anpassade färgade etiketter för att katalogisera dina uppgifter.",
      },
      title: "Uppgifter",
    },
    title: "Inställningar",
    unsaved: "Det finns ej sparade ändringar",
  },

  tasks: {
    add: "Skapa uppgift för min lista",
    assignedBy: "Tilldelas av",
    assignedTaskLabel: "<b>{{user}}</b> har tilldelat dig en ny uppgift:",
    assignedTaskTitle: "Ny uppgift tilldelad",
    assignedTo: "Tilldelats",
    assignTask: "Skapa uppgift att tilldela",
    basic: {
      label:
        "Uppgiftshantering är en tjänst som är tillgänglig<br />när du uppdaterar din profil.<br /><br />Uppdateringen inkluderar även delad kalender<br />och stöd för videomöten.",
      modalTitle: "Verktyg för att optimera ditt arbete",
      modalSubTitle: "tillgänglig med profiluppdatering",
      modalFooter:
        "Din tekniska agent kan presentera de ytterligare funktionerna i detalj utan förpliktelser",

      calendarLabel: "Delad <b>Kalender</b>.",
      tasksLabel: "<b>Uppgifter</b> och påminnelser.",
      signatureLabel: "Centraliserad e-post <b>signatur</b>.",
      zoomLabel: "Inbyggd <b>Zoom</b> för videomöte.",
      requestInfo: "jag är intresserad",
      requestInfoConfirmation: {
        text: "Du kommer att kontaktas av din tekniska agent.",
        title: "Begäran om information har skickats.",
      },
      requestLater: "Kanske senare",
    },
    closedTaskLabel: "<b>{{user}}</b> slutförde en uppgift:",
    closedTaskTitle: "Tilldelad uppgift slutförd",
    completionDate: "Avslutad",
    deleteTaskModal: {
      desc: "Är du säker på att du vill ta bort den valda uppgiften? Om uppgiften har tilldelats andra användare kommer den också att raderas för dem.",
      title: "Ta bort uppgift",
    },
    dueTime: {
      today: "Idag",
      tomorrow: "Imorgon",
      nextWeekend: "Nästa helg",
      thisWeekend: "Denna helgen",
      custom: "Datum och tid",
    },
    labels: "Etiketter",
    deleteLabelTitle: "Ta bort etikett",
    deleteLabelDsc:
      "Denna etikett har tilldelats en eller flera aktiviteter. Fortsätta med dess eliminering?",
    linkedMail: "Länkad e-mail",
    listImagesLabels: {
      completed: {
        text: "Listan över slutförda uppgifter är tom",
        title: "Inga uppgifter slutförda",
      },
      overdue: {
        text: "Du har inga försenade uppgifter ännu att göra",
        title: "Bra jobbat",
      },
      notCompleted: {
        text: "Du har inte planerat några uppgifter att göra",
        title: "Inget att göra här",
      },
      search: {
        text: "Skriv något för att göra en sökning",
        title: "Sök...",
      },
      assignedToDo: {
        text: "Listan över tilldelade uppgifter är tom",
        title: "Du har inte tilldelat några aktiviteter",
      },
      assignedCompleted: {
        text: "Listan över slutförda tilldelade uppgifter är tom",
        title: "Inga tilldelade uppgifter slutförda",
      },
      noResult: {
        title: "Inga resultat funna",
      },
    },
    lists: "Listor",
    modalTitle: "Uppgiftsdetaljer",
    note: "Notes (Max 1000 tecken)",
    occurrences: {
      all: "Alla händelser",
      occurrence: "Endast denna händelse",
    },
    openedTaskLabel: "<b>{{user}}</b> har öppnat en slutförd uppgift igen:",
    openedTaskTitle: "Tilldelad uppgift har öppnats igen",
    openMessageModal: {
      desc: "Om du öppnar meddelandet som är kopplat till uppgiften kommer uppgiftslistan att stängas.",
      title: "Vill du öppna meddelandet?",
    },
    overdueTasksPresent: "Försenade uppgifter: {{overdueTasksPresentCount}}",
    planned: "När",
    repeat: "Upprepa",
    repetitions: {
      NEVER: "Aldrig",
      DAILY: "Dagligen",
      WEEKLY: "Varje vecka",
      MONTHLY: "Månatlig",
      YEARLY: "Årlig",
    },
    showMyTasks: "Mina uppgifter",
    showAssignedTasks: "Tilldelad till andras",
    task: "Uppgift",
    taskFromNotification:
      "Vill du se detaljerna för den anmälda uppgiften och förlora data för den nya uppgiften som komponeras?",
    title: "Uppgifter",
    types: {
      view_todo: "Att göra",
      view_all: "Allt",
      view_today: "Idag",
      view_next7: "Nästa 7 dagar",
      view_overdue: "Försenad",
      view_completed: "Avslutad",
    },
  },

  toast: {
    error: {
      alreadyPresent: "Varning, resursen finns redan",
      avatarTooBig: "Varning, avatarstorlek för stor",
      compact: "Fel vid komprimering av mapp",
      connectionUnavailable: "Ingen anslutning tillgänglig",
      delete: "Fel vid radering",
      deleteDraft: "Fel vid utkast radering",
      emailAddressNotValid: "E-postadressen är inte giltig",
      enqueued: "Uppdatera inställningar, försök igen",
      fetchingAttachments: "Fel vid hämtning av bilagor",
      filterActionsMissing: "Åtgärder inte närvarande",
      filterConditionsMissing: "Parametrar inte närvarande",
      filterNameMissing: "Regelnamn saknas",
      folderCreation: "Fel vid skapande av ny mapp",
      folderCreationCharNotValid:
        "Fel vid skapande/namn byte av mapp, tecken är inte giltigt ({{char}})",
      folderCreationNoName: "Fel vid skapande av mapp, du måste ange ett giltigt namn",
      folderDelete: "Fel vid radering av mapp",
      folderNotPresent: "Mapp inte närvarande",
      folderRename: "Fel vid namnbyte av mapp, redan närvarande",
      folderSubscribe: "Fel vid prenumerations av mapp",
      generic: "Något gick fel",
      invalidDateRange: "Datumintervallet är inte giltigt",
      maxMembers: "Varning, maximalt antal uppnådda medlemmar",
      maxSignatureSize: "Maximal signaturstorlek överskriden. Max {{maxSize}}",
      maxTemplateAttachmentsNumberReached:
        "Gränsen för bilagor för detta standardmeddelande har nåtts",
      maxTemplateSize: "Varning, standardmeddelandestorleken är för stor",
      maxTemplatesNumberReached:
        "Gränsen för standardmeddelanden som kan konfigureras för detta konto har nåtts",
      messageCopy: "Fel vid kopiering av meddelanden",
      messageMove: "Fel vid flyttning av meddelanden",
      messageNotFound: "Meddelandet hittades inte",
      messageRemove: "Fel vid borttagning av meddelanden",
      missingParameters: "Parametrar saknas",
      missingSettings: "Användarinställningar saknas",
      notifications: "Fel vid aviseringar",
      notPermitted: "Åtgärden inte tillåten",
      notValid: "Varning, ogiltigt värde",
      onlyOneHomeAddress: "Du kan bara infoga en hemadress",
      onlyOneWorkAddress: "Du kan bara infoga en arbetsadress",
      save: "Fel vid sparande",
      saveAcl: "Fel spara mappbehörigheter",
      saveEvent:
        "Ett fel uppstod, du kanske inte har tillräckliga behörigheter för den här kalendern",
      saveZoomMeeting: "Det gick inte att skapa mötet på Zoom-plattformen",
      savingDraft: "Utkast till sparning pågår, försök igen i slutet",
      searchNotAvailable: "Sökning är inte tillgänglig för tillfället",
      sendingMessage: "Fel vid leverans av meddelanden",
      serverDisconnection: "Server uppdateras, försök igen senare!",
      sessionExpired: "Sessionen löpte ut",
      smtpBlockedByAntispam: "Meddelande inte skickat: blockerad av antispam",
      smtpBlockedByAntivirus: "Meddelande inte skickat: blockerat av antivirus",
      smtpDisabled: "Meddelande inte skickat: SMTP inaktiverat på det här kontot",
      smtpQuotaExceeded:
        "Meddelandet har inte skickats: meddelandekvoten för skickade meddelanden överskreds",
      requestLimit: "Efterfrågningsgräns (request limit) har överskridits, försök igen senare",
      requestError: "Efterfråningfel har inträffat, försök igen senare",
      updateFolders: "Ett fel uppstod vid uppdatering av mappar",
      updateMessageEvent: "Fel vid uppdatering av händelsestatus",
      updatingParentFlags: "Fel vid uppdatering av meddelandeflaggor",
    },
    info: {
      newVersionAvailable: {
        desc: "Denna åtgärd är säker, dina inställningar ändras inte.",
        title:
          "Nya funktioner är tillgängliga, ladda om sidan för att uppdatera till den senaste versionen.",
      },
      serverReconnected: "Webmailen är tillgänglig igen",
      sourceMail: "E-postkälla kopierad till urklipp",
    },
    progress: {
      newFolder: "Skapande av ny mapp pågår...",
      operationInProgress: "Operation pågår...",
    },
    success: {
      compact: "Mapp komprimerad framgångsrikt",
      copiedLink: "Länk kopierad till urklipp",
      copiedMail: "Meddelandet har kopierats.",
      copiedMailAddress: "E-postadress kopierad till urklipp",
      copiedText: "Text kopierad till urklipp",
      createFolder: "Mapp skapad framgångsrik",
      delete: "Raderad framgångsrikt",
      disabledOtp: "OTP inaktiverad framgångsrikt",
      enabledOtp: "OTP aktiverat framgångsrikt",
      movedMail: "Meddelandet flyttades framgångsrikt",
      notificationEnabled: "Meddelanden från webbläsaren har aktiverats",
      otpDisabled: "OTP har avaktiverats",
      otpEnable: "OTP har aktiverats",
      save: "Sparades framgångsrikt",
      saveAcl: "Behörigheter sparade framgångsrikt",
      saveDraft: "Utkastet sparats framgångsrikt",
      saveFolder: "Mapp har uppdaterades framgångsrikt",
      sentMail: "Meddelandet skickades framgångsrikt",
      subscribeFolder: "Prenumerationen har uppdaterats framgångsrikt",
      updateMessageEvent: "Händelsestatus uppdaterad",
    },
    warning: {
      forwardSet: "Minst en vidarebefordran har konfigurerats för det här kontot",
      notificationNotSupported: "Varning, din webbläsare stöder inte meddelanden",
    },
  },

  toggles: {
    labels: {
      allDayEvent: "Hela dagen",
      autoSaveContact: "Spara automatiskt alla mottagare som inte finns i dina adressböcker",
      denyInvites: "Förhindra inbjudningar till möten",
      enableAutorespopnd: "Aktivera autosvar",
      enableAutorespopndInterval: "Aktivera datumintervall",
      enableBrowserNotification: "Aktivera webbläsaraviseringar",
      enableDateSearch: "Aktivera datumssökning",
      enableFullBody: "Aktivera fulltextsökning",
      enableNotification: "Aktivera webbläsaraviseringar",
      keepCopy: "Behåll kopia av meddelandet lokalt",
      showPriority: "Visa mottagen meddelandeprioritet",
      showThreads: "Visa meddelanden som tråd",
      subscribeFolder: "Prenumerera på mapp",
      tasksEmailNotifications: "Aktivera e-postaviseringar",
    },
    hint: {
      enableFullBody:
        "Hela kroppssökningen är endast tillgänglig för en enda mapp. Välj en mapp för att aktivera den.",
    },
  },

  wizard: {
    layout: {
      desc: "Anpassa din Webmail genom att välja inställningar som du föredrar.",
      title: "Visa alternativ",
    },
    wizardData: {
      desc: "Anpassa din profil med en bild och komplettera med detaljer som saknas",
      title: "Slutför profil",
    },
  },
};
